// =============================================================================
// 🥤 MOCKTAILS (sans alcool)
// =============================================================================
// Ces recettes sont fusionnées dans l'objet `recettes` global.
// Init par défaut : foyer entier sauf les bébés.
// =============================================================================

Object.assign(recettes, {
  virginmojito: {
    nom: "Virgin Mojito",
    cat: "mocktails", pays: "france",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥤",
    description: "Le Virgin Mojito — menthe fraîche, citron vert, sucre de canne et eau gazeuse. Toute la fraîcheur du mojito, sans alcool !",
    tableauVirginMojito: [
      { nb: 1, citron: "1", menthe: "10 feuilles", sucre: "10 g", eauGaz: "15 cl", sirop: "1 cl" },
      { nb: 2, citron: "2", menthe: "20 feuilles", sucre: "20 g", eauGaz: "30 cl", sirop: "2 cl" },
      { nb: 3, citron: "3", menthe: "30 feuilles", sucre: "30 g", eauGaz: "45 cl", sirop: "3 cl" },
      { nb: 4, citron: "4", menthe: "40 feuilles", sucre: "40 g", eauGaz: "60 cl", sirop: "4 cl" },
      { nb: 5, citron: "5", menthe: "50 feuilles", sucre: "50 g", eauGaz: "75 cl", sirop: "5 cl" },
      { nb: 6, citron: "6", menthe: "60 feuilles", sucre: "60 g", eauGaz: "90 cl", sirop: "6 cl" },
      { nb: 7, citron: "7", menthe: "70 feuilles", sucre: "70 g", eauGaz: "1 L", sirop: "7 cl" },
      { nb: 8, citron: "8", menthe: "80 feuilles", sucre: "80 g", eauGaz: "1.2 L", sirop: "8 cl" },
      { nb: 9, citron: "9", menthe: "90 feuilles", sucre: "90 g", eauGaz: "1.35 L", sirop: "9 cl" },
      { nb: 10, citron: "10", menthe: "100 feuilles", sucre: "100 g", eauGaz: "1.5 L", sirop: "10 cl" },
      { nb: 11, citron: "11", menthe: "110 feuilles", sucre: "110 g", eauGaz: "1.65 L", sirop: "11 cl" },
      { nb: 12, citron: "12", menthe: "120 feuilles", sucre: "120 g", eauGaz: "1.8 L", sirop: "12 cl" },
      { nb: 13, citron: "13", menthe: "130 feuilles", sucre: "130 g", eauGaz: "1.95 L", sirop: "13 cl" },
      { nb: 14, citron: "14", menthe: "140 feuilles", sucre: "140 g", eauGaz: "2.1 L", sirop: "14 cl" },
      { nb: 15, citron: "15", menthe: "150 feuilles", sucre: "150 g", eauGaz: "2.25 L", sirop: "15 cl" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🍋", titre: "Piler menthe + citron", detail: "Dans un verre, mettre les feuilles de menthe et le sucre. Presser le citron vert par-dessus. Piler doucement.", badge: null },
      { icone: "🧊", titre: "Glace", detail: "Remplir de glace pilée.", badge: null },
      { icone: "💧", titre: "Compléter", detail: "Ajouter le sirop de menthe et l'eau gazeuse. Mélanger délicatement. Garnir de menthe fraîche.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  limonademaison: {
    nom: "Limonade Maison",
    cat: "mocktails", pays: "france",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🍋",
    description: "La limonade maison fraîche et naturelle — citrons pressés, sucre de canne et eau gazeuse. Bien meilleure que celle du commerce !",
    tableauLimonade: [
      { nb: 1, citrons: "1", sucre: "30 g", eauGaz: "20 cl", menthe: "3 feuilles" },
      { nb: 2, citrons: "1", sucre: "45 g", eauGaz: "40 cl", menthe: "6 feuilles" },
      { nb: 3, citrons: "2", sucre: "75 g", eauGaz: "60 cl", menthe: "9 feuilles" },
      { nb: 4, citrons: "3", sucre: "90 g", eauGaz: "80 cl", menthe: "12 feuilles" },
      { nb: 5, citrons: "3", sucre: "120 g", eauGaz: "100 cl", menthe: "15 feuilles" },
      { nb: 6, citrons: "4", sucre: "135 g", eauGaz: "120 cl", menthe: "18 feuilles" },
      { nb: 7, citrons: "5", sucre: "165 g", eauGaz: "140 cl", menthe: "21 feuilles" },
      { nb: 8, citrons: "5", sucre: "180 g", eauGaz: "160 cl", menthe: "24 feuilles" },
      { nb: 9, citrons: "6", sucre: "210 g", eauGaz: "180 cl", menthe: "27 feuilles" },
      { nb: 10, citrons: "7", sucre: "225 g", eauGaz: "200 cl", menthe: "30 feuilles" },
      { nb: 11, citrons: "7", sucre: "255 g", eauGaz: "220 cl", menthe: "33 feuilles" },
      { nb: 12, citrons: "8", sucre: "270 g", eauGaz: "240 cl", menthe: "36 feuilles" },
      { nb: 13, citrons: "9", sucre: "300 g", eauGaz: "260 cl", menthe: "39 feuilles" },
      { nb: 14, citrons: "9", sucre: "315 g", eauGaz: "280 cl", menthe: "42 feuilles" },
      { nb: 15, citrons: "10", sucre: "345 g", eauGaz: "300 cl", menthe: "45 feuilles" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍋", titre: "Préparer le sirop", detail: "Faire chauffer 100ml d'eau avec le sucre jusqu'à dissolution complète. Laisser refroidir.", badge: null },
      { icone: "🍋", titre: "Presser les citrons", detail: "Presser les citrons. Filtrer le jus.", badge: null },
      { icone: "🥤", titre: "Assembler", detail: "Mélanger jus de citron et sirop refroidi. Ajouter l'eau gazeuse froide. Mélanger délicatement.", badge: null },
      { icone: "🌿", titre: "Servir", detail: "Servir dans des grands verres avec glaçons, rondelles de citron et feuilles de menthe.", badge: null }
    ]
  },
  smoothiemangopassion: {
    nom: "Smoothie Mangue Passion",
    cat: "mocktails", pays: "france",
    base: 2,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥭",
    description: "Smoothie mangue passion tropical — onctueux, vitaminé et sans alcool. Un vrai voyage sous les tropiques !",
    tableauSmoothieMango: [
      { nb: 1, mangue: "100 g", passion: "1", banane: "60 g", lait: "80 ml", miel: "5 g" },
      { nb: 2, mangue: "200 g", passion: "2", banane: "1", lait: "160 ml", miel: "10 g" },
      { nb: 3, mangue: "300 g", passion: "3", banane: "180 g", lait: "240 ml", miel: "15 g" },
      { nb: 4, mangue: "400 g", passion: "4", banane: "2", lait: "320 ml", miel: "20 g" },
      { nb: 5, mangue: "500 g", passion: "5", banane: "300 g", lait: "400 ml", miel: "25 g" },
      { nb: 6, mangue: "600 g", passion: "6", banane: "3", lait: "480 ml", miel: "30 g" },
      { nb: 7, mangue: "700 g", passion: "7", banane: "420 g", lait: "560 ml", miel: "35 g" },
      { nb: 8, mangue: "800 g", passion: "8", banane: "4", lait: "640 ml", miel: "40 g" },
      { nb: 9, mangue: "900 g", passion: "9", banane: "540 g", lait: "720 ml", miel: "45 g" },
      { nb: 10, mangue: "1 kg", passion: "10", banane: "5", lait: "800 ml", miel: "50 g" },
      { nb: 11, mangue: "1.1 kg", passion: "11", banane: "660 g", lait: "880 ml", miel: "55 g" },
      { nb: 12, mangue: "1.2 kg", passion: "12", banane: "6", lait: "960 ml", miel: "60 g" },
      { nb: 13, mangue: "1.3 kg", passion: "13", banane: "780 g", lait: "1040 ml", miel: "65 g" },
      { nb: 14, mangue: "1.4 kg", passion: "14", banane: "7", lait: "1120 ml", miel: "70 g" },
      { nb: 15, mangue: "1.5 kg", passion: "15", banane: "900 g", lait: "1200 ml", miel: "75 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥭", titre: "Préparer les fruits", detail: "Éplucher et couper la mangue en morceaux. Couper les fruits de la passion en deux et récupérer la pulpe. Éplucher la banane. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🌀", titre: "Mixer", detail: "Mettre tous les ingrédients dans le blender avec quelques glaçons. Mixer jusqu'à texture lisse.", badge: "⏱ 30 sec" },
      { icone: "🥤", titre: "Servir", detail: "Verser dans des grands verres. Décorer d'une tranche de mangue et d'une paille. Déguster immédiatement !", badge: null }
    ]
  },
  citronadementhe: {
    nom: "Citronnade à la Menthe",
    cat: "mocktails", pays: "france",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "La citronnade à la menthe maison — fraîche, parfumée et naturelle. La boisson estivale incontournable sans alcool.",
    tableauCitronade: [
      { nb: 1, citrons: "1", menthe: "5 feuilles", sucre: "30 g", eau: "20 cl" },
      { nb: 2, citrons: "1", menthe: "8 feuilles", sucre: "45 g", eau: "40 cl" },
      { nb: 3, citrons: "2", menthe: "10 feuilles", sucre: "75 g", eau: "60 cl" },
      { nb: 4, citrons: "2", menthe: "15 feuilles", sucre: "90 g", eau: "80 cl" },
      { nb: 5, citrons: "3", menthe: "18 feuilles", sucre: "120 g", eau: "100 cl" },
      { nb: 6, citrons: "3", menthe: "20 feuilles", sucre: "135 g", eau: "120 cl" },
      { nb: 7, citrons: "4", menthe: "25 feuilles", sucre: "165 g", eau: "140 cl" },
      { nb: 8, citrons: "4", menthe: "28 feuilles", sucre: "180 g", eau: "160 cl" },
      { nb: 9, citrons: "5", menthe: "30 feuilles", sucre: "210 g", eau: "180 cl" },
      { nb: 10, citrons: "5", menthe: "35 feuilles", sucre: "225 g", eau: "200 cl" },
      { nb: 11, citrons: "6", menthe: "38 feuilles", sucre: "255 g", eau: "220 cl" },
      { nb: 12, citrons: "6", menthe: "40 feuilles", sucre: "270 g", eau: "240 cl" },
      { nb: 13, citrons: "7", menthe: "45 feuilles", sucre: "300 g", eau: "260 cl" },
      { nb: 14, citrons: "7", menthe: "48 feuilles", sucre: "315 g", eau: "280 cl" },
      { nb: 15, citrons: "8", menthe: "50 feuilles", sucre: "345 g", eau: "300 cl" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🌿", titre: "Sirop menthe", detail: "Chauffer 100ml d'eau avec le sucre et la menthe. Laisser infuser 10 min hors du feu. Filtrer et refroidir.", badge: "⏱ 10 min infusion" },
      { icone: "🍋", titre: "Presser les citrons", detail: "Presser les citrons et filtrer le jus.", badge: null },
      { icone: "🥤", titre: "Assembler et servir", detail: "Mélanger jus de citron, sirop à la menthe et eau fraîche. Servir avec glaçons et feuilles de menthe fraîches.", badge: null }
    ]
  },
  jusPastequeMenthe: {
    nom: "Jus Pastèque Menthe",
    cat: "mocktails", saisons: ["ete"], pays: "france",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🍉",
    description: "Jus de pastèque à la menthe — ultra rafraîchissant, naturellement sucré et plein de vitamines. Le mocktail de l'été !",
    tableauJusPasteque: [
      { nb: 1, pasteque: "250 g", menthe: "3 feuilles", citron: "25 g", gingembre: "0,5 cm" },
      { nb: 2, pasteque: "500 g", menthe: "5 feuilles", citron: "50 g", gingembre: "1 cm" },
      { nb: 3, pasteque: "750 g", menthe: "8 feuilles", citron: "75 g", gingembre: "1 cm" },
      { nb: 4, pasteque: "1 kg", menthe: "10 feuilles", citron: "1", gingembre: "2 cm" },
      { nb: 5, pasteque: "1.25 kg", menthe: "12 feuilles", citron: "1", gingembre: "2 cm" },
      { nb: 6, pasteque: "1.5 kg", menthe: "15 feuilles", citron: "150 g", gingembre: "2 cm" },
      { nb: 7, pasteque: "1.75 kg", menthe: "18 feuilles", citron: "150 g", gingembre: "3 cm" },
      { nb: 8, pasteque: "2 kg", menthe: "20 feuilles", citron: "2", gingembre: "3 cm" },
      { nb: 9, pasteque: "2.25 kg", menthe: "22 feuilles", citron: "2", gingembre: "3 cm" },
      { nb: 10, pasteque: "2.5 kg", menthe: "25 feuilles", citron: "250 g", gingembre: "4 cm" },
      { nb: 11, pasteque: "2.75 kg", menthe: "28 feuilles", citron: "250 g", gingembre: "4 cm" },
      { nb: 12, pasteque: "3 kg", menthe: "30 feuilles", citron: "3", gingembre: "4 cm" },
      { nb: 13, pasteque: "3.25 kg", menthe: "32 feuilles", citron: "3", gingembre: "5 cm" },
      { nb: 14, pasteque: "3.5 kg", menthe: "35 feuilles", citron: "350 g", gingembre: "5 cm" },
      { nb: 15, pasteque: "3.75 kg", menthe: "38 feuilles", citron: "350 g", gingembre: "5 cm" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍉", titre: "Préparer la pastèque", detail: "Couper la pastèque en morceaux, retirer les pépins et enlever la peau. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🌀", titre: "Mixer", detail: "Mixer la pastèque avec la menthe, le jus de citron et le gingembre râpé jusqu'à texture lisse.", badge: "⏱ 30 sec" },
      { icone: "🥤", titre: "Filtrer et servir", detail: "Filtrer si souhaité. Servir très frais avec glaçons et feuilles de menthe. Ne pas sucrer — la pastèque est naturellement sucrée !", badge: null }
    ]
  },
  virginpinacolada: {
    nom: "Virgin Piña Colada",
    cat: "mocktails", pays: "france",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥥",
    description: "Virgin Piña Colada — lait de coco, jus d'ananas et glace pilée. Toute la magie tropicale, sans alcool !",
    tableauVirginPina: [
      { nb: 1, cremeCoco: "6 cl", ananas: "12 cl", laitCoco: "4 cl", glace: "1 poignée" },
      { nb: 2, cremeCoco: "12 cl", ananas: "24 cl", laitCoco: "8 cl", glace: "2 poignées" },
      { nb: 3, cremeCoco: "18 cl", ananas: "36 cl", laitCoco: "12 cl", glace: "3 poignées" },
      { nb: 4, cremeCoco: "24 cl", ananas: "48 cl", laitCoco: "16 cl", glace: "4 poignées" },
      { nb: 5, cremeCoco: "30 cl", ananas: "60 cl", laitCoco: "20 cl", glace: "5 poignées" },
      { nb: 6, cremeCoco: "36 cl", ananas: "72 cl", laitCoco: "24 cl", glace: "6 poignées" },
      { nb: 7, cremeCoco: "42 cl", ananas: "84 cl", laitCoco: "28 cl", glace: "7 poignées" },
      { nb: 8, cremeCoco: "48 cl", ananas: "96 cl", laitCoco: "32 cl", glace: "8 poignées" },
      { nb: 9, cremeCoco: "54 cl", ananas: "108 cl", laitCoco: "36 cl", glace: "9 poignées" },
      { nb: 10, cremeCoco: "60 cl", ananas: "120 cl", laitCoco: "40 cl", glace: "10 poignées" },
      { nb: 11, cremeCoco: "66 cl", ananas: "132 cl", laitCoco: "44 cl", glace: "11 poignées" },
      { nb: 12, cremeCoco: "72 cl", ananas: "144 cl", laitCoco: "48 cl", glace: "12 poignées" },
      { nb: 13, cremeCoco: "78 cl", ananas: "156 cl", laitCoco: "52 cl", glace: "13 poignées" },
      { nb: 14, cremeCoco: "84 cl", ananas: "168 cl", laitCoco: "56 cl", glace: "14 poignées" },
      { nb: 15, cremeCoco: "90 cl", ananas: "180 cl", laitCoco: "60 cl", glace: "15 poignées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mettre tous les ingrédients dans le blender avec la glace pilée. Mixer jusqu'à texture crémeuse et onctueuse.", badge: "⏱ 30 sec" },
      { icone: "🥥", titre: "Servir", detail: "Verser dans un grand verre. Décorer d'une tranche d'ananas, de noix de coco râpée et d'une paille. Servir immédiatement !", badge: null }
    ]
  },
  cherryblossommocktail: {
    nom: "Cherry Blossom",
    cat: "mocktails", pays: "france",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🌸",
    description: "Le Cherry Blossom Mocktail — jus de cerise, eau de rose, citron et eau gazeuse. Un mocktail floral et élégant, sans alcool.",
    tableauCherryBlossom: [
      { nb: 1, cerise: "8 cl", eauRose: "1 cl", citron: "1 cl", sirop: "1 cl", eauGaz: "8 cl", sucre: "10 g" },
      { nb: 2, cerise: "16 cl", eauRose: "2 cl", citron: "2 cl", sirop: "2 cl", eauGaz: "16 cl", sucre: "20 g" },
      { nb: 3, cerise: "24 cl", eauRose: "3 cl", citron: "3 cl", sirop: "3 cl", eauGaz: "24 cl", sucre: "30 g" },
      { nb: 4, cerise: "32 cl", eauRose: "4 cl", citron: "4 cl", sirop: "4 cl", eauGaz: "32 cl", sucre: "40 g" },
      { nb: 5, cerise: "40 cl", eauRose: "5 cl", citron: "5 cl", sirop: "5 cl", eauGaz: "40 cl", sucre: "50 g" },
      { nb: 6, cerise: "48 cl", eauRose: "6 cl", citron: "6 cl", sirop: "6 cl", eauGaz: "48 cl", sucre: "60 g" },
      { nb: 7, cerise: "56 cl", eauRose: "7 cl", citron: "7 cl", sirop: "7 cl", eauGaz: "56 cl", sucre: "70 g" },
      { nb: 8, cerise: "64 cl", eauRose: "8 cl", citron: "8 cl", sirop: "8 cl", eauGaz: "64 cl", sucre: "80 g" },
      { nb: 9, cerise: "72 cl", eauRose: "9 cl", citron: "9 cl", sirop: "9 cl", eauGaz: "72 cl", sucre: "90 g" },
      { nb: 10, cerise: "80 cl", eauRose: "10 cl", citron: "10 cl", sirop: "10 cl", eauGaz: "80 cl", sucre: "100 g" },
      { nb: 11, cerise: "88 cl", eauRose: "11 cl", citron: "11 cl", sirop: "11 cl", eauGaz: "88 cl", sucre: "110 g" },
      { nb: 12, cerise: "96 cl", eauRose: "12 cl", citron: "12 cl", sirop: "12 cl", eauGaz: "96 cl", sucre: "120 g" },
      { nb: 13, cerise: "104 cl", eauRose: "13 cl", citron: "13 cl", sirop: "13 cl", eauGaz: "104 cl", sucre: "130 g" },
      { nb: 14, cerise: "112 cl", eauRose: "14 cl", citron: "14 cl", sirop: "14 cl", eauGaz: "112 cl", sucre: "140 g" },
      { nb: 15, cerise: "120 cl", eauRose: "15 cl", citron: "15 cl", sirop: "15 cl", eauGaz: "120 cl", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🍒", titre: "Mélanger", detail: "Dans un shaker avec glace, mélanger jus de cerise, eau de rose, jus de citron et sirop de sucre.", badge: null },
      { icone: "🥶", titre: "Shaker", detail: "Shaker 10 secondes.", badge: "⏱ 10 sec" },
      { icone: "🌸", titre: "Filtrer et servir", detail: "Filtrer dans un verre à champagne ou coupe. Compléter avec l'eau gazeuse. Décorer d'une fleur comestible ou cerise.", badge: null }
    ]
  },
  shrubframboisebasilic: {
    nom: "Shrub Framboise Basilic",
    cat: "mocktails", saisons: ["ete"], pays: "france",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🫐",
    description: "Shrub Framboise Basilic — sirop vinaigré aux framboises et basilic, allongé d'eau gazeuse. Un mocktail sophistiqué et acidulé.",
    tableauShrub: [
      { nb: 1, framboises: "50 g", basilic: "3 feuilles", vinaigreFramboise: "2 cl", sucre: "30 g", eauGaz: "15 cl" },
      { nb: 2, framboises: "100 g", basilic: "6 feuilles", vinaigreFramboise: "4 cl", sucre: "60 g", eauGaz: "30 cl" },
      { nb: 3, framboises: "150 g", basilic: "9 feuilles", vinaigreFramboise: "6 cl", sucre: "90 g", eauGaz: "45 cl" },
      { nb: 4, framboises: "200 g", basilic: "12 feuilles", vinaigreFramboise: "8 cl", sucre: "120 g", eauGaz: "60 cl" },
      { nb: 5, framboises: "250 g", basilic: "15 feuilles", vinaigreFramboise: "10 cl", sucre: "150 g", eauGaz: "75 cl" },
      { nb: 6, framboises: "300 g", basilic: "18 feuilles", vinaigreFramboise: "12 cl", sucre: "180 g", eauGaz: "90 cl" },
      { nb: 7, framboises: "350 g", basilic: "21 feuilles", vinaigreFramboise: "14 cl", sucre: "210 g", eauGaz: "105 cl" },
      { nb: 8, framboises: "400 g", basilic: "24 feuilles", vinaigreFramboise: "16 cl", sucre: "240 g", eauGaz: "120 cl" },
      { nb: 9, framboises: "450 g", basilic: "27 feuilles", vinaigreFramboise: "18 cl", sucre: "270 g", eauGaz: "135 cl" },
      { nb: 10, framboises: "500 g", basilic: "30 feuilles", vinaigreFramboise: "20 cl", sucre: "300 g", eauGaz: "150 cl" },
      { nb: 11, framboises: "550 g", basilic: "33 feuilles", vinaigreFramboise: "22 cl", sucre: "330 g", eauGaz: "165 cl" },
      { nb: 12, framboises: "600 g", basilic: "36 feuilles", vinaigreFramboise: "24 cl", sucre: "360 g", eauGaz: "180 cl" },
      { nb: 13, framboises: "650 g", basilic: "39 feuilles", vinaigreFramboise: "26 cl", sucre: "390 g", eauGaz: "195 cl" },
      { nb: 14, framboises: "700 g", basilic: "42 feuilles", vinaigreFramboise: "28 cl", sucre: "420 g", eauGaz: "210 cl" },
      { nb: 15, framboises: "750 g", basilic: "45 feuilles", vinaigreFramboise: "30 cl", sucre: "450 g", eauGaz: "225 cl" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫐", titre: "Préparer le shrub", detail: "Écraser les framboises avec le sucre et le vinaigre de cidre dans un bol. Ajouter le basilic froissé. Laisser macérer au frigo.", badge: "⏱ 2h macération" },
      { icone: "🌀", titre: "Filtrer", detail: "Filtrer le sirop obtenu en pressant bien les framboises. Conserver en bocal au frigo (se garde 2 semaines).", badge: null },
      { icone: "🥤", titre: "Assembler", detail: "Dans un verre avec glace, verser le shrub. Compléter avec eau gazeuse. Décorer d'une framboise et feuille de basilic.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailcoconananas: {
    nom: "Mocktail Coco Ananas",
    cat: "mocktails", pays: "france",
    base: 2,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥥",
    description: "Mocktail Coco Ananas — lait de coco, jus d'ananas, citron vert et gingembre. Tropical, frais et sans alcool pour toute la famille.",
    tableauCocoAnanas: [
      { nb: 1, coco: "8 cl", ananas: "10 cl", citron: "1 cl", gingembre: "0,5 cm", miel: "5 g", lait: "50 ml" },
      { nb: 2, coco: "16 cl", ananas: "20 cl", citron: "2 cl", gingembre: "1 cm", miel: "10 g", lait: "100 ml" },
      { nb: 3, coco: "24 cl", ananas: "30 cl", citron: "3 cl", gingembre: "1 cm", miel: "15 g", lait: "150 ml" },
      { nb: 4, coco: "32 cl", ananas: "40 cl", citron: "4 cl", gingembre: "2 cm", miel: "20 g", lait: "200 ml" },
      { nb: 5, coco: "40 cl", ananas: "50 cl", citron: "5 cl", gingembre: "2 cm", miel: "25 g", lait: "250 ml" },
      { nb: 6, coco: "48 cl", ananas: "60 cl", citron: "6 cl", gingembre: "2 cm", miel: "30 g", lait: "300 ml" },
      { nb: 7, coco: "56 cl", ananas: "70 cl", citron: "7 cl", gingembre: "3 cm", miel: "35 g", lait: "350 ml" },
      { nb: 8, coco: "64 cl", ananas: "80 cl", citron: "8 cl", gingembre: "3 cm", miel: "40 g", lait: "400 ml" },
      { nb: 9, coco: "72 cl", ananas: "90 cl", citron: "9 cl", gingembre: "3 cm", miel: "45 g", lait: "450 ml" },
      { nb: 10, coco: "80 cl", ananas: "100 cl", citron: "10 cl", gingembre: "4 cm", miel: "50 g", lait: "500 ml" },
      { nb: 11, coco: "88 cl", ananas: "110 cl", citron: "11 cl", gingembre: "4 cm", miel: "55 g", lait: "550 ml" },
      { nb: 12, coco: "96 cl", ananas: "120 cl", citron: "12 cl", gingembre: "4 cm", miel: "60 g", lait: "600 ml" },
      { nb: 13, coco: "104 cl", ananas: "130 cl", citron: "13 cl", gingembre: "5 cm", miel: "65 g", lait: "650 ml" },
      { nb: 14, coco: "112 cl", ananas: "140 cl", citron: "14 cl", gingembre: "5 cm", miel: "70 g", lait: "700 ml" },
      { nb: 15, coco: "120 cl", ananas: "150 cl", citron: "15 cl", gingembre: "5 cm", miel: "75 g", lait: "750 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer lait de coco, jus d'ananas, jus de citron vert, gingembre râpé et miel avec quelques glaçons jusqu'à texture lisse.", badge: "⏱ 30 sec" },
      { icone: "🥥", titre: "Servir", detail: "Verser dans des grands verres avec glaçons. Décorer d'une tranche d'ananas, noix de coco râpée et paille. Servir immédiatement !", badge: null }
    ]
  },
  mocktailberrybliss: {
    nom: "Mocktail Berry Bliss",
    cat: "mocktails", saisons: ["ete"], pays: "france",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🫐",
    description: "Berry Bliss Mocktail — myrtilles, framboises, jus de cranberry et eau gazeuse. Un mocktail antioxydant et spectaculaire sans alcool.",
    tableauBerryBliss: [
      { nb: 1, myrtilles: "30 g", framboises: "20 g", cranberry: "8 cl", citron: "1 cl", eauGaz: "8 cl", miel: "15 g" },
      { nb: 2, myrtilles: "60 g", framboises: "40 g", cranberry: "16 cl", citron: "2 cl", eauGaz: "16 cl", miel: "30 g" },
      { nb: 3, myrtilles: "90 g", framboises: "60 g", cranberry: "24 cl", citron: "3 cl", eauGaz: "24 cl", miel: "45 g" },
      { nb: 4, myrtilles: "120 g", framboises: "80 g", cranberry: "32 cl", citron: "4 cl", eauGaz: "32 cl", miel: "60 g" },
      { nb: 5, myrtilles: "150 g", framboises: "100 g", cranberry: "40 cl", citron: "5 cl", eauGaz: "40 cl", miel: "75 g" },
      { nb: 6, myrtilles: "180 g", framboises: "120 g", cranberry: "48 cl", citron: "6 cl", eauGaz: "48 cl", miel: "90 g" },
      { nb: 7, myrtilles: "210 g", framboises: "140 g", cranberry: "56 cl", citron: "7 cl", eauGaz: "56 cl", miel: "105 g" },
      { nb: 8, myrtilles: "240 g", framboises: "160 g", cranberry: "64 cl", citron: "8 cl", eauGaz: "64 cl", miel: "120 g" },
      { nb: 9, myrtilles: "270 g", framboises: "180 g", cranberry: "72 cl", citron: "9 cl", eauGaz: "72 cl", miel: "135 g" },
      { nb: 10, myrtilles: "300 g", framboises: "200 g", cranberry: "80 cl", citron: "10 cl", eauGaz: "80 cl", miel: "150 g" },
      { nb: 11, myrtilles: "330 g", framboises: "220 g", cranberry: "88 cl", citron: "11 cl", eauGaz: "88 cl", miel: "165 g" },
      { nb: 12, myrtilles: "360 g", framboises: "240 g", cranberry: "96 cl", citron: "12 cl", eauGaz: "96 cl", miel: "180 g" },
      { nb: 13, myrtilles: "390 g", framboises: "260 g", cranberry: "104 cl", citron: "13 cl", eauGaz: "104 cl", miel: "195 g" },
      { nb: 14, myrtilles: "420 g", framboises: "280 g", cranberry: "112 cl", citron: "14 cl", eauGaz: "112 cl", miel: "210 g" },
      { nb: 15, myrtilles: "450 g", framboises: "300 g", cranberry: "120 cl", citron: "15 cl", eauGaz: "120 cl", miel: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🫐", titre: "Mixer les fruits", detail: "Mixer myrtilles et framboises avec le jus de citron et 1 c.à.s de miel. Filtrer.", badge: null },
      { icone: "🍒", titre: "Assembler", detail: "Verser le coulis de fruits dans un verre avec glace. Ajouter le jus de cranberry.", badge: null },
      { icone: "💧", titre: "Eau gazeuse et déco", detail: "Compléter avec l'eau gazeuse. Garnir de quelques fruits frais et feuille de menthe.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailcoconorchidee: {
    nom: "Mocktail Coco Orchidée",
    cat: "mocktails", saisons: ["hiver"], pays: "france",
    base: 2,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🌺",
    description: "Mocktail Coco Orchidée — lait de coco, sirop de fleur d'oranger, citron vert et eau gazeuse. Exotique, floral et sans alcool.",
    tableauCocoOrchidee: [
      { nb: 1, laitCoco: "8 cl", fleurOranger: "1 cl", citron: "1 cl", eauGaz: "8 cl", miel: "5 g" },
      { nb: 2, laitCoco: "16 cl", fleurOranger: "2 cl", citron: "2 cl", eauGaz: "16 cl", miel: "10 g" },
      { nb: 3, laitCoco: "24 cl", fleurOranger: "3 cl", citron: "3 cl", eauGaz: "24 cl", miel: "15 g" },
      { nb: 4, laitCoco: "32 cl", fleurOranger: "4 cl", citron: "4 cl", eauGaz: "32 cl", miel: "20 g" },
      { nb: 5, laitCoco: "40 cl", fleurOranger: "5 cl", citron: "5 cl", eauGaz: "40 cl", miel: "25 g" },
      { nb: 6, laitCoco: "48 cl", fleurOranger: "6 cl", citron: "6 cl", eauGaz: "48 cl", miel: "30 g" },
      { nb: 7, laitCoco: "56 cl", fleurOranger: "7 cl", citron: "7 cl", eauGaz: "56 cl", miel: "35 g" },
      { nb: 8, laitCoco: "64 cl", fleurOranger: "8 cl", citron: "8 cl", eauGaz: "64 cl", miel: "40 g" },
      { nb: 9, laitCoco: "72 cl", fleurOranger: "9 cl", citron: "9 cl", eauGaz: "72 cl", miel: "45 g" },
      { nb: 10, laitCoco: "80 cl", fleurOranger: "10 cl", citron: "10 cl", eauGaz: "80 cl", miel: "50 g" },
      { nb: 11, laitCoco: "88 cl", fleurOranger: "11 cl", citron: "11 cl", eauGaz: "88 cl", miel: "55 g" },
      { nb: 12, laitCoco: "96 cl", fleurOranger: "12 cl", citron: "12 cl", eauGaz: "96 cl", miel: "60 g" },
      { nb: 13, laitCoco: "104 cl", fleurOranger: "13 cl", citron: "13 cl", eauGaz: "104 cl", miel: "65 g" },
      { nb: 14, laitCoco: "112 cl", fleurOranger: "14 cl", citron: "14 cl", eauGaz: "112 cl", miel: "70 g" },
      { nb: 15, laitCoco: "120 cl", fleurOranger: "15 cl", citron: "15 cl", eauGaz: "120 cl", miel: "75 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🥥", titre: "Mélanger", detail: "Dans un shaker avec glace, mélanger lait de coco, eau de fleur d'oranger, jus de citron vert et miel.", badge: null },
      { icone: "💧", titre: "Eau gazeuse", detail: "Filtrer dans un verre avec glace. Compléter d'eau gazeuse.", badge: null },
      { icone: "🌺", titre: "Décorer", detail: "Garnir d'une fleur comestible ou zeste de citron vert. Servir très frais.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailmentheagume: {
    nom: "Mocktail Menthe Concombre",
    cat: "mocktails", saisons: ["ete"], pays: "france",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Mocktail Menthe Concombre — concombre frais, menthe, citron vert et eau gazeuse. Le mocktail ultra-frais et detox de l'été.",
    tableauMocktailMenthe: [
      { nb: 1, concombre: "75 g", menthe: "6 feuilles", citron: "50 g", miel: "5 g", eauGaz: "150 ml" },
      { nb: 2, concombre: "150 g", menthe: "12 feuilles", citron: "1", miel: "10 g", eauGaz: "300 ml" },
      { nb: 3, concombre: "225 g", menthe: "18 feuilles", citron: "150 g", miel: "15 g", eauGaz: "450 ml" },
      { nb: 4, concombre: "1", menthe: "24 feuilles", citron: "2", miel: "20 g", eauGaz: "600 ml" },
      { nb: 5, concombre: "1", menthe: "30 feuilles", citron: "2", miel: "25 g", eauGaz: "750 ml" },
      { nb: 6, concombre: "450 g", menthe: "36 feuilles", citron: "3", miel: "30 g", eauGaz: "900 ml" },
      { nb: 7, concombre: "450 g", menthe: "42 feuilles", citron: "3", miel: "35 g", eauGaz: "1050 ml" },
      { nb: 8, concombre: "2", menthe: "48 feuilles", citron: "4", miel: "40 g", eauGaz: "1200 ml" },
      { nb: 9, concombre: "2", menthe: "54 feuilles", citron: "4", miel: "45 g", eauGaz: "1350 ml" },
      { nb: 10, concombre: "750 g", menthe: "60 feuilles", citron: "5", miel: "50 g", eauGaz: "1500 ml" },
      { nb: 11, concombre: "750 g", menthe: "66 feuilles", citron: "5", miel: "55 g", eauGaz: "1650 ml" },
      { nb: 12, concombre: "3", menthe: "72 feuilles", citron: "6", miel: "60 g", eauGaz: "1800 ml" },
      { nb: 13, concombre: "3", menthe: "78 feuilles", citron: "6", miel: "65 g", eauGaz: "1950 ml" },
      { nb: 14, concombre: "1050 g", menthe: "84 feuilles", citron: "7", miel: "70 g", eauGaz: "2100 ml" },
      { nb: 15, concombre: "1050 g", menthe: "90 feuilles", citron: "7", miel: "75 g", eauGaz: "2250 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🥒", titre: "Mixer concombre", detail: "Mixer le concombre épluché avec les feuilles de menthe, jus de citron et miel.", badge: null },
      { icone: "🧊", titre: "Filtrer et glacer", detail: "Filtrer le mélange. Verser sur glaçons.", badge: null },
      { icone: "💧", titre: "Compléter", detail: "Compléter d'eau gazeuse. Décorer de rondelles de concombre et feuilles de menthe fraîche.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailframboisementhe: {
    nom: "Mocktail Framboise Menthe",
    cat: "mocktails", saisons: ["ete","printemps"], pays: "monde",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🫐",
    description: "Mocktail framboise menthe — framboises fraîches pilées, sirop de menthe, limonade pétillante et glaçons. Frais, coloré et zéro alcool.",
    fixe: true,
    ingredientsFixes: [["fraises","50 g framboises"],["menthe","5 feuilles"],["sirop","20 ml sirop framboise"],["tonic","120 ml limonade"],["glace","glaçons"]],
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🫐", titre: "Piler les framboises", detail: "Dans le verre, piler les framboises avec la menthe et le sirop.", badge: null },
      { icone: "🧊", titre: "Ajouter les glaçons", detail: "Remplir de glaçons.", badge: null },
      { icone: "💧", titre: "Compléter", detail: "Verser la limonade pétillante. Remuer délicatement. Décorer avec framboises et menthe fraîche.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailpassionsoleil: {
    nom: "Mocktail Passion Soleil",
    cat: "mocktails", saisons: ["hiver"], pays: "monde",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "☀️",
    description: "Mocktail Passion Soleil — fruit de la passion, mangue, jus d'orange et eau gazeuse. Tropical, vitaminé et ensoleillé même en hiver.",
    fixe: true,
    ingredientsFixes: [["passion","1 fruit de la passion"],["orange","60 ml jus mangue"],["orangeJus","60 ml jus d'orange"],["tonic","60 ml eau gazeuse"],["glace","glaçons"]],
    etapes: [
      { icone: "☀️", titre: "Préparer", detail: "Dans un shaker avec glaçons, verser pulpe de fruit de la passion, jus de mangue et jus d'orange.", badge: null },
      { icone: "🍹", titre: "Shaker", detail: "Shaker vigoureusement 10 secondes.", badge: "⏱ 10 sec" },
      { icone: "💧", titre: "Servir", detail: "Verser dans un verre. Compléter avec l'eau gazeuse. Décorer avec une rondelle d'orange.", badge: null }
    ]
  },
  mocktailconcombrecitr: {
    nom: "Mocktail Concombre Citron",
    cat: "mocktails", saisons: ["ete"], pays: "monde",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥒",
    description: "Mocktail concombre citron vert — concombre frais, citron vert, basilic et eau pétillante. Ultrafraîchissant, détox et élégant pour l'apéritif.",
    fixe: true,
    ingredientsFixes: [["concombre","4 rondelles"],["citrons","30 ml jus citron vert"],["basilic","3 feuilles"],["sirop","15 ml sirop agave"],["tonic","100 ml eau gazeuse"],["glace","glaçons"]],
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🥒", titre: "Piler", detail: "Dans le verre, piler les rondelles de concombre avec le basilic et le sirop d'agave.", badge: null },
      { icone: "🍋", titre: "Ajouter", detail: "Ajouter jus de citron vert et glaçons.", badge: null },
      { icone: "💧", titre: "Compléter", detail: "Verser l'eau gazeuse. Garnir d'une rondelle de concombre et basilic.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailgingembre: {
    nom: "Ginger Mocktail",
    cat: "mocktails", pays: "monde",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Ginger Mocktail — gingembre frais, citron, miel et ginger beer. Épicé, piquant et revigorant. La version sans alcool du Moscow Mule.",
    fixe: true,
    ingredientsFixes: [["gingembre","5 g râpé"],["citrons","30 ml jus"],["miel","15 ml"],["gingerBeer","150 ml ginger beer"],["glace","glaçons"]],
    etapes: [
      { icone: "🌿", titre: "Préparer", detail: "Mélanger gingembre râpé, jus de citron et miel. Laisser infuser 2 min.", badge: "⏱ 2 min" },
      { icone: "🧊", titre: "Remplir", detail: "Filtrer dans un mug en cuivre ou verre rempli de glaçons.", badge: null },
      { icone: "💧", titre: "Compléter", detail: "Verser le ginger beer. Garnir de rondelle de citron et brin de menthe.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mocktailfraisesvanille: {
    nom: "Mocktail Fraises Vanille",
    cat: "mocktails", saisons: ["ete","printemps"], pays: "monde",
    base: 1,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍓",
    description: "Mocktail Fraises Vanille — coulis de fraises fraîches, extrait de vanille, lait de coco et eau gazeuse. Doux, fruité et terriblement gourmand.",
    fixe: true,
    ingredientsFixes: [["fraises","80 g fraises"],["vanilleE","½ c.à.c"],["cremeCoco","40 ml lait de coco"],["sirop","15 ml sirop de sucre"],["tonic","80 ml eau gazeuse"],["glace","glaçons"]],
    etapes: [
      { icone: "❄️", titre: "Préparer le verre", detail: "Refroidir le verre au congélateur 10 min avant. Un verre froid sublime l'expérience même sans alcool.", badge: "⏱ 10 min" },
      { icone: "🍓", titre: "Mixer", detail: "Mixer les fraises avec la vanille et le sirop jusqu'à obtenir un coulis lisse.", badge: null },
      { icone: "🥥", titre: "Assembler", detail: "Dans un verre rempli de glaçons, verser le coulis de fraises puis le lait de coco.", badge: null },
      { icone: "💧", titre: "Finir", detail: "Ajouter l'eau gazeuse. Remuer délicatement. Décorer avec une fraise sur le bord du verre.", badge: null },
      { icone: "🥤", titre: "Service rafraîchissant", detail: "Servir IMMÉDIATEMENT avec une jolie paille. Décorer généreusement (le visuel compte !). Idéal en apéritif ou rafraîchissement.", badge: null }
    ]
  },
  mangolassi: {
    nom: "Mango Lassi",
    cat: "mocktails", pays: "inde",
    base: 4,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥭",
    description: "Mango Lassi — boisson indienne onctueuse à la mangue et yaourt. Crémeux, frais et naturellement sucré. Le parfait accompagnement d'un curry épicé ou en dessert.",
    tableauMangoLassi: [
      { nb: 1, mangue: "80 g", yaourt: "80 g", lait: "40 ml", sucre: "5 g", cardamome: "1 g", glace: "20 g", menthe: "1 g", zestecitron: "0" },
      { nb: 2, mangue: "160 g", yaourt: "160 g", lait: "80 ml", sucre: "10 g", cardamome: "1 g", glace: "40 g", menthe: "2 g", zestecitron: "1" },
      { nb: 3, mangue: "240 g", yaourt: "240 g", lait: "120 ml", sucre: "15 g", cardamome: "2 g", glace: "60 g", menthe: "3 g", zestecitron: "1" },
      { nb: 4, mangue: "320 g", yaourt: "320 g", lait: "160 ml", sucre: "20 g", cardamome: "2 g", glace: "80 g", menthe: "4 g", zestecitron: "1" },
      { nb: 5, mangue: "400 g", yaourt: "400 g", lait: "200 ml", sucre: "25 g", cardamome: "2 g", glace: "100 g", menthe: "5 g", zestecitron: "1" },
      { nb: 6, mangue: "480 g", yaourt: "480 g", lait: "240 ml", sucre: "30 g", cardamome: "3 g", glace: "120 g", menthe: "6 g", zestecitron: "1" },
      { nb: 7, mangue: "560 g", yaourt: "560 g", lait: "280 ml", sucre: "35 g", cardamome: "4 g", glace: "140 g", menthe: "7 g", zestecitron: "1" },
      { nb: 8, mangue: "640 g", yaourt: "640 g", lait: "320 ml", sucre: "40 g", cardamome: "4 g", glace: "160 g", menthe: "8 g", zestecitron: "1" },
      { nb: 9, mangue: "720 g", yaourt: "720 g", lait: "360 ml", sucre: "45 g", cardamome: "4 g", glace: "180 g", menthe: "9 g", zestecitron: "1" },
      { nb: 10, mangue: "800 g", yaourt: "800 g", lait: "400 ml", sucre: "50 g", cardamome: "5 g", glace: "200 g", menthe: "10 g", zestecitron: "1" },
      { nb: 11, mangue: "880 g", yaourt: "880 g", lait: "440 ml", sucre: "55 g", cardamome: "6 g", glace: "220 g", menthe: "11 g", zestecitron: "1" },
      { nb: 12, mangue: "960 g", yaourt: "960 g", lait: "480 ml", sucre: "60 g", cardamome: "6 g", glace: "240 g", menthe: "12 g", zestecitron: "1" },
      { nb: 13, mangue: "1 kg", yaourt: "1 kg", lait: "520 ml", sucre: "65 g", cardamome: "6 g", glace: "260 g", menthe: "13 g", zestecitron: "1" },
      { nb: 14, mangue: "1.1 kg", yaourt: "1.1 kg", lait: "560 ml", sucre: "70 g", cardamome: "7 g", glace: "280 g", menthe: "14 g", zestecitron: "1" },
      { nb: 15, mangue: "1.2 kg", yaourt: "1.2 kg", lait: "600 ml", sucre: "75 g", cardamome: "8 g", glace: "300 g", menthe: "15 g", zestecitron: "1" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥭", titre: "Choisir les mangues", detail: "ESSENTIEL : mangues MÛRES À POINT (cèdent au doigt, parfumées). Variétés Alphonso (Inde) ou Kent idéales. ASTUCE CHEF : pour version express, utiliser de la PURÉE DE MANGUE indienne en boîte (Ratna, Patak's).", badge: "⏱ 1 min" },
      { icone: "🍽️", titre: "Préparer la mangue", detail: "Éplucher la mangue, couper la chair autour du noyau central. Couper en cubes. Si trop ferme : laisser 1h à température ambiante.", badge: "⏱ 3 min" },
      { icone: "🌿", titre: "Cardamome (option authentique)", detail: "SECRET DU LASSI INDIEN : ouvrir 4 gousses de cardamome verte. Récupérer les graines noires. Piler au mortier ou écraser avec le dos d'une cuillère. C'est LE parfum signature.", badge: "⏱ 2 min" },
      { icone: "❄️", titre: "Yaourt bien froid", detail: "Utiliser du YAOURT NATURE ENTIER (yaourt grec ou yaourt indien Dahi). Bien froid = onctuosité maximale. NE PAS prendre 0% (texture aqueuse).", badge: "⏱ -" },
      { icone: "🌀", titre: "Mixer", detail: "Dans un blender : cubes de mangue (400g) + yaourt (400ml) + lait (200ml) + sucre (2 cs ajuster selon douceur de la mangue) + cardamome moulue + 1 poignée de glaçons. Mixer 30-45 secondes à pleine puissance.", badge: "⏱ 45 sec" },
      { icone: "✨", titre: "Texture", detail: "Doit être SOYEUSE et ONCTUEUSE comme un milkshake. Si trop épais : ajouter lait. Si trop liquide : ajouter glace ou yaourt.", badge: "⏱ 30 sec" },
      { icone: "🥤", titre: "Service", detail: "Servir dans des verres GLACÉS (au congélateur 10 min avant). Saupoudrer d'une pincée de cardamome moulue ou de pistaches concassées sur le dessus.", badge: null },
      { icone: "🌿", titre: "Touches finales", detail: "Une feuille de menthe fraîche, un zeste de citron vert. Servir avec paille. PARFAIT avec un curry épicé (rafraîchit le palais) ou seul en collation.", badge: null }
    ]
  },
  matchalattewi: {
    nom: "Matcha Latte",
    cat: "mocktails", pays: "japon",
    base: 2,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍵",
    description: "Matcha Latte — boisson japonaise crémeuse et énergisante. Poudre de matcha cérémoniale fouettée avec du lait chaud, légèrement sucrée au miel ou sirop. Antioxydants et zen attitude !",
    tableauMatchaLatte: [
      { nb: 1, matcha: "2 g", laitamande: "150 ml", eauchaude: "30 ml", sirop: "8 ml", vanille: "1 g", cannelle: "1 g", sucre: "3 g", glace: "50 g" },
      { nb: 2, matcha: "4 g", laitamande: "300 ml", eauchaude: "60 ml", sirop: "16 ml", vanille: "1 g", cannelle: "1 g", sucre: "6 g", glace: "100 g" },
      { nb: 3, matcha: "6 g", laitamande: "450 ml", eauchaude: "90 ml", sirop: "24 ml", vanille: "2 g", cannelle: "2 g", sucre: "9 g", glace: "150 g" },
      { nb: 4, matcha: "8 g", laitamande: "600 ml", eauchaude: "120 ml", sirop: "32 ml", vanille: "2 g", cannelle: "2 g", sucre: "12 g", glace: "200 g" },
      { nb: 5, matcha: "10 g", laitamande: "750 ml", eauchaude: "150 ml", sirop: "40 ml", vanille: "2 g", cannelle: "2 g", sucre: "15 g", glace: "250 g" },
      { nb: 6, matcha: "12 g", laitamande: "900 ml", eauchaude: "180 ml", sirop: "48 ml", vanille: "3 g", cannelle: "3 g", sucre: "18 g", glace: "300 g" },
      { nb: 7, matcha: "14 g", laitamande: "1.1 l", eauchaude: "210 ml", sirop: "56 ml", vanille: "4 g", cannelle: "4 g", sucre: "21 g", glace: "350 g" },
      { nb: 8, matcha: "16 g", laitamande: "1.2 l", eauchaude: "240 ml", sirop: "64 ml", vanille: "4 g", cannelle: "4 g", sucre: "24 g", glace: "400 g" },
      { nb: 9, matcha: "18 g", laitamande: "1.4 l", eauchaude: "270 ml", sirop: "72 ml", vanille: "4 g", cannelle: "4 g", sucre: "27 g", glace: "450 g" },
      { nb: 10, matcha: "20 g", laitamande: "1.5 l", eauchaude: "300 ml", sirop: "80 ml", vanille: "5 g", cannelle: "5 g", sucre: "30 g", glace: "500 g" },
      { nb: 11, matcha: "22 g", laitamande: "1.6 l", eauchaude: "330 ml", sirop: "88 ml", vanille: "6 g", cannelle: "6 g", sucre: "33 g", glace: "550 g" },
      { nb: 12, matcha: "24 g", laitamande: "1.8 l", eauchaude: "360 ml", sirop: "96 ml", vanille: "6 g", cannelle: "6 g", sucre: "36 g", glace: "600 g" },
      { nb: 13, matcha: "26 g", laitamande: "1.9 l", eauchaude: "390 ml", sirop: "104 ml", vanille: "6 g", cannelle: "6 g", sucre: "39 g", glace: "650 g" },
      { nb: 14, matcha: "28 g", laitamande: "2.1 l", eauchaude: "420 ml", sirop: "112 ml", vanille: "7 g", cannelle: "7 g", sucre: "42 g", glace: "700 g" },
      { nb: 15, matcha: "30 g", laitamande: "2.2 l", eauchaude: "450 ml", sirop: "120 ml", vanille: "8 g", cannelle: "8 g", sucre: "45 g", glace: "750 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍵", titre: "Choisir le matcha", detail: "CRITIQUE : utiliser du VRAI matcha cérémoniel (qualité haute, vert vif). Le matcha culinaire (vert jaunâtre) est amer. Marques recommandées : Ippodo, Marukyu Koyamaen.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Eau à bonne température", detail: "Faire chauffer l'eau à 70-75°C (PAS bouillante — sinon matcha amer). ASTUCE CHEF : porter à ébullition puis laisser 2 min pour redescendre à la bonne température.", badge: "⏱ 3 min" },
      { icone: "🍵", titre: "Tamiser le matcha", detail: "SECRET DU MATCHA : passer le matcha à travers un petit tamis fin pour éviter les grumeaux. C'est CE QUE FONT TOUS les sommeliers de matcha.", badge: "⏱ 1 min" },
      { icone: "🥢", titre: "Préparer la base", detail: "Dans un grand bol (chawan japonais ou bol large) : verser 1 cc de matcha tamisé + 60ml d'eau chaude.", badge: "⏱ 1 min" },
      { icone: "🍃", titre: "Fouetter au chasen", detail: "TECHNIQUE TRADITIONNELLE : fouetter avec un CHASEN (fouet bambou) en mouvements ZIG-ZAG rapides (W ou M) pendant 30 secondes. Le matcha doit devenir MOUSSEUX en surface. À défaut : fouet électrique.", badge: "⏱ 30 sec" },
      { icone: "🥛", titre: "Chauffer le lait", detail: "Pendant ce temps, chauffer 200ml de lait (vache ou avoine pour version moderne) à 65°C. NE PAS BOUILLIR. Optionnel : faire mousser avec un mousseur à lait.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Sucrer (option)", detail: "Dans le matcha mousseux, ajouter : 1 cs de sirop d'érable, miel ou agave + 1/2 cc de vanille. Mélanger.", badge: "⏱ 1 min" },
      { icone: "🍵", titre: "Assembler", detail: "Verser le lait chaud LENTEMENT en filet sur la mousse de matcha. Si bien fait : le matcha vert pur reste au-dessus, le lait blanc en-dessous = effet visuel signature.", badge: "⏱ 30 sec" },
      { icone: "✨", titre: "Service zen", detail: "Servir IMMÉDIATEMENT dans une grande tasse. Saupoudrer d'un peu de matcha en surface. Pour version GLACÉE : verser sur des glaçons. Pour version originale : sans sucre, juste matcha + lait. 抹茶ラテ !", badge: null }
    ]
  },
  bieraubeurre: {
    nom: "Bière au Beurre",
    cat: "mocktails", pays: "angleterre",
    dateAjout: "2026-06-01",
    base: 1,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍺",
    description: "La célèbre Bière au Beurre des sorciers — sans alcool ! Une boisson pétillante au caramel beurre salé, coiffée d'une mousse onctueuse. Magique pour petits et grands. 🪄",
    tableauBiereBeurre: [
      { nb: 1, limonade: "20 cl", caramel: "30 g", beurre: "10 g", cassonade: "15 g", creme: "5 cl" },
      { nb: 2, limonade: "40 cl", caramel: "60 g", beurre: "20 g", cassonade: "30 g", creme: "10 cl" },
      { nb: 3, limonade: "60 cl", caramel: "90 g", beurre: "30 g", cassonade: "45 g", creme: "15 cl" },
      { nb: 4, limonade: "80 cl", caramel: "120 g", beurre: "40 g", cassonade: "60 g", creme: "20 cl" },
      { nb: 5, limonade: "1 L", caramel: "150 g", beurre: "50 g", cassonade: "75 g", creme: "25 cl" },
      { nb: 6, limonade: "1,2 L", caramel: "150 g", beurre: "60 g", cassonade: "90 g", creme: "30 cl" },
      { nb: 7, limonade: "1,4 L", caramel: "225 g", beurre: "70 g", cassonade: "105 g", creme: "35 cl" },
      { nb: 8, limonade: "1,6 L", caramel: "225 g", beurre: "80 g", cassonade: "120 g", creme: "40 cl" },
      { nb: 9, limonade: "1,8 L", caramel: "300 g", beurre: "90 g", cassonade: "135 g", creme: "45 cl" },
      { nb: 10, limonade: "2 L", caramel: "300 g", beurre: "100 g", cassonade: "150 g", creme: "50 cl" },
      { nb: 11, limonade: "2,2 L", caramel: "300 g", beurre: "110 g", cassonade: "150 g", creme: "55 cl" },
      { nb: 12, limonade: "2,4 L", caramel: "375 g", beurre: "120 g", cassonade: "150 g", creme: "60 cl" },
      { nb: 13, limonade: "2,6 L", caramel: "375 g", beurre: "130 g", cassonade: "225 g", creme: "65 cl" },
      { nb: 14, limonade: "2,8 L", caramel: "450 g", beurre: "140 g", cassonade: "225 g", creme: "70 cl" },
      { nb: 15, limonade: "3 L", caramel: "450 g", beurre: "150 g", cassonade: "225 g", creme: "75 cl" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧈", titre: "Le sirop beurré", detail: "Dans une petite casserole à feu doux, faire fondre le beurre avec le caramel beurre salé et la cassonade. Mélanger jusqu'à obtenir un sirop lisse et brillant. Hors du feu, ajouter la vanille (≈1 c.à.c pour 4 verres).", badge: "⏱ 5 min" },
      { icone: "❄️", titre: "Faire tiédir", detail: "Laisser refroidir le sirop quelques minutes. ASTUCE : s'il est trop chaud, il fera retomber les bulles de la limonade.", badge: "⏱ 5 min" },
      { icone: "🥛", titre: "La mousse signature", detail: "Fouetter la crème BIEN FROIDE avec 1 c.à.s de caramel et un peu de sucre glace, jusqu'à une mousse SOUPLE (surtout pas ferme : elle doit encore couler un peu).", badge: "⏱ 3 min" },
      { icone: "🥤", titre: "Assembler", detail: "Au fond de chaque verre, verser le sirop beurré tiède. Compléter avec la limonade (ou un cream soda) bien fraîche, en remuant délicatement pour garder les bulles.", badge: null },
      { icone: "✨", titre: "Couronner de mousse", detail: "Déposer généreusement la mousse à la crème sur le dessus, façon faux-col de bière. Un filet de caramel par-dessus pour la gourmandise.", badge: null },
      { icone: "🪄", titre: "Service magique", detail: "Servir AUSSITÔT, mousse débordante. Version froide en été ; pour une version chaude réconfortante, remplacer la limonade par du lait chaud vanillé. À déguster même par les sorciers de moins de 11 ans !", badge: null }
    ]
  },
  shirleytemple: {
    nom: "Shirley Temple",
    dateAjout: "2026-06-04",
    cat: "mocktails", pays: "usa",
    base: 1,
    temps: "3 min",
    niveau: "⭐ Très facile",
    emoji: "🍒",
    description: "Le mocktail rétro préféré des enfants : limonade pétillante, grenadine et cerise. Doux, fruité et festif.",
    tableauShirleytemple: [
      { nb: 1, limonade: "15 cl", grenadine: "2 cl", citronvert: "40 g", cerise: "1" },
      { nb: 2, limonade: "30 cl", grenadine: "4 cl", citronvert: "1", cerise: "2" },
      { nb: 3, limonade: "45 cl", grenadine: "6 cl", citronvert: "120 g", cerise: "3" },
      { nb: 4, limonade: "60 cl", grenadine: "8 cl", citronvert: "2", cerise: "4" },
      { nb: 5, limonade: "75 cl", grenadine: "10 cl", citronvert: "200 g", cerise: "5" },
      { nb: 6, limonade: "90 cl", grenadine: "12 cl", citronvert: "3", cerise: "6" },
      { nb: 7, limonade: "1,05 L", grenadine: "14 cl", citronvert: "280 g", cerise: "7" },
      { nb: 8, limonade: "1,2 L", grenadine: "16 cl", citronvert: "4", cerise: "8" },
      { nb: 9, limonade: "1,35 L", grenadine: "18 cl", citronvert: "360 g", cerise: "9" },
      { nb: 10, limonade: "1,5 L", grenadine: "20 cl", citronvert: "5", cerise: "10" },
      { nb: 11, limonade: "1,65 L", grenadine: "22 cl", citronvert: "440 g", cerise: "11" },
      { nb: 12, limonade: "1,8 L", grenadine: "24 cl", citronvert: "6", cerise: "12" },
      { nb: 13, limonade: "1,95 L", grenadine: "26 cl", citronvert: "520 g", cerise: "13" },
      { nb: 14, limonade: "2,1 L", grenadine: "28 cl", citronvert: "7", cerise: "14" },
      { nb: 15, limonade: "2,25 L", grenadine: "30 cl", citronvert: "600 g", cerise: "15" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧊", titre: "Glace", detail: "Remplir un grand verre de glaçons.", badge: null },
      { icone: "🍒", titre: "Grenadine", detail: "Verser le sirop de grenadine au fond du verre.", badge: null },
      { icone: "🥤", titre: "Limonade", detail: "Compléter doucement avec la limonade bien fraîche pour conserver les bulles.", badge: null },
      { icone: "🍋", titre: "Citron", detail: "Presser le demi-citron vert.", badge: null },
      { icone: "🥄", titre: "Mélanger", detail: "Remuer délicatement une fois.", badge: null },
      { icone: "🍒", titre: "Garnir & servir", detail: "Décorer d'une cerise et d'une paille. ASTUCE CHEF : versez la grenadine en dernier sur le dos d'une cuillère pour un dégradé rouge spectaculaire.", badge: null }
    ]
  },
  virginspritz: {
    nom: "Virgin Spritz",
    dateAjout: "2026-06-04",
    cat: "mocktails", pays: "italie",
    base: 1,
    temps: "4 min",
    niveau: "⭐ Facile",
    emoji: "🍊",
    description: "La version sans alcool du spritz italien : jus d'orange, soda amer et eau gazeuse. Pétillant, légèrement amer et très désaltérant.",
    tableauVirginspritz: [
      { nb: 1, jusorange: "6 cl", sodaamer: "6 cl", eauGaz: "6 cl", orange: "1" },
      { nb: 2, jusorange: "12 cl", sodaamer: "12 cl", eauGaz: "12 cl", orange: "2" },
      { nb: 3, jusorange: "18 cl", sodaamer: "18 cl", eauGaz: "18 cl", orange: "3" },
      { nb: 4, jusorange: "24 cl", sodaamer: "24 cl", eauGaz: "24 cl", orange: "4" },
      { nb: 5, jusorange: "30 cl", sodaamer: "30 cl", eauGaz: "30 cl", orange: "5" },
      { nb: 6, jusorange: "36 cl", sodaamer: "36 cl", eauGaz: "36 cl", orange: "6" },
      { nb: 7, jusorange: "42 cl", sodaamer: "42 cl", eauGaz: "42 cl", orange: "7" },
      { nb: 8, jusorange: "48 cl", sodaamer: "48 cl", eauGaz: "48 cl", orange: "8" },
      { nb: 9, jusorange: "54 cl", sodaamer: "54 cl", eauGaz: "54 cl", orange: "9" },
      { nb: 10, jusorange: "60 cl", sodaamer: "60 cl", eauGaz: "60 cl", orange: "10" },
      { nb: 11, jusorange: "66 cl", sodaamer: "66 cl", eauGaz: "66 cl", orange: "11" },
      { nb: 12, jusorange: "72 cl", sodaamer: "72 cl", eauGaz: "72 cl", orange: "12" },
      { nb: 13, jusorange: "78 cl", sodaamer: "78 cl", eauGaz: "78 cl", orange: "13" },
      { nb: 14, jusorange: "84 cl", sodaamer: "84 cl", eauGaz: "84 cl", orange: "14" },
      { nb: 15, jusorange: "90 cl", sodaamer: "90 cl", eauGaz: "90 cl", orange: "15" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧊", titre: "Glace", detail: "Remplir un grand verre à vin de glaçons.", badge: null },
      { icone: "🍊", titre: "Jus", detail: "Verser le jus d'orange.", badge: null },
      { icone: "🌿", titre: "Amer", detail: "Ajouter le soda amer sans alcool.", badge: null },
      { icone: "💧", titre: "Bulles", detail: "Compléter avec l'eau gazeuse.", badge: null },
      { icone: "🥄", titre: "Mélanger", detail: "Remuer délicatement.", badge: null },
      { icone: "🍊", titre: "Garnir & servir", detail: "Décorer d'une tranche d'orange et d'une olive verte. ASTUCE CHEF : un soupçon de jus de pamplemousse apporte l'amertume typique du spritz.", badge: null }
    ]
  },
  thepechemaison: {
    nom: "Thé glacé pêche maison",
    dateAjout: "2026-06-04",
    cat: "mocktails", pays: "france",
    base: 1,
    temps: "10 min + repos",
    niveau: "⭐ Facile",
    emoji: "🍑",
    description: "Un thé glacé maison bien meilleur que ceux du commerce : thé noir infusé, pêche fraîche, citron et juste ce qu'il faut de sucre.",
    tableauThepechemaison: [
      { nb: 1, thenoir: "20 cl", peche: "75 g", juscitron: "1 cl", siropsucre: "2 cl" },
      { nb: 2, thenoir: "40 cl", peche: "1", juscitron: "2 cl", siropsucre: "4 cl" },
      { nb: 3, thenoir: "60 cl", peche: "225 g", juscitron: "3 cl", siropsucre: "6 cl" },
      { nb: 4, thenoir: "80 cl", peche: "2", juscitron: "4 cl", siropsucre: "8 cl" },
      { nb: 5, thenoir: "1 L", peche: "375 g", juscitron: "5 cl", siropsucre: "10 cl" },
      { nb: 6, thenoir: "1,2 L", peche: "3", juscitron: "6 cl", siropsucre: "12 cl" },
      { nb: 7, thenoir: "1,4 L", peche: "525 g", juscitron: "7 cl", siropsucre: "14 cl" },
      { nb: 8, thenoir: "1,6 L", peche: "4", juscitron: "8 cl", siropsucre: "16 cl" },
      { nb: 9, thenoir: "1,8 L", peche: "675 g", juscitron: "9 cl", siropsucre: "18 cl" },
      { nb: 10, thenoir: "2 L", peche: "5", juscitron: "10 cl", siropsucre: "20 cl" },
      { nb: 11, thenoir: "2,2 L", peche: "825 g", juscitron: "11 cl", siropsucre: "22 cl" },
      { nb: 12, thenoir: "2,4 L", peche: "6", juscitron: "12 cl", siropsucre: "24 cl" },
      { nb: 13, thenoir: "2,6 L", peche: "975 g", juscitron: "13 cl", siropsucre: "26 cl" },
      { nb: 14, thenoir: "2,8 L", peche: "7", juscitron: "14 cl", siropsucre: "28 cl" },
      { nb: 15, thenoir: "3 L", peche: "1125 g", juscitron: "15 cl", siropsucre: "30 cl" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫖", titre: "Infuser", detail: "Faire infuser le thé noir 4 minutes dans une eau frémissante, pas plus, pour éviter l'amertume.", badge: "⏱ 4 min" },
      { icone: "🍯", titre: "Sucrer", detail: "Retirer le sachet et sucrer légèrement l'infusion.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser refroidir complètement.", badge: null },
      { icone: "🍑", titre: "Pêche", detail: "Couper la pêche en fines lamelles et en déposer dans le verre.", badge: null },
      { icone: "🧊", titre: "Assembler", detail: "Remplir de glaçons, verser le thé froid et le jus de citron.", badge: null },
      { icone: "🥄", titre: "Mélanger", detail: "Remuer et goûter pour ajuster le sucre.", badge: null },
      { icone: "🍑", titre: "Servir", detail: "Servir bien frais. ASTUCE CHEF : écrasez quelques morceaux de pêche au fond du verre pour un thé glacé naturellement parfumé.", badge: null }
    ]
  },
  virginmargarita: {
    nom: "Virgin Margarita",
    dateAjout: "2026-06-04",
    cat: "mocktails", pays: "mexique",
    base: 1,
    temps: "4 min",
    niveau: "⭐ Facile",
    emoji: "🍸",
    description: "La margarita sans alcool : citron vert, orange et sirop d'agave, avec un bord de verre givré au sel. Acidulé et rafraîchissant.",
    tableauVirginmargarita: [
      { nb: 1, juscitronvert: "2 cl", jusorange: "4 cl", siropagave: "1,5 cl", eauGaz: "4 cl", sel: "1 g" },
      { nb: 2, juscitronvert: "4 cl", jusorange: "8 cl", siropagave: "3 cl", eauGaz: "8 cl", sel: "2 g" },
      { nb: 3, juscitronvert: "6 cl", jusorange: "12 cl", siropagave: "4,5 cl", eauGaz: "12 cl", sel: "3 g" },
      { nb: 4, juscitronvert: "8 cl", jusorange: "16 cl", siropagave: "6 cl", eauGaz: "16 cl", sel: "4 g" },
      { nb: 5, juscitronvert: "10 cl", jusorange: "20 cl", siropagave: "7,5 cl", eauGaz: "20 cl", sel: "5 g" },
      { nb: 6, juscitronvert: "12 cl", jusorange: "24 cl", siropagave: "9 cl", eauGaz: "24 cl", sel: "6 g" },
      { nb: 7, juscitronvert: "14 cl", jusorange: "28 cl", siropagave: "10,5 cl", eauGaz: "28 cl", sel: "7 g" },
      { nb: 8, juscitronvert: "16 cl", jusorange: "32 cl", siropagave: "12 cl", eauGaz: "32 cl", sel: "8 g" },
      { nb: 9, juscitronvert: "18 cl", jusorange: "36 cl", siropagave: "13,5 cl", eauGaz: "36 cl", sel: "9 g" },
      { nb: 10, juscitronvert: "20 cl", jusorange: "40 cl", siropagave: "15 cl", eauGaz: "40 cl", sel: "10 g" },
      { nb: 11, juscitronvert: "22 cl", jusorange: "44 cl", siropagave: "16,5 cl", eauGaz: "44 cl", sel: "11 g" },
      { nb: 12, juscitronvert: "24 cl", jusorange: "48 cl", siropagave: "18 cl", eauGaz: "48 cl", sel: "12 g" },
      { nb: 13, juscitronvert: "26 cl", jusorange: "52 cl", siropagave: "19,5 cl", eauGaz: "52 cl", sel: "13 g" },
      { nb: 14, juscitronvert: "28 cl", jusorange: "56 cl", siropagave: "21 cl", eauGaz: "56 cl", sel: "14 g" },
      { nb: 15, juscitronvert: "30 cl", jusorange: "60 cl", siropagave: "22,5 cl", eauGaz: "60 cl", sel: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧂", titre: "Givrer", detail: "Passer un quartier de citron sur le bord du verre puis le tremper dans le sel fin.", badge: null },
      { icone: "🥃", titre: "Au shaker", detail: "Verser le jus de citron vert, le jus d'orange et le sirop d'agave dans un shaker avec des glaçons.", badge: null },
      { icone: "🤝", titre: "Frapper", detail: "Secouer une dizaine de secondes.", badge: null },
      { icone: "🍸", titre: "Verser", detail: "Filtrer dans le verre givré rempli de glace.", badge: null },
      { icone: "💧", titre: "Allonger", detail: "Compléter d'un trait d'eau gazeuse.", badge: null },
      { icone: "🥄", titre: "Mélanger & servir", detail: "Remuer délicatement et servir. ASTUCE CHEF : remplacez le sirop d'agave par du miel détendu à l'eau chaude pour une douceur plus parfumée.", badge: null }
    ]
  },
  gingerbeer: {
    nom: "Ginger beer maison",
    dateAjout: "2026-06-05",
    cat: "mocktails", pays: "angleterre",
    base: 1,
    temps: "15 min + repos",
    niveau: "⭐ Facile",
    emoji: "🫚",
    description: "Une limonade pétillante et relevée au gingembre frais, sans alcool. Piquante, désaltérante et naturellement parfumée.",
    tableauGingerbeer: [
      { nb: 1, gingembre: "15 g", juscitron: "2 cl", sucrecanne: "10 g", eauGaz: "18 cl" },
      { nb: 2, gingembre: "30 g", juscitron: "4 cl", sucrecanne: "20 g", eauGaz: "36 cl" },
      { nb: 3, gingembre: "45 g", juscitron: "6 cl", sucrecanne: "30 g", eauGaz: "54 cl" },
      { nb: 4, gingembre: "60 g", juscitron: "8 cl", sucrecanne: "40 g", eauGaz: "72 cl" },
      { nb: 5, gingembre: "75 g", juscitron: "10 cl", sucrecanne: "50 g", eauGaz: "90 cl" },
      { nb: 6, gingembre: "90 g", juscitron: "12 cl", sucrecanne: "60 g", eauGaz: "1,08 L" },
      { nb: 7, gingembre: "105 g", juscitron: "14 cl", sucrecanne: "70 g", eauGaz: "1,26 L" },
      { nb: 8, gingembre: "120 g", juscitron: "16 cl", sucrecanne: "80 g", eauGaz: "1,44 L" },
      { nb: 9, gingembre: "135 g", juscitron: "18 cl", sucrecanne: "90 g", eauGaz: "1,62 L" },
      { nb: 10, gingembre: "150 g", juscitron: "20 cl", sucrecanne: "100 g", eauGaz: "1,8 L" },
      { nb: 11, gingembre: "165 g", juscitron: "22 cl", sucrecanne: "110 g", eauGaz: "1,98 L" },
      { nb: 12, gingembre: "180 g", juscitron: "24 cl", sucrecanne: "120 g", eauGaz: "2,16 L" },
      { nb: 13, gingembre: "195 g", juscitron: "26 cl", sucrecanne: "130 g", eauGaz: "2,34 L" },
      { nb: 14, gingembre: "210 g", juscitron: "28 cl", sucrecanne: "140 g", eauGaz: "2,52 L" },
      { nb: 15, gingembre: "225 g", juscitron: "30 cl", sucrecanne: "150 g", eauGaz: "2,7 L" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫚", titre: "Râper", detail: "Râper finement le gingembre frais, bien lavé (avec la peau).", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Faire chauffer le gingembre avec le sucre et un peu d'eau 5 minutes pour obtenir un sirop parfumé.", badge: "⏱ 5 min" },
      { icone: "⏳", titre: "Infuser", detail: "Laisser infuser hors du feu, puis filtrer.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser tiédir le sirop.", badge: null },
      { icone: "🧊", titre: "Assembler", detail: "Dans un verre rempli de glaçons, verser le sirop de gingembre et le jus de citron.", badge: null },
      { icone: "💧", titre: "Pétiller", detail: "Compléter avec l'eau gazeuse bien fraîche.", badge: null },
      { icone: "🥄", titre: "Servir", detail: "Remuer et servir. ASTUCE CHEF : ajustez la dose de sirop ; plus vous en mettez, plus ça pique délicieusement en fin de bouche.", badge: null }
    ]
  },
  hibiscuscooler: {
    nom: "Hibiscus cooler",
    dateAjout: "2026-06-05",
    cat: "mocktails", pays: "mexique",
    base: 1,
    temps: "10 min + repos",
    niveau: "⭐ Facile",
    emoji: "🌺",
    description: "Une boisson rouge rubis sans alcool à base d'infusion d'hibiscus, citron vert et menthe, allongée d'eau pétillante. Acidulée et rafraîchissante.",
    tableauHibiscuscooler: [
      { nb: 1, hibiscusseche: "2 g", eau: "12 cl", juscitronvert: "1,5 cl", sucrecanne: "10 g", eauGaz: "5 cl", menthe: "3 feuilles" },
      { nb: 2, hibiscusseche: "4 g", eau: "24 cl", juscitronvert: "3 cl", sucrecanne: "20 g", eauGaz: "10 cl", menthe: "6 feuilles" },
      { nb: 3, hibiscusseche: "6 g", eau: "36 cl", juscitronvert: "4,5 cl", sucrecanne: "30 g", eauGaz: "15 cl", menthe: "9 feuilles" },
      { nb: 4, hibiscusseche: "8 g", eau: "48 cl", juscitronvert: "6 cl", sucrecanne: "40 g", eauGaz: "20 cl", menthe: "12 feuilles" },
      { nb: 5, hibiscusseche: "10 g", eau: "60 cl", juscitronvert: "7,5 cl", sucrecanne: "50 g", eauGaz: "25 cl", menthe: "15 feuilles" },
      { nb: 6, hibiscusseche: "12 g", eau: "72 cl", juscitronvert: "9 cl", sucrecanne: "60 g", eauGaz: "30 cl", menthe: "18 feuilles" },
      { nb: 7, hibiscusseche: "14 g", eau: "84 cl", juscitronvert: "10,5 cl", sucrecanne: "70 g", eauGaz: "35 cl", menthe: "21 feuilles" },
      { nb: 8, hibiscusseche: "16 g", eau: "96 cl", juscitronvert: "12 cl", sucrecanne: "80 g", eauGaz: "40 cl", menthe: "24 feuilles" },
      { nb: 9, hibiscusseche: "18 g", eau: "1,08 L", juscitronvert: "13,5 cl", sucrecanne: "90 g", eauGaz: "45 cl", menthe: "27 feuilles" },
      { nb: 10, hibiscusseche: "20 g", eau: "1,2 L", juscitronvert: "15 cl", sucrecanne: "100 g", eauGaz: "50 cl", menthe: "30 feuilles" },
      { nb: 11, hibiscusseche: "22 g", eau: "1,32 L", juscitronvert: "16,5 cl", sucrecanne: "110 g", eauGaz: "55 cl", menthe: "33 feuilles" },
      { nb: 12, hibiscusseche: "24 g", eau: "1,44 L", juscitronvert: "18 cl", sucrecanne: "120 g", eauGaz: "60 cl", menthe: "36 feuilles" },
      { nb: 13, hibiscusseche: "26 g", eau: "1,56 L", juscitronvert: "19,5 cl", sucrecanne: "130 g", eauGaz: "65 cl", menthe: "39 feuilles" },
      { nb: 14, hibiscusseche: "28 g", eau: "1,68 L", juscitronvert: "21 cl", sucrecanne: "140 g", eauGaz: "70 cl", menthe: "42 feuilles" },
      { nb: 15, hibiscusseche: "30 g", eau: "1,8 L", juscitronvert: "22,5 cl", sucrecanne: "150 g", eauGaz: "75 cl", menthe: "45 feuilles" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌺", titre: "Infuser", detail: "Faire infuser les fleurs d'hibiscus séchées 5 minutes dans l'eau chaude, puis filtrer.", badge: "⏱ 5 min" },
      { icone: "🍯", titre: "Sucrer", detail: "Sucrer l'infusion encore chaude.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser refroidir complètement.", badge: null },
      { icone: "🧊", titre: "Glace", detail: "Remplir un verre de glaçons.", badge: null },
      { icone: "🍷", titre: "Assembler", detail: "Verser l'infusion d'hibiscus et le jus de citron vert.", badge: null },
      { icone: "💧", titre: "Pétiller", detail: "Compléter avec l'eau gazeuse et remuer délicatement.", badge: null },
      { icone: "🌿", titre: "Servir", detail: "Décorer de feuilles de menthe fraîche. ASTUCE CHEF : ne dépassez pas 5 minutes d'infusion, l'hibiscus devient amer ; mieux vaut court et corsé.", badge: null }
    ]
  },
  milkshakefraise: {
    liees: ["glacevanille"],
    nom: "Milkshake à la Fraise",
    dateAjout: "2026-06-06T12:51:00",
    cat: "mocktails", pays: "usa",
    base: 4,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥤",
    description: "Un milkshake crémeux et gourmand à la fraise : fraises fraîches mixées avec du lait bien froid et une boule de glace vanille.",
    tableauMilkshakefraise: [
      { nb: 1, fraises: "80 g", lait: "15 cl", glacevanille: "1", sucre: "selon envie" },
      { nb: 2, fraises: "160 g", lait: "30 cl", glacevanille: "2", sucre: "selon envie" },
      { nb: 3, fraises: "240 g", lait: "45 cl", glacevanille: "3", sucre: "selon envie" },
      { nb: 4, fraises: "320 g", lait: "60 cl", glacevanille: "4", sucre: "selon envie" },
      { nb: 5, fraises: "400 g", lait: "75 cl", glacevanille: "5", sucre: "selon envie" },
      { nb: 6, fraises: "480 g", lait: "90 cl", glacevanille: "6", sucre: "selon envie" },
      { nb: 7, fraises: "560 g", lait: "105 cl", glacevanille: "7", sucre: "selon envie" },
      { nb: 8, fraises: "640 g", lait: "120 cl", glacevanille: "8", sucre: "selon envie" },
      { nb: 9, fraises: "720 g", lait: "135 cl", glacevanille: "9", sucre: "selon envie" },
      { nb: 10, fraises: "800 g", lait: "150 cl", glacevanille: "10", sucre: "selon envie" },
      { nb: 11, fraises: "880 g", lait: "165 cl", glacevanille: "11", sucre: "selon envie" },
      { nb: 12, fraises: "960 g", lait: "180 cl", glacevanille: "12", sucre: "selon envie" },
      { nb: 13, fraises: "1040 g", lait: "195 cl", glacevanille: "13", sucre: "selon envie" },
      { nb: 14, fraises: "1120 g", lait: "210 cl", glacevanille: "14", sucre: "selon envie" },
      { nb: 15, fraises: "1200 g", lait: "225 cl", glacevanille: "15", sucre: "selon envie" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍓", titre: "Préparer les fraises", detail: "Équeuter et couper les fraises. ASTUCE CHEF : des fraises bien mûres, voire un peu trop, apportent assez de sucre pour ne pas en rajouter.", badge: null },
      { icone: "❄️", titre: "Tout au frais", detail: "Mettre lait et verre au frais pour un résultat bien glacé.", badge: null },
      { icone: "🥤", titre: "Mixer", detail: "Mixer fraises, lait et glace vanille jusqu'à onctuosité.", badge: null },
      { icone: "🍯", titre: "Ajuster", detail: "Goûter et ajuster le sucre si besoin.", badge: null },
      { icone: "🥛", titre: "Verser", detail: "Verser dans un grand verre.", badge: null },
      { icone: "🍓", titre: "Servir", detail: "Décorer d'une fraise et servir aussitôt avec une paille.", badge: null }
    ]
  },
  frappefraise: {
    nom: "Frappé à la Fraise",
    dateAjout: "2026-06-06T12:50:00",
    cat: "mocktails", pays: "france",
    base: 4,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🧊",
    description: "Un frappé glacé et désaltérant à la fraise et à la menthe, sans alcool, mixé avec de la glace pilée.",
    tableauFrappefraise: [
      { nb: 1, fraises: "80 g", glacons: "6", citronvert: "20 g", sucre: "5 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 2, fraises: "160 g", glacons: "12", citronvert: "40 g", sucre: "10 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 3, fraises: "240 g", glacons: "18", citronvert: "60 g", sucre: "15 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 4, fraises: "320 g", glacons: "24", citronvert: "1", sucre: "20 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 5, fraises: "400 g", glacons: "30", citronvert: "100 g", sucre: "25 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 6, fraises: "480 g", glacons: "36", citronvert: "120 g", sucre: "30 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 7, fraises: "560 g", glacons: "42", citronvert: "140 g", sucre: "35 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 8, fraises: "640 g", glacons: "48", citronvert: "2", sucre: "40 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 9, fraises: "720 g", glacons: "54", citronvert: "180 g", sucre: "45 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 10, fraises: "800 g", glacons: "60", citronvert: "200 g", sucre: "50 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 11, fraises: "880 g", glacons: "66", citronvert: "220 g", sucre: "55 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 12, fraises: "960 g", glacons: "72", citronvert: "3", sucre: "60 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 13, fraises: "1040 g", glacons: "78", citronvert: "260 g", sucre: "65 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 14, fraises: "1120 g", glacons: "84", citronvert: "280 g", sucre: "70 g", menthe: "selon envie", eaupetillante: "trait" },
      { nb: 15, fraises: "1200 g", glacons: "90", citronvert: "300 g", sucre: "75 g", menthe: "selon envie", eaupetillante: "trait" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍓", titre: "Fraises", detail: "Équeuter les fraises.", badge: null },
      { icone: "🧊", titre: "Mixer", detail: "Mixer fraises, glaçons, citron vert, sucre et menthe en granité. ASTUCE CHEF : mixez par à-coups pour casser la glace sans la liquéfier, le frappé doit rester neigeux.", badge: null },
      { icone: "🥄", titre: "Texture", detail: "Vérifier la texture, ajouter un glaçon si trop liquide.", badge: null },
      { icone: "🥤", titre: "Verser", detail: "Verser dans un verre bien froid.", badge: null },
      { icone: "🫧", titre: "Pétillant", detail: "Compléter d'un trait d'eau pétillante.", badge: null },
      { icone: "🌿", titre: "Servir", detail: "Décorer de menthe et d'une fraise, servir avec une paille.", badge: null }
    ]
  },
  switcha: {
    dateAjout: "2026-07-22T14:03:00",
    nom: "Switcha",
    cat: "mocktails", pays: "bahamas",
    base: 4,
    temps: "15 min + frais",
    niveau: "⭐ Facile",
    emoji: "🍋",
    description: "Switcha — la citronnade nationale des Bahamas : du citron vert fraîchement pressé, du sucre et de l'eau bien froide, rien de plus. Servie sur glace, ultra-désaltérante, c'est la boisson de tous les instants de l'archipel, du pique-nique de plage au déjeuner du dimanche.",
    tableauSwitcha: [
      { nb: 1, citronvert: "1½", sucre: "15 g", sel: "0.5 g" },
      { nb: 2, citronvert: "3", sucre: "30 g", sel: "1 g" },
      { nb: 3, citronvert: "4½", sucre: "45 g", sel: "1.5 g" },
      { nb: 4, citronvert: "6", sucre: "60 g", sel: "2 g" },
      { nb: 5, citronvert: "7½", sucre: "75 g", sel: "2.5 g" },
      { nb: 6, citronvert: "9", sucre: "90 g", sel: "3 g" },
      { nb: 7, citronvert: "10½", sucre: "105 g", sel: "3.5 g" },
      { nb: 8, citronvert: "12", sucre: "120 g", sel: "4 g" },
      { nb: 9, citronvert: "13½", sucre: "135 g", sel: "4.5 g" },
      { nb: 10, citronvert: "15", sucre: "150 g", sel: "5 g" },
      { nb: 11, citronvert: "16½", sucre: "165 g", sel: "5.5 g" },
      { nb: 12, citronvert: "18", sucre: "180 g", sel: "6 g" },
      { nb: 13, citronvert: "19½", sucre: "195 g", sel: "6.5 g" },
      { nb: 14, citronvert: "21", sucre: "210 g", sel: "7 g" },
      { nb: 15, citronvert: "22½", sucre: "225 g", sel: "7.5 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍋", titre: "Les citrons", detail: "Roulez fermement les citrons verts sous votre paume pour libérer le jus.", badge: null },
      { icone: "🔪", titre: "Couper", detail: "Coupez-les en deux et pressez-les.", badge: null },
      { icone: "🍯", titre: "Le sirop", detail: "Dissolvez le sucre dans un peu d'eau chaude avec la pincée de sel.", badge: null },
      { icone: "🥤", titre: "Mélanger", detail: "Réunissez le jus de citron vert, le sirop et de l'eau bien froide.", badge: null },
      { icone: "👅", titre: "Ajuster", detail: "Goûtez et ajustez : ni trop sucré, ni trop acide.", badge: null },
      { icone: "🧊", titre: "Rafraîchir", detail: "Laissez au réfrigérateur jusqu'à ce que ce soit glacé.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Servez sur beaucoup de glaçons, avec une rondelle de citron vert. Désaltérant — le switcha bahaméen.", badge: null }
    ]
  },
});
