// ============================================================
// recettes_glaces.js — Recettes de catégorie "glaces" (Glaces & Sorbets) — 20 recettes
// 👉 Pour AJOUTER une glace : place-la juste avant le  });  final.
// ============================================================
Object.assign(recettes, {

  glacevanille: {
    nom: "Glace Vanille",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:00:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace vanille maison onctueuse sur base de crème anglaise, parfumée à la gousse.",
    tableauGlaceVanille: [
      { nb: 1, lait: "50 ml", creme: "40 ml", jaunedoeuf: "1", sucre: "20 g", vanille: "1 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", jaunedoeuf: "2", sucre: "40 g", vanille: "2 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", jaunedoeuf: "3", sucre: "60 g", vanille: "3 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", jaunedoeuf: "4", sucre: "80 g", vanille: "4 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", jaunedoeuf: "5", sucre: "100 g", vanille: "5 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", jaunedoeuf: "6", sucre: "120 g", vanille: "6 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", jaunedoeuf: "7", sucre: "140 g", vanille: "7 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", jaunedoeuf: "8", sucre: "160 g", vanille: "8 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", jaunedoeuf: "9", sucre: "180 g", vanille: "9 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", jaunedoeuf: "10", sucre: "200 g", vanille: "10 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", jaunedoeuf: "11", sucre: "220 g", vanille: "11 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", jaunedoeuf: "12", sucre: "240 g", vanille: "12 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", jaunedoeuf: "13", sucre: "260 g", vanille: "13 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", jaunedoeuf: "14", sucre: "280 g", vanille: "14 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", jaunedoeuf: "15", sucre: "300 g", vanille: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Chauffer le lait et la crème avec la gousse de vanille fendue.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter les jaunes avec le sucre jusqu'à blanchiment.", badge: null },
      { icone: "♨️", titre: "Crème anglaise", detail: "Verser le lait chaud sur les jaunes, cuire à feu doux sans bouillir. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir rapidement la crème puis réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner en sorbetière (ou méthode sans).", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Réserver au congélateur pour raffermir.", badge: "⏱ 1 h" }
    ]
  },
  glacechocolat: {
    nom: "Glace Chocolat",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:01:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍫",
    description: "Une glace au chocolat noir intense et crémeuse, sur base de crème anglaise.",
    tableauGlaceChocolat: [
      { nb: 1, lait: "50 ml", creme: "40 ml", chocolatnoir: "25 g", jaunedoeuf: "1", sucre: "15 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", chocolatnoir: "50 g", jaunedoeuf: "2", sucre: "30 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", chocolatnoir: "75 g", jaunedoeuf: "3", sucre: "45 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", chocolatnoir: "100 g", jaunedoeuf: "4", sucre: "60 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", chocolatnoir: "125 g", jaunedoeuf: "5", sucre: "75 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", chocolatnoir: "150 g", jaunedoeuf: "6", sucre: "90 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", chocolatnoir: "175 g", jaunedoeuf: "7", sucre: "105 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", chocolatnoir: "200 g", jaunedoeuf: "8", sucre: "120 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", chocolatnoir: "225 g", jaunedoeuf: "9", sucre: "135 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", chocolatnoir: "250 g", jaunedoeuf: "10", sucre: "150 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", chocolatnoir: "275 g", jaunedoeuf: "11", sucre: "165 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", chocolatnoir: "300 g", jaunedoeuf: "12", sucre: "180 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", chocolatnoir: "325 g", jaunedoeuf: "13", sucre: "195 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", chocolatnoir: "350 g", jaunedoeuf: "14", sucre: "210 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", chocolatnoir: "375 g", jaunedoeuf: "15", sucre: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Verser sur le chocolat haché et lisser.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer la préparation.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner puis raffermir au congélateur.", badge: "⏱ 30 min" }
    ]
  },
  glacepistache: {
    nom: "Glace Pistache",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:02:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace à la pistache, douce et parfumée, à la couleur naturelle délicate.",
    tableauGlacePistache: [
      { nb: 1, lait: "50 ml", creme: "40 ml", pistache: "25 g", jaunedoeuf: "1", sucre: "18 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", pistache: "50 g", jaunedoeuf: "2", sucre: "36 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", pistache: "75 g", jaunedoeuf: "3", sucre: "54 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", pistache: "100 g", jaunedoeuf: "4", sucre: "72 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", pistache: "125 g", jaunedoeuf: "5", sucre: "90 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", pistache: "150 g", jaunedoeuf: "6", sucre: "108 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", pistache: "175 g", jaunedoeuf: "7", sucre: "126 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", pistache: "200 g", jaunedoeuf: "8", sucre: "144 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", pistache: "225 g", jaunedoeuf: "9", sucre: "162 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", pistache: "250 g", jaunedoeuf: "10", sucre: "180 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", pistache: "275 g", jaunedoeuf: "11", sucre: "198 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", pistache: "300 g", jaunedoeuf: "12", sucre: "216 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", pistache: "325 g", jaunedoeuf: "13", sucre: "234 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", pistache: "350 g", jaunedoeuf: "14", sucre: "252 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", pistache: "375 g", jaunedoeuf: "15", sucre: "270 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Pâte", detail: "Mixer les pistaches en pâte fine. ASTUCE CHEF : utilise des pistaches émondées non salées et mixe-les en pâte, c'est plus parfumé et naturel qu'un arôme.", badge: null },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème avec la pâte de pistache.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise sans bouillir.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacecafe: {
    nom: "Glace Café",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:03:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "☕",
    description: "Une glace au café corsée et veloutée, idéale en affogato ou en fin de repas.",
    tableauGlaceCafe: [
      { nb: 1, lait: "50 ml", creme: "40 ml", cafe: "5 g", jaunedoeuf: "1", sucre: "18 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", cafe: "10 g", jaunedoeuf: "2", sucre: "36 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", cafe: "15 g", jaunedoeuf: "3", sucre: "54 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", cafe: "20 g", jaunedoeuf: "4", sucre: "72 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", cafe: "25 g", jaunedoeuf: "5", sucre: "90 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", cafe: "30 g", jaunedoeuf: "6", sucre: "108 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", cafe: "35 g", jaunedoeuf: "7", sucre: "126 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", cafe: "40 g", jaunedoeuf: "8", sucre: "144 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", cafe: "45 g", jaunedoeuf: "9", sucre: "162 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", cafe: "50 g", jaunedoeuf: "10", sucre: "180 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", cafe: "55 g", jaunedoeuf: "11", sucre: "198 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", cafe: "60 g", jaunedoeuf: "12", sucre: "216 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", cafe: "65 g", jaunedoeuf: "13", sucre: "234 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", cafe: "70 g", jaunedoeuf: "14", sucre: "252 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", cafe: "75 g", jaunedoeuf: "15", sucre: "270 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "☕", titre: "Infuser", detail: "Infuser le café fort dans le lait et la crème chauds. ASTUCE CHEF : un expresso serré ou du café soluble de qualité donne plus de profondeur qu'un café allongé.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacecaramel: {
    nom: "Glace Caramel Beurre Salé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:04:00",
    base: 4,
    temps: "35 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "La glace au caramel au beurre salé, gourmande et fondante, aux notes ambrées.",
    tableauGlaceCaramel: [
      { nb: 1, sucre: "25 g", beurre: "8 g", lait: "50 ml", creme: "40 ml", jaunedoeuf: "1", sel: "1 pincée" },
      { nb: 2, sucre: "50 g", beurre: "16 g", lait: "100 ml", creme: "80 ml", jaunedoeuf: "2", sel: "1 pincée" },
      { nb: 3, sucre: "75 g", beurre: "24 g", lait: "150 ml", creme: "120 ml", jaunedoeuf: "3", sel: "1 pincée" },
      { nb: 4, sucre: "100 g", beurre: "32 g", lait: "200 ml", creme: "160 ml", jaunedoeuf: "4", sel: "1 pincée" },
      { nb: 5, sucre: "125 g", beurre: "40 g", lait: "250 ml", creme: "200 ml", jaunedoeuf: "5", sel: "1 pincée" },
      { nb: 6, sucre: "150 g", beurre: "48 g", lait: "300 ml", creme: "240 ml", jaunedoeuf: "6", sel: "2 pincées" },
      { nb: 7, sucre: "175 g", beurre: "56 g", lait: "350 ml", creme: "280 ml", jaunedoeuf: "7", sel: "2 pincées" },
      { nb: 8, sucre: "200 g", beurre: "64 g", lait: "400 ml", creme: "320 ml", jaunedoeuf: "8", sel: "2 pincées" },
      { nb: 9, sucre: "225 g", beurre: "72 g", lait: "450 ml", creme: "360 ml", jaunedoeuf: "9", sel: "2 pincées" },
      { nb: 10, sucre: "250 g", beurre: "80 g", lait: "500 ml", creme: "400 ml", jaunedoeuf: "10", sel: "2 pincées" },
      { nb: 11, sucre: "275 g", beurre: "88 g", lait: "550 ml", creme: "440 ml", jaunedoeuf: "11", sel: "3 pincées" },
      { nb: 12, sucre: "300 g", beurre: "96 g", lait: "600 ml", creme: "480 ml", jaunedoeuf: "12", sel: "3 pincées" },
      { nb: 13, sucre: "325 g", beurre: "104 g", lait: "650 ml", creme: "520 ml", jaunedoeuf: "13", sel: "3 pincées" },
      { nb: 14, sucre: "350 g", beurre: "112 g", lait: "700 ml", creme: "560 ml", jaunedoeuf: "14", sel: "3 pincées" },
      { nb: 15, sucre: "375 g", beurre: "120 g", lait: "750 ml", creme: "600 ml", jaunedoeuf: "15", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel", detail: "Réaliser un caramel à sec puis décuire au beurre salé. ASTUCE CHEF : pousse le caramel jusqu'à une couleur ambrée foncée (sans brûler) : c'est l'amertume légère qui fait le caractère du caramel beurre salé.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Détendre", detail: "Verser lait et crème chauds sur le caramel.", badge: null },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter le jaune.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise caramel.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacestracciatella: {
    nom: "Glace Stracciatella",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:05:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace italienne au lait parsemée d'éclats de chocolat croquants.",
    tableauGlaceStracciatella: [
      { nb: 1, lait: "50 ml", creme: "40 ml", sucre: "18 g", jaunedoeuf: "1", chocolatnoir: "15 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", sucre: "36 g", jaunedoeuf: "2", chocolatnoir: "30 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", sucre: "54 g", jaunedoeuf: "3", chocolatnoir: "45 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", sucre: "72 g", jaunedoeuf: "4", chocolatnoir: "60 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", sucre: "90 g", jaunedoeuf: "5", chocolatnoir: "75 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", sucre: "108 g", jaunedoeuf: "6", chocolatnoir: "90 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", sucre: "126 g", jaunedoeuf: "7", chocolatnoir: "105 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", sucre: "144 g", jaunedoeuf: "8", chocolatnoir: "120 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", sucre: "162 g", jaunedoeuf: "9", chocolatnoir: "135 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", sucre: "180 g", jaunedoeuf: "10", chocolatnoir: "150 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", sucre: "198 g", jaunedoeuf: "11", chocolatnoir: "165 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", sucre: "216 g", jaunedoeuf: "12", chocolatnoir: "180 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", sucre: "234 g", jaunedoeuf: "13", chocolatnoir: "195 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", sucre: "252 g", jaunedoeuf: "14", chocolatnoir: "210 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", sucre: "270 g", jaunedoeuf: "15", chocolatnoir: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer puis turbiner.", badge: "⏱ 2 h" },
      { icone: "🍫", titre: "Éclats", detail: "En fin de turbinage, verser le chocolat fondu en filet. ASTUCE CHEF : verse le chocolat fondu en mince filet sur la glace en mouvement : il fige instantanément en fins éclats croquants.", badge: null },
      { icone: "🌀", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacementhe: {
    nom: "Glace Menthe-Chocolat",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:06:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🌿",
    description: "La glace menthe fraîche aux pépites de chocolat, rafraîchissante et gourmande.",
    tableauGlaceMenthe: [
      { nb: 1, lait: "50 ml", creme: "40 ml", menthe: "6 g", sucre: "18 g", jaunedoeuf: "1", chocolatnoir: "15 g" },
      { nb: 2, lait: "100 ml", creme: "80 ml", menthe: "12 g", sucre: "36 g", jaunedoeuf: "2", chocolatnoir: "30 g" },
      { nb: 3, lait: "150 ml", creme: "120 ml", menthe: "18 g", sucre: "54 g", jaunedoeuf: "3", chocolatnoir: "45 g" },
      { nb: 4, lait: "200 ml", creme: "160 ml", menthe: "24 g", sucre: "72 g", jaunedoeuf: "4", chocolatnoir: "60 g" },
      { nb: 5, lait: "250 ml", creme: "200 ml", menthe: "30 g", sucre: "90 g", jaunedoeuf: "5", chocolatnoir: "75 g" },
      { nb: 6, lait: "300 ml", creme: "240 ml", menthe: "36 g", sucre: "108 g", jaunedoeuf: "6", chocolatnoir: "90 g" },
      { nb: 7, lait: "350 ml", creme: "280 ml", menthe: "42 g", sucre: "126 g", jaunedoeuf: "7", chocolatnoir: "105 g" },
      { nb: 8, lait: "400 ml", creme: "320 ml", menthe: "48 g", sucre: "144 g", jaunedoeuf: "8", chocolatnoir: "120 g" },
      { nb: 9, lait: "450 ml", creme: "360 ml", menthe: "54 g", sucre: "162 g", jaunedoeuf: "9", chocolatnoir: "135 g" },
      { nb: 10, lait: "500 ml", creme: "400 ml", menthe: "60 g", sucre: "180 g", jaunedoeuf: "10", chocolatnoir: "150 g" },
      { nb: 11, lait: "550 ml", creme: "440 ml", menthe: "66 g", sucre: "198 g", jaunedoeuf: "11", chocolatnoir: "165 g" },
      { nb: 12, lait: "600 ml", creme: "480 ml", menthe: "72 g", sucre: "216 g", jaunedoeuf: "12", chocolatnoir: "180 g" },
      { nb: 13, lait: "650 ml", creme: "520 ml", menthe: "78 g", sucre: "234 g", jaunedoeuf: "13", chocolatnoir: "195 g" },
      { nb: 14, lait: "700 ml", creme: "560 ml", menthe: "84 g", sucre: "252 g", jaunedoeuf: "14", chocolatnoir: "210 g" },
      { nb: 15, lait: "750 ml", creme: "600 ml", menthe: "90 g", sucre: "270 g", jaunedoeuf: "15", chocolatnoir: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Infuser la menthe fraîche dans le lait chaud, puis filtrer. ASTUCE CHEF : infuse de la vraie menthe fraîche puis filtre : le goût est net et naturel, loin du sirop de menthe industriel.", badge: "⏱ 15 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise mentholée.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍫", titre: "Pépites", detail: "Ajouter les pépites de chocolat en fin de turbinage.", badge: null }
    ]
  },
  glacerhumraisin: {
    nom: "Glace Rhum-Raisin",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:07:00",
    base: 4,
    temps: "30 min + macération",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace rhum-raisin, classique des grands, aux raisins moelleux gorgés de rhum.",
    tableauGlaceRhumRaisin: [
      { nb: 1, lait: "50 ml", creme: "40 ml", raisinssecs: "20 g", rhum: "10 ml", sucre: "18 g", jaunedoeuf: "1" },
      { nb: 2, lait: "100 ml", creme: "80 ml", raisinssecs: "40 g", rhum: "20 ml", sucre: "36 g", jaunedoeuf: "2" },
      { nb: 3, lait: "150 ml", creme: "120 ml", raisinssecs: "60 g", rhum: "30 ml", sucre: "54 g", jaunedoeuf: "3" },
      { nb: 4, lait: "200 ml", creme: "160 ml", raisinssecs: "80 g", rhum: "40 ml", sucre: "72 g", jaunedoeuf: "4" },
      { nb: 5, lait: "250 ml", creme: "200 ml", raisinssecs: "100 g", rhum: "50 ml", sucre: "90 g", jaunedoeuf: "5" },
      { nb: 6, lait: "300 ml", creme: "240 ml", raisinssecs: "120 g", rhum: "60 ml", sucre: "108 g", jaunedoeuf: "6" },
      { nb: 7, lait: "350 ml", creme: "280 ml", raisinssecs: "140 g", rhum: "70 ml", sucre: "126 g", jaunedoeuf: "7" },
      { nb: 8, lait: "400 ml", creme: "320 ml", raisinssecs: "160 g", rhum: "80 ml", sucre: "144 g", jaunedoeuf: "8" },
      { nb: 9, lait: "450 ml", creme: "360 ml", raisinssecs: "180 g", rhum: "90 ml", sucre: "162 g", jaunedoeuf: "9" },
      { nb: 10, lait: "500 ml", creme: "400 ml", raisinssecs: "200 g", rhum: "100 ml", sucre: "180 g", jaunedoeuf: "10" },
      { nb: 11, lait: "550 ml", creme: "440 ml", raisinssecs: "220 g", rhum: "110 ml", sucre: "198 g", jaunedoeuf: "11" },
      { nb: 12, lait: "600 ml", creme: "480 ml", raisinssecs: "240 g", rhum: "120 ml", sucre: "216 g", jaunedoeuf: "12" },
      { nb: 13, lait: "650 ml", creme: "520 ml", raisinssecs: "260 g", rhum: "130 ml", sucre: "234 g", jaunedoeuf: "13" },
      { nb: 14, lait: "700 ml", creme: "560 ml", raisinssecs: "280 g", rhum: "140 ml", sucre: "252 g", jaunedoeuf: "14" },
      { nb: 15, lait: "750 ml", creme: "600 ml", raisinssecs: "300 g", rhum: "150 ml", sucre: "270 g", jaunedoeuf: "15" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍇", titre: "Macérer", detail: "Faire gonfler les raisins secs dans le rhum tiède. ASTUCE CHEF : laisse macérer les raisins plusieurs heures (voire une nuit) : moelleux et parfumés, ils ne durciront pas au congélateur.", badge: "⏱ 2 h" },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner la base refroidie.", badge: "⏱ 30 min" },
      { icone: "🍇", titre: "Raisins", detail: "Incorporer les raisins égouttés en fin de turbinage.", badge: null }
    ]
  },
  sorbetcitron: {
    nom: "Sorbet Citron",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:08:00",
    base: 4,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍋",
    description: "Le sorbet citron vif et désaltérant, parfait nettoyeur de palais.",
    tableauSorbetCitron: [
      { nb: 1, citron: "40 ml", eau: "80 ml", sucre: "35 g" },
      { nb: 2, citron: "80 ml", eau: "160 ml", sucre: "70 g" },
      { nb: 3, citron: "120 ml", eau: "240 ml", sucre: "105 g" },
      { nb: 4, citron: "160 ml", eau: "320 ml", sucre: "140 g" },
      { nb: 5, citron: "200 ml", eau: "400 ml", sucre: "175 g" },
      { nb: 6, citron: "240 ml", eau: "480 ml", sucre: "210 g" },
      { nb: 7, citron: "280 ml", eau: "560 ml", sucre: "245 g" },
      { nb: 8, citron: "320 ml", eau: "640 ml", sucre: "280 g" },
      { nb: 9, citron: "360 ml", eau: "720 ml", sucre: "315 g" },
      { nb: 10, citron: "400 ml", eau: "800 ml", sucre: "350 g" },
      { nb: 11, citron: "440 ml", eau: "880 ml", sucre: "385 g" },
      { nb: 12, citron: "480 ml", eau: "960 ml", sucre: "420 g" },
      { nb: 13, citron: "520 ml", eau: "1040 ml", sucre: "455 g" },
      { nb: 14, citron: "560 ml", eau: "1120 ml", sucre: "490 g" },
      { nb: 15, citron: "600 ml", eau: "1200 ml", sucre: "525 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Porter l'eau et le sucre à frémissement pour dissoudre.", badge: "⏱ 4 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser refroidir complètement le sirop. ASTUCE CHEF : un sirop bien froid avant d'ajouter le jus préserve la fraîcheur et la vitamine C du citron.", badge: null },
      { icone: "🍋", titre: "Presser", detail: "Presser les citrons et filtrer le jus.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger sirop froid et jus de citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à texture sorbet.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetframboise: {
    nom: "Sorbet Framboise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:09:00",
    base: 4,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet framboise intensément fruité, à la jolie couleur rubis.",
    tableauSorbetFramboise: [
      { nb: 1, framboise: "90 g", eau: "40 ml", sucre: "30 g", citron: "5 ml" },
      { nb: 2, framboise: "180 g", eau: "80 ml", sucre: "60 g", citron: "10 ml" },
      { nb: 3, framboise: "270 g", eau: "120 ml", sucre: "90 g", citron: "15 ml" },
      { nb: 4, framboise: "360 g", eau: "160 ml", sucre: "120 g", citron: "20 ml" },
      { nb: 5, framboise: "450 g", eau: "200 ml", sucre: "150 g", citron: "25 ml" },
      { nb: 6, framboise: "540 g", eau: "240 ml", sucre: "180 g", citron: "30 ml" },
      { nb: 7, framboise: "630 g", eau: "280 ml", sucre: "210 g", citron: "35 ml" },
      { nb: 8, framboise: "720 g", eau: "320 ml", sucre: "240 g", citron: "40 ml" },
      { nb: 9, framboise: "810 g", eau: "360 ml", sucre: "270 g", citron: "45 ml" },
      { nb: 10, framboise: "900 g", eau: "400 ml", sucre: "300 g", citron: "50 ml" },
      { nb: 11, framboise: "990 g", eau: "440 ml", sucre: "330 g", citron: "55 ml" },
      { nb: 12, framboise: "1080 g", eau: "480 ml", sucre: "360 g", citron: "60 ml" },
      { nb: 13, framboise: "1170 g", eau: "520 ml", sucre: "390 g", citron: "65 ml" },
      { nb: 14, framboise: "1260 g", eau: "560 ml", sucre: "420 g", citron: "70 ml" },
      { nb: 15, framboise: "1350 g", eau: "600 ml", sucre: "450 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre et le refroidir.", badge: "⏱ 5 min" },
      { icone: "🍓", titre: "Coulis", detail: "Mixer les framboises en purée.", badge: null },
      { icone: "🫗", titre: "Tamiser", detail: "Passer la purée au tamis pour retirer les pépins. ASTUCE CHEF : tamise le coulis pour un sorbet tout lisse : sans les pépins, la texture en bouche est bien plus agréable.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetmangue: {
    nom: "Sorbet Mangue",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:10:00",
    base: 4,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🥭",
    description: "Le sorbet mangue exotique et velouté, ensoleillé à souhait.",
    tableauSorbetMangue: [
      { nb: 1, mangue: "100 g", eau: "30 ml", sucre: "25 g", citronvert: "5 ml" },
      { nb: 2, mangue: "200 g", eau: "60 ml", sucre: "50 g", citronvert: "10 ml" },
      { nb: 3, mangue: "300 g", eau: "90 ml", sucre: "75 g", citronvert: "15 ml" },
      { nb: 4, mangue: "400 g", eau: "120 ml", sucre: "100 g", citronvert: "20 ml" },
      { nb: 5, mangue: "500 g", eau: "150 ml", sucre: "125 g", citronvert: "25 ml" },
      { nb: 6, mangue: "600 g", eau: "180 ml", sucre: "150 g", citronvert: "30 ml" },
      { nb: 7, mangue: "700 g", eau: "210 ml", sucre: "175 g", citronvert: "35 ml" },
      { nb: 8, mangue: "800 g", eau: "240 ml", sucre: "200 g", citronvert: "40 ml" },
      { nb: 9, mangue: "900 g", eau: "270 ml", sucre: "225 g", citronvert: "45 ml" },
      { nb: 10, mangue: "1000 g", eau: "300 ml", sucre: "250 g", citronvert: "50 ml" },
      { nb: 11, mangue: "1100 g", eau: "330 ml", sucre: "275 g", citronvert: "55 ml" },
      { nb: 12, mangue: "1200 g", eau: "360 ml", sucre: "300 g", citronvert: "60 ml" },
      { nb: 13, mangue: "1300 g", eau: "390 ml", sucre: "325 g", citronvert: "65 ml" },
      { nb: 14, mangue: "1400 g", eau: "420 ml", sucre: "350 g", citronvert: "70 ml" },
      { nb: 15, mangue: "1500 g", eau: "450 ml", sucre: "375 g", citronvert: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥭", titre: "Purée", detail: "Mixer la chair de mangue bien mûre. ASTUCE CHEF : choisis des mangues très mûres et parfumées : plus le fruit est sucré, moins tu ajoutes de sucre.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger et le refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron vert.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à prise.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser à la spatule.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpassion: {
    nom: "Sorbet Fruit de la Passion",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:11:00",
    base: 4,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet fruit de la passion, acidulé et parfumé, d'une fraîcheur tropicale.",
    tableauSorbetPassion: [
      { nb: 1, fruitpassion: "70 g", eau: "50 ml", sucre: "35 g", citron: "3 ml" },
      { nb: 2, fruitpassion: "140 g", eau: "100 ml", sucre: "70 g", citron: "6 ml" },
      { nb: 3, fruitpassion: "210 g", eau: "150 ml", sucre: "105 g", citron: "9 ml" },
      { nb: 4, fruitpassion: "280 g", eau: "200 ml", sucre: "140 g", citron: "12 ml" },
      { nb: 5, fruitpassion: "350 g", eau: "250 ml", sucre: "175 g", citron: "15 ml" },
      { nb: 6, fruitpassion: "420 g", eau: "300 ml", sucre: "210 g", citron: "18 ml" },
      { nb: 7, fruitpassion: "490 g", eau: "350 ml", sucre: "245 g", citron: "21 ml" },
      { nb: 8, fruitpassion: "560 g", eau: "400 ml", sucre: "280 g", citron: "24 ml" },
      { nb: 9, fruitpassion: "630 g", eau: "450 ml", sucre: "315 g", citron: "27 ml" },
      { nb: 10, fruitpassion: "700 g", eau: "500 ml", sucre: "350 g", citron: "30 ml" },
      { nb: 11, fruitpassion: "770 g", eau: "550 ml", sucre: "385 g", citron: "33 ml" },
      { nb: 12, fruitpassion: "840 g", eau: "600 ml", sucre: "420 g", citron: "36 ml" },
      { nb: 13, fruitpassion: "910 g", eau: "650 ml", sucre: "455 g", citron: "39 ml" },
      { nb: 14, fruitpassion: "980 g", eau: "700 ml", sucre: "490 g", citron: "42 ml" },
      { nb: 15, fruitpassion: "1050 g", eau: "750 ml", sucre: "525 g", citron: "45 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre, refroidir.", badge: "⏱ 5 min" },
      { icone: "💛", titre: "Pulpe", detail: "Récupérer la pulpe des fruits de la passion.", badge: null },
      { icone: "🫗", titre: "Filtrer", detail: "Filtrer une partie de la pulpe pour retirer des graines. ASTUCE CHEF : garde quelques graines pour le croquant et la couleur, mais filtre le reste pour ne pas avoir un sorbet trop granuleux.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger pulpe, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpoire: {
    nom: "Sorbet Poire",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:12:00",
    base: 4,
    temps: "20 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍐",
    description: "Le sorbet poire tout en douceur, délicat et fondant.",
    tableauSorbetPoire: [
      { nb: 1, poire: "100 g", eau: "30 ml", sucre: "25 g", citron: "5 ml" },
      { nb: 2, poire: "200 g", eau: "60 ml", sucre: "50 g", citron: "10 ml" },
      { nb: 3, poire: "300 g", eau: "90 ml", sucre: "75 g", citron: "15 ml" },
      { nb: 4, poire: "400 g", eau: "120 ml", sucre: "100 g", citron: "20 ml" },
      { nb: 5, poire: "500 g", eau: "150 ml", sucre: "125 g", citron: "25 ml" },
      { nb: 6, poire: "600 g", eau: "180 ml", sucre: "150 g", citron: "30 ml" },
      { nb: 7, poire: "700 g", eau: "210 ml", sucre: "175 g", citron: "35 ml" },
      { nb: 8, poire: "800 g", eau: "240 ml", sucre: "200 g", citron: "40 ml" },
      { nb: 9, poire: "900 g", eau: "270 ml", sucre: "225 g", citron: "45 ml" },
      { nb: 10, poire: "1000 g", eau: "300 ml", sucre: "250 g", citron: "50 ml" },
      { nb: 11, poire: "1100 g", eau: "330 ml", sucre: "275 g", citron: "55 ml" },
      { nb: 12, poire: "1200 g", eau: "360 ml", sucre: "300 g", citron: "60 ml" },
      { nb: 13, poire: "1300 g", eau: "390 ml", sucre: "325 g", citron: "65 ml" },
      { nb: 14, poire: "1400 g", eau: "420 ml", sucre: "350 g", citron: "70 ml" },
      { nb: 15, poire: "1500 g", eau: "450 ml", sucre: "375 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍐", titre: "Pocher", detail: "Pocher les poires épluchées dans l'eau sucrée.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer les poires avec un peu de sirop.", badge: null },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le citron pour éviter le brunissement. ASTUCE CHEF : le jus de citron empêche la purée de poire de brunir et relève sa douceur un peu fade.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir complètement.", badge: "⏱ 1 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetfraise: {
    nom: "Sorbet Fraise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:13:00",
    base: 4,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍓",
    description: "Le sorbet fraise gourmand, intense en fruit, idéal en été.",
    tableauSorbetFraise: [
      { nb: 1, fraise: "100 g", eau: "30 ml", sucre: "28 g", citron: "5 ml" },
      { nb: 2, fraise: "200 g", eau: "60 ml", sucre: "56 g", citron: "10 ml" },
      { nb: 3, fraise: "300 g", eau: "90 ml", sucre: "84 g", citron: "15 ml" },
      { nb: 4, fraise: "400 g", eau: "120 ml", sucre: "112 g", citron: "20 ml" },
      { nb: 5, fraise: "500 g", eau: "150 ml", sucre: "140 g", citron: "25 ml" },
      { nb: 6, fraise: "600 g", eau: "180 ml", sucre: "168 g", citron: "30 ml" },
      { nb: 7, fraise: "700 g", eau: "210 ml", sucre: "196 g", citron: "35 ml" },
      { nb: 8, fraise: "800 g", eau: "240 ml", sucre: "224 g", citron: "40 ml" },
      { nb: 9, fraise: "900 g", eau: "270 ml", sucre: "252 g", citron: "45 ml" },
      { nb: 10, fraise: "1000 g", eau: "300 ml", sucre: "280 g", citron: "50 ml" },
      { nb: 11, fraise: "1100 g", eau: "330 ml", sucre: "308 g", citron: "55 ml" },
      { nb: 12, fraise: "1200 g", eau: "360 ml", sucre: "336 g", citron: "60 ml" },
      { nb: 13, fraise: "1300 g", eau: "390 ml", sucre: "364 g", citron: "65 ml" },
      { nb: 14, fraise: "1400 g", eau: "420 ml", sucre: "392 g", citron: "70 ml" },
      { nb: 15, fraise: "1500 g", eau: "450 ml", sucre: "420 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍓", titre: "Purée", detail: "Mixer les fraises en purée. ASTUCE CHEF : équeute et mixe les fraises crues (sans les cuire) pour garder le goût vif et la couleur éclatante du fruit frais.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger, refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser et goûter.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  vacheringlace: {
    nom: "Vacherin Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:14:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍰",
    description: "Le vacherin glacé festif : meringue, crème glacée et coulis de fruits rouges.",
    tableauVacheringGlace: [
      { nb: 1, meringue: "30 g", creme: "60 ml", sucre: "18 g", framboise: "40 g", vanille: "1 g" },
      { nb: 2, meringue: "60 g", creme: "120 ml", sucre: "36 g", framboise: "80 g", vanille: "2 g" },
      { nb: 3, meringue: "90 g", creme: "180 ml", sucre: "54 g", framboise: "120 g", vanille: "3 g" },
      { nb: 4, meringue: "120 g", creme: "240 ml", sucre: "72 g", framboise: "160 g", vanille: "4 g" },
      { nb: 5, meringue: "150 g", creme: "300 ml", sucre: "90 g", framboise: "200 g", vanille: "5 g" },
      { nb: 6, meringue: "180 g", creme: "360 ml", sucre: "108 g", framboise: "240 g", vanille: "6 g" },
      { nb: 7, meringue: "210 g", creme: "420 ml", sucre: "126 g", framboise: "280 g", vanille: "7 g" },
      { nb: 8, meringue: "240 g", creme: "480 ml", sucre: "144 g", framboise: "320 g", vanille: "8 g" },
      { nb: 9, meringue: "270 g", creme: "540 ml", sucre: "162 g", framboise: "360 g", vanille: "9 g" },
      { nb: 10, meringue: "300 g", creme: "600 ml", sucre: "180 g", framboise: "400 g", vanille: "10 g" },
      { nb: 11, meringue: "330 g", creme: "660 ml", sucre: "198 g", framboise: "440 g", vanille: "11 g" },
      { nb: 12, meringue: "360 g", creme: "720 ml", sucre: "216 g", framboise: "480 g", vanille: "12 g" },
      { nb: 13, meringue: "390 g", creme: "780 ml", sucre: "234 g", framboise: "520 g", vanille: "13 g" },
      { nb: 14, meringue: "420 g", creme: "840 ml", sucre: "252 g", framboise: "560 g", vanille: "14 g" },
      { nb: 15, meringue: "450 g", creme: "900 ml", sucre: "270 g", framboise: "600 g", vanille: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly avec un peu de sucre.", badge: null },
      { icone: "🍦", titre: "Glace", detail: "Préparer (ou utiliser) une glace vanille.", badge: null },
      { icone: "🟤", titre: "Meringue", detail: "Émietter ou disposer des meringues. ASTUCE CHEF : monte le vacherin et remets-le au congélateur entre chaque couche pour qu'il garde une forme nette.", badge: null },
      { icone: "🥣", titre: "Monter", detail: "Alterner glace, meringue et chantilly dans un moule.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler le vacherin plusieurs heures.", badge: "⏱ 4 h" },
      { icone: "🍓", titre: "Servir", detail: "Démouler et napper de coulis de framboise.", badge: null }
    ]
  },
  nougatglace: {
    nom: "Nougat Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:15:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍯",
    description: "Le nougat glacé provençal au miel, fruits confits et amandes caramélisées.",
    tableauNougatGlace: [
      { nb: 1, creme: "60 ml", miel: "20 g", oeuf: "1", amandes: "15 g", fruitsconfits: "15 g", sucre: "10 g" },
      { nb: 2, creme: "120 ml", miel: "40 g", oeuf: "2", amandes: "30 g", fruitsconfits: "30 g", sucre: "20 g" },
      { nb: 3, creme: "180 ml", miel: "60 g", oeuf: "3", amandes: "45 g", fruitsconfits: "45 g", sucre: "30 g" },
      { nb: 4, creme: "240 ml", miel: "80 g", oeuf: "4", amandes: "60 g", fruitsconfits: "60 g", sucre: "40 g" },
      { nb: 5, creme: "300 ml", miel: "100 g", oeuf: "5", amandes: "75 g", fruitsconfits: "75 g", sucre: "50 g" },
      { nb: 6, creme: "360 ml", miel: "120 g", oeuf: "6", amandes: "90 g", fruitsconfits: "90 g", sucre: "60 g" },
      { nb: 7, creme: "420 ml", miel: "140 g", oeuf: "7", amandes: "105 g", fruitsconfits: "105 g", sucre: "70 g" },
      { nb: 8, creme: "480 ml", miel: "160 g", oeuf: "8", amandes: "120 g", fruitsconfits: "120 g", sucre: "80 g" },
      { nb: 9, creme: "540 ml", miel: "180 g", oeuf: "9", amandes: "135 g", fruitsconfits: "135 g", sucre: "90 g" },
      { nb: 10, creme: "600 ml", miel: "200 g", oeuf: "10", amandes: "150 g", fruitsconfits: "150 g", sucre: "100 g" },
      { nb: 11, creme: "660 ml", miel: "220 g", oeuf: "11", amandes: "165 g", fruitsconfits: "165 g", sucre: "110 g" },
      { nb: 12, creme: "720 ml", miel: "240 g", oeuf: "12", amandes: "180 g", fruitsconfits: "180 g", sucre: "120 g" },
      { nb: 13, creme: "780 ml", miel: "260 g", oeuf: "13", amandes: "195 g", fruitsconfits: "195 g", sucre: "130 g" },
      { nb: 14, creme: "840 ml", miel: "280 g", oeuf: "14", amandes: "210 g", fruitsconfits: "210 g", sucre: "140 g" },
      { nb: 15, creme: "900 ml", miel: "300 g", oeuf: "15", amandes: "225 g", fruitsconfits: "225 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Nougatine", detail: "Caraméliser les amandes au sucre puis concasser.", badge: "⏱ 6 min" },
      { icone: "🍯", titre: "Meringue", detail: "Monter les blancs et serrer au miel chaud. ASTUCE CHEF : verse le miel bien chaud en filet sur les blancs en neige : ça les cuit légèrement et donne un nougat glacé stable et aérien.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Incorporer délicatement chantilly, fruits confits et amandes.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans un moule à cake.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise complète.", badge: "⏱ 5 h" }
    ]
  },
  bananasplit: {
    nom: "Banana Split",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:16:00",
    base: 2,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍌",
    description: "Le dessert glacé américain : banane, boules de glace, chantilly, sauce chocolat et amandes.",
    tableauBananaSplit: [
      { nb: 1, banane: "1", creme: "40 ml", chocolatnoir: "20 g", amandes: "10 g", sucre: "10 g" },
      { nb: 2, banane: "2", creme: "80 ml", chocolatnoir: "40 g", amandes: "20 g", sucre: "20 g" },
      { nb: 3, banane: "3", creme: "120 ml", chocolatnoir: "60 g", amandes: "30 g", sucre: "30 g" },
      { nb: 4, banane: "4", creme: "160 ml", chocolatnoir: "80 g", amandes: "40 g", sucre: "40 g" },
      { nb: 5, banane: "5", creme: "200 ml", chocolatnoir: "100 g", amandes: "50 g", sucre: "50 g" },
      { nb: 6, banane: "6", creme: "240 ml", chocolatnoir: "120 g", amandes: "60 g", sucre: "60 g" },
      { nb: 7, banane: "7", creme: "280 ml", chocolatnoir: "140 g", amandes: "70 g", sucre: "70 g" },
      { nb: 8, banane: "8", creme: "320 ml", chocolatnoir: "160 g", amandes: "80 g", sucre: "80 g" },
      { nb: 9, banane: "9", creme: "360 ml", chocolatnoir: "180 g", amandes: "90 g", sucre: "90 g" },
      { nb: 10, banane: "10", creme: "400 ml", chocolatnoir: "200 g", amandes: "100 g", sucre: "100 g" },
      { nb: 11, banane: "11", creme: "440 ml", chocolatnoir: "220 g", amandes: "110 g", sucre: "110 g" },
      { nb: 12, banane: "12", creme: "480 ml", chocolatnoir: "240 g", amandes: "120 g", sucre: "120 g" },
      { nb: 13, banane: "13", creme: "520 ml", chocolatnoir: "260 g", amandes: "130 g", sucre: "130 g" },
      { nb: 14, banane: "14", creme: "560 ml", chocolatnoir: "280 g", amandes: "140 g", sucre: "140 g" },
      { nb: 15, banane: "15", creme: "600 ml", chocolatnoir: "300 g", amandes: "150 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍌", titre: "Banane", detail: "Couper la banane en deux dans la longueur.", badge: null },
      { icone: "🍦", titre: "Boules", detail: "Disposer trois boules de glace entre les demi-bananes. ASTUCE CHEF : trempe la cuillère à glace dans l'eau chaude entre chaque boule pour des quenelles nettes et régulières.", badge: null },
      { icone: "🍫", titre: "Sauce", detail: "Faire fondre le chocolat en sauce.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🌰", titre: "Garnir", detail: "Napper de sauce chocolat et chantilly.", badge: null },
      { icone: "🍒", titre: "Servir", detail: "Parsemer d'amandes et servir aussitôt.", badge: null }
    ]
  },
  gelato: {
    nom: "Gelato Fior di Latte",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:17:00",
    base: 4,
    temps: "25 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "Le gelato fior di latte à l'italienne : dense et soyeux, sans œuf, tout en lait.",
    tableauGelato: [
      { nb: 1, lait: "80 ml", creme: "30 ml", sucre: "22 g", fecule: "3 g" },
      { nb: 2, lait: "160 ml", creme: "60 ml", sucre: "44 g", fecule: "6 g" },
      { nb: 3, lait: "240 ml", creme: "90 ml", sucre: "66 g", fecule: "9 g" },
      { nb: 4, lait: "320 ml", creme: "120 ml", sucre: "88 g", fecule: "12 g" },
      { nb: 5, lait: "400 ml", creme: "150 ml", sucre: "110 g", fecule: "15 g" },
      { nb: 6, lait: "480 ml", creme: "180 ml", sucre: "132 g", fecule: "18 g" },
      { nb: 7, lait: "560 ml", creme: "210 ml", sucre: "154 g", fecule: "21 g" },
      { nb: 8, lait: "640 ml", creme: "240 ml", sucre: "176 g", fecule: "24 g" },
      { nb: 9, lait: "720 ml", creme: "270 ml", sucre: "198 g", fecule: "27 g" },
      { nb: 10, lait: "800 ml", creme: "300 ml", sucre: "220 g", fecule: "30 g" },
      { nb: 11, lait: "880 ml", creme: "330 ml", sucre: "242 g", fecule: "33 g" },
      { nb: 12, lait: "960 ml", creme: "360 ml", sucre: "264 g", fecule: "36 g" },
      { nb: 13, lait: "1040 ml", creme: "390 ml", sucre: "286 g", fecule: "39 g" },
      { nb: 14, lait: "1120 ml", creme: "420 ml", sucre: "308 g", fecule: "42 g" },
      { nb: 15, lait: "1200 ml", creme: "450 ml", sucre: "330 g", fecule: "45 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer le lait, la crème et le sucre.", badge: "⏱ 4 min" },
      { icone: "🥄", titre: "Lier", detail: "Délayer la fécule à froid et l'incorporer pour épaissir légèrement. ASTUCE CHEF : le gelato contient moins de crème et d'air qu'une glace : c'est ce qui lui donne sa densité soyeuse caractéristique.", badge: "⏱ 3 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer bien la base.", badge: "⏱ 3 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner lentement.", badge: "⏱ 25 min" },
      { icone: "🍨", titre: "Texture", detail: "Servir plus tempéré qu'une glace classique.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Déguster en boules généreuses.", badge: null }
    ]
  },
  kulfi: {
    nom: "Kulfi",
    cat: "glaces",
    pays: "inde",
    dateAjout: "2026-06-08T21:18:00",
    base: 4,
    temps: "40 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace indienne au lait réduit, parfumée à la cardamome et aux pistaches.",
    tableauKulfi: [
      { nb: 1, lait: "100 ml", laitconcentre: "15 g", sucre: "15 g", cardamome: "1 g", pistache: "8 g" },
      { nb: 2, lait: "200 ml", laitconcentre: "30 g", sucre: "30 g", cardamome: "2 g", pistache: "16 g" },
      { nb: 3, lait: "300 ml", laitconcentre: "45 g", sucre: "45 g", cardamome: "3 g", pistache: "24 g" },
      { nb: 4, lait: "400 ml", laitconcentre: "60 g", sucre: "60 g", cardamome: "4 g", pistache: "32 g" },
      { nb: 5, lait: "500 ml", laitconcentre: "75 g", sucre: "75 g", cardamome: "5 g", pistache: "40 g" },
      { nb: 6, lait: "600 ml", laitconcentre: "90 g", sucre: "90 g", cardamome: "6 g", pistache: "48 g" },
      { nb: 7, lait: "700 ml", laitconcentre: "105 g", sucre: "105 g", cardamome: "7 g", pistache: "56 g" },
      { nb: 8, lait: "800 ml", laitconcentre: "120 g", sucre: "120 g", cardamome: "8 g", pistache: "64 g" },
      { nb: 9, lait: "900 ml", laitconcentre: "135 g", sucre: "135 g", cardamome: "9 g", pistache: "72 g" },
      { nb: 10, lait: "1000 ml", laitconcentre: "150 g", sucre: "150 g", cardamome: "10 g", pistache: "80 g" },
      { nb: 11, lait: "1100 ml", laitconcentre: "165 g", sucre: "165 g", cardamome: "11 g", pistache: "88 g" },
      { nb: 12, lait: "1200 ml", laitconcentre: "180 g", sucre: "180 g", cardamome: "12 g", pistache: "96 g" },
      { nb: 13, lait: "1300 ml", laitconcentre: "195 g", sucre: "195 g", cardamome: "13 g", pistache: "104 g" },
      { nb: 14, lait: "1400 ml", laitconcentre: "210 g", sucre: "210 g", cardamome: "14 g", pistache: "112 g" },
      { nb: 15, lait: "1500 ml", laitconcentre: "225 g", sucre: "225 g", cardamome: "15 g", pistache: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Réduire", detail: "Faire réduire longuement le lait à feu doux. ASTUCE CHEF : réduis le lait de moitié en remuant : cette concentration donne au kulfi son goût lacté intense et sa texture dense.", badge: "⏱ 30 min" },
      { icone: "🍬", titre: "Sucrer", detail: "Ajouter le lait concentré et le sucre.", badge: null },
      { icone: "🌿", titre: "Parfumer", detail: "Parfumer à la cardamome et aux pistaches.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans des moules (sans turbiner).", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise.", badge: "⏱ 5 h" },
      { icone: "🌰", titre: "Servir", detail: "Démouler et parsemer de pistaches.", badge: null }
    ]
  },
  granite: {
    nom: "Granité Citron",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:19:00",
    base: 4,
    temps: "10 min + congélation",
    niveau: "⭐ Facile",
    emoji: "🧊",
    description: "Le granité sicilien au citron, cristaux glacés à gratter à la fourchette, sans sorbetière.",
    tableauGranite: [
      { nb: 1, citron: "40 ml", eau: "90 ml", sucre: "30 g" },
      { nb: 2, citron: "80 ml", eau: "180 ml", sucre: "60 g" },
      { nb: 3, citron: "120 ml", eau: "270 ml", sucre: "90 g" },
      { nb: 4, citron: "160 ml", eau: "360 ml", sucre: "120 g" },
      { nb: 5, citron: "200 ml", eau: "450 ml", sucre: "150 g" },
      { nb: 6, citron: "240 ml", eau: "540 ml", sucre: "180 g" },
      { nb: 7, citron: "280 ml", eau: "630 ml", sucre: "210 g" },
      { nb: 8, citron: "320 ml", eau: "720 ml", sucre: "240 g" },
      { nb: 9, citron: "360 ml", eau: "810 ml", sucre: "270 g" },
      { nb: 10, citron: "400 ml", eau: "900 ml", sucre: "300 g" },
      { nb: 11, citron: "440 ml", eau: "990 ml", sucre: "330 g" },
      { nb: 12, citron: "480 ml", eau: "1080 ml", sucre: "360 g" },
      { nb: 13, citron: "520 ml", eau: "1170 ml", sucre: "390 g" },
      { nb: 14, citron: "560 ml", eau: "1260 ml", sucre: "420 g" },
      { nb: 15, citron: "600 ml", eau: "1350 ml", sucre: "450 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Dissoudre le sucre dans l'eau tiède, refroidir.", badge: "⏱ 4 min" },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le jus de citron filtré.", badge: null },
      { icone: "🧊", titre: "Congeler", detail: "Verser dans un bac peu profond et placer au congélateur.", badge: null },
      { icone: "🍴", titre: "Gratter", detail: "Gratter à la fourchette toutes les 30 min. ASTUCE CHEF : c'est le grattage régulier qui crée les cristaux du granité : ne le laisse jamais prendre en bloc, racle-le 4-5 fois.", badge: "⏱ 2 h" },
      { icone: "❄️", titre: "Texture", detail: "Obtenir une neige de cristaux légers.", badge: null },
      { icone: "🥄", titre: "Servir", detail: "Servir aussitôt en verrines givrées.", badge: null }
    ]
  },
});
