// ============================================================
// recettes_tartinables.js — Recettes de catégorie "tartinables" (Pâtes à tartiner) — 11 recettes
// 👉 Pour AJOUTER une pâte à tartiner : place-la juste avant le  });  final.
// ============================================================
Object.assign(recettes, {
  anchoiade: {
    nom: "Anchoïade",
    cat: "tartinables", pays: "france",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🐟",
    description: "L'anchoïade provençale — anchois, ail et huile d'olive montés en purée puissante et parfumée. À tartiner sur du pain grillé ou en dip avec des légumes croquants.",
    tableauAnchoiade: [
      { nb: 1, anchois: "100 g", ail: "8 g", huileolive: "60 ml", capres: "20 g", vinaigreVin: "10 ml" },
      { nb: 2, anchois: "200 g", ail: "16 g", huileolive: "120 ml", capres: "40 g", vinaigreVin: "20 ml" },
      { nb: 3, anchois: "300 g", ail: "24 g", huileolive: "180 ml", capres: "60 g", vinaigreVin: "30 ml" },
      { nb: 4, anchois: "400 g", ail: "32 g", huileolive: "240 ml", capres: "80 g", vinaigreVin: "40 ml" },
      { nb: 5, anchois: "500 g", ail: "40 g", huileolive: "300 ml", capres: "100 g", vinaigreVin: "50 ml" },
      { nb: 6, anchois: "600 g", ail: "48 g", huileolive: "360 ml", capres: "120 g", vinaigreVin: "60 ml" },
      { nb: 7, anchois: "700 g", ail: "56 g", huileolive: "420 ml", capres: "140 g", vinaigreVin: "70 ml" },
      { nb: 8, anchois: "800 g", ail: "64 g", huileolive: "480 ml", capres: "160 g", vinaigreVin: "80 ml" },
      { nb: 9, anchois: "900 g", ail: "72 g", huileolive: "540 ml", capres: "180 g", vinaigreVin: "90 ml" },
      { nb: 10, anchois: "1000 g", ail: "80 g", huileolive: "600 ml", capres: "200 g", vinaigreVin: "100 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🐟", titre: "Préparer les anchois", detail: "Égoutter les filets d'anchois à l'huile. ASTUCE CHEF : pour une anchoïade plus douce, les rincer rapidement sous l'eau et les éponger.", badge: null },
      { icone: "🧄", titre: "Dégermer l'ail", detail: "Éplucher l'ail et retirer le germe central (c'est lui qui rend l'ail indigeste et trop piquant).", badge: null },
      { icone: "🥣", titre: "Piler ou mixer", detail: "Écraser anchois, ail et câpres au pilon (version rustique) ou au mixeur (version lisse).", badge: "⏱ 3 min" },
      { icone: "🫒", titre: "Monter à l'huile", detail: "Verser l'huile d'olive en filet en mélangeant, comme pour une mayonnaise, jusqu'à obtenir une pâte souple et brillante.", badge: "⏱ 3 min" },
      { icone: "🍷", titre: "Relever", detail: "Ajouter le trait de vinaigre de vin et poivrer généreusement. Pas de sel — les anchois s'en chargent !", badge: null },
      { icone: "🥖", titre: "Servir", detail: "Servir en pot avec pain de campagne grillé, ou en anchoïade chaude avec des légumes croquants (céleri, chou-fleur, radis).", badge: null }
    ]
  },
  confitoignons: {
    nom: "Confit d'oignons",
    cat: "tartinables", pays: "france",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "50 min",
    niveau: "⭐ Facile",
    emoji: "🧅",
    description: "Le confit d'oignons — oignons rouges longuement fondus avec sucre et vinaigre balsamique jusqu'à la texture de confiture. L'allié du foie gras, des fromages et des burgers.",
    tableauConfitOignons: [
      { nb: 1, oignonrouge: "500 g", sucre: "60 g", vinaigreBalsamique: "40 ml", beurre: "20 g", thym: "2 g" },
      { nb: 2, oignonrouge: "1000 g", sucre: "120 g", vinaigreBalsamique: "80 ml", beurre: "40 g", thym: "4 g" },
      { nb: 3, oignonrouge: "1500 g", sucre: "180 g", vinaigreBalsamique: "120 ml", beurre: "60 g", thym: "6 g" },
      { nb: 4, oignonrouge: "2000 g", sucre: "240 g", vinaigreBalsamique: "160 ml", beurre: "80 g", thym: "8 g" },
      { nb: 5, oignonrouge: "2500 g", sucre: "300 g", vinaigreBalsamique: "200 ml", beurre: "100 g", thym: "10 g" },
      { nb: 6, oignonrouge: "3000 g", sucre: "360 g", vinaigreBalsamique: "240 ml", beurre: "120 g", thym: "12 g" },
      { nb: 7, oignonrouge: "3500 g", sucre: "420 g", vinaigreBalsamique: "280 ml", beurre: "140 g", thym: "14 g" },
      { nb: 8, oignonrouge: "4000 g", sucre: "480 g", vinaigreBalsamique: "320 ml", beurre: "160 g", thym: "16 g" },
      { nb: 9, oignonrouge: "4500 g", sucre: "540 g", vinaigreBalsamique: "360 ml", beurre: "180 g", thym: "18 g" },
      { nb: 10, oignonrouge: "5000 g", sucre: "600 g", vinaigreBalsamique: "400 ml", beurre: "200 g", thym: "20 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧅", titre: "Émincer", detail: "Éplucher les oignons rouges et les émincer en fines lamelles régulières. CLÉ : plus c'est fin, plus ça fond.", badge: "⏱ 10 min" },
      { icone: "🧈", titre: "Faire fondre", detail: "Faire revenir les oignons dans le beurre à feu doux avec le thym, sans coloration, en remuant régulièrement.", badge: "⏱ 15 min" },
      { icone: "🍬", titre: "Sucrer", detail: "Ajouter le sucre et laisser caraméliser doucement en mélangeant.", badge: "⏱ 5 min" },
      { icone: "🍷", titre: "Déglacer", detail: "Verser le vinaigre balsamique, bien gratter les sucs et mélanger.", badge: null },
      { icone: "⏲️", titre: "Confire", detail: "Laisser compoter à feu très doux jusqu'à une texture de confiture brillante, presque sans liquide. IMPORTANT : remuer souvent en fin de cuisson pour ne pas accrocher.", badge: "⏱ 20 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Saler, poivrer, verser en pot. Se garde 2 semaines au frais — parfait avec foie gras, fromages ou dans un burger.", badge: null }
    ]
  },
  caviartomates: {
    nom: "Caviar de tomates séchées",
    cat: "tartinables", pays: "france",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🍅",
    description: "Le caviar de tomates séchées — tomates confites, parmesan, câpres et basilic mixés en tartinade intense aux accents du Sud. Irrésistible à l'apéro sur des toasts.",
    tableauCaviarTomates: [
      { nb: 1, tomatesechees: "200 g", parmesan: "40 g", capres: "20 g", ail: "4 g", huileolive: "50 ml", basilic: "8 g" },
      { nb: 2, tomatesechees: "400 g", parmesan: "80 g", capres: "40 g", ail: "8 g", huileolive: "100 ml", basilic: "16 g" },
      { nb: 3, tomatesechees: "600 g", parmesan: "120 g", capres: "60 g", ail: "12 g", huileolive: "150 ml", basilic: "24 g" },
      { nb: 4, tomatesechees: "800 g", parmesan: "160 g", capres: "80 g", ail: "16 g", huileolive: "200 ml", basilic: "32 g" },
      { nb: 5, tomatesechees: "1000 g", parmesan: "200 g", capres: "100 g", ail: "20 g", huileolive: "250 ml", basilic: "40 g" },
      { nb: 6, tomatesechees: "1200 g", parmesan: "240 g", capres: "120 g", ail: "24 g", huileolive: "300 ml", basilic: "48 g" },
      { nb: 7, tomatesechees: "1400 g", parmesan: "280 g", capres: "140 g", ail: "28 g", huileolive: "350 ml", basilic: "56 g" },
      { nb: 8, tomatesechees: "1600 g", parmesan: "320 g", capres: "160 g", ail: "32 g", huileolive: "400 ml", basilic: "64 g" },
      { nb: 9, tomatesechees: "1800 g", parmesan: "360 g", capres: "180 g", ail: "36 g", huileolive: "450 ml", basilic: "72 g" },
      { nb: 10, tomatesechees: "2000 g", parmesan: "400 g", capres: "200 g", ail: "40 g", huileolive: "500 ml", basilic: "80 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍅", titre: "Égoutter les tomates", detail: "Égoutter les tomates séchées à l'huile en réservant un peu de leur huile parfumée.", badge: null },
      { icone: "🧄", titre: "Préparer les aromates", detail: "Dégermer l'ail, effeuiller le basilic, égoutter les câpres.", badge: null },
      { icone: "🌀", titre: "Mixer grossièrement", detail: "Mixer tomates, ail, câpres et parmesan par impulsions. CLÉ : garder une texture légèrement granuleuse « caviar », pas une purée lisse.", badge: "⏱ 2 min" },
      { icone: "🫒", titre: "Détendre à l'huile", detail: "Incorporer l'huile d'olive (et un peu d'huile des tomates) jusqu'à une tartinade souple.", badge: null },
      { icone: "🌿", titre: "Parfumer", detail: "Ajouter le basilic ciselé, poivrer. Goûter avant de saler — parmesan et câpres sont déjà bien salés.", badge: null },
      { icone: "🥖", titre: "Servir", detail: "Sur des toasts grillés, dans des pâtes chaudes ou avec une burrata. Se garde 5 jours au frais sous un filet d'huile.", badge: null }
    ]
  },
  rillettessardines: {
    nom: "Rillettes de sardines",
    cat: "tartinables", pays: "france",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🐟",
    description: "Rillettes de sardines express — sardines à l'huile écrasées avec fromage frais, échalote et citron. La tartinade marine prête en 10 minutes pour l'apéro.",
    tableauRillettesSardines: [
      { nb: 1, sardine: "200 g", fromagefrais: "120 g", echalote: "30 g", citron: "20 g", ciboulette: "5 g", moutarde: "10 g" },
      { nb: 2, sardine: "400 g", fromagefrais: "240 g", echalote: "60 g", citron: "40 g", ciboulette: "10 g", moutarde: "20 g" },
      { nb: 3, sardine: "600 g", fromagefrais: "360 g", echalote: "90 g", citron: "60 g", ciboulette: "15 g", moutarde: "30 g" },
      { nb: 4, sardine: "800 g", fromagefrais: "480 g", echalote: "120 g", citron: "80 g", ciboulette: "20 g", moutarde: "40 g" },
      { nb: 5, sardine: "1000 g", fromagefrais: "600 g", echalote: "150 g", citron: "100 g", ciboulette: "25 g", moutarde: "50 g" },
      { nb: 6, sardine: "1200 g", fromagefrais: "720 g", echalote: "180 g", citron: "120 g", ciboulette: "30 g", moutarde: "60 g" },
      { nb: 7, sardine: "1400 g", fromagefrais: "840 g", echalote: "210 g", citron: "140 g", ciboulette: "35 g", moutarde: "70 g" },
      { nb: 8, sardine: "1600 g", fromagefrais: "960 g", echalote: "240 g", citron: "160 g", ciboulette: "40 g", moutarde: "80 g" },
      { nb: 9, sardine: "1800 g", fromagefrais: "1080 g", echalote: "270 g", citron: "180 g", ciboulette: "45 g", moutarde: "90 g" },
      { nb: 10, sardine: "2000 g", fromagefrais: "1200 g", echalote: "300 g", citron: "200 g", ciboulette: "50 g", moutarde: "100 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🐟", titre: "Égoutter les sardines", detail: "Égoutter les sardines à l'huile et retirer l'arête centrale si vous préférez (elle s'écrase très bien aussi, c'est plein de calcium !).", badge: null },
      { icone: "🍴", titre: "Écraser", detail: "Écraser les sardines à la fourchette dans un saladier — texture rustique, pas besoin de mixeur.", badge: null },
      { icone: "🧀", titre: "Lier", detail: "Incorporer le fromage frais et la moutarde, bien mélanger.", badge: null },
      { icone: "🧅", titre: "Parfumer", detail: "Ajouter l'échalote finement ciselée, le jus de citron et la ciboulette.", badge: null },
      { icone: "🧂", titre: "Assaisonner", detail: "Poivrer généreusement, saler légèrement. ASTUCE CHEF : un trait de piment d'Espelette réveille le tout.", badge: null },
      { icone: "❄️", titre: "Raffermir", detail: "Réserver 30 min au frais avant de servir sur pain grillé ou blinis — les saveurs se marient et la texture se raffermit.", badge: "⏱ 30 min" }
    ]
  },
  tarama: {
    nom: "Tarama maison",
    cat: "tartinables", pays: "grece",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "15 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🐟",
    description: "Le tarama grec maison — œufs de cabillaud fumés montés à l'huile avec du pain trempé au lait et du citron. Rose pâle, mousseux, incomparablement meilleur que celui du commerce.",
    tableauTarama: [
      { nb: 1, oeufscabillaud: "100 g", painmie: "60 g", lait: "60 ml", huileolive: "100 ml", citron: "30 g" },
      { nb: 2, oeufscabillaud: "200 g", painmie: "120 g", lait: "120 ml", huileolive: "200 ml", citron: "60 g" },
      { nb: 3, oeufscabillaud: "300 g", painmie: "180 g", lait: "180 ml", huileolive: "300 ml", citron: "90 g" },
      { nb: 4, oeufscabillaud: "400 g", painmie: "240 g", lait: "240 ml", huileolive: "400 ml", citron: "120 g" },
      { nb: 5, oeufscabillaud: "500 g", painmie: "300 g", lait: "300 ml", huileolive: "500 ml", citron: "150 g" },
      { nb: 6, oeufscabillaud: "600 g", painmie: "360 g", lait: "360 ml", huileolive: "600 ml", citron: "180 g" },
      { nb: 7, oeufscabillaud: "700 g", painmie: "420 g", lait: "420 ml", huileolive: "700 ml", citron: "210 g" },
      { nb: 8, oeufscabillaud: "800 g", painmie: "480 g", lait: "480 ml", huileolive: "800 ml", citron: "240 g" },
      { nb: 9, oeufscabillaud: "900 g", painmie: "540 g", lait: "540 ml", huileolive: "900 ml", citron: "270 g" },
      { nb: 10, oeufscabillaud: "1000 g", painmie: "600 g", lait: "600 ml", huileolive: "1000 ml", citron: "300 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍞", titre: "Tremper le pain", detail: "Retirer la croûte du pain de mie et faire tremper la mie dans le lait.", badge: "⏱ 5 min" },
      { icone: "🐟", titre: "Préparer les œufs", detail: "Retirer la fine membrane des œufs de cabillaud fumés en grattant à la cuillère pour récupérer les œufs.", badge: null },
      { icone: "🥣", titre: "Mixer la base", detail: "Mixer les œufs de cabillaud avec le pain essoré jusqu'à obtenir une pâte homogène.", badge: "⏱ 1 min" },
      { icone: "🫒", titre: "Monter à l'huile", detail: "Moteur en marche, verser l'huile en mince filet comme pour une mayonnaise : le tarama monte, pâlit et devient mousseux. CLÉ : l'huile en filet LENT, sinon ça retombe.", badge: "⏱ 4 min" },
      { icone: "🍋", titre: "Détendre au citron", detail: "Incorporer le jus de citron petit à petit en goûtant. Le vrai tarama est rose PÂLE — pas rose fluo comme en supermarché !", badge: null },
      { icone: "❄️", titre: "Reposer au frais", detail: "Réserver 1 h au réfrigérateur : il se raffermit et les saveurs s'équilibrent. Servir avec pain grillé ou pita.", badge: "⏱ 1 h" }
    ]
  },
  ktipiti: {
    nom: "Ktipiti",
    cat: "tartinables", pays: "grece",
    dateAjout: "2026-07-07T19:00:00",
    base: 1,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🫑",
    description: "Le ktipiti grec — feta fouettée au poivron rouge rôti, yaourt grec et pointe de paprika. Une tartinade crémeuse, fraîche et légèrement fumée, star des mezze.",
    tableauKtipiti: [
      { nb: 1, feta: "200 g", poivron: "150 g", yaourtgrec: "80 g", huileolive: "20 ml", ail: "3 g", paprika: "2 g" },
      { nb: 2, feta: "400 g", poivron: "300 g", yaourtgrec: "160 g", huileolive: "40 ml", ail: "6 g", paprika: "4 g" },
      { nb: 3, feta: "600 g", poivron: "450 g", yaourtgrec: "240 g", huileolive: "60 ml", ail: "9 g", paprika: "6 g" },
      { nb: 4, feta: "800 g", poivron: "600 g", yaourtgrec: "320 g", huileolive: "80 ml", ail: "12 g", paprika: "8 g" },
      { nb: 5, feta: "1000 g", poivron: "750 g", yaourtgrec: "400 g", huileolive: "100 ml", ail: "15 g", paprika: "10 g" },
      { nb: 6, feta: "1200 g", poivron: "900 g", yaourtgrec: "480 g", huileolive: "120 ml", ail: "18 g", paprika: "12 g" },
      { nb: 7, feta: "1400 g", poivron: "1050 g", yaourtgrec: "560 g", huileolive: "140 ml", ail: "21 g", paprika: "14 g" },
      { nb: 8, feta: "1600 g", poivron: "1200 g", yaourtgrec: "640 g", huileolive: "160 ml", ail: "24 g", paprika: "16 g" },
      { nb: 9, feta: "1800 g", poivron: "1350 g", yaourtgrec: "720 g", huileolive: "180 ml", ail: "27 g", paprika: "18 g" },
      { nb: 10, feta: "2000 g", poivron: "1500 g", yaourtgrec: "800 g", huileolive: "200 ml", ail: "30 g", paprika: "20 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫑", titre: "Rôtir le poivron", detail: "Rôtir le poivron entier au four à 220°C (ou sous le gril) jusqu'à ce que la peau noircisse de partout.", badge: "⏱ 20 min" },
      { icone: "🫙", titre: "Faire suer", detail: "Enfermer le poivron rôti 10 min dans un bol filmé (ou un sac) : la vapeur décolle la peau, qui s'enlève alors très facilement.", badge: "⏱ 10 min" },
      { icone: "🔪", titre: "Peler et épépiner", detail: "Peler le poivron, retirer les graines et le hacher grossièrement.", badge: null },
      { icone: "🧀", titre: "Écraser la feta", detail: "Écraser la feta à la fourchette avec le yaourt grec — texture crémeuse avec quelques morceaux.", badge: null },
      { icone: "🌀", titre: "Assembler", detail: "Mélanger feta, poivron, ail dégermé pressé, paprika et huile d'olive. ASTUCE CHEF : une pincée de piment pour la version « tyrokafteri » qui pique.", badge: null },
      { icone: "🥙", titre: "Servir frais", detail: "Réserver 30 min au frais et servir arrosé d'un filet d'huile d'olive, avec pita grillée ou crudités.", badge: "⏱ 30 min" }
    ]
  },

  patetartiner: {
    nom: "Pâte à Tartiner façon Nutella Maison",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:00:00",
    base: 6,
    temps: "30 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍫",
    description: "Le Nutella maison, en bien meilleur : noisettes torréfiées mixées en praliné, mariées au chocolat au lait pour une texture onctueuse, sans huile de palme ni additifs. Le fameux goût choco-noisette, fait maison et plus parfumé que celui du commerce.",
    tableauPateTartiner: [
      { nb: 1, noisettes: "35 g", chocolatLait: "30 g", sucreglace: "18 g", huile: "10 ml", laitpoudre: "8 g", cacao: "5 g" },
      { nb: 2, noisettes: "70 g", chocolatLait: "60 g", sucreglace: "36 g", huile: "20 ml", laitpoudre: "16 g", cacao: "10 g" },
      { nb: 3, noisettes: "105 g", chocolatLait: "90 g", sucreglace: "54 g", huile: "30 ml", laitpoudre: "24 g", cacao: "15 g" },
      { nb: 4, noisettes: "140 g", chocolatLait: "120 g", sucreglace: "72 g", huile: "40 ml", laitpoudre: "32 g", cacao: "20 g" },
      { nb: 5, noisettes: "175 g", chocolatLait: "150 g", sucreglace: "90 g", huile: "50 ml", laitpoudre: "40 g", cacao: "25 g" },
      { nb: 6, noisettes: "210 g", chocolatLait: "180 g", sucreglace: "108 g", huile: "60 ml", laitpoudre: "48 g", cacao: "30 g" },
      { nb: 7, noisettes: "245 g", chocolatLait: "210 g", sucreglace: "126 g", huile: "70 ml", laitpoudre: "56 g", cacao: "35 g" },
      { nb: 8, noisettes: "280 g", chocolatLait: "240 g", sucreglace: "144 g", huile: "80 ml", laitpoudre: "64 g", cacao: "40 g" },
      { nb: 9, noisettes: "315 g", chocolatLait: "270 g", sucreglace: "162 g", huile: "90 ml", laitpoudre: "72 g", cacao: "45 g" },
      { nb: 10, noisettes: "350 g", chocolatLait: "300 g", sucreglace: "180 g", huile: "100 ml", laitpoudre: "80 g", cacao: "50 g" },
      { nb: 11, noisettes: "385 g", chocolatLait: "330 g", sucreglace: "198 g", huile: "110 ml", laitpoudre: "88 g", cacao: "55 g" },
      { nb: 12, noisettes: "420 g", chocolatLait: "360 g", sucreglace: "216 g", huile: "120 ml", laitpoudre: "96 g", cacao: "60 g" },
      { nb: 13, noisettes: "455 g", chocolatLait: "390 g", sucreglace: "234 g", huile: "130 ml", laitpoudre: "104 g", cacao: "65 g" },
      { nb: 14, noisettes: "490 g", chocolatLait: "420 g", sucreglace: "252 g", huile: "140 ml", laitpoudre: "112 g", cacao: "70 g" },
      { nb: 15, noisettes: "525 g", chocolatLait: "450 g", sucreglace: "270 g", huile: "150 ml", laitpoudre: "120 g", cacao: "75 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les noisettes au four à 160°C jusqu'à ce qu'elles dorent et embaument.", badge: "⏱ 12 min" },
      { icone: "🤚", titre: "Émonder", detail: "Frotter les noisettes tièdes dans un torchon pour retirer la peau.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Praliné", detail: "Mixer longuement les noisettes seules jusqu'à une purée lisse et coulante. ASTUCE CHEF : continuer à mixer bien au-delà de la poudre : les noisettes relâchent leur huile et deviennent pâte liquide, c'est ce praliné maison qui fait tout le parfum.", badge: "⏱ 6 min" },
      { icone: "🍫", titre: "Fondre", detail: "Faire fondre le chocolat au lait doucement au bain-marie.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir purée de noisettes, chocolat, sucre glace, lait en poudre et cacao.", badge: "⏱ 3 min" },
      { icone: "💧", titre: "Lisser", detail: "Ajouter l'huile neutre et mixer jusqu'à lisse et brillant.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser dans un pot. Conserver à température ambiante (le froid la fige).", badge: "⏱ 2 min" }
    ]
  },
  tartinerspeculoos: {
    nom: "Pâte à Tartiner Spéculoos",
    cat: "tartinables",
    pays: "belgique",
    dateAjout: "2026-06-08T16:01:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍪",
    description: "La pâte à tartiner aux spéculoos maison : biscuits caramélisés mixés et liés au lait concentré pour une crème onctueuse et épicée. Le goût cannelle-cassonade irrésistible, en pot.",
    tableauTartinerSpeculoos: [
      { nb: 1, speculoos: "55 g", laitconcentre: "30 ml", huile: "10 ml", beurre: "8 g", cannelle: "1 g" },
      { nb: 2, speculoos: "110 g", laitconcentre: "60 ml", huile: "20 ml", beurre: "16 g", cannelle: "1 g" },
      { nb: 3, speculoos: "165 g", laitconcentre: "90 ml", huile: "30 ml", beurre: "24 g", cannelle: "1 g" },
      { nb: 4, speculoos: "220 g", laitconcentre: "120 ml", huile: "40 ml", beurre: "32 g", cannelle: "1 g" },
      { nb: 5, speculoos: "275 g", laitconcentre: "150 ml", huile: "50 ml", beurre: "40 g", cannelle: "1 g" },
      { nb: 6, speculoos: "330 g", laitconcentre: "180 ml", huile: "60 ml", beurre: "48 g", cannelle: "2 g" },
      { nb: 7, speculoos: "385 g", laitconcentre: "210 ml", huile: "70 ml", beurre: "56 g", cannelle: "2 g" },
      { nb: 8, speculoos: "440 g", laitconcentre: "240 ml", huile: "80 ml", beurre: "64 g", cannelle: "2 g" },
      { nb: 9, speculoos: "495 g", laitconcentre: "270 ml", huile: "90 ml", beurre: "72 g", cannelle: "2 g" },
      { nb: 10, speculoos: "550 g", laitconcentre: "300 ml", huile: "100 ml", beurre: "80 g", cannelle: "2 g" },
      { nb: 11, speculoos: "605 g", laitconcentre: "330 ml", huile: "110 ml", beurre: "88 g", cannelle: "3 g" },
      { nb: 12, speculoos: "660 g", laitconcentre: "360 ml", huile: "120 ml", beurre: "96 g", cannelle: "3 g" },
      { nb: 13, speculoos: "715 g", laitconcentre: "390 ml", huile: "130 ml", beurre: "104 g", cannelle: "3 g" },
      { nb: 14, speculoos: "770 g", laitconcentre: "420 ml", huile: "140 ml", beurre: "112 g", cannelle: "3 g" },
      { nb: 15, speculoos: "825 g", laitconcentre: "450 ml", huile: "150 ml", beurre: "120 g", cannelle: "3 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍪", titre: "Réduire en poudre", detail: "Mixer les spéculoos en poudre la plus fine possible. ASTUCE CHEF : plus la poudre de biscuit est fine, plus la pâte sera lisse ; mixez par à-coups puis en continu.", badge: "⏱ 3 min" },
      { icone: "🧈", titre: "Beurre", detail: "Ajouter le beurre fondu et mixer.", badge: "⏱ 2 min" },
      { icone: "🥛", titre: "Lait concentré", detail: "Incorporer le lait concentré sucré peu à peu.", badge: "⏱ 2 min" },
      { icone: "🌿", titre: "Épices", detail: "Ajouter une pointe de cannelle pour renforcer le goût spéculoos.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile neutre jusqu'à la texture tartinable voulue.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser dans un pot ; elle épaissit en refroidissant.", badge: "⏱ 2 min" }
    ]
  },
  tartinerpistache: {
    nom: "Pâte à Tartiner Pistache",
    cat: "tartinables",
    pays: "monde",
    dateAjout: "2026-06-08T16:02:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🟢",
    description: "La pâte à tartiner à la pistache, douceur tendance : pistaches mixées en pâte fine, adoucies au chocolat blanc. Couleur verte naturelle, goût intense et raffiné.",
    tableauTartinerPistache: [
      { nb: 1, pistache: "45 g", chocolatBlanc: "25 g", sucreglace: "12 g", huile: "10 ml", lait: "10 ml" },
      { nb: 2, pistache: "90 g", chocolatBlanc: "50 g", sucreglace: "24 g", huile: "20 ml", lait: "20 ml" },
      { nb: 3, pistache: "135 g", chocolatBlanc: "75 g", sucreglace: "36 g", huile: "30 ml", lait: "30 ml" },
      { nb: 4, pistache: "180 g", chocolatBlanc: "100 g", sucreglace: "48 g", huile: "40 ml", lait: "40 ml" },
      { nb: 5, pistache: "225 g", chocolatBlanc: "125 g", sucreglace: "60 g", huile: "50 ml", lait: "50 ml" },
      { nb: 6, pistache: "270 g", chocolatBlanc: "150 g", sucreglace: "72 g", huile: "60 ml", lait: "60 ml" },
      { nb: 7, pistache: "315 g", chocolatBlanc: "175 g", sucreglace: "84 g", huile: "70 ml", lait: "70 ml" },
      { nb: 8, pistache: "360 g", chocolatBlanc: "200 g", sucreglace: "96 g", huile: "80 ml", lait: "80 ml" },
      { nb: 9, pistache: "405 g", chocolatBlanc: "225 g", sucreglace: "108 g", huile: "90 ml", lait: "90 ml" },
      { nb: 10, pistache: "450 g", chocolatBlanc: "250 g", sucreglace: "120 g", huile: "100 ml", lait: "100 ml" },
      { nb: 11, pistache: "495 g", chocolatBlanc: "275 g", sucreglace: "132 g", huile: "110 ml", lait: "110 ml" },
      { nb: 12, pistache: "540 g", chocolatBlanc: "300 g", sucreglace: "144 g", huile: "120 ml", lait: "120 ml" },
      { nb: 13, pistache: "585 g", chocolatBlanc: "325 g", sucreglace: "156 g", huile: "130 ml", lait: "130 ml" },
      { nb: 14, pistache: "630 g", chocolatBlanc: "350 g", sucreglace: "168 g", huile: "140 ml", lait: "140 ml" },
      { nb: 15, pistache: "675 g", chocolatBlanc: "375 g", sucreglace: "180 g", huile: "150 ml", lait: "150 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier légèrement les pistaches émondées non salées.", badge: "⏱ 6 min" },
      { icone: "🌀", titre: "Pâte de pistache", detail: "Mixer longuement les pistaches jusqu'à une pâte fine et coulante. ASTUCE CHEF : utiliser des pistaches émondées non salées et mixer longtemps : c'est ce qui donne la couleur verte franche et la finesse, sans amertume de peau.", badge: "⏱ 7 min" },
      { icone: "🍫", titre: "Chocolat blanc", detail: "Faire fondre le chocolat blanc doucement.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir pâte de pistache, chocolat blanc fondu et sucre glace.", badge: "⏱ 2 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile et un peu de lait jusqu'à onctueux.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et conserver à température ambiante.", badge: "⏱ 2 min" }
    ]
  },
  tartinerchocoblanc: {
    nom: "Pâte à Tartiner Chocolat Blanc",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:03:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🤍",
    description: "Une pâte à tartiner toute douce au chocolat blanc et à la vanille, façon ganache onctueuse. Gourmande et fondante, l'alliée des tartines du goûter.",
    tableauTartinerChocoBlanc: [
      { nb: 1, chocolatBlanc: "45 g", creme: "25 ml", huile: "8 ml", laitpoudre: "6 g", vanille: "1 g" },
      { nb: 2, chocolatBlanc: "90 g", creme: "50 ml", huile: "16 ml", laitpoudre: "12 g", vanille: "1 g" },
      { nb: 3, chocolatBlanc: "135 g", creme: "75 ml", huile: "24 ml", laitpoudre: "18 g", vanille: "1 g" },
      { nb: 4, chocolatBlanc: "180 g", creme: "100 ml", huile: "32 ml", laitpoudre: "24 g", vanille: "1 g" },
      { nb: 5, chocolatBlanc: "225 g", creme: "125 ml", huile: "40 ml", laitpoudre: "30 g", vanille: "1 g" },
      { nb: 6, chocolatBlanc: "270 g", creme: "150 ml", huile: "48 ml", laitpoudre: "36 g", vanille: "2 g" },
      { nb: 7, chocolatBlanc: "315 g", creme: "175 ml", huile: "56 ml", laitpoudre: "42 g", vanille: "2 g" },
      { nb: 8, chocolatBlanc: "360 g", creme: "200 ml", huile: "64 ml", laitpoudre: "48 g", vanille: "2 g" },
      { nb: 9, chocolatBlanc: "405 g", creme: "225 ml", huile: "72 ml", laitpoudre: "54 g", vanille: "2 g" },
      { nb: 10, chocolatBlanc: "450 g", creme: "250 ml", huile: "80 ml", laitpoudre: "60 g", vanille: "2 g" },
      { nb: 11, chocolatBlanc: "495 g", creme: "275 ml", huile: "88 ml", laitpoudre: "66 g", vanille: "3 g" },
      { nb: 12, chocolatBlanc: "540 g", creme: "300 ml", huile: "96 ml", laitpoudre: "72 g", vanille: "3 g" },
      { nb: 13, chocolatBlanc: "585 g", creme: "325 ml", huile: "104 ml", laitpoudre: "78 g", vanille: "3 g" },
      { nb: 14, chocolatBlanc: "630 g", creme: "350 ml", huile: "112 ml", laitpoudre: "84 g", vanille: "3 g" },
      { nb: 15, chocolatBlanc: "675 g", creme: "375 ml", huile: "120 ml", laitpoudre: "90 g", vanille: "3 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍫", titre: "Hacher", detail: "Hacher finement le chocolat blanc.", badge: "⏱ 3 min" },
      { icone: "🥛", titre: "Crème chaude", detail: "Chauffer la crème puis la verser sur le chocolat blanc. ASTUCE CHEF : le chocolat blanc brûle très vite, ne jamais le chauffer directement : la crème chaude versée dessus le fait fondre tout en douceur.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Émulsionner", detail: "Remuer du centre vers l'extérieur jusqu'à une ganache lisse.", badge: "⏱ 2 min" },
      { icone: "🌼", titre: "Vanille", detail: "Ajouter la vanille et le lait en poudre.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile, mélanger.", badge: "⏱ 1 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, laisser épaissir au frais brièvement.", badge: "⏱ 5 min" }
    ]
  },
  caramelbeurresale: {
    nom: "Pâte à Tartiner Caramel Beurre Salé",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:04:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🧈",
    description: "Le caramel au beurre salé breton, version tartinable : un caramel ambré et coulant, adouci de crème et relevé d'une pointe de fleur de sel. Sur des crêpes ou à la petite cuillère.",
    tableauCaramelBeurreSale: [
      { nb: 1, sucre: "40 g", creme: "30 ml", beurre: "15 g", fleurdesel: "1 g" },
      { nb: 2, sucre: "80 g", creme: "60 ml", beurre: "30 g", fleurdesel: "1 g" },
      { nb: 3, sucre: "120 g", creme: "90 ml", beurre: "45 g", fleurdesel: "1 g" },
      { nb: 4, sucre: "160 g", creme: "120 ml", beurre: "60 g", fleurdesel: "1 g" },
      { nb: 5, sucre: "200 g", creme: "150 ml", beurre: "75 g", fleurdesel: "1 g" },
      { nb: 6, sucre: "240 g", creme: "180 ml", beurre: "90 g", fleurdesel: "2 g" },
      { nb: 7, sucre: "280 g", creme: "210 ml", beurre: "105 g", fleurdesel: "2 g" },
      { nb: 8, sucre: "320 g", creme: "240 ml", beurre: "120 g", fleurdesel: "2 g" },
      { nb: 9, sucre: "360 g", creme: "270 ml", beurre: "135 g", fleurdesel: "2 g" },
      { nb: 10, sucre: "400 g", creme: "300 ml", beurre: "150 g", fleurdesel: "2 g" },
      { nb: 11, sucre: "440 g", creme: "330 ml", beurre: "165 g", fleurdesel: "3 g" },
      { nb: 12, sucre: "480 g", creme: "360 ml", beurre: "180 g", fleurdesel: "3 g" },
      { nb: 13, sucre: "520 g", creme: "390 ml", beurre: "195 g", fleurdesel: "3 g" },
      { nb: 14, sucre: "560 g", creme: "420 ml", beurre: "210 g", fleurdesel: "3 g" },
      { nb: 15, sucre: "600 g", creme: "450 ml", beurre: "225 g", fleurdesel: "3 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel à sec", detail: "Faire fondre le sucre à sec, sans remuer, jusqu'à un caramel ambré.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Déglacer", detail: "Hors du feu, verser la crème TIÈDE en plusieurs fois. ASTUCE CHEF : crème tiède (jamais froide) versée hors du feu : ça évite les projections et le caramel qui durcit en bloc.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Beurre", detail: "Incorporer le beurre en morceaux jusqu'à fondu.", badge: "⏱ 2 min" },
      { icone: "🧂", titre: "Fleur de sel", detail: "Ajouter la fleur de sel et mélanger.", badge: "⏱ 1 min" },
      { icone: "♨️", titre: "Réduire", detail: "Cuire 2-3 minutes jusqu'à une consistance nappante.", badge: "⏱ 3 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot ; il épaissit en refroidissant.", badge: "⏱ 4 min" }
    ]
  },
  lemoncurd: {
    nom: "Lemon Curd",
    cat: "tartinables",
    pays: "angleterre",
    dateAjout: "2026-06-08T16:05:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍋",
    description: "La crème de citron anglaise : acidulée, soyeuse et brillante, montée au beurre. Parfaite à tartiner, à fourrer ou à napper sur un cheesecake.",
    tableauLemonCurd: [
      { nb: 1, citron: "1", oeuf: "1", sucre: "30 g", beurre: "15 g" },
      { nb: 2, citron: "1", oeuf: "1", sucre: "60 g", beurre: "30 g" },
      { nb: 3, citron: "2", oeuf: "2", sucre: "90 g", beurre: "45 g" },
      { nb: 4, citron: "2", oeuf: "3", sucre: "120 g", beurre: "60 g" },
      { nb: 5, citron: "3", oeuf: "4", sucre: "150 g", beurre: "75 g" },
      { nb: 6, citron: "3", oeuf: "4", sucre: "180 g", beurre: "90 g" },
      { nb: 7, citron: "4", oeuf: "5", sucre: "210 g", beurre: "105 g" },
      { nb: 8, citron: "4", oeuf: "6", sucre: "240 g", beurre: "120 g" },
      { nb: 9, citron: "5", oeuf: "6", sucre: "270 g", beurre: "135 g" },
      { nb: 10, citron: "5", oeuf: "7", sucre: "300 g", beurre: "150 g" },
      { nb: 11, citron: "6", oeuf: "8", sucre: "330 g", beurre: "165 g" },
      { nb: 12, citron: "6", oeuf: "8", sucre: "360 g", beurre: "180 g" },
      { nb: 13, citron: "7", oeuf: "9", sucre: "390 g", beurre: "195 g" },
      { nb: 14, citron: "7", oeuf: "10", sucre: "420 g", beurre: "210 g" },
      { nb: 15, citron: "8", oeuf: "11", sucre: "450 g", beurre: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍋", titre: "Zester & presser", detail: "Zester puis presser les citrons.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Battre", detail: "Fouetter les œufs avec le sucre, le jus et le zeste.", badge: "⏱ 3 min" },
      { icone: "♨️", titre: "Cuisson douce", detail: "Cuire au bain-marie en remuant sans cesse jusqu'à épaississement. ASTUCE CHEF : feu doux au bain-marie et fouet constant : si le mélange bout, les œufs coagulent et le curd devient granuleux.", badge: "⏱ 10 min" },
      { icone: "🧈", titre: "Monter au beurre", detail: "Hors du feu, incorporer le beurre froid en parcelles.", badge: "⏱ 2 min" },
      { icone: "🫗", titre: "Filtrer", detail: "Passer au tamis pour une texture parfaitement lisse.", badge: "⏱ 2 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Filmer au contact et réfrigérer ; il fige en refroidissant.", badge: "⏱ 2 h" }
    ]
  },
  tartinerchococo: {
    nom: "Pâte à Tartiner Choco-Coco",
    cat: "tartinables",
    pays: "monde",
    dateAjout: "2026-06-08T16:06:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥥",
    description: "Une pâte à tartiner gourmande chocolat et noix de coco, dans l'esprit d'une barre Bounty. Le fondant du chocolat et le parfum tropical de la coco.",
    tableauTartinerChocoCo: [
      { nb: 1, noixCoco: "30 g", chocolatLait: "30 g", laitcoco: "25 ml", sucreglace: "12 g", huile: "8 ml" },
      { nb: 2, noixCoco: "60 g", chocolatLait: "60 g", laitcoco: "50 ml", sucreglace: "24 g", huile: "16 ml" },
      { nb: 3, noixCoco: "90 g", chocolatLait: "90 g", laitcoco: "75 ml", sucreglace: "36 g", huile: "24 ml" },
      { nb: 4, noixCoco: "120 g", chocolatLait: "120 g", laitcoco: "100 ml", sucreglace: "48 g", huile: "32 ml" },
      { nb: 5, noixCoco: "150 g", chocolatLait: "150 g", laitcoco: "125 ml", sucreglace: "60 g", huile: "40 ml" },
      { nb: 6, noixCoco: "180 g", chocolatLait: "180 g", laitcoco: "150 ml", sucreglace: "72 g", huile: "48 ml" },
      { nb: 7, noixCoco: "210 g", chocolatLait: "210 g", laitcoco: "175 ml", sucreglace: "84 g", huile: "56 ml" },
      { nb: 8, noixCoco: "240 g", chocolatLait: "240 g", laitcoco: "200 ml", sucreglace: "96 g", huile: "64 ml" },
      { nb: 9, noixCoco: "270 g", chocolatLait: "270 g", laitcoco: "225 ml", sucreglace: "108 g", huile: "72 ml" },
      { nb: 10, noixCoco: "300 g", chocolatLait: "300 g", laitcoco: "250 ml", sucreglace: "120 g", huile: "80 ml" },
      { nb: 11, noixCoco: "330 g", chocolatLait: "330 g", laitcoco: "275 ml", sucreglace: "132 g", huile: "88 ml" },
      { nb: 12, noixCoco: "360 g", chocolatLait: "360 g", laitcoco: "300 ml", sucreglace: "144 g", huile: "96 ml" },
      { nb: 13, noixCoco: "390 g", chocolatLait: "390 g", laitcoco: "325 ml", sucreglace: "156 g", huile: "104 ml" },
      { nb: 14, noixCoco: "420 g", chocolatLait: "420 g", laitcoco: "350 ml", sucreglace: "168 g", huile: "112 ml" },
      { nb: 15, noixCoco: "450 g", chocolatLait: "450 g", laitcoco: "375 ml", sucreglace: "180 g", huile: "120 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥥", titre: "Torréfier la coco", detail: "Faire dorer légèrement la noix de coco râpée à la poêle.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer la coco torréfiée pour la réduire en pâte. ASTUCE CHEF : torréfier la coco avant de la mixer réveille ses huiles et son parfum, la pâte n'en sera que plus intense.", badge: "⏱ 4 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Faire fondre le chocolat au lait.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir coco, chocolat, lait de coco et sucre glace.", badge: "⏱ 2 min" },
      { icone: "💧", titre: "Lisser", detail: "Ajouter l'huile et lisser au mixeur.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, conserver à température ambiante.", badge: "⏱ 2 min" }
    ]
  },
  tartinerchocoorange: {
    nom: "Pâte à Tartiner Choco-Orange",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:07:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍊",
    description: "L'alliance chocolat noir et orange en pâte à tartiner : une ganache intense parfumée au zeste et au jus d'orange. Élégante, légèrement amère, terriblement gourmande.",
    tableauTartinerChocoOrange: [
      { nb: 1, chocolatnoir: "40 g", creme: "25 ml", orange: "1", beurre: "10 g", sucre: "8 g" },
      { nb: 2, chocolatnoir: "80 g", creme: "50 ml", orange: "1", beurre: "20 g", sucre: "16 g" },
      { nb: 3, chocolatnoir: "120 g", creme: "75 ml", orange: "1", beurre: "30 g", sucre: "24 g" },
      { nb: 4, chocolatnoir: "160 g", creme: "100 ml", orange: "1", beurre: "40 g", sucre: "32 g" },
      { nb: 5, chocolatnoir: "200 g", creme: "125 ml", orange: "2", beurre: "50 g", sucre: "40 g" },
      { nb: 6, chocolatnoir: "240 g", creme: "150 ml", orange: "2", beurre: "60 g", sucre: "48 g" },
      { nb: 7, chocolatnoir: "280 g", creme: "175 ml", orange: "2", beurre: "70 g", sucre: "56 g" },
      { nb: 8, chocolatnoir: "320 g", creme: "200 ml", orange: "2", beurre: "80 g", sucre: "64 g" },
      { nb: 9, chocolatnoir: "360 g", creme: "225 ml", orange: "3", beurre: "90 g", sucre: "72 g" },
      { nb: 10, chocolatnoir: "400 g", creme: "250 ml", orange: "3", beurre: "100 g", sucre: "80 g" },
      { nb: 11, chocolatnoir: "440 g", creme: "275 ml", orange: "3", beurre: "110 g", sucre: "88 g" },
      { nb: 12, chocolatnoir: "480 g", creme: "300 ml", orange: "4", beurre: "120 g", sucre: "96 g" },
      { nb: 13, chocolatnoir: "520 g", creme: "325 ml", orange: "4", beurre: "130 g", sucre: "104 g" },
      { nb: 14, chocolatnoir: "560 g", creme: "350 ml", orange: "4", beurre: "140 g", sucre: "112 g" },
      { nb: 15, chocolatnoir: "600 g", creme: "375 ml", orange: "5", beurre: "150 g", sucre: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍊", titre: "Zester", detail: "Zester l'orange puis la presser. ASTUCE CHEF : zester avant de presser : c'est l'huile essentielle du zeste qui porte l'essentiel du parfum d'orange, le jus n'apporte que l'acidité.", badge: "⏱ 4 min" },
      { icone: "🍫", titre: "Hacher", detail: "Hacher le chocolat noir.", badge: "⏱ 2 min" },
      { icone: "🥛", titre: "Ganache", detail: "Chauffer la crème avec le jus d'orange et verser sur le chocolat.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Émulsionner", detail: "Remuer jusqu'à une ganache lisse et brillante.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Beurre & zeste", detail: "Incorporer le beurre et le zeste, mélanger.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et laisser prendre légèrement.", badge: "⏱ 5 min" }
    ]
  },
  pralinerose: {
    nom: "Pâte à Tartiner Praliné Rose",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:08:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🌸",
    description: "La gourmandise lyonnaise en pâte à tartiner : pralines roses concassées liées à une douce base de chocolat blanc. Croquante, rose bonbon et régressive.",
    tableauPralineRose: [
      { nb: 1, pralinesroses: "40 g", chocolatBlanc: "25 g", creme: "20 ml", beurre: "8 g" },
      { nb: 2, pralinesroses: "80 g", chocolatBlanc: "50 g", creme: "40 ml", beurre: "16 g" },
      { nb: 3, pralinesroses: "120 g", chocolatBlanc: "75 g", creme: "60 ml", beurre: "24 g" },
      { nb: 4, pralinesroses: "160 g", chocolatBlanc: "100 g", creme: "80 ml", beurre: "32 g" },
      { nb: 5, pralinesroses: "200 g", chocolatBlanc: "125 g", creme: "100 ml", beurre: "40 g" },
      { nb: 6, pralinesroses: "240 g", chocolatBlanc: "150 g", creme: "120 ml", beurre: "48 g" },
      { nb: 7, pralinesroses: "280 g", chocolatBlanc: "175 g", creme: "140 ml", beurre: "56 g" },
      { nb: 8, pralinesroses: "320 g", chocolatBlanc: "200 g", creme: "160 ml", beurre: "64 g" },
      { nb: 9, pralinesroses: "360 g", chocolatBlanc: "225 g", creme: "180 ml", beurre: "72 g" },
      { nb: 10, pralinesroses: "400 g", chocolatBlanc: "250 g", creme: "200 ml", beurre: "80 g" },
      { nb: 11, pralinesroses: "440 g", chocolatBlanc: "275 g", creme: "220 ml", beurre: "88 g" },
      { nb: 12, pralinesroses: "480 g", chocolatBlanc: "300 g", creme: "240 ml", beurre: "96 g" },
      { nb: 13, pralinesroses: "520 g", chocolatBlanc: "325 g", creme: "260 ml", beurre: "104 g" },
      { nb: 14, pralinesroses: "560 g", chocolatBlanc: "350 g", creme: "280 ml", beurre: "112 g" },
      { nb: 15, pralinesroses: "600 g", chocolatBlanc: "375 g", creme: "300 ml", beurre: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌸", titre: "Concasser", detail: "Concasser grossièrement les pralines roses.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Mixer une partie", detail: "Mixer la moitié des pralines en poudre fine, garder l'autre en éclats. ASTUCE CHEF : garder une partie en éclats apporte le croquant caractéristique ; tout mixer donnerait une pâte plate, sans texture.", badge: "⏱ 3 min" },
      { icone: "🍫", titre: "Base", detail: "Faire fondre le chocolat blanc avec la crème en ganache.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Incorporer la poudre puis les éclats de pralines.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Lier", detail: "Ajouter le beurre pour le fondant.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, jolie couleur rose.", badge: "⏱ 4 min" }
    ]
  },
  tartineramandecacao: {
    nom: "Pâte à Tartiner Amande-Cacao",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:09:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🌰",
    description: "Une pâte à tartiner plus saine : purée d'amandes maison et cacao, sucrée au sirop d'agave, sans chocolat ajouté ni huile de palme. Intense en cacao et riche en bons gras.",
    tableauTartinerAmandeCacao: [
      { nb: 1, amandes: "45 g", cacao: "8 g", siropagave: "15 g", huile: "8 ml", sel: "1 g" },
      { nb: 2, amandes: "90 g", cacao: "16 g", siropagave: "30 g", huile: "16 ml", sel: "1 g" },
      { nb: 3, amandes: "135 g", cacao: "24 g", siropagave: "45 g", huile: "24 ml", sel: "1 g" },
      { nb: 4, amandes: "180 g", cacao: "32 g", siropagave: "60 g", huile: "32 ml", sel: "1 g" },
      { nb: 5, amandes: "225 g", cacao: "40 g", siropagave: "75 g", huile: "40 ml", sel: "1 g" },
      { nb: 6, amandes: "270 g", cacao: "48 g", siropagave: "90 g", huile: "48 ml", sel: "2 g" },
      { nb: 7, amandes: "315 g", cacao: "56 g", siropagave: "105 g", huile: "56 ml", sel: "2 g" },
      { nb: 8, amandes: "360 g", cacao: "64 g", siropagave: "120 g", huile: "64 ml", sel: "2 g" },
      { nb: 9, amandes: "405 g", cacao: "72 g", siropagave: "135 g", huile: "72 ml", sel: "2 g" },
      { nb: 10, amandes: "450 g", cacao: "80 g", siropagave: "150 g", huile: "80 ml", sel: "2 g" },
      { nb: 11, amandes: "495 g", cacao: "88 g", siropagave: "165 g", huile: "88 ml", sel: "3 g" },
      { nb: 12, amandes: "540 g", cacao: "96 g", siropagave: "180 g", huile: "96 ml", sel: "3 g" },
      { nb: 13, amandes: "585 g", cacao: "104 g", siropagave: "195 g", huile: "104 ml", sel: "3 g" },
      { nb: 14, amandes: "630 g", cacao: "112 g", siropagave: "210 g", huile: "112 ml", sel: "3 g" },
      { nb: 15, amandes: "675 g", cacao: "120 g", siropagave: "225 g", huile: "120 ml", sel: "3 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les amandes au four pour révéler leur goût.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Purée d'amande", detail: "Mixer longuement les amandes jusqu'à une purée coulante. ASTUCE CHEF : comme les noisettes, persévérez au mixeur : la poudre devient pâte quand l'huile des amandes se libère, c'est la base de la tartinade.", badge: "⏱ 7 min" },
      { icone: "🍫", titre: "Cacao", detail: "Ajouter le cacao non sucré et une pincée de sel.", badge: "⏱ 1 min" },
      { icone: "🍯", titre: "Sucrer", detail: "Incorporer le sirop d'agave (ou miel) selon le goût.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec un filet d'huile jusqu'à tartinable.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot ; remuer avant usage (séparation naturelle).", badge: "⏱ 2 min" }
    ]
  },
  tartinerchococaramel: {
    nom: "Pâte à Tartiner Choco-Caramel",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:10:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "Le mariage du chocolat au lait et du caramel en pâte à tartiner : une marbrure fondante et gourmande, relevée d'une pointe de fleur de sel. Pour les tartines régressives.",
    tableauTartinerChocoCaramel: [
      { nb: 1, chocolatLait: "30 g", sucre: "25 g", creme: "25 ml", beurre: "10 g", fleurdesel: "1 g" },
      { nb: 2, chocolatLait: "60 g", sucre: "50 g", creme: "50 ml", beurre: "20 g", fleurdesel: "1 g" },
      { nb: 3, chocolatLait: "90 g", sucre: "75 g", creme: "75 ml", beurre: "30 g", fleurdesel: "1 g" },
      { nb: 4, chocolatLait: "120 g", sucre: "100 g", creme: "100 ml", beurre: "40 g", fleurdesel: "1 g" },
      { nb: 5, chocolatLait: "150 g", sucre: "125 g", creme: "125 ml", beurre: "50 g", fleurdesel: "1 g" },
      { nb: 6, chocolatLait: "180 g", sucre: "150 g", creme: "150 ml", beurre: "60 g", fleurdesel: "2 g" },
      { nb: 7, chocolatLait: "210 g", sucre: "175 g", creme: "175 ml", beurre: "70 g", fleurdesel: "2 g" },
      { nb: 8, chocolatLait: "240 g", sucre: "200 g", creme: "200 ml", beurre: "80 g", fleurdesel: "2 g" },
      { nb: 9, chocolatLait: "270 g", sucre: "225 g", creme: "225 ml", beurre: "90 g", fleurdesel: "2 g" },
      { nb: 10, chocolatLait: "300 g", sucre: "250 g", creme: "250 ml", beurre: "100 g", fleurdesel: "2 g" },
      { nb: 11, chocolatLait: "330 g", sucre: "275 g", creme: "275 ml", beurre: "110 g", fleurdesel: "3 g" },
      { nb: 12, chocolatLait: "360 g", sucre: "300 g", creme: "300 ml", beurre: "120 g", fleurdesel: "3 g" },
      { nb: 13, chocolatLait: "390 g", sucre: "325 g", creme: "325 ml", beurre: "130 g", fleurdesel: "3 g" },
      { nb: 14, chocolatLait: "420 g", sucre: "350 g", creme: "350 ml", beurre: "140 g", fleurdesel: "3 g" },
      { nb: 15, chocolatLait: "450 g", sucre: "375 g", creme: "375 ml", beurre: "150 g", fleurdesel: "3 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel", detail: "Réaliser un caramel à sec ambré.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Déglacer", detail: "Déglacer hors du feu avec la crème tiède.", badge: "⏱ 2 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Faire fondre le chocolat au lait à part.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Marbrer", detail: "Incorporer le caramel tiède au chocolat fondu. ASTUCE CHEF : mélanger le caramel encore tiède au chocolat fondu (pas froid) donne cette marbrure fondante et homogène, sans grumeaux de caramel figé.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Lier", detail: "Ajouter le beurre et la fleur de sel.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et laisser prendre.", badge: "⏱ 5 min" }
    ]
  },
  caviaraubergine: {
    nom: "Caviar d'aubergine", cat: "tartinables", pays: "france", dateAjout: "2026-06-17T10:00:00",
    base: 4, temps: "45 min", niveau: "⭐ Facile", emoji: "🍆",
    description: "Une tartinade méditerranéenne fondante : la chair d'aubergines rôties au four, fouettée avec ail, citron, tahin et huile d'olive. Parfait à l'apéro sur du pain grillé.",
    saisons: ["ete"],
    ingredients: {},
    tableauCaviarAubergine: [
      { nb: 1, aubergine: "150 g", ail: "2 g", huileolive: "10 ml", citron: "4 ml", tahini: "5 g", cumin: "1 g", sel: "1 g", persil: "3 g" },
      { nb: 2, aubergine: "300 g", ail: "2 g", huileolive: "20 ml", citron: "8 ml", tahini: "10 g", cumin: "1 g", sel: "2 g", persil: "5 g" },
      { nb: 3, aubergine: "450 g", ail: "4 g", huileolive: "30 ml", citron: "11 ml", tahini: "15 g", cumin: "2 g", sel: "3 g", persil: "8 g" },
      { nb: 4, aubergine: "600 g", ail: "1 gousse", huileolive: "40 ml", citron: "15 ml", tahini: "20 g", cumin: "2 g", sel: "4 g", persil: "10 g" },
      { nb: 5, aubergine: "750 g", ail: "6 g", huileolive: "50 ml", citron: "19 ml", tahini: "25 g", cumin: "3 g", sel: "5 g", persil: "13 g" },
      { nb: 6, aubergine: "900 g", ail: "8 g", huileolive: "60 ml", citron: "23 ml", tahini: "30 g", cumin: "3 g", sel: "6 g", persil: "15 g" },
      { nb: 7, aubergine: "1050 g", ail: "9 g", huileolive: "70 ml", citron: "26 ml", tahini: "35 g", cumin: "4 g", sel: "7 g", persil: "18 g" },
      { nb: 8, aubergine: "1200 g", ail: "2 gousse", huileolive: "80 ml", citron: "30 ml", tahini: "40 g", cumin: "4 g", sel: "8 g", persil: "20 g" },
      { nb: 9, aubergine: "1350 g", ail: "12 g", huileolive: "90 ml", citron: "34 ml", tahini: "45 g", cumin: "5 g", sel: "9 g", persil: "23 g" },
      { nb: 10, aubergine: "1500 g", ail: "12 g", huileolive: "100 ml", citron: "38 ml", tahini: "50 g", cumin: "5 g", sel: "10 g", persil: "25 g" },
      { nb: 11, aubergine: "1650 g", ail: "14 g", huileolive: "110 ml", citron: "41 ml", tahini: "55 g", cumin: "6 g", sel: "11 g", persil: "28 g" },
      { nb: 12, aubergine: "1800 g", ail: "3 gousse", huileolive: "120 ml", citron: "45 ml", tahini: "60 g", cumin: "6 g", sel: "12 g", persil: "30 g" },
      { nb: 13, aubergine: "1950 g", ail: "16 g", huileolive: "130 ml", citron: "49 ml", tahini: "65 g", cumin: "7 g", sel: "13 g", persil: "33 g" },
      { nb: 14, aubergine: "2100 g", ail: "18 g", huileolive: "140 ml", citron: "53 ml", tahini: "70 g", cumin: "7 g", sel: "14 g", persil: "35 g" },
      { nb: 15, aubergine: "2250 g", ail: "19 g", huileolive: "150 ml", citron: "56 ml", tahini: "75 g", cumin: "8 g", sel: "15 g", persil: "38 g" }
    ],
    etapes: [
      { icone: "🔥", titre: "Rôtir", detail: "Piquer les aubergines et les rôtir au four jusqu'à ce que la peau soit boursouflée et la chair fondante.", badge: "⏱ 35 min" },
      { icone: "🥄", titre: "Évider", detail: "Laisser tiédir, fendre les aubergines et récupérer la chair à la cuillère.", badge: null },
      { icone: "🌀", titre: "Mixer", detail: "Mixer la chair avec l'ail, le jus de citron, le tahin, l'huile d'olive et le cumin.", badge: null },
      { icone: "🧂", titre: "Assaisonner", detail: "Saler et ajuster en citron. Incorporer le persil ciselé.", badge: null },
      { icone: "❄️", titre: "Réserver", detail: "Réserver au frais au moins 30 min pour développer les saveurs.", badge: "⏱ 30 min" },
      { icone: "🍞", titre: "Servir", detail: "Servir frais, filé d'huile d'olive, avec du pain grillé.", badge: null }
    ]
  },
  confiturefraise: {
    nom: "Confiture de fraises", cat: "tartinables", pays: "france", dateAjout: "2026-06-17T10:00:00",
    base: 6, temps: "40 min", niveau: "⭐ Facile", emoji: "🍓",
    description: "La confiture maison comme à la ferme : des fraises gorgées de soleil, juste assez de sucre et un trait de citron pour une prise parfaite. Le goût de l'été en pot.",
    saisons: ["printemps", "ete"],
    ingredients: {},
    tableauConfitureFraise: [
      { nb: 1, fraise: "167 g", sucre: "133 g", citron: "5 ml" },
      { nb: 2, fraise: "333 g", sucre: "267 g", citron: "10 ml" },
      { nb: 3, fraise: "500 g", sucre: "400 g", citron: "15 ml" },
      { nb: 4, fraise: "667 g", sucre: "533 g", citron: "20 ml" },
      { nb: 5, fraise: "833 g", sucre: "667 g", citron: "25 ml" },
      { nb: 6, fraise: "1000 g", sucre: "800 g", citron: "30 ml" },
      { nb: 7, fraise: "1167 g", sucre: "933 g", citron: "35 ml" },
      { nb: 8, fraise: "1333 g", sucre: "1067 g", citron: "40 ml" },
      { nb: 9, fraise: "1500 g", sucre: "1200 g", citron: "45 ml" },
      { nb: 10, fraise: "1667 g", sucre: "1333 g", citron: "50 ml" },
      { nb: 11, fraise: "1833 g", sucre: "1467 g", citron: "55 ml" },
      { nb: 12, fraise: "2000 g", sucre: "1600 g", citron: "60 ml" },
      { nb: 13, fraise: "2167 g", sucre: "1733 g", citron: "65 ml" },
      { nb: 14, fraise: "2333 g", sucre: "1867 g", citron: "70 ml" },
      { nb: 15, fraise: "2500 g", sucre: "2000 g", citron: "75 ml" }
    ],
    etapes: [
      { icone: "🍓", titre: "Macérer", detail: "Équeuter et couper les fraises. Les mélanger au sucre et au jus de citron, laisser dégorger quelques heures.", badge: "⏱ 2 h" },
      { icone: "🔥", titre: "Cuire", detail: "Porter à ébullition puis laisser cuire à feu vif en remuant.", badge: "⏱ 25 min" },
      { icone: "🥄", titre: "Écumer", detail: "Écumer la mousse rose qui se forme en surface.", badge: null },
      { icone: "💧", titre: "Tester", detail: "Test de la goutte : une goutte déposée sur une assiette froide doit figer.", badge: null },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant dans des pots stérilisés, fermer et retourner jusqu'à refroidissement.", badge: null }
    ]
  },
  houmousbetterave: {
    liees: ["painpita"],
    nom: "Houmous de Betterave",
    cat: "tartinables", saisons: ["printemps","ete","automne"], pays: "liban", dateAjout: "2026-06-19T10:00:00",
    base: 1, temps: "10 min", niveau: "⭐ Facile", emoji: "💜",
    description: "Un houmous rose vif et acidulé : la douceur terreuse de la betterave cuite mariée au crémeux des pois chiches et du tahini. Aussi joli que bon, parfait à l'apéro avec des crudités.",
    ingredients: {},
    tableauHoumousBetterave: [
      { nb: 1, poischiches: "250 g", betterave: "150 g", tahini: "30 g", citron: "1", ail: "5 g", huileolive: "30 ml", cumin: "2 g", sel: "2 g" },
      { nb: 2, poischiches: "500 g", betterave: "300 g", tahini: "60 g", citron: "2", ail: "10 g", huileolive: "60 ml", cumin: "4 g", sel: "4 g" },
      { nb: 3, poischiches: "750 g", betterave: "450 g", tahini: "90 g", citron: "3", ail: "15 g", huileolive: "90 ml", cumin: "6 g", sel: "6 g" },
      { nb: 4, poischiches: "1000 g", betterave: "600 g", tahini: "120 g", citron: "4", ail: "20 g", huileolive: "120 ml", cumin: "8 g", sel: "8 g" },
      { nb: 5, poischiches: "1250 g", betterave: "750 g", tahini: "150 g", citron: "5", ail: "25 g", huileolive: "150 ml", cumin: "10 g", sel: "10 g" },
      { nb: 6, poischiches: "1500 g", betterave: "900 g", tahini: "180 g", citron: "6", ail: "30 g", huileolive: "180 ml", cumin: "12 g", sel: "12 g" },
      { nb: 7, poischiches: "1750 g", betterave: "1050 g", tahini: "210 g", citron: "7", ail: "35 g", huileolive: "210 ml", cumin: "14 g", sel: "14 g" },
      { nb: 8, poischiches: "2000 g", betterave: "1200 g", tahini: "240 g", citron: "8", ail: "40 g", huileolive: "240 ml", cumin: "16 g", sel: "16 g" },
      { nb: 9, poischiches: "2250 g", betterave: "1350 g", tahini: "270 g", citron: "9", ail: "45 g", huileolive: "270 ml", cumin: "18 g", sel: "18 g" },
      { nb: 10, poischiches: "2500 g", betterave: "1500 g", tahini: "300 g", citron: "10", ail: "50 g", huileolive: "300 ml", cumin: "20 g", sel: "20 g" },
      { nb: 11, poischiches: "2750 g", betterave: "1650 g", tahini: "330 g", citron: "11", ail: "55 g", huileolive: "330 ml", cumin: "22 g", sel: "22 g" },
      { nb: 12, poischiches: "3000 g", betterave: "1800 g", tahini: "360 g", citron: "12", ail: "60 g", huileolive: "360 ml", cumin: "24 g", sel: "24 g" },
      { nb: 13, poischiches: "3250 g", betterave: "1950 g", tahini: "390 g", citron: "13", ail: "65 g", huileolive: "390 ml", cumin: "26 g", sel: "26 g" },
      { nb: 14, poischiches: "3500 g", betterave: "2100 g", tahini: "420 g", citron: "14", ail: "70 g", huileolive: "420 ml", cumin: "28 g", sel: "28 g" },
      { nb: 15, poischiches: "3750 g", betterave: "2250 g", tahini: "450 g", citron: "15", ail: "75 g", huileolive: "450 ml", cumin: "30 g", sel: "30 g" }
    ],
    etapes: [
      { icone: "🫐", titre: "Cuire la betterave", detail: "Utiliser de la betterave déjà cuite, ou la cuire à l'eau/au four puis la peler et la couper en morceaux.", badge: null },
      { icone: "🌀", titre: "Mixer", detail: "Mettre pois chiches égouttés, betterave, tahini, jus de citron, ail, cumin et sel au mixeur. Mixer à pleine puissance.", badge: "⏱ 2 min" },
      { icone: "💧", titre: "Détendre", detail: "Ajouter l'huile d'olive et un peu d'eau froide jusqu'à une texture lisse et crémeuse.", badge: null },
      { icone: "👅", titre: "Ajuster", detail: "Goûter et rectifier sel et citron : la betterave demande un bon coup d'acidité.", badge: null },
      { icone: "🍽️", titre: "Dresser", detail: "Verser dans un bol, lisser et creuser un puits au centre.", badge: null },
      { icone: "🫒", titre: "Finir", detail: "Filet d'huile d'olive, graines (sésame, courge) et quelques feuilles de menthe. Servir frais avec pain pita ou crudités.", badge: null }
    ]
  },
  ecrasepetitspois: {
    liees: ["painpita"],
    nom: "Écrasé de Petits Pois, Feta & Menthe",
    cat: "tartinables", saisons: ["printemps","ete"], pays: "grece", dateAjout: "2026-06-19T10:01:00",
    base: 1, temps: "10 min", niveau: "⭐ Facile", emoji: "🟢",
    description: "Une tartinade fraîche et printanière : petits pois écrasés, feta émiettée, menthe et citron. Sur une tartine de pain grillé, c'est l'apéro parfait des beaux jours.",
    ingredients: {},
    tableauEcrasePetitsPois: [
      { nb: 1, petitspois: "200 g", feta: "60 g", menthe: "5 g", citron: "1", huileolive: "15 ml", sel: "1 g" },
      { nb: 2, petitspois: "400 g", feta: "120 g", menthe: "10 g", citron: "2", huileolive: "30 ml", sel: "2 g" },
      { nb: 3, petitspois: "600 g", feta: "180 g", menthe: "15 g", citron: "3", huileolive: "45 ml", sel: "3 g" },
      { nb: 4, petitspois: "800 g", feta: "240 g", menthe: "20 g", citron: "4", huileolive: "60 ml", sel: "4 g" },
      { nb: 5, petitspois: "1000 g", feta: "300 g", menthe: "25 g", citron: "5", huileolive: "75 ml", sel: "5 g" },
      { nb: 6, petitspois: "1200 g", feta: "360 g", menthe: "30 g", citron: "6", huileolive: "90 ml", sel: "6 g" },
      { nb: 7, petitspois: "1400 g", feta: "420 g", menthe: "35 g", citron: "7", huileolive: "105 ml", sel: "7 g" },
      { nb: 8, petitspois: "1600 g", feta: "480 g", menthe: "40 g", citron: "8", huileolive: "120 ml", sel: "8 g" },
      { nb: 9, petitspois: "1800 g", feta: "540 g", menthe: "45 g", citron: "9", huileolive: "135 ml", sel: "9 g" },
      { nb: 10, petitspois: "2000 g", feta: "600 g", menthe: "50 g", citron: "10", huileolive: "150 ml", sel: "10 g" },
      { nb: 11, petitspois: "2200 g", feta: "660 g", menthe: "55 g", citron: "11", huileolive: "165 ml", sel: "11 g" },
      { nb: 12, petitspois: "2400 g", feta: "720 g", menthe: "60 g", citron: "12", huileolive: "180 ml", sel: "12 g" },
      { nb: 13, petitspois: "2600 g", feta: "780 g", menthe: "65 g", citron: "13", huileolive: "195 ml", sel: "13 g" },
      { nb: 14, petitspois: "2800 g", feta: "840 g", menthe: "70 g", citron: "14", huileolive: "210 ml", sel: "14 g" },
      { nb: 15, petitspois: "3000 g", feta: "900 g", menthe: "75 g", citron: "15", huileolive: "225 ml", sel: "15 g" }
    ],
    etapes: [
      { icone: "🟢", titre: "Cuire les petits pois", detail: "Cuire les petits pois (frais ou surgelés) quelques minutes à l'eau bouillante salée, puis égoutter et rafraîchir.", badge: "⏱ 4 min" },
      { icone: "🥄", titre: "Écraser", detail: "Écraser grossièrement les petits pois à la fourchette en gardant de la texture.", badge: null },
      { icone: "🧀", titre: "Mélanger", detail: "Ajouter la feta émiettée, la menthe ciselée, le jus de citron et l'huile d'olive.", badge: null },
      { icone: "👅", titre: "Assaisonner", detail: "Saler légèrement (attention, la feta est déjà salée) et poivrer.", badge: null },
      { icone: "🍞", titre: "Servir", detail: "Tartiner sur du pain grillé frotté à l'ail, ou servir en dip avec des gressins.", badge: null }
    ]
  },
  beurrecacahuete: {
    nom: "Beurre de Cacahuète",
    cat: "tartinables",
    pays: "usa",
    dateAjout: "2026-06-22T10:00:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🥜",
    description: "Le beurre de cacahuète maison : juste des cacahuètes torréfiées mixées longuement jusqu'à libérer leur huile, relevées d'une pointe de miel et de sel. Onctueux, sans huile de palme ni sucre ajouté inutile — bien meilleur (et moins cher) que celui du commerce.",
    tableauBeurreCacahuete: [
      { nb: 1, cacahuetes: "150 g", huile: "10 ml", miel: "10 g", sel: "2 g" },
      { nb: 2, cacahuetes: "300 g", huile: "20 ml", miel: "20 g", sel: "4 g" },
      { nb: 3, cacahuetes: "450 g", huile: "30 ml", miel: "30 g", sel: "6 g" },
      { nb: 4, cacahuetes: "600 g", huile: "40 ml", miel: "40 g", sel: "8 g" },
      { nb: 5, cacahuetes: "750 g", huile: "50 ml", miel: "50 g", sel: "10 g" },
      { nb: 6, cacahuetes: "900 g", huile: "60 ml", miel: "60 g", sel: "12 g" },
      { nb: 7, cacahuetes: "1050 g", huile: "70 ml", miel: "70 g", sel: "14 g" },
      { nb: 8, cacahuetes: "1200 g", huile: "80 ml", miel: "80 g", sel: "16 g" },
      { nb: 9, cacahuetes: "1350 g", huile: "90 ml", miel: "90 g", sel: "18 g" },
      { nb: 10, cacahuetes: "1500 g", huile: "100 ml", miel: "100 g", sel: "20 g" },
      { nb: 11, cacahuetes: "1650 g", huile: "110 ml", miel: "110 g", sel: "22 g" },
      { nb: 12, cacahuetes: "1800 g", huile: "120 ml", miel: "120 g", sel: "24 g" },
      { nb: 13, cacahuetes: "1950 g", huile: "130 ml", miel: "130 g", sel: "26 g" },
      { nb: 14, cacahuetes: "2100 g", huile: "140 ml", miel: "140 g", sel: "28 g" },
      { nb: 15, cacahuetes: "2250 g", huile: "150 ml", miel: "150 g", sel: "30 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les cacahuètes non salées au four à 160°C jusqu'à ce qu'elles dorent et embaument (saute cette étape si elles sont déjà grillées).", badge: "⏱ 8 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer longuement les cacahuètes seules : elles passent de la poudre à une purée. ASTUCE CHEF : continue bien au-delà du stade poudre, les cacahuètes relâchent leur huile et deviennent crème — c'est ce qui donne la texture lisse sans rien ajouter.", badge: "⏱ 5 min" },
      { icone: "🍯", titre: "Assaisonner", detail: "Ajouter le miel, le sel et l'huile neutre, puis mixer encore pour lisser. Goûter et ajuster (plus salé pour un goût américain, plus de miel pour une version sucrée).", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser dans un pot hermétique. Se conserve 3-4 semaines au frais (l'huile peut remonter : un coup de cuillère et c'est reparti).", badge: null }
    ]
  },
  beurreamande: {
    nom: "Beurre d'Amande",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🌰",
    description: "La purée d'amande maison : juste des amandes torréfiées mixées longuement jusqu'à libérer leur huile, avec une pointe de miel et de sel. Riche et onctueuse.",
    tableauBeurreamande: [
      { nb: 1, amandes: "150 g", huile: "10 ml", miel: "10 g", sel: "2 g" },
      { nb: 2, amandes: "300 g", huile: "20 ml", miel: "20 g", sel: "4 g" },
      { nb: 3, amandes: "450 g", huile: "30 ml", miel: "30 g", sel: "6 g" },
      { nb: 4, amandes: "600 g", huile: "40 ml", miel: "40 g", sel: "8 g" },
      { nb: 5, amandes: "750 g", huile: "50 ml", miel: "50 g", sel: "10 g" },
      { nb: 6, amandes: "900 g", huile: "60 ml", miel: "60 g", sel: "12 g" },
      { nb: 7, amandes: "1050 g", huile: "70 ml", miel: "70 g", sel: "14 g" },
      { nb: 8, amandes: "1200 g", huile: "80 ml", miel: "80 g", sel: "16 g" },
      { nb: 9, amandes: "1350 g", huile: "90 ml", miel: "90 g", sel: "18 g" },
      { nb: 10, amandes: "1500 g", huile: "100 ml", miel: "100 g", sel: "20 g" },
      { nb: 11, amandes: "1650 g", huile: "110 ml", miel: "110 g", sel: "22 g" },
      { nb: 12, amandes: "1800 g", huile: "120 ml", miel: "120 g", sel: "24 g" },
      { nb: 13, amandes: "1950 g", huile: "130 ml", miel: "130 g", sel: "26 g" },
      { nb: 14, amandes: "2100 g", huile: "140 ml", miel: "140 g", sel: "28 g" },
      { nb: 15, amandes: "2250 g", huile: "150 ml", miel: "150 g", sel: "30 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les amandes au four à 160°C jusqu'à ce qu'elles dorent et embaument.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer longuement les amandes seules jusqu'à une purée coulante. ASTUCE CHEF : persévère bien au-delà du stade poudre — les amandes relâchent leur huile et deviennent crème.", badge: "⏱ 6 min" },
      { icone: "🍯", titre: "Assaisonner", detail: "Ajouter miel, sel et huile, mixer pour lisser.", badge: null },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot ; remuer avant usage (séparation naturelle).", badge: null }
    ]
  },
  confitureabricot: {
    nom: "Confiture d'Abricots",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["ete"],
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍑",
    description: "La confiture d'été par excellence : des abricots mûrs, un trait de citron et juste assez de sucre pour une prise parfaite et un goût franc.",
    tableauConfitureabricot: [
      { nb: 1, abricot: "170 g", sucre: "130 g", citron: "5 ml" },
      { nb: 2, abricot: "340 g", sucre: "260 g", citron: "10 ml" },
      { nb: 3, abricot: "510 g", sucre: "390 g", citron: "15 ml" },
      { nb: 4, abricot: "680 g", sucre: "520 g", citron: "20 ml" },
      { nb: 5, abricot: "850 g", sucre: "650 g", citron: "25 ml" },
      { nb: 6, abricot: "1020 g", sucre: "780 g", citron: "30 ml" },
      { nb: 7, abricot: "1190 g", sucre: "910 g", citron: "35 ml" },
      { nb: 8, abricot: "1360 g", sucre: "1040 g", citron: "40 ml" },
      { nb: 9, abricot: "1530 g", sucre: "1170 g", citron: "45 ml" },
      { nb: 10, abricot: "1700 g", sucre: "1300 g", citron: "50 ml" },
      { nb: 11, abricot: "1870 g", sucre: "1430 g", citron: "55 ml" },
      { nb: 12, abricot: "2040 g", sucre: "1560 g", citron: "60 ml" },
      { nb: 13, abricot: "2210 g", sucre: "1690 g", citron: "65 ml" },
      { nb: 14, abricot: "2380 g", sucre: "1820 g", citron: "70 ml" },
      { nb: 15, abricot: "2550 g", sucre: "1950 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍑", titre: "Macérer", detail: "Dénoyauter et couper les abricots, mélanger au sucre et au citron, laisser dégorger 1 h.", badge: "⏱ 1 h" },
      { icone: "🔥", titre: "Cuire", detail: "Porter à ébullition et cuire à feu vif en remuant.", badge: "⏱ 25 min" },
      { icone: "💧", titre: "Tester", detail: "Test de la goutte sur assiette froide : elle doit figer. ASTUCE CHEF : garde quelques noyaux cassés dans un nouet pendant la cuisson — l'amande du noyau parfume subtilement la confiture.", badge: null },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant dans des pots stérilisés, fermer et retourner.", badge: null }
    ]
  },
  confituremyrtille: {
    nom: "Confiture de Myrtilles",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["ete"],
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🫐",
    description: "Une confiture intense et veloutée : des myrtilles gorgées de sucre, à peine relevées de citron. Sublime sur du pain frais ou un yaourt.",
    tableauConfituremyrtille: [
      { nb: 1, myrtille: "170 g", sucre: "130 g", citron: "5 ml" },
      { nb: 2, myrtille: "340 g", sucre: "260 g", citron: "10 ml" },
      { nb: 3, myrtille: "510 g", sucre: "390 g", citron: "15 ml" },
      { nb: 4, myrtille: "680 g", sucre: "520 g", citron: "20 ml" },
      { nb: 5, myrtille: "850 g", sucre: "650 g", citron: "25 ml" },
      { nb: 6, myrtille: "1020 g", sucre: "780 g", citron: "30 ml" },
      { nb: 7, myrtille: "1190 g", sucre: "910 g", citron: "35 ml" },
      { nb: 8, myrtille: "1360 g", sucre: "1040 g", citron: "40 ml" },
      { nb: 9, myrtille: "1530 g", sucre: "1170 g", citron: "45 ml" },
      { nb: 10, myrtille: "1700 g", sucre: "1300 g", citron: "50 ml" },
      { nb: 11, myrtille: "1870 g", sucre: "1430 g", citron: "55 ml" },
      { nb: 12, myrtille: "2040 g", sucre: "1560 g", citron: "60 ml" },
      { nb: 13, myrtille: "2210 g", sucre: "1690 g", citron: "65 ml" },
      { nb: 14, myrtille: "2380 g", sucre: "1820 g", citron: "70 ml" },
      { nb: 15, myrtille: "2550 g", sucre: "1950 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫐", titre: "Macérer", detail: "Mélanger les myrtilles au sucre et au citron, laisser dégorger 1 h.", badge: "⏱ 1 h" },
      { icone: "🔥", titre: "Cuire", detail: "Cuire à feu vif en remuant et en écrasant une partie des fruits.", badge: "⏱ 25 min" },
      { icone: "💧", titre: "Tester", detail: "Test de la goutte sur assiette froide. ASTUCE CHEF : le jus de citron, riche en pectine, aide la confiture à prendre sans surcharger en sucre.", badge: null },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant en pots stérilisés et retourner.", badge: null }
    ]
  },
  marmeladeorange: {
    nom: "Marmelade d'Orange",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["hiver"],
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍊",
    description: "La marmelade anglaise du petit-déjeuner : oranges, écorces confites et une amertume élégante équilibrée par le sucre. Le réveil des tartines d'hiver.",
    tableauMarmeladeorange: [
      { nb: 1, orange: "180 g", sucre: "140 g", citron: "5 ml" },
      { nb: 2, orange: "360 g", sucre: "280 g", citron: "10 ml" },
      { nb: 3, orange: "540 g", sucre: "420 g", citron: "15 ml" },
      { nb: 4, orange: "720 g", sucre: "560 g", citron: "20 ml" },
      { nb: 5, orange: "900 g", sucre: "700 g", citron: "25 ml" },
      { nb: 6, orange: "1080 g", sucre: "840 g", citron: "30 ml" },
      { nb: 7, orange: "1260 g", sucre: "980 g", citron: "35 ml" },
      { nb: 8, orange: "1440 g", sucre: "1120 g", citron: "40 ml" },
      { nb: 9, orange: "1620 g", sucre: "1260 g", citron: "45 ml" },
      { nb: 10, orange: "1800 g", sucre: "1400 g", citron: "50 ml" },
      { nb: 11, orange: "1980 g", sucre: "1540 g", citron: "55 ml" },
      { nb: 12, orange: "2160 g", sucre: "1680 g", citron: "60 ml" },
      { nb: 13, orange: "2340 g", sucre: "1820 g", citron: "65 ml" },
      { nb: 14, orange: "2520 g", sucre: "1960 g", citron: "70 ml" },
      { nb: 15, orange: "2700 g", sucre: "2100 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍊", titre: "Préparer", detail: "Prélever le zeste en fines lanières, peler les oranges à vif et récupérer la pulpe.", badge: "⏱ 15 min" },
      { icone: "💧", titre: "Blanchir", detail: "Blanchir les zestes 2-3 fois pour adoucir l'amertume.", badge: "⏱ 10 min" },
      { icone: "🔥", titre: "Cuire", detail: "Cuire pulpe, zestes, sucre et citron jusqu'à la prise. ASTUCE CHEF : blanchir les zestes plusieurs fois retire l'amertume agressive tout en gardant le parfum.", badge: "⏱ 35 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant en pots stérilisés.", badge: null }
    ]
  },
  geleecoing: {
    nom: "Gelée de Coing",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["automne"],
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍐",
    description: "La gelée translucide de nos grands-mères : le jus de coing, naturellement riche en pectine, prend tout seul en une gelée ambrée et parfumée.",
    tableauGeleecoing: [
      { nb: 1, coing: "200 g", sucre: "150 g", citron: "5 ml" },
      { nb: 2, coing: "400 g", sucre: "300 g", citron: "10 ml" },
      { nb: 3, coing: "600 g", sucre: "450 g", citron: "15 ml" },
      { nb: 4, coing: "800 g", sucre: "600 g", citron: "20 ml" },
      { nb: 5, coing: "1000 g", sucre: "750 g", citron: "25 ml" },
      { nb: 6, coing: "1200 g", sucre: "900 g", citron: "30 ml" },
      { nb: 7, coing: "1400 g", sucre: "1050 g", citron: "35 ml" },
      { nb: 8, coing: "1600 g", sucre: "1200 g", citron: "40 ml" },
      { nb: 9, coing: "1800 g", sucre: "1350 g", citron: "45 ml" },
      { nb: 10, coing: "2000 g", sucre: "1500 g", citron: "50 ml" },
      { nb: 11, coing: "2200 g", sucre: "1650 g", citron: "55 ml" },
      { nb: 12, coing: "2400 g", sucre: "1800 g", citron: "60 ml" },
      { nb: 13, coing: "2600 g", sucre: "1950 g", citron: "65 ml" },
      { nb: 14, coing: "2800 g", sucre: "2100 g", citron: "70 ml" },
      { nb: 15, coing: "3000 g", sucre: "2250 g", citron: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍐", titre: "Cuire les coings", detail: "Couper les coings (avec peau et pépins) et les cuire dans l'eau jusqu'à tendreté.", badge: "⏱ 40 min" },
      { icone: "💧", titre: "Extraire le jus", detail: "Filtrer à travers une étamine sans presser, pour un jus limpide.", badge: "⏱ 2 h" },
      { icone: "🔥", titre: "Cuire la gelée", detail: "Cuire le jus avec le sucre et le citron jusqu'à la prise. ASTUCE CHEF : ne presse pas l'étamine — un jus trouble donnerait une gelée opaque au lieu de translucide.", badge: "⏱ 30 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant en pots stérilisés.", badge: null }
    ]
  },
  blackbutterjersey: {
    dateAjout: "2026-07-23T09:01:00",
    nom: "Black Butter",
    cat: "tartinables", pays: "jersey",
    base: 4,
    temps: "2h30",
    niveau: "⭐ Facile",
    emoji: "🍎",
    description: "Black butter (lé nièr beurre) — la confiture noire de Jersey : des pommes cuites très longuement avec du sucre, du citron, de la cannelle et du clou de girofle, jusqu'à devenir une pâte sombre, épaisse et intensément parfumée. Tradition d'automne de l'île, elle se tartine sur du pain beurré ou des crêpes.",
    tableauBlackbutterjersey: [
      { nb: 1, pomme: "180 g", sucre: "25 g", citron: "¼", cannelle: "1 g", clougirofle: "0.3 g", sel: "0.5 g" },
      { nb: 2, pomme: "360 g", sucre: "50 g", citron: "½", cannelle: "2 g", clougirofle: "0.6 g", sel: "1 g" },
      { nb: 3, pomme: "540 g", sucre: "75 g", citron: "¾", cannelle: "3 g", clougirofle: "0.9 g", sel: "1.5 g" },
      { nb: 4, pomme: "720 g", sucre: "100 g", citron: "1", cannelle: "4 g", clougirofle: "1.2 g", sel: "2 g" },
      { nb: 5, pomme: "900 g", sucre: "125 g", citron: "1¼", cannelle: "5 g", clougirofle: "1.5 g", sel: "2.5 g" },
      { nb: 6, pomme: "1080 g", sucre: "150 g", citron: "1½", cannelle: "6 g", clougirofle: "1.8 g", sel: "3 g" },
      { nb: 7, pomme: "1260 g", sucre: "175 g", citron: "1¾", cannelle: "7 g", clougirofle: "2.1 g", sel: "3.5 g" },
      { nb: 8, pomme: "1440 g", sucre: "200 g", citron: "2", cannelle: "8 g", clougirofle: "2.4 g", sel: "4 g" },
      { nb: 9, pomme: "1620 g", sucre: "225 g", citron: "2¼", cannelle: "9 g", clougirofle: "2.7 g", sel: "4.5 g" },
      { nb: 10, pomme: "1800 g", sucre: "250 g", citron: "2½", cannelle: "10 g", clougirofle: "3 g", sel: "5 g" },
      { nb: 11, pomme: "1980 g", sucre: "275 g", citron: "2¾", cannelle: "11 g", clougirofle: "3.3 g", sel: "5.5 g" },
      { nb: 12, pomme: "2160 g", sucre: "300 g", citron: "3", cannelle: "12 g", clougirofle: "3.6 g", sel: "6 g" },
      { nb: 13, pomme: "2340 g", sucre: "325 g", citron: "3¼", cannelle: "13 g", clougirofle: "3.9 g", sel: "6.5 g" },
      { nb: 14, pomme: "2520 g", sucre: "350 g", citron: "3½", cannelle: "14 g", clougirofle: "4.2 g", sel: "7 g" },
      { nb: 15, pomme: "2700 g", sucre: "375 g", citron: "3¾", cannelle: "15 g", clougirofle: "4.5 g", sel: "7.5 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍎", titre: "Les pommes", detail: "Épluchez, épépinez et coupez les pommes en morceaux.", badge: null },
      { icone: "🍋", titre: "Le départ", detail: "Mettez-les dans une casserole avec le jus de citron et un fond d'eau.", badge: null },
      { icone: "♨️", titre: "Compoter", detail: "Laissez cuire à feu doux jusqu'à obtenir une compote épaisse.", badge: null },
      { icone: "🍬", titre: "Sucrer", detail: "Ajoutez le sucre, la cannelle, le clou de girofle moulu et la pincée de sel.", badge: null },
      { icone: "🕰️", titre: "Cuire longuement", detail: "Poursuivez la cuisson à feu très doux en remuant souvent : la pâte fonce et épaissit.", badge: null },
      { icone: "🥄", titre: "La texture", detail: "Arrêtez quand la masse est sombre, nappante et intensément parfumée.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Mettez en pot et laissez refroidir. Tartinez sur du pain beurré — le black butter de Jersey.", badge: null }
    ]
  },
});
