// ============================================================
// recettes_tartinables.js — Recettes de catégorie "tartinables" (Pâtes à tartiner) — 11 recettes
// 👉 Pour AJOUTER une pâte à tartiner : place-la juste avant le  });  final.
// ============================================================
Object.assign(recettes, {
  patetartiner: {
    nom: "Pâte à Tartiner Choco-Noisette",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:00:00",
    base: 6,
    temps: "30 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍫",
    description: "La pâte à tartiner choco-noisette maison : noisettes torréfiées mixées en praliné, mariées au chocolat pour une texture onctueuse, sans huile de palme ni additifs. Bien plus parfumée que celle du commerce.",
    tableauPateTartiner: [
      { nb: 1, noisettes: "35 g", chocolatLait: "30 g", sucreglace: "18 g", huile: "10 ml", laitpoudre: "8 g", cacao: "5 g" },
      { nb: 2, noisettes: "70 g", chocolatLait: "60 g", sucreglace: "36 g", huile: "20 ml", laitpoudre: "16 g", cacao: "10 g" },
      { nb: 3, noisettes: "105 g", chocolatLait: "90 g", sucreglace: "54 g", huile: "30 ml", laitpoudre: "24 g", cacao: "15 g" },
      { nb: 4, noisettes: "140 g", chocolatLait: "120 g", sucreglace: "72 g", huile: "40 ml", laitpoudre: "32 g", cacao: "20 g" },
      { nb: 5, noisettes: "175 g", chocolatLait: "150 g", sucreglace: "90 g", huile: "50 ml", laitpoudre: "40 g", cacao: "25 g" },
      { nb: 6, noisettes: "210 g", chocolatLait: "180 g", sucreglace: "108 g", huile: "60 ml", laitpoudre: "48 g", cacao: "30 g" },
      { nb: 7, noisettes: "245 g", chocolatLait: "210 g", sucreglace: "126 g", huile: "70 ml", laitpoudre: "56 g", cacao: "35 g" },
      { nb: 8, noisettes: "280 g", chocolatLait: "240 g", sucreglace: "144 g", huile: "80 ml", laitpoudre: "64 g", cacao: "40 g" },
      { nb: 9, noisettes: "315 g", chocolatLait: "270 g", sucreglace: "162 g", huile: "90 ml", laitpoudre: "72 g", cacao: "45 g" },
      { nb: 10, noisettes: "350 g", chocolatLait: "300 g", sucreglace: "180 g", huile: "100 ml", laitpoudre: "80 g", cacao: "50 g" },
      { nb: 11, noisettes: "385 g", chocolatLait: "330 g", sucreglace: "198 g", huile: "110 ml", laitpoudre: "88 g", cacao: "55 g" },
      { nb: 12, noisettes: "420 g", chocolatLait: "360 g", sucreglace: "216 g", huile: "120 ml", laitpoudre: "96 g", cacao: "60 g" },
      { nb: 13, noisettes: "455 g", chocolatLait: "390 g", sucreglace: "234 g", huile: "130 ml", laitpoudre: "104 g", cacao: "65 g" },
      { nb: 14, noisettes: "490 g", chocolatLait: "420 g", sucreglace: "252 g", huile: "140 ml", laitpoudre: "112 g", cacao: "70 g" },
      { nb: 15, noisettes: "525 g", chocolatLait: "450 g", sucreglace: "270 g", huile: "150 ml", laitpoudre: "120 g", cacao: "75 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les noisettes au four à 160°C jusqu'à ce qu'elles dorent et embaument.", badge: "⏱ 12 min" },
      { icone: "🤚", titre: "Émonder", detail: "Frotter les noisettes tièdes dans un torchon pour retirer la peau.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Praliné", detail: "Mixer longuement les noisettes seules jusqu'à une purée lisse et coulante. ASTUCE CHEF : continuer à mixer bien au-delà de la poudre : les noisettes relâchent leur huile et deviennent pâte liquide, c'est ce praliné maison qui fait tout le parfum.", badge: "⏱ 6 min" },
      { icone: "🍫", titre: "Fondre", detail: "Faire fondre le chocolat au lait doucement au bain-marie.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir purée de noisettes, chocolat, sucre glace, lait en poudre et cacao.", badge: "⏱ 3 min" },
      { icone: "💧", titre: "Lisser", detail: "Ajouter l'huile neutre et mixer jusqu'à lisse et brillant.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser dans un pot. Conserver à température ambiante (le froid la fige).", badge: "⏱ 2 min" }
    ]
  },
  tartinerspeculoos: {
    nom: "Pâte à Tartiner Spéculoos",
    cat: "tartinables",
    pays: "belgique",
    dateAjout: "2026-06-08T16:01:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍪",
    description: "La pâte à tartiner aux spéculoos maison : biscuits caramélisés mixés et liés au lait concentré pour une crème onctueuse et épicée. Le goût cannelle-cassonade irrésistible, en pot.",
    tableauTartinerSpeculoos: [
      { nb: 1, speculoos: "55 g", laitconcentre: "30 ml", huile: "10 ml", beurre: "8 g", cannelle: "1 pincée" },
      { nb: 2, speculoos: "110 g", laitconcentre: "60 ml", huile: "20 ml", beurre: "16 g", cannelle: "1 pincée" },
      { nb: 3, speculoos: "165 g", laitconcentre: "90 ml", huile: "30 ml", beurre: "24 g", cannelle: "1 pincée" },
      { nb: 4, speculoos: "220 g", laitconcentre: "120 ml", huile: "40 ml", beurre: "32 g", cannelle: "1 pincée" },
      { nb: 5, speculoos: "275 g", laitconcentre: "150 ml", huile: "50 ml", beurre: "40 g", cannelle: "1 pincée" },
      { nb: 6, speculoos: "330 g", laitconcentre: "180 ml", huile: "60 ml", beurre: "48 g", cannelle: "2 pincées" },
      { nb: 7, speculoos: "385 g", laitconcentre: "210 ml", huile: "70 ml", beurre: "56 g", cannelle: "2 pincées" },
      { nb: 8, speculoos: "440 g", laitconcentre: "240 ml", huile: "80 ml", beurre: "64 g", cannelle: "2 pincées" },
      { nb: 9, speculoos: "495 g", laitconcentre: "270 ml", huile: "90 ml", beurre: "72 g", cannelle: "2 pincées" },
      { nb: 10, speculoos: "550 g", laitconcentre: "300 ml", huile: "100 ml", beurre: "80 g", cannelle: "2 pincées" },
      { nb: 11, speculoos: "605 g", laitconcentre: "330 ml", huile: "110 ml", beurre: "88 g", cannelle: "3 pincées" },
      { nb: 12, speculoos: "660 g", laitconcentre: "360 ml", huile: "120 ml", beurre: "96 g", cannelle: "3 pincées" },
      { nb: 13, speculoos: "715 g", laitconcentre: "390 ml", huile: "130 ml", beurre: "104 g", cannelle: "3 pincées" },
      { nb: 14, speculoos: "770 g", laitconcentre: "420 ml", huile: "140 ml", beurre: "112 g", cannelle: "3 pincées" },
      { nb: 15, speculoos: "825 g", laitconcentre: "450 ml", huile: "150 ml", beurre: "120 g", cannelle: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍪", titre: "Réduire en poudre", detail: "Mixer les spéculoos en poudre la plus fine possible. ASTUCE CHEF : plus la poudre de biscuit est fine, plus la pâte sera lisse ; mixez par à-coups puis en continu.", badge: "⏱ 3 min" },
      { icone: "🧈", titre: "Beurre", detail: "Ajouter le beurre fondu et mixer.", badge: "⏱ 2 min" },
      { icone: "🥛", titre: "Lait concentré", detail: "Incorporer le lait concentré sucré peu à peu.", badge: "⏱ 2 min" },
      { icone: "🌿", titre: "Épices", detail: "Ajouter une pointe de cannelle pour renforcer le goût spéculoos.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile neutre jusqu'à la texture tartinable voulue.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser dans un pot ; elle épaissit en refroidissant.", badge: "⏱ 2 min" }
    ]
  },
  tartinerpistache: {
    nom: "Pâte à Tartiner Pistache",
    cat: "tartinables",
    pays: "monde",
    dateAjout: "2026-06-08T16:02:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🟢",
    description: "La pâte à tartiner à la pistache, douceur tendance : pistaches mixées en pâte fine, adoucies au chocolat blanc. Couleur verte naturelle, goût intense et raffiné.",
    tableauTartinerPistache: [
      { nb: 1, pistache: "45 g", chocolatBlanc: "25 g", sucreglace: "12 g", huile: "10 ml", lait: "10 ml" },
      { nb: 2, pistache: "90 g", chocolatBlanc: "50 g", sucreglace: "24 g", huile: "20 ml", lait: "20 ml" },
      { nb: 3, pistache: "135 g", chocolatBlanc: "75 g", sucreglace: "36 g", huile: "30 ml", lait: "30 ml" },
      { nb: 4, pistache: "180 g", chocolatBlanc: "100 g", sucreglace: "48 g", huile: "40 ml", lait: "40 ml" },
      { nb: 5, pistache: "225 g", chocolatBlanc: "125 g", sucreglace: "60 g", huile: "50 ml", lait: "50 ml" },
      { nb: 6, pistache: "270 g", chocolatBlanc: "150 g", sucreglace: "72 g", huile: "60 ml", lait: "60 ml" },
      { nb: 7, pistache: "315 g", chocolatBlanc: "175 g", sucreglace: "84 g", huile: "70 ml", lait: "70 ml" },
      { nb: 8, pistache: "360 g", chocolatBlanc: "200 g", sucreglace: "96 g", huile: "80 ml", lait: "80 ml" },
      { nb: 9, pistache: "405 g", chocolatBlanc: "225 g", sucreglace: "108 g", huile: "90 ml", lait: "90 ml" },
      { nb: 10, pistache: "450 g", chocolatBlanc: "250 g", sucreglace: "120 g", huile: "100 ml", lait: "100 ml" },
      { nb: 11, pistache: "495 g", chocolatBlanc: "275 g", sucreglace: "132 g", huile: "110 ml", lait: "110 ml" },
      { nb: 12, pistache: "540 g", chocolatBlanc: "300 g", sucreglace: "144 g", huile: "120 ml", lait: "120 ml" },
      { nb: 13, pistache: "585 g", chocolatBlanc: "325 g", sucreglace: "156 g", huile: "130 ml", lait: "130 ml" },
      { nb: 14, pistache: "630 g", chocolatBlanc: "350 g", sucreglace: "168 g", huile: "140 ml", lait: "140 ml" },
      { nb: 15, pistache: "675 g", chocolatBlanc: "375 g", sucreglace: "180 g", huile: "150 ml", lait: "150 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier légèrement les pistaches émondées non salées.", badge: "⏱ 6 min" },
      { icone: "🌀", titre: "Pâte de pistache", detail: "Mixer longuement les pistaches jusqu'à une pâte fine et coulante. ASTUCE CHEF : utiliser des pistaches émondées non salées et mixer longtemps : c'est ce qui donne la couleur verte franche et la finesse, sans amertume de peau.", badge: "⏱ 7 min" },
      { icone: "🍫", titre: "Chocolat blanc", detail: "Faire fondre le chocolat blanc doucement.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir pâte de pistache, chocolat blanc fondu et sucre glace.", badge: "⏱ 2 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile et un peu de lait jusqu'à onctueux.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et conserver à température ambiante.", badge: "⏱ 2 min" }
    ]
  },
  tartinerchocoblanc: {
    nom: "Pâte à Tartiner Chocolat Blanc",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:03:00",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🤍",
    description: "Une pâte à tartiner toute douce au chocolat blanc et à la vanille, façon ganache onctueuse. Gourmande et fondante, l'alliée des tartines du goûter.",
    tableauTartinerChocoBlanc: [
      { nb: 1, chocolatBlanc: "45 g", creme: "25 ml", huile: "8 ml", laitpoudre: "6 g", vanille: "1 pincée" },
      { nb: 2, chocolatBlanc: "90 g", creme: "50 ml", huile: "16 ml", laitpoudre: "12 g", vanille: "1 pincée" },
      { nb: 3, chocolatBlanc: "135 g", creme: "75 ml", huile: "24 ml", laitpoudre: "18 g", vanille: "1 pincée" },
      { nb: 4, chocolatBlanc: "180 g", creme: "100 ml", huile: "32 ml", laitpoudre: "24 g", vanille: "1 pincée" },
      { nb: 5, chocolatBlanc: "225 g", creme: "125 ml", huile: "40 ml", laitpoudre: "30 g", vanille: "1 pincée" },
      { nb: 6, chocolatBlanc: "270 g", creme: "150 ml", huile: "48 ml", laitpoudre: "36 g", vanille: "2 pincées" },
      { nb: 7, chocolatBlanc: "315 g", creme: "175 ml", huile: "56 ml", laitpoudre: "42 g", vanille: "2 pincées" },
      { nb: 8, chocolatBlanc: "360 g", creme: "200 ml", huile: "64 ml", laitpoudre: "48 g", vanille: "2 pincées" },
      { nb: 9, chocolatBlanc: "405 g", creme: "225 ml", huile: "72 ml", laitpoudre: "54 g", vanille: "2 pincées" },
      { nb: 10, chocolatBlanc: "450 g", creme: "250 ml", huile: "80 ml", laitpoudre: "60 g", vanille: "2 pincées" },
      { nb: 11, chocolatBlanc: "495 g", creme: "275 ml", huile: "88 ml", laitpoudre: "66 g", vanille: "3 pincées" },
      { nb: 12, chocolatBlanc: "540 g", creme: "300 ml", huile: "96 ml", laitpoudre: "72 g", vanille: "3 pincées" },
      { nb: 13, chocolatBlanc: "585 g", creme: "325 ml", huile: "104 ml", laitpoudre: "78 g", vanille: "3 pincées" },
      { nb: 14, chocolatBlanc: "630 g", creme: "350 ml", huile: "112 ml", laitpoudre: "84 g", vanille: "3 pincées" },
      { nb: 15, chocolatBlanc: "675 g", creme: "375 ml", huile: "120 ml", laitpoudre: "90 g", vanille: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍫", titre: "Hacher", detail: "Hacher finement le chocolat blanc.", badge: "⏱ 3 min" },
      { icone: "🥛", titre: "Crème chaude", detail: "Chauffer la crème puis la verser sur le chocolat blanc. ASTUCE CHEF : le chocolat blanc brûle très vite, ne jamais le chauffer directement : la crème chaude versée dessus le fait fondre tout en douceur.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Émulsionner", detail: "Remuer du centre vers l'extérieur jusqu'à une ganache lisse.", badge: "⏱ 2 min" },
      { icone: "🌼", titre: "Vanille", detail: "Ajouter la vanille et le lait en poudre.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec l'huile, mélanger.", badge: "⏱ 1 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, laisser épaissir au frais brièvement.", badge: "⏱ 5 min" }
    ]
  },
  caramelbeurresale: {
    nom: "Pâte à Tartiner Caramel Beurre Salé",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:04:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🧈",
    description: "Le caramel au beurre salé breton, version tartinable : un caramel ambré et coulant, adouci de crème et relevé d'une pointe de fleur de sel. Sur des crêpes ou à la petite cuillère.",
    tableauCaramelBeurreSale: [
      { nb: 1, sucre: "40 g", creme: "30 ml", beurre: "15 g", fleurdesel: "1 pincée" },
      { nb: 2, sucre: "80 g", creme: "60 ml", beurre: "30 g", fleurdesel: "1 pincée" },
      { nb: 3, sucre: "120 g", creme: "90 ml", beurre: "45 g", fleurdesel: "1 pincée" },
      { nb: 4, sucre: "160 g", creme: "120 ml", beurre: "60 g", fleurdesel: "1 pincée" },
      { nb: 5, sucre: "200 g", creme: "150 ml", beurre: "75 g", fleurdesel: "1 pincée" },
      { nb: 6, sucre: "240 g", creme: "180 ml", beurre: "90 g", fleurdesel: "2 pincées" },
      { nb: 7, sucre: "280 g", creme: "210 ml", beurre: "105 g", fleurdesel: "2 pincées" },
      { nb: 8, sucre: "320 g", creme: "240 ml", beurre: "120 g", fleurdesel: "2 pincées" },
      { nb: 9, sucre: "360 g", creme: "270 ml", beurre: "135 g", fleurdesel: "2 pincées" },
      { nb: 10, sucre: "400 g", creme: "300 ml", beurre: "150 g", fleurdesel: "2 pincées" },
      { nb: 11, sucre: "440 g", creme: "330 ml", beurre: "165 g", fleurdesel: "3 pincées" },
      { nb: 12, sucre: "480 g", creme: "360 ml", beurre: "180 g", fleurdesel: "3 pincées" },
      { nb: 13, sucre: "520 g", creme: "390 ml", beurre: "195 g", fleurdesel: "3 pincées" },
      { nb: 14, sucre: "560 g", creme: "420 ml", beurre: "210 g", fleurdesel: "3 pincées" },
      { nb: 15, sucre: "600 g", creme: "450 ml", beurre: "225 g", fleurdesel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel à sec", detail: "Faire fondre le sucre à sec, sans remuer, jusqu'à un caramel ambré.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Déglacer", detail: "Hors du feu, verser la crème TIÈDE en plusieurs fois. ASTUCE CHEF : crème tiède (jamais froide) versée hors du feu : ça évite les projections et le caramel qui durcit en bloc.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Beurre", detail: "Incorporer le beurre en morceaux jusqu'à fondu.", badge: "⏱ 2 min" },
      { icone: "🧂", titre: "Fleur de sel", detail: "Ajouter la fleur de sel et mélanger.", badge: "⏱ 1 min" },
      { icone: "♨️", titre: "Réduire", detail: "Cuire 2-3 minutes jusqu'à une consistance nappante.", badge: "⏱ 3 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot ; il épaissit en refroidissant.", badge: "⏱ 4 min" }
    ]
  },
  lemoncurd: {
    nom: "Lemon Curd",
    cat: "tartinables",
    pays: "angleterre",
    dateAjout: "2026-06-08T16:05:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍋",
    description: "La crème de citron anglaise : acidulée, soyeuse et brillante, montée au beurre. Parfaite à tartiner, à fourrer ou à napper sur un cheesecake.",
    tableauLemonCurd: [
      { nb: 1, citron: "1", oeuf: "1", sucre: "30 g", beurre: "15 g" },
      { nb: 2, citron: "1", oeuf: "1", sucre: "60 g", beurre: "30 g" },
      { nb: 3, citron: "2", oeuf: "2", sucre: "90 g", beurre: "45 g" },
      { nb: 4, citron: "2", oeuf: "3", sucre: "120 g", beurre: "60 g" },
      { nb: 5, citron: "3", oeuf: "4", sucre: "150 g", beurre: "75 g" },
      { nb: 6, citron: "3", oeuf: "4", sucre: "180 g", beurre: "90 g" },
      { nb: 7, citron: "4", oeuf: "5", sucre: "210 g", beurre: "105 g" },
      { nb: 8, citron: "4", oeuf: "6", sucre: "240 g", beurre: "120 g" },
      { nb: 9, citron: "5", oeuf: "6", sucre: "270 g", beurre: "135 g" },
      { nb: 10, citron: "5", oeuf: "7", sucre: "300 g", beurre: "150 g" },
      { nb: 11, citron: "6", oeuf: "8", sucre: "330 g", beurre: "165 g" },
      { nb: 12, citron: "6", oeuf: "8", sucre: "360 g", beurre: "180 g" },
      { nb: 13, citron: "7", oeuf: "9", sucre: "390 g", beurre: "195 g" },
      { nb: 14, citron: "7", oeuf: "10", sucre: "420 g", beurre: "210 g" },
      { nb: 15, citron: "8", oeuf: "11", sucre: "450 g", beurre: "225 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍋", titre: "Zester & presser", detail: "Zester puis presser les citrons.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Battre", detail: "Fouetter les œufs avec le sucre, le jus et le zeste.", badge: "⏱ 3 min" },
      { icone: "♨️", titre: "Cuisson douce", detail: "Cuire au bain-marie en remuant sans cesse jusqu'à épaississement. ASTUCE CHEF : feu doux au bain-marie et fouet constant : si le mélange bout, les œufs coagulent et le curd devient granuleux.", badge: "⏱ 10 min" },
      { icone: "🧈", titre: "Monter au beurre", detail: "Hors du feu, incorporer le beurre froid en parcelles.", badge: "⏱ 2 min" },
      { icone: "🫗", titre: "Filtrer", detail: "Passer au tamis pour une texture parfaitement lisse.", badge: "⏱ 2 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Filmer au contact et réfrigérer ; il fige en refroidissant.", badge: "⏱ 2 h" }
    ]
  },
  tartinerchococo: {
    nom: "Pâte à Tartiner Choco-Coco",
    cat: "tartinables",
    pays: "monde",
    dateAjout: "2026-06-08T16:06:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥥",
    description: "Une pâte à tartiner gourmande chocolat et noix de coco, dans l'esprit d'une barre Bounty. Le fondant du chocolat et le parfum tropical de la coco.",
    tableauTartinerChocoCo: [
      { nb: 1, noixCoco: "30 g", chocolatLait: "30 g", laitcoco: "25 ml", sucreglace: "12 g", huile: "8 ml" },
      { nb: 2, noixCoco: "60 g", chocolatLait: "60 g", laitcoco: "50 ml", sucreglace: "24 g", huile: "16 ml" },
      { nb: 3, noixCoco: "90 g", chocolatLait: "90 g", laitcoco: "75 ml", sucreglace: "36 g", huile: "24 ml" },
      { nb: 4, noixCoco: "120 g", chocolatLait: "120 g", laitcoco: "100 ml", sucreglace: "48 g", huile: "32 ml" },
      { nb: 5, noixCoco: "150 g", chocolatLait: "150 g", laitcoco: "125 ml", sucreglace: "60 g", huile: "40 ml" },
      { nb: 6, noixCoco: "180 g", chocolatLait: "180 g", laitcoco: "150 ml", sucreglace: "72 g", huile: "48 ml" },
      { nb: 7, noixCoco: "210 g", chocolatLait: "210 g", laitcoco: "175 ml", sucreglace: "84 g", huile: "56 ml" },
      { nb: 8, noixCoco: "240 g", chocolatLait: "240 g", laitcoco: "200 ml", sucreglace: "96 g", huile: "64 ml" },
      { nb: 9, noixCoco: "270 g", chocolatLait: "270 g", laitcoco: "225 ml", sucreglace: "108 g", huile: "72 ml" },
      { nb: 10, noixCoco: "300 g", chocolatLait: "300 g", laitcoco: "250 ml", sucreglace: "120 g", huile: "80 ml" },
      { nb: 11, noixCoco: "330 g", chocolatLait: "330 g", laitcoco: "275 ml", sucreglace: "132 g", huile: "88 ml" },
      { nb: 12, noixCoco: "360 g", chocolatLait: "360 g", laitcoco: "300 ml", sucreglace: "144 g", huile: "96 ml" },
      { nb: 13, noixCoco: "390 g", chocolatLait: "390 g", laitcoco: "325 ml", sucreglace: "156 g", huile: "104 ml" },
      { nb: 14, noixCoco: "420 g", chocolatLait: "420 g", laitcoco: "350 ml", sucreglace: "168 g", huile: "112 ml" },
      { nb: 15, noixCoco: "450 g", chocolatLait: "450 g", laitcoco: "375 ml", sucreglace: "180 g", huile: "120 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥥", titre: "Torréfier la coco", detail: "Faire dorer légèrement la noix de coco râpée à la poêle.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer la coco torréfiée pour la réduire en pâte. ASTUCE CHEF : torréfier la coco avant de la mixer réveille ses huiles et son parfum, la pâte n'en sera que plus intense.", badge: "⏱ 4 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Faire fondre le chocolat au lait.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir coco, chocolat, lait de coco et sucre glace.", badge: "⏱ 2 min" },
      { icone: "💧", titre: "Lisser", detail: "Ajouter l'huile et lisser au mixeur.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, conserver à température ambiante.", badge: "⏱ 2 min" }
    ]
  },
  tartinerchocoorange: {
    nom: "Pâte à Tartiner Choco-Orange",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:07:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍊",
    description: "L'alliance chocolat noir et orange en pâte à tartiner : une ganache intense parfumée au zeste et au jus d'orange. Élégante, légèrement amère, terriblement gourmande.",
    tableauTartinerChocoOrange: [
      { nb: 1, chocolatnoir: "40 g", creme: "25 ml", orange: "1", beurre: "10 g", sucre: "8 g" },
      { nb: 2, chocolatnoir: "80 g", creme: "50 ml", orange: "1", beurre: "20 g", sucre: "16 g" },
      { nb: 3, chocolatnoir: "120 g", creme: "75 ml", orange: "1", beurre: "30 g", sucre: "24 g" },
      { nb: 4, chocolatnoir: "160 g", creme: "100 ml", orange: "1", beurre: "40 g", sucre: "32 g" },
      { nb: 5, chocolatnoir: "200 g", creme: "125 ml", orange: "2", beurre: "50 g", sucre: "40 g" },
      { nb: 6, chocolatnoir: "240 g", creme: "150 ml", orange: "2", beurre: "60 g", sucre: "48 g" },
      { nb: 7, chocolatnoir: "280 g", creme: "175 ml", orange: "2", beurre: "70 g", sucre: "56 g" },
      { nb: 8, chocolatnoir: "320 g", creme: "200 ml", orange: "2", beurre: "80 g", sucre: "64 g" },
      { nb: 9, chocolatnoir: "360 g", creme: "225 ml", orange: "3", beurre: "90 g", sucre: "72 g" },
      { nb: 10, chocolatnoir: "400 g", creme: "250 ml", orange: "3", beurre: "100 g", sucre: "80 g" },
      { nb: 11, chocolatnoir: "440 g", creme: "275 ml", orange: "3", beurre: "110 g", sucre: "88 g" },
      { nb: 12, chocolatnoir: "480 g", creme: "300 ml", orange: "4", beurre: "120 g", sucre: "96 g" },
      { nb: 13, chocolatnoir: "520 g", creme: "325 ml", orange: "4", beurre: "130 g", sucre: "104 g" },
      { nb: 14, chocolatnoir: "560 g", creme: "350 ml", orange: "4", beurre: "140 g", sucre: "112 g" },
      { nb: 15, chocolatnoir: "600 g", creme: "375 ml", orange: "5", beurre: "150 g", sucre: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍊", titre: "Zester", detail: "Zester l'orange puis la presser. ASTUCE CHEF : zester avant de presser : c'est l'huile essentielle du zeste qui porte l'essentiel du parfum d'orange, le jus n'apporte que l'acidité.", badge: "⏱ 4 min" },
      { icone: "🍫", titre: "Hacher", detail: "Hacher le chocolat noir.", badge: "⏱ 2 min" },
      { icone: "🥛", titre: "Ganache", detail: "Chauffer la crème avec le jus d'orange et verser sur le chocolat.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Émulsionner", detail: "Remuer jusqu'à une ganache lisse et brillante.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Beurre & zeste", detail: "Incorporer le beurre et le zeste, mélanger.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et laisser prendre légèrement.", badge: "⏱ 5 min" }
    ]
  },
  pralinerose: {
    nom: "Pâte à Tartiner Praliné Rose",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:08:00",
    base: 6,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🌸",
    description: "La gourmandise lyonnaise en pâte à tartiner : pralines roses concassées liées à une douce base de chocolat blanc. Croquante, rose bonbon et régressive.",
    tableauPralineRose: [
      { nb: 1, pralinesroses: "40 g", chocolatBlanc: "25 g", creme: "20 ml", beurre: "8 g" },
      { nb: 2, pralinesroses: "80 g", chocolatBlanc: "50 g", creme: "40 ml", beurre: "16 g" },
      { nb: 3, pralinesroses: "120 g", chocolatBlanc: "75 g", creme: "60 ml", beurre: "24 g" },
      { nb: 4, pralinesroses: "160 g", chocolatBlanc: "100 g", creme: "80 ml", beurre: "32 g" },
      { nb: 5, pralinesroses: "200 g", chocolatBlanc: "125 g", creme: "100 ml", beurre: "40 g" },
      { nb: 6, pralinesroses: "240 g", chocolatBlanc: "150 g", creme: "120 ml", beurre: "48 g" },
      { nb: 7, pralinesroses: "280 g", chocolatBlanc: "175 g", creme: "140 ml", beurre: "56 g" },
      { nb: 8, pralinesroses: "320 g", chocolatBlanc: "200 g", creme: "160 ml", beurre: "64 g" },
      { nb: 9, pralinesroses: "360 g", chocolatBlanc: "225 g", creme: "180 ml", beurre: "72 g" },
      { nb: 10, pralinesroses: "400 g", chocolatBlanc: "250 g", creme: "200 ml", beurre: "80 g" },
      { nb: 11, pralinesroses: "440 g", chocolatBlanc: "275 g", creme: "220 ml", beurre: "88 g" },
      { nb: 12, pralinesroses: "480 g", chocolatBlanc: "300 g", creme: "240 ml", beurre: "96 g" },
      { nb: 13, pralinesroses: "520 g", chocolatBlanc: "325 g", creme: "260 ml", beurre: "104 g" },
      { nb: 14, pralinesroses: "560 g", chocolatBlanc: "350 g", creme: "280 ml", beurre: "112 g" },
      { nb: 15, pralinesroses: "600 g", chocolatBlanc: "375 g", creme: "300 ml", beurre: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌸", titre: "Concasser", detail: "Concasser grossièrement les pralines roses.", badge: "⏱ 4 min" },
      { icone: "🌀", titre: "Mixer une partie", detail: "Mixer la moitié des pralines en poudre fine, garder l'autre en éclats. ASTUCE CHEF : garder une partie en éclats apporte le croquant caractéristique ; tout mixer donnerait une pâte plate, sans texture.", badge: "⏱ 3 min" },
      { icone: "🍫", titre: "Base", detail: "Faire fondre le chocolat blanc avec la crème en ganache.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Incorporer la poudre puis les éclats de pralines.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Lier", detail: "Ajouter le beurre pour le fondant.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot, jolie couleur rose.", badge: "⏱ 4 min" }
    ]
  },
  tartineramandecacao: {
    nom: "Pâte à Tartiner Amande-Cacao",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:09:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🌰",
    description: "Une pâte à tartiner plus saine : purée d'amandes maison et cacao, sucrée au sirop d'agave, sans chocolat ajouté ni huile de palme. Intense en cacao et riche en bons gras.",
    tableauTartinerAmandeCacao: [
      { nb: 1, amandes: "45 g", cacao: "8 g", siropagave: "15 g", huile: "8 ml", sel: "1 pincée" },
      { nb: 2, amandes: "90 g", cacao: "16 g", siropagave: "30 g", huile: "16 ml", sel: "1 pincée" },
      { nb: 3, amandes: "135 g", cacao: "24 g", siropagave: "45 g", huile: "24 ml", sel: "1 pincée" },
      { nb: 4, amandes: "180 g", cacao: "32 g", siropagave: "60 g", huile: "32 ml", sel: "1 pincée" },
      { nb: 5, amandes: "225 g", cacao: "40 g", siropagave: "75 g", huile: "40 ml", sel: "1 pincée" },
      { nb: 6, amandes: "270 g", cacao: "48 g", siropagave: "90 g", huile: "48 ml", sel: "2 pincées" },
      { nb: 7, amandes: "315 g", cacao: "56 g", siropagave: "105 g", huile: "56 ml", sel: "2 pincées" },
      { nb: 8, amandes: "360 g", cacao: "64 g", siropagave: "120 g", huile: "64 ml", sel: "2 pincées" },
      { nb: 9, amandes: "405 g", cacao: "72 g", siropagave: "135 g", huile: "72 ml", sel: "2 pincées" },
      { nb: 10, amandes: "450 g", cacao: "80 g", siropagave: "150 g", huile: "80 ml", sel: "2 pincées" },
      { nb: 11, amandes: "495 g", cacao: "88 g", siropagave: "165 g", huile: "88 ml", sel: "3 pincées" },
      { nb: 12, amandes: "540 g", cacao: "96 g", siropagave: "180 g", huile: "96 ml", sel: "3 pincées" },
      { nb: 13, amandes: "585 g", cacao: "104 g", siropagave: "195 g", huile: "104 ml", sel: "3 pincées" },
      { nb: 14, amandes: "630 g", cacao: "112 g", siropagave: "210 g", huile: "112 ml", sel: "3 pincées" },
      { nb: 15, amandes: "675 g", cacao: "120 g", siropagave: "225 g", huile: "120 ml", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔥", titre: "Torréfier", detail: "Torréfier les amandes au four pour révéler leur goût.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Purée d'amande", detail: "Mixer longuement les amandes jusqu'à une purée coulante. ASTUCE CHEF : comme les noisettes, persévérez au mixeur : la poudre devient pâte quand l'huile des amandes se libère, c'est la base de la tartinade.", badge: "⏱ 7 min" },
      { icone: "🍫", titre: "Cacao", detail: "Ajouter le cacao non sucré et une pincée de sel.", badge: "⏱ 1 min" },
      { icone: "🍯", titre: "Sucrer", detail: "Incorporer le sirop d'agave (ou miel) selon le goût.", badge: "⏱ 1 min" },
      { icone: "💧", titre: "Lisser", detail: "Détendre avec un filet d'huile jusqu'à tartinable.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot ; remuer avant usage (séparation naturelle).", badge: "⏱ 2 min" }
    ]
  },
  tartinerchococaramel: {
    nom: "Pâte à Tartiner Choco-Caramel",
    cat: "tartinables",
    pays: "france",
    dateAjout: "2026-06-08T16:10:00",
    base: 6,
    temps: "25 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "Le mariage du chocolat au lait et du caramel en pâte à tartiner : une marbrure fondante et gourmande, relevée d'une pointe de fleur de sel. Pour les tartines régressives.",
    tableauTartinerChocoCaramel: [
      { nb: 1, chocolatLait: "30 g", sucre: "25 g", creme: "25 ml", beurre: "10 g", fleurdesel: "1 pincée" },
      { nb: 2, chocolatLait: "60 g", sucre: "50 g", creme: "50 ml", beurre: "20 g", fleurdesel: "1 pincée" },
      { nb: 3, chocolatLait: "90 g", sucre: "75 g", creme: "75 ml", beurre: "30 g", fleurdesel: "1 pincée" },
      { nb: 4, chocolatLait: "120 g", sucre: "100 g", creme: "100 ml", beurre: "40 g", fleurdesel: "1 pincée" },
      { nb: 5, chocolatLait: "150 g", sucre: "125 g", creme: "125 ml", beurre: "50 g", fleurdesel: "1 pincée" },
      { nb: 6, chocolatLait: "180 g", sucre: "150 g", creme: "150 ml", beurre: "60 g", fleurdesel: "2 pincées" },
      { nb: 7, chocolatLait: "210 g", sucre: "175 g", creme: "175 ml", beurre: "70 g", fleurdesel: "2 pincées" },
      { nb: 8, chocolatLait: "240 g", sucre: "200 g", creme: "200 ml", beurre: "80 g", fleurdesel: "2 pincées" },
      { nb: 9, chocolatLait: "270 g", sucre: "225 g", creme: "225 ml", beurre: "90 g", fleurdesel: "2 pincées" },
      { nb: 10, chocolatLait: "300 g", sucre: "250 g", creme: "250 ml", beurre: "100 g", fleurdesel: "2 pincées" },
      { nb: 11, chocolatLait: "330 g", sucre: "275 g", creme: "275 ml", beurre: "110 g", fleurdesel: "3 pincées" },
      { nb: 12, chocolatLait: "360 g", sucre: "300 g", creme: "300 ml", beurre: "120 g", fleurdesel: "3 pincées" },
      { nb: 13, chocolatLait: "390 g", sucre: "325 g", creme: "325 ml", beurre: "130 g", fleurdesel: "3 pincées" },
      { nb: 14, chocolatLait: "420 g", sucre: "350 g", creme: "350 ml", beurre: "140 g", fleurdesel: "3 pincées" },
      { nb: 15, chocolatLait: "450 g", sucre: "375 g", creme: "375 ml", beurre: "150 g", fleurdesel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel", detail: "Réaliser un caramel à sec ambré.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Déglacer", detail: "Déglacer hors du feu avec la crème tiède.", badge: "⏱ 2 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Faire fondre le chocolat au lait à part.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Marbrer", detail: "Incorporer le caramel tiède au chocolat fondu. ASTUCE CHEF : mélanger le caramel encore tiède au chocolat fondu (pas froid) donne cette marbrure fondante et homogène, sans grumeaux de caramel figé.", badge: "⏱ 2 min" },
      { icone: "🧈", titre: "Lier", detail: "Ajouter le beurre et la fleur de sel.", badge: "⏱ 2 min" },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser en pot et laisser prendre.", badge: "⏱ 5 min" }
    ]
  },
  caviaraubergine: {
    nom: "Caviar d'aubergine", cat: "tartinables", pays: "france",
    base: 4, temps: "45 min", niveau: "⭐ Facile", emoji: "🍆",
    description: "Une tartinade méditerranéenne fondante : la chair d'aubergines rôties au four, fouettée avec ail, citron, tahin et huile d'olive. Parfait à l'apéro sur du pain grillé.",
    ingredients: { "Aubergine (g)": 600, "Ail (gousse)": 1, "Huile d'olive (ml)": 40, "Jus de citron (ml)": 15, "Tahin (g)": 20, "Cumin (g)": 2, "Sel (g)": 4, "Persil (g)": 10 },
    etapes: [
      { icone: "🔥", titre: "Rôtir", detail: "Piquer les aubergines et les rôtir au four jusqu'à ce que la peau soit boursouflée et la chair fondante.", badge: "⏱ 35 min" },
      { icone: "🥄", titre: "Évider", detail: "Laisser tiédir, fendre les aubergines et récupérer la chair à la cuillère.", badge: null },
      { icone: "🌀", titre: "Mixer", detail: "Mixer la chair avec l'ail, le jus de citron, le tahin, l'huile d'olive et le cumin.", badge: null },
      { icone: "🧂", titre: "Assaisonner", detail: "Saler et ajuster en citron. Incorporer le persil ciselé.", badge: null },
      { icone: "❄️", titre: "Réserver", detail: "Réserver au frais au moins 30 min pour développer les saveurs.", badge: "⏱ 30 min" },
      { icone: "🍞", titre: "Servir", detail: "Servir frais, filé d'huile d'olive, avec du pain grillé.", badge: null }
    ]
  },
  confiturefraise: {
    nom: "Confiture de fraises", cat: "tartinables", pays: "france",
    base: 6, temps: "40 min", niveau: "⭐ Facile", emoji: "🍓",
    description: "La confiture maison comme à la ferme : des fraises gorgées de soleil, juste assez de sucre et un trait de citron pour une prise parfaite. Le goût de l'été en pot.",
    ingredients: { "Fraises (g)": 1000, "Sucre (g)": 800, "Jus de citron (ml)": 30 },
    etapes: [
      { icone: "🍓", titre: "Macérer", detail: "Équeuter et couper les fraises. Les mélanger au sucre et au jus de citron, laisser dégorger quelques heures.", badge: "⏱ 2 h" },
      { icone: "🔥", titre: "Cuire", detail: "Porter à ébullition puis laisser cuire à feu vif en remuant.", badge: "⏱ 25 min" },
      { icone: "🥄", titre: "Écumer", detail: "Écumer la mousse rose qui se forme en surface.", badge: null },
      { icone: "💧", titre: "Tester", detail: "Test de la goutte : une goutte déposée sur une assiette froide doit figer.", badge: null },
      { icone: "🫙", titre: "Mettre en pot", detail: "Verser brûlant dans des pots stérilisés, fermer et retourner jusqu'à refroidissement.", badge: null }
    ]
  },
});
