// ============================================================
// recettes_glaces.js — Recettes de catégorie "glaces" (Glaces & Sorbets) — 20 recettes
// 👉 Pour AJOUTER une glace : place-la juste avant le  });  final.
// ============================================================
Object.assign(recettes, {

  glacevanille: {
    nom: "Glace Vanille",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:00:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace vanille maison onctueuse sur base de crème anglaise, parfumée à la gousse.",
    tableauGlaceVanille: [
      { nb: 1, lait: "200 ml", creme: "160 ml", jaunedoeuf: "4", sucre: "80 g", vanille: "4 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", jaunedoeuf: "8", sucre: "160 g", vanille: "8 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", jaunedoeuf: "12", sucre: "240 g", vanille: "12 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", jaunedoeuf: "16", sucre: "320 g", vanille: "16 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", jaunedoeuf: "20", sucre: "400 g", vanille: "20 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", jaunedoeuf: "24", sucre: "480 g", vanille: "24 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", jaunedoeuf: "28", sucre: "560 g", vanille: "28 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", jaunedoeuf: "32", sucre: "640 g", vanille: "32 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", jaunedoeuf: "36", sucre: "720 g", vanille: "36 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", jaunedoeuf: "40", sucre: "800 g", vanille: "40 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Chauffer le lait et la crème avec la gousse de vanille fendue.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter les jaunes avec le sucre jusqu'à blanchiment.", badge: null },
      { icone: "♨️", titre: "Crème anglaise", detail: "Verser le lait chaud sur les jaunes, cuire à feu doux sans bouillir. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir rapidement la crème puis réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner en sorbetière (ou méthode sans).", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Réserver au congélateur pour raffermir.", badge: "⏱ 1 h" }
    ]
  },
  glacechocolat: {
    nom: "Glace Chocolat",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:01:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍫",
    description: "Une glace au chocolat noir intense et crémeuse, sur base de crème anglaise.",
    tableauGlaceChocolat: [
      { nb: 1, lait: "200 ml", creme: "160 ml", chocolatnoir: "100 g", jaunedoeuf: "4", sucre: "60 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", chocolatnoir: "200 g", jaunedoeuf: "8", sucre: "120 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", chocolatnoir: "300 g", jaunedoeuf: "12", sucre: "180 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", chocolatnoir: "400 g", jaunedoeuf: "16", sucre: "240 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", chocolatnoir: "500 g", jaunedoeuf: "20", sucre: "300 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", chocolatnoir: "600 g", jaunedoeuf: "24", sucre: "360 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", chocolatnoir: "700 g", jaunedoeuf: "28", sucre: "420 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", chocolatnoir: "800 g", jaunedoeuf: "32", sucre: "480 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", chocolatnoir: "900 g", jaunedoeuf: "36", sucre: "540 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", chocolatnoir: "1000 g", jaunedoeuf: "40", sucre: "600 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Verser sur le chocolat haché et lisser.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer la préparation.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner puis raffermir au congélateur.", badge: "⏱ 30 min" }
    ]
  },
  glacepistache: {
    nom: "Glace Pistache",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:02:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace à la pistache, douce et parfumée, à la couleur naturelle délicate.",
    tableauGlacePistache: [
      { nb: 1, lait: "200 ml", creme: "160 ml", pistache: "100 g", jaunedoeuf: "4", sucre: "72 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", pistache: "200 g", jaunedoeuf: "8", sucre: "144 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", pistache: "300 g", jaunedoeuf: "12", sucre: "216 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", pistache: "400 g", jaunedoeuf: "16", sucre: "288 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", pistache: "500 g", jaunedoeuf: "20", sucre: "360 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", pistache: "600 g", jaunedoeuf: "24", sucre: "432 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", pistache: "700 g", jaunedoeuf: "28", sucre: "504 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", pistache: "800 g", jaunedoeuf: "32", sucre: "576 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", pistache: "900 g", jaunedoeuf: "36", sucre: "648 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", pistache: "1000 g", jaunedoeuf: "40", sucre: "720 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Pâte", detail: "Mixer les pistaches en pâte fine. ASTUCE CHEF : utilise des pistaches émondées non salées et mixe-les en pâte, c'est plus parfumé et naturel qu'un arôme.", badge: null },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème avec la pâte de pistache.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise sans bouillir.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacecafe: {
    nom: "Glace Café",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:03:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "☕",
    description: "Une glace au café corsée et veloutée, idéale en affogato ou en fin de repas.",
    tableauGlaceCafe: [
      { nb: 1, lait: "200 ml", creme: "160 ml", cafe: "20 g", jaunedoeuf: "4", sucre: "72 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", cafe: "40 g", jaunedoeuf: "8", sucre: "144 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", cafe: "60 g", jaunedoeuf: "12", sucre: "216 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", cafe: "80 g", jaunedoeuf: "16", sucre: "288 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", cafe: "100 g", jaunedoeuf: "20", sucre: "360 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", cafe: "120 g", jaunedoeuf: "24", sucre: "432 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", cafe: "140 g", jaunedoeuf: "28", sucre: "504 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", cafe: "160 g", jaunedoeuf: "32", sucre: "576 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", cafe: "180 g", jaunedoeuf: "36", sucre: "648 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", cafe: "200 g", jaunedoeuf: "40", sucre: "720 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "☕", titre: "Infuser", detail: "Infuser le café fort dans le lait et la crème chauds. ASTUCE CHEF : un expresso serré ou du café soluble de qualité donne plus de profondeur qu'un café allongé.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacecaramel: {
    nom: "Glace Caramel Beurre Salé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:04:00",
    base: 1,
    temps: "35 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "La glace au caramel au beurre salé, gourmande et fondante, aux notes ambrées.",
    tableauGlaceCaramel: [
      { nb: 1, sucre: "100 g", beurre: "32 g", lait: "200 ml", creme: "160 ml", jaunedoeuf: "4", sel: "1 g" },
      { nb: 2, sucre: "200 g", beurre: "64 g", lait: "400 ml", creme: "320 ml", jaunedoeuf: "8", sel: "2 g" },
      { nb: 3, sucre: "300 g", beurre: "96 g", lait: "600 ml", creme: "480 ml", jaunedoeuf: "12", sel: "3 g" },
      { nb: 4, sucre: "400 g", beurre: "128 g", lait: "800 ml", creme: "640 ml", jaunedoeuf: "16", sel: "4 g" },
      { nb: 5, sucre: "500 g", beurre: "160 g", lait: "1000 ml", creme: "800 ml", jaunedoeuf: "20", sel: "5 g" },
      { nb: 6, sucre: "600 g", beurre: "192 g", lait: "1200 ml", creme: "960 ml", jaunedoeuf: "24", sel: "6 g" },
      { nb: 7, sucre: "700 g", beurre: "224 g", lait: "1400 ml", creme: "1120 ml", jaunedoeuf: "28", sel: "7 g" },
      { nb: 8, sucre: "800 g", beurre: "256 g", lait: "1600 ml", creme: "1280 ml", jaunedoeuf: "32", sel: "8 g" },
      { nb: 9, sucre: "900 g", beurre: "288 g", lait: "1800 ml", creme: "1440 ml", jaunedoeuf: "36", sel: "9 g" },
      { nb: 10, sucre: "1000 g", beurre: "320 g", lait: "2000 ml", creme: "1600 ml", jaunedoeuf: "40", sel: "10 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel", detail: "Réaliser un caramel à sec puis décuire au beurre salé. ASTUCE CHEF : pousse le caramel jusqu'à une couleur ambrée foncée (sans brûler) : c'est l'amertume légère qui fait le caractère du caramel beurre salé.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Détendre", detail: "Verser lait et crème chauds sur le caramel.", badge: null },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter le jaune.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise caramel.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacestracciatella: {
    nom: "Glace Stracciatella",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:05:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace italienne au lait parsemée d'éclats de chocolat croquants.",
    tableauGlaceStracciatella: [
      { nb: 1, lait: "200 ml", creme: "160 ml", sucre: "72 g", jaunedoeuf: "4", chocolatnoir: "60 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", sucre: "144 g", jaunedoeuf: "8", chocolatnoir: "120 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", sucre: "216 g", jaunedoeuf: "12", chocolatnoir: "180 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", sucre: "288 g", jaunedoeuf: "16", chocolatnoir: "240 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", sucre: "360 g", jaunedoeuf: "20", chocolatnoir: "300 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", sucre: "432 g", jaunedoeuf: "24", chocolatnoir: "360 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", sucre: "504 g", jaunedoeuf: "28", chocolatnoir: "420 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", sucre: "576 g", jaunedoeuf: "32", chocolatnoir: "480 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", sucre: "648 g", jaunedoeuf: "36", chocolatnoir: "540 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", sucre: "720 g", jaunedoeuf: "40", chocolatnoir: "600 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer puis turbiner.", badge: "⏱ 2 h" },
      { icone: "🍫", titre: "Éclats", detail: "En fin de turbinage, verser le chocolat fondu en filet. ASTUCE CHEF : verse le chocolat fondu en mince filet sur la glace en mouvement : il fige instantanément en fins éclats croquants.", badge: null },
      { icone: "🌀", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacementhe: {
    nom: "Glace Menthe-Chocolat",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:06:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🌿",
    description: "La glace menthe fraîche aux pépites de chocolat, rafraîchissante et gourmande.",
    tableauGlaceMenthe: [
      { nb: 1, lait: "200 ml", creme: "160 ml", menthe: "24 g", sucre: "72 g", jaunedoeuf: "4", chocolatnoir: "60 g" },
      { nb: 2, lait: "400 ml", creme: "320 ml", menthe: "48 g", sucre: "144 g", jaunedoeuf: "8", chocolatnoir: "120 g" },
      { nb: 3, lait: "600 ml", creme: "480 ml", menthe: "72 g", sucre: "216 g", jaunedoeuf: "12", chocolatnoir: "180 g" },
      { nb: 4, lait: "800 ml", creme: "640 ml", menthe: "96 g", sucre: "288 g", jaunedoeuf: "16", chocolatnoir: "240 g" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", menthe: "120 g", sucre: "360 g", jaunedoeuf: "20", chocolatnoir: "300 g" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", menthe: "144 g", sucre: "432 g", jaunedoeuf: "24", chocolatnoir: "360 g" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", menthe: "168 g", sucre: "504 g", jaunedoeuf: "28", chocolatnoir: "420 g" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", menthe: "192 g", sucre: "576 g", jaunedoeuf: "32", chocolatnoir: "480 g" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", menthe: "216 g", sucre: "648 g", jaunedoeuf: "36", chocolatnoir: "540 g" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", menthe: "240 g", sucre: "720 g", jaunedoeuf: "40", chocolatnoir: "600 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Infuser la menthe fraîche dans le lait chaud, puis filtrer. ASTUCE CHEF : infuse de la vraie menthe fraîche puis filtre : le goût est net et naturel, loin du sirop de menthe industriel.", badge: "⏱ 15 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise mentholée.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍫", titre: "Pépites", detail: "Ajouter les pépites de chocolat en fin de turbinage.", badge: null }
    ]
  },
  glacerhumraisin: {
    nom: "Glace Rhum-Raisin",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:07:00",
    base: 1,
    temps: "30 min + macération",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace rhum-raisin, classique des grands, aux raisins moelleux gorgés de rhum.",
    tableauGlaceRhumRaisin: [
      { nb: 1, lait: "200 ml", creme: "160 ml", raisinssecs: "80 g", rhum: "40 ml", sucre: "72 g", jaunedoeuf: "4" },
      { nb: 2, lait: "400 ml", creme: "320 ml", raisinssecs: "160 g", rhum: "80 ml", sucre: "144 g", jaunedoeuf: "8" },
      { nb: 3, lait: "600 ml", creme: "480 ml", raisinssecs: "240 g", rhum: "120 ml", sucre: "216 g", jaunedoeuf: "12" },
      { nb: 4, lait: "800 ml", creme: "640 ml", raisinssecs: "320 g", rhum: "160 ml", sucre: "288 g", jaunedoeuf: "16" },
      { nb: 5, lait: "1000 ml", creme: "800 ml", raisinssecs: "400 g", rhum: "200 ml", sucre: "360 g", jaunedoeuf: "20" },
      { nb: 6, lait: "1200 ml", creme: "960 ml", raisinssecs: "480 g", rhum: "240 ml", sucre: "432 g", jaunedoeuf: "24" },
      { nb: 7, lait: "1400 ml", creme: "1120 ml", raisinssecs: "560 g", rhum: "280 ml", sucre: "504 g", jaunedoeuf: "28" },
      { nb: 8, lait: "1600 ml", creme: "1280 ml", raisinssecs: "640 g", rhum: "320 ml", sucre: "576 g", jaunedoeuf: "32" },
      { nb: 9, lait: "1800 ml", creme: "1440 ml", raisinssecs: "720 g", rhum: "360 ml", sucre: "648 g", jaunedoeuf: "36" },
      { nb: 10, lait: "2000 ml", creme: "1600 ml", raisinssecs: "800 g", rhum: "400 ml", sucre: "720 g", jaunedoeuf: "40" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍇", titre: "Macérer", detail: "Faire gonfler les raisins secs dans le rhum tiède. ASTUCE CHEF : laisse macérer les raisins plusieurs heures (voire une nuit) : moelleux et parfumés, ils ne durciront pas au congélateur.", badge: "⏱ 2 h" },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner la base refroidie.", badge: "⏱ 30 min" },
      { icone: "🍇", titre: "Raisins", detail: "Incorporer les raisins égouttés en fin de turbinage.", badge: null }
    ]
  },
  sorbetcitron: {
    nom: "Sorbet Citron",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:08:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍋",
    description: "Le sorbet citron vif et désaltérant, parfait nettoyeur de palais.",
    tableauSorbetCitron: [
      { nb: 1, citron: "160 ml", eau: "320 ml", sucre: "140 g" },
      { nb: 2, citron: "320 ml", eau: "640 ml", sucre: "280 g" },
      { nb: 3, citron: "480 ml", eau: "960 ml", sucre: "420 g" },
      { nb: 4, citron: "640 ml", eau: "1280 ml", sucre: "560 g" },
      { nb: 5, citron: "800 ml", eau: "1600 ml", sucre: "700 g" },
      { nb: 6, citron: "960 ml", eau: "1920 ml", sucre: "840 g" },
      { nb: 7, citron: "1120 ml", eau: "2240 ml", sucre: "980 g" },
      { nb: 8, citron: "1280 ml", eau: "2560 ml", sucre: "1120 g" },
      { nb: 9, citron: "1440 ml", eau: "2880 ml", sucre: "1260 g" },
      { nb: 10, citron: "1600 ml", eau: "3200 ml", sucre: "1400 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Porter l'eau et le sucre à frémissement pour dissoudre.", badge: "⏱ 4 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser refroidir complètement le sirop. ASTUCE CHEF : un sirop bien froid avant d'ajouter le jus préserve la fraîcheur et la vitamine C du citron.", badge: null },
      { icone: "🍋", titre: "Presser", detail: "Presser les citrons et filtrer le jus.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger sirop froid et jus de citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à texture sorbet.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetframboise: {
    nom: "Sorbet Framboise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:09:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet framboise intensément fruité, à la jolie couleur rubis.",
    tableauSorbetFramboise: [
      { nb: 1, framboise: "360 g", eau: "160 ml", sucre: "120 g", citron: "20 ml" },
      { nb: 2, framboise: "720 g", eau: "320 ml", sucre: "240 g", citron: "40 ml" },
      { nb: 3, framboise: "1080 g", eau: "480 ml", sucre: "360 g", citron: "60 ml" },
      { nb: 4, framboise: "1440 g", eau: "640 ml", sucre: "480 g", citron: "80 ml" },
      { nb: 5, framboise: "1800 g", eau: "800 ml", sucre: "600 g", citron: "100 ml" },
      { nb: 6, framboise: "2160 g", eau: "960 ml", sucre: "720 g", citron: "120 ml" },
      { nb: 7, framboise: "2520 g", eau: "1120 ml", sucre: "840 g", citron: "140 ml" },
      { nb: 8, framboise: "2880 g", eau: "1280 ml", sucre: "960 g", citron: "160 ml" },
      { nb: 9, framboise: "3240 g", eau: "1440 ml", sucre: "1080 g", citron: "180 ml" },
      { nb: 10, framboise: "3600 g", eau: "1600 ml", sucre: "1200 g", citron: "200 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre et le refroidir.", badge: "⏱ 5 min" },
      { icone: "🍓", titre: "Coulis", detail: "Mixer les framboises en purée.", badge: null },
      { icone: "🫗", titre: "Tamiser", detail: "Passer la purée au tamis pour retirer les pépins. ASTUCE CHEF : tamise le coulis pour un sorbet tout lisse : sans les pépins, la texture en bouche est bien plus agréable.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetmangue: {
    nom: "Sorbet Mangue",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:10:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🥭",
    description: "Le sorbet mangue exotique et velouté, ensoleillé à souhait.",
    tableauSorbetMangue: [
      { nb: 1, mangue: "400 g", eau: "120 ml", sucre: "100 g", citronvert: "20 ml" },
      { nb: 2, mangue: "800 g", eau: "240 ml", sucre: "200 g", citronvert: "40 ml" },
      { nb: 3, mangue: "1200 g", eau: "360 ml", sucre: "300 g", citronvert: "60 ml" },
      { nb: 4, mangue: "1600 g", eau: "480 ml", sucre: "400 g", citronvert: "80 ml" },
      { nb: 5, mangue: "2000 g", eau: "600 ml", sucre: "500 g", citronvert: "100 ml" },
      { nb: 6, mangue: "2400 g", eau: "720 ml", sucre: "600 g", citronvert: "120 ml" },
      { nb: 7, mangue: "2800 g", eau: "840 ml", sucre: "700 g", citronvert: "140 ml" },
      { nb: 8, mangue: "3200 g", eau: "960 ml", sucre: "800 g", citronvert: "160 ml" },
      { nb: 9, mangue: "3600 g", eau: "1080 ml", sucre: "900 g", citronvert: "180 ml" },
      { nb: 10, mangue: "4000 g", eau: "1200 ml", sucre: "1000 g", citronvert: "200 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥭", titre: "Purée", detail: "Mixer la chair de mangue bien mûre. ASTUCE CHEF : choisis des mangues très mûres et parfumées : plus le fruit est sucré, moins tu ajoutes de sucre.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger et le refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron vert.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à prise.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser à la spatule.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpassion: {
    nom: "Sorbet Fruit de la Passion",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:11:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet fruit de la passion, acidulé et parfumé, d'une fraîcheur tropicale.",
    tableauSorbetPassion: [
      { nb: 1, fruitpassion: "280 g", eau: "200 ml", sucre: "140 g", citron: "12 ml" },
      { nb: 2, fruitpassion: "560 g", eau: "400 ml", sucre: "280 g", citron: "24 ml" },
      { nb: 3, fruitpassion: "840 g", eau: "600 ml", sucre: "420 g", citron: "36 ml" },
      { nb: 4, fruitpassion: "1120 g", eau: "800 ml", sucre: "560 g", citron: "48 ml" },
      { nb: 5, fruitpassion: "1400 g", eau: "1000 ml", sucre: "700 g", citron: "60 ml" },
      { nb: 6, fruitpassion: "1680 g", eau: "1200 ml", sucre: "840 g", citron: "72 ml" },
      { nb: 7, fruitpassion: "1960 g", eau: "1400 ml", sucre: "980 g", citron: "84 ml" },
      { nb: 8, fruitpassion: "2240 g", eau: "1600 ml", sucre: "1120 g", citron: "96 ml" },
      { nb: 9, fruitpassion: "2520 g", eau: "1800 ml", sucre: "1260 g", citron: "108 ml" },
      { nb: 10, fruitpassion: "2800 g", eau: "2000 ml", sucre: "1400 g", citron: "120 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre, refroidir.", badge: "⏱ 5 min" },
      { icone: "💛", titre: "Pulpe", detail: "Récupérer la pulpe des fruits de la passion.", badge: null },
      { icone: "🫗", titre: "Filtrer", detail: "Filtrer une partie de la pulpe pour retirer des graines. ASTUCE CHEF : garde quelques graines pour le croquant et la couleur, mais filtre le reste pour ne pas avoir un sorbet trop granuleux.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger pulpe, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpoire: {
    nom: "Sorbet Poire",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:12:00",
    base: 1,
    temps: "20 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍐",
    description: "Le sorbet poire tout en douceur, délicat et fondant.",
    tableauSorbetPoire: [
      { nb: 1, poire: "400 g", eau: "120 ml", sucre: "100 g", citron: "20 ml" },
      { nb: 2, poire: "800 g", eau: "240 ml", sucre: "200 g", citron: "40 ml" },
      { nb: 3, poire: "1200 g", eau: "360 ml", sucre: "300 g", citron: "60 ml" },
      { nb: 4, poire: "1600 g", eau: "480 ml", sucre: "400 g", citron: "80 ml" },
      { nb: 5, poire: "2000 g", eau: "600 ml", sucre: "500 g", citron: "100 ml" },
      { nb: 6, poire: "2400 g", eau: "720 ml", sucre: "600 g", citron: "120 ml" },
      { nb: 7, poire: "2800 g", eau: "840 ml", sucre: "700 g", citron: "140 ml" },
      { nb: 8, poire: "3200 g", eau: "960 ml", sucre: "800 g", citron: "160 ml" },
      { nb: 9, poire: "3600 g", eau: "1080 ml", sucre: "900 g", citron: "180 ml" },
      { nb: 10, poire: "4000 g", eau: "1200 ml", sucre: "1000 g", citron: "200 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍐", titre: "Pocher", detail: "Pocher les poires épluchées dans l'eau sucrée.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer les poires avec un peu de sirop.", badge: null },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le citron pour éviter le brunissement. ASTUCE CHEF : le jus de citron empêche la purée de poire de brunir et relève sa douceur un peu fade.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir complètement.", badge: "⏱ 1 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetfraise: {
    nom: "Sorbet Fraise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:13:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍓",
    description: "Le sorbet fraise gourmand, intense en fruit, idéal en été.",
    tableauSorbetFraise: [
      { nb: 1, fraise: "400 g", eau: "120 ml", sucre: "112 g", citron: "20 ml" },
      { nb: 2, fraise: "800 g", eau: "240 ml", sucre: "224 g", citron: "40 ml" },
      { nb: 3, fraise: "1200 g", eau: "360 ml", sucre: "336 g", citron: "60 ml" },
      { nb: 4, fraise: "1600 g", eau: "480 ml", sucre: "448 g", citron: "80 ml" },
      { nb: 5, fraise: "2000 g", eau: "600 ml", sucre: "560 g", citron: "100 ml" },
      { nb: 6, fraise: "2400 g", eau: "720 ml", sucre: "672 g", citron: "120 ml" },
      { nb: 7, fraise: "2800 g", eau: "840 ml", sucre: "784 g", citron: "140 ml" },
      { nb: 8, fraise: "3200 g", eau: "960 ml", sucre: "896 g", citron: "160 ml" },
      { nb: 9, fraise: "3600 g", eau: "1080 ml", sucre: "1008 g", citron: "180 ml" },
      { nb: 10, fraise: "4000 g", eau: "1200 ml", sucre: "1120 g", citron: "200 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍓", titre: "Purée", detail: "Mixer les fraises en purée. ASTUCE CHEF : équeute et mixe les fraises crues (sans les cuire) pour garder le goût vif et la couleur éclatante du fruit frais.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger, refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser et goûter.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  vacheringlace: {
    nom: "Vacherin Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:14:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍰",
    description: "Le vacherin glacé festif : meringue, crème glacée et coulis de fruits rouges.",
    tableauVacheringGlace: [
      { nb: 1, meringue: "30 g", creme: "60 ml", sucre: "18 g", framboise: "40 g", vanille: "1 g" },
      { nb: 2, meringue: "60 g", creme: "120 ml", sucre: "36 g", framboise: "80 g", vanille: "2 g" },
      { nb: 3, meringue: "90 g", creme: "180 ml", sucre: "54 g", framboise: "120 g", vanille: "3 g" },
      { nb: 4, meringue: "120 g", creme: "240 ml", sucre: "72 g", framboise: "160 g", vanille: "4 g" },
      { nb: 5, meringue: "150 g", creme: "300 ml", sucre: "90 g", framboise: "200 g", vanille: "5 g" },
      { nb: 6, meringue: "180 g", creme: "360 ml", sucre: "108 g", framboise: "240 g", vanille: "6 g" },
      { nb: 7, meringue: "210 g", creme: "420 ml", sucre: "126 g", framboise: "280 g", vanille: "7 g" },
      { nb: 8, meringue: "240 g", creme: "480 ml", sucre: "144 g", framboise: "320 g", vanille: "8 g" },
      { nb: 9, meringue: "270 g", creme: "540 ml", sucre: "162 g", framboise: "360 g", vanille: "9 g" },
      { nb: 10, meringue: "300 g", creme: "600 ml", sucre: "180 g", framboise: "400 g", vanille: "10 g" },
      { nb: 11, meringue: "330 g", creme: "660 ml", sucre: "198 g", framboise: "440 g", vanille: "11 g" },
      { nb: 12, meringue: "360 g", creme: "720 ml", sucre: "216 g", framboise: "480 g", vanille: "12 g" },
      { nb: 13, meringue: "390 g", creme: "780 ml", sucre: "234 g", framboise: "520 g", vanille: "13 g" },
      { nb: 14, meringue: "420 g", creme: "840 ml", sucre: "252 g", framboise: "560 g", vanille: "14 g" },
      { nb: 15, meringue: "450 g", creme: "900 ml", sucre: "270 g", framboise: "600 g", vanille: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly avec un peu de sucre.", badge: null },
      { icone: "🍦", titre: "Glace", detail: "Préparer (ou utiliser) une glace vanille.", badge: null },
      { icone: "🟤", titre: "Meringue", detail: "Émietter ou disposer des meringues. ASTUCE CHEF : monte le vacherin et remets-le au congélateur entre chaque couche pour qu'il garde une forme nette.", badge: null },
      { icone: "🥣", titre: "Monter", detail: "Alterner glace, meringue et chantilly dans un moule.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler le vacherin plusieurs heures.", badge: "⏱ 4 h" },
      { icone: "🍓", titre: "Servir", detail: "Démouler et napper de coulis de framboise.", badge: null }
    ]
  },
  nougatglace: {
    nom: "Nougat Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:15:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍯",
    description: "Le nougat glacé provençal au miel, fruits confits et amandes caramélisées.",
    tableauNougatGlace: [
      { nb: 1, creme: "60 ml", miel: "20 g", oeuf: "1", amandes: "15 g", fruitsconfits: "15 g", sucre: "10 g" },
      { nb: 2, creme: "120 ml", miel: "40 g", oeuf: "2", amandes: "30 g", fruitsconfits: "30 g", sucre: "20 g" },
      { nb: 3, creme: "180 ml", miel: "60 g", oeuf: "3", amandes: "45 g", fruitsconfits: "45 g", sucre: "30 g" },
      { nb: 4, creme: "240 ml", miel: "80 g", oeuf: "4", amandes: "60 g", fruitsconfits: "60 g", sucre: "40 g" },
      { nb: 5, creme: "300 ml", miel: "100 g", oeuf: "5", amandes: "75 g", fruitsconfits: "75 g", sucre: "50 g" },
      { nb: 6, creme: "360 ml", miel: "120 g", oeuf: "6", amandes: "90 g", fruitsconfits: "90 g", sucre: "60 g" },
      { nb: 7, creme: "420 ml", miel: "140 g", oeuf: "7", amandes: "105 g", fruitsconfits: "105 g", sucre: "70 g" },
      { nb: 8, creme: "480 ml", miel: "160 g", oeuf: "8", amandes: "120 g", fruitsconfits: "120 g", sucre: "80 g" },
      { nb: 9, creme: "540 ml", miel: "180 g", oeuf: "9", amandes: "135 g", fruitsconfits: "135 g", sucre: "90 g" },
      { nb: 10, creme: "600 ml", miel: "200 g", oeuf: "10", amandes: "150 g", fruitsconfits: "150 g", sucre: "100 g" },
      { nb: 11, creme: "660 ml", miel: "220 g", oeuf: "11", amandes: "165 g", fruitsconfits: "165 g", sucre: "110 g" },
      { nb: 12, creme: "720 ml", miel: "240 g", oeuf: "12", amandes: "180 g", fruitsconfits: "180 g", sucre: "120 g" },
      { nb: 13, creme: "780 ml", miel: "260 g", oeuf: "13", amandes: "195 g", fruitsconfits: "195 g", sucre: "130 g" },
      { nb: 14, creme: "840 ml", miel: "280 g", oeuf: "14", amandes: "210 g", fruitsconfits: "210 g", sucre: "140 g" },
      { nb: 15, creme: "900 ml", miel: "300 g", oeuf: "15", amandes: "225 g", fruitsconfits: "225 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Nougatine", detail: "Caraméliser les amandes au sucre puis concasser.", badge: "⏱ 6 min" },
      { icone: "🍯", titre: "Meringue", detail: "Monter les blancs et serrer au miel chaud. ASTUCE CHEF : verse le miel bien chaud en filet sur les blancs en neige : ça les cuit légèrement et donne un nougat glacé stable et aérien.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Incorporer délicatement chantilly, fruits confits et amandes.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans un moule à cake.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise complète.", badge: "⏱ 5 h" }
    ]
  },
  bananasplit: {
    nom: "Banana Split",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:16:00",
    base: 2,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍌",
    description: "Le dessert glacé américain : banane, boules de glace, chantilly, sauce chocolat et amandes.",
    tableauBananaSplit: [
      { nb: 1, banane: "1", creme: "40 ml", chocolatnoir: "20 g", amandes: "10 g", sucre: "10 g" },
      { nb: 2, banane: "2", creme: "80 ml", chocolatnoir: "40 g", amandes: "20 g", sucre: "20 g" },
      { nb: 3, banane: "3", creme: "120 ml", chocolatnoir: "60 g", amandes: "30 g", sucre: "30 g" },
      { nb: 4, banane: "4", creme: "160 ml", chocolatnoir: "80 g", amandes: "40 g", sucre: "40 g" },
      { nb: 5, banane: "5", creme: "200 ml", chocolatnoir: "100 g", amandes: "50 g", sucre: "50 g" },
      { nb: 6, banane: "6", creme: "240 ml", chocolatnoir: "120 g", amandes: "60 g", sucre: "60 g" },
      { nb: 7, banane: "7", creme: "280 ml", chocolatnoir: "140 g", amandes: "70 g", sucre: "70 g" },
      { nb: 8, banane: "8", creme: "320 ml", chocolatnoir: "160 g", amandes: "80 g", sucre: "80 g" },
      { nb: 9, banane: "9", creme: "360 ml", chocolatnoir: "180 g", amandes: "90 g", sucre: "90 g" },
      { nb: 10, banane: "10", creme: "400 ml", chocolatnoir: "200 g", amandes: "100 g", sucre: "100 g" },
      { nb: 11, banane: "11", creme: "440 ml", chocolatnoir: "220 g", amandes: "110 g", sucre: "110 g" },
      { nb: 12, banane: "12", creme: "480 ml", chocolatnoir: "240 g", amandes: "120 g", sucre: "120 g" },
      { nb: 13, banane: "13", creme: "520 ml", chocolatnoir: "260 g", amandes: "130 g", sucre: "130 g" },
      { nb: 14, banane: "14", creme: "560 ml", chocolatnoir: "280 g", amandes: "140 g", sucre: "140 g" },
      { nb: 15, banane: "15", creme: "600 ml", chocolatnoir: "300 g", amandes: "150 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍌", titre: "Banane", detail: "Couper la banane en deux dans la longueur.", badge: null },
      { icone: "🍦", titre: "Boules", detail: "Disposer trois boules de glace entre les demi-bananes. ASTUCE CHEF : trempe la cuillère à glace dans l'eau chaude entre chaque boule pour des quenelles nettes et régulières.", badge: null },
      { icone: "🍫", titre: "Sauce", detail: "Faire fondre le chocolat en sauce.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🌰", titre: "Garnir", detail: "Napper de sauce chocolat et chantilly.", badge: null },
      { icone: "🍒", titre: "Servir", detail: "Parsemer d'amandes et servir aussitôt.", badge: null }
    ]
  },
  gelato: {
    nom: "Gelato Fior di Latte",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:17:00",
    base: 1,
    temps: "25 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "Le gelato fior di latte à l'italienne : dense et soyeux, sans œuf, tout en lait.",
    tableauGelato: [
      { nb: 1, lait: "320 ml", creme: "120 ml", sucre: "88 g", fecule: "12 g" },
      { nb: 2, lait: "640 ml", creme: "240 ml", sucre: "176 g", fecule: "24 g" },
      { nb: 3, lait: "960 ml", creme: "360 ml", sucre: "264 g", fecule: "36 g" },
      { nb: 4, lait: "1280 ml", creme: "480 ml", sucre: "352 g", fecule: "48 g" },
      { nb: 5, lait: "1600 ml", creme: "600 ml", sucre: "440 g", fecule: "60 g" },
      { nb: 6, lait: "1920 ml", creme: "720 ml", sucre: "528 g", fecule: "72 g" },
      { nb: 7, lait: "2240 ml", creme: "840 ml", sucre: "616 g", fecule: "84 g" },
      { nb: 8, lait: "2560 ml", creme: "960 ml", sucre: "704 g", fecule: "96 g" },
      { nb: 9, lait: "2880 ml", creme: "1080 ml", sucre: "792 g", fecule: "108 g" },
      { nb: 10, lait: "3200 ml", creme: "1200 ml", sucre: "880 g", fecule: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer le lait, la crème et le sucre.", badge: "⏱ 4 min" },
      { icone: "🥄", titre: "Lier", detail: "Délayer la fécule à froid et l'incorporer pour épaissir légèrement. ASTUCE CHEF : le gelato contient moins de crème et d'air qu'une glace : c'est ce qui lui donne sa densité soyeuse caractéristique.", badge: "⏱ 3 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer bien la base.", badge: "⏱ 3 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner lentement.", badge: "⏱ 25 min" },
      { icone: "🍨", titre: "Texture", detail: "Servir plus tempéré qu'une glace classique.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Déguster en boules généreuses.", badge: null }
    ]
  },
  kulfi: {
    nom: "Kulfi",
    cat: "glaces",
    pays: "inde",
    dateAjout: "2026-06-08T21:18:00",
    base: 4,
    temps: "40 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace indienne au lait réduit, parfumée à la cardamome et aux pistaches.",
    tableauKulfi: [
      { nb: 1, lait: "100 ml", laitconcentre: "15 g", sucre: "15 g", cardamome: "1 g", pistache: "8 g" },
      { nb: 2, lait: "200 ml", laitconcentre: "30 g", sucre: "30 g", cardamome: "2 g", pistache: "16 g" },
      { nb: 3, lait: "300 ml", laitconcentre: "45 g", sucre: "45 g", cardamome: "3 g", pistache: "24 g" },
      { nb: 4, lait: "400 ml", laitconcentre: "60 g", sucre: "60 g", cardamome: "4 g", pistache: "32 g" },
      { nb: 5, lait: "500 ml", laitconcentre: "75 g", sucre: "75 g", cardamome: "5 g", pistache: "40 g" },
      { nb: 6, lait: "600 ml", laitconcentre: "90 g", sucre: "90 g", cardamome: "6 g", pistache: "48 g" },
      { nb: 7, lait: "700 ml", laitconcentre: "105 g", sucre: "105 g", cardamome: "7 g", pistache: "56 g" },
      { nb: 8, lait: "800 ml", laitconcentre: "120 g", sucre: "120 g", cardamome: "8 g", pistache: "64 g" },
      { nb: 9, lait: "900 ml", laitconcentre: "135 g", sucre: "135 g", cardamome: "9 g", pistache: "72 g" },
      { nb: 10, lait: "1000 ml", laitconcentre: "150 g", sucre: "150 g", cardamome: "10 g", pistache: "80 g" },
      { nb: 11, lait: "1100 ml", laitconcentre: "165 g", sucre: "165 g", cardamome: "11 g", pistache: "88 g" },
      { nb: 12, lait: "1200 ml", laitconcentre: "180 g", sucre: "180 g", cardamome: "12 g", pistache: "96 g" },
      { nb: 13, lait: "1300 ml", laitconcentre: "195 g", sucre: "195 g", cardamome: "13 g", pistache: "104 g" },
      { nb: 14, lait: "1400 ml", laitconcentre: "210 g", sucre: "210 g", cardamome: "14 g", pistache: "112 g" },
      { nb: 15, lait: "1500 ml", laitconcentre: "225 g", sucre: "225 g", cardamome: "15 g", pistache: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Réduire", detail: "Faire réduire longuement le lait à feu doux. ASTUCE CHEF : réduis le lait de moitié en remuant : cette concentration donne au kulfi son goût lacté intense et sa texture dense.", badge: "⏱ 30 min" },
      { icone: "🍬", titre: "Sucrer", detail: "Ajouter le lait concentré et le sucre.", badge: null },
      { icone: "🌿", titre: "Parfumer", detail: "Parfumer à la cardamome et aux pistaches.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans des moules (sans turbiner).", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise.", badge: "⏱ 5 h" },
      { icone: "🌰", titre: "Servir", detail: "Démouler et parsemer de pistaches.", badge: null }
    ]
  },
  granite: {
    nom: "Granité Citron",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:19:00",
    base: 1,
    temps: "10 min + congélation",
    niveau: "⭐ Facile",
    emoji: "🧊",
    description: "Le granité sicilien au citron, cristaux glacés à gratter à la fourchette, sans sorbetière.",
    tableauGranite: [
      { nb: 1, citron: "160 ml", eau: "360 ml", sucre: "120 g" },
      { nb: 2, citron: "320 ml", eau: "720 ml", sucre: "240 g" },
      { nb: 3, citron: "480 ml", eau: "1080 ml", sucre: "360 g" },
      { nb: 4, citron: "640 ml", eau: "1440 ml", sucre: "480 g" },
      { nb: 5, citron: "800 ml", eau: "1800 ml", sucre: "600 g" },
      { nb: 6, citron: "960 ml", eau: "2160 ml", sucre: "720 g" },
      { nb: 7, citron: "1120 ml", eau: "2520 ml", sucre: "840 g" },
      { nb: 8, citron: "1280 ml", eau: "2880 ml", sucre: "960 g" },
      { nb: 9, citron: "1440 ml", eau: "3240 ml", sucre: "1080 g" },
      { nb: 10, citron: "1600 ml", eau: "3600 ml", sucre: "1200 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Dissoudre le sucre dans l'eau tiède, refroidir.", badge: "⏱ 4 min" },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le jus de citron filtré.", badge: null },
      { icone: "🧊", titre: "Congeler", detail: "Verser dans un bac peu profond et placer au congélateur.", badge: null },
      { icone: "🍴", titre: "Gratter", detail: "Gratter à la fourchette toutes les 30 min. ASTUCE CHEF : c'est le grattage régulier qui crée les cristaux du granité : ne le laisse jamais prendre en bloc, racle-le 4-5 fois.", badge: "⏱ 2 h" },
      { icone: "❄️", titre: "Texture", detail: "Obtenir une neige de cristaux légers.", badge: null },
      { icone: "🥄", titre: "Servir", detail: "Servir aussitôt en verrines givrées.", badge: null }
    ]
  },
  frozenyogurt: {
    nom: "Frozen yogurt", cat: "glaces", pays: "usa", dateAjout: "2026-06-17T10:00:00",
    base: 1, temps: "10 min + congélation", niveau: "⭐ Facile", emoji: "🍦",
    description: "L'alternative légère et acidulée à la glace : un yaourt grec onctueux glacé aux fruits rouges. Plus frais et moins sucré qu'une crème glacée.",
    saisons: ["ete"],
    ingredients: {},
    tableauFrozenYogurt: [
      { nb: 1, yaourtgrec: "500 g", sucreglace: "80 g", miel: "40 g", citron: "20 ml", fraise: "150 g" },
      { nb: 2, yaourtgrec: "1000 g", sucreglace: "160 g", miel: "80 g", citron: "40 ml", fraise: "300 g" },
      { nb: 3, yaourtgrec: "1500 g", sucreglace: "240 g", miel: "120 g", citron: "60 ml", fraise: "450 g" },
      { nb: 4, yaourtgrec: "2000 g", sucreglace: "320 g", miel: "160 g", citron: "80 ml", fraise: "600 g" },
      { nb: 5, yaourtgrec: "2500 g", sucreglace: "400 g", miel: "200 g", citron: "100 ml", fraise: "750 g" },
      { nb: 6, yaourtgrec: "3000 g", sucreglace: "480 g", miel: "240 g", citron: "120 ml", fraise: "900 g" },
      { nb: 7, yaourtgrec: "3500 g", sucreglace: "560 g", miel: "280 g", citron: "140 ml", fraise: "1050 g" },
      { nb: 8, yaourtgrec: "4000 g", sucreglace: "640 g", miel: "320 g", citron: "160 ml", fraise: "1200 g" },
      { nb: 9, yaourtgrec: "4500 g", sucreglace: "720 g", miel: "360 g", citron: "180 ml", fraise: "1350 g" },
      { nb: 10, yaourtgrec: "5000 g", sucreglace: "800 g", miel: "400 g", citron: "200 ml", fraise: "1500 g" }
    ],
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Fouetter le yaourt grec avec le sucre glace, le miel et le jus de citron.", badge: null },
      { icone: "🍓", titre: "Fruits", detail: "Incorporer les fruits rouges, écrasés ou entiers selon l'envie.", badge: null },
      { icone: "🧊", titre: "Turbiner", detail: "Verser en sorbetière jusqu'à une texture crémeuse, ou placer au congélateur.", badge: "⏱ 30 min" },
      { icone: "🥄", titre: "Lisser", detail: "Sans sorbetière, mélanger toutes les 30 min pour éviter les cristaux.", badge: null },
      { icone: "🍨", titre: "Servir", detail: "Servir en boules, légèrement souple, avec quelques fruits frais.", badge: null }
    ]
  },
});
