// ============================================================
// recettes_sauces.js — Recettes de catégorie "sauces" (Sauces) — 24 recettes
// 👉 Pour AJOUTER une recette Sauces : place-la juste avant le  });  final.
//    (le plus simple : copie une recette existante et change les valeurs)
// ============================================================
Object.assign(recettes, {
mayonnaise: {
    cat: "sauces", pays: "france",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🥚",
    description: "Mayonnaise maison — l'émulsion de base : jaune d'œuf, moutarde et huile montés au fouet. Sans additifs, mille fois meilleure que l'industrielle.",
    tableauMayonnaise: [
      { nb: 1, oeufs: "¼", huile: "25 ml", moutarde: "½ c.à.c", vinaigre: "¼ c.à.c", sel: "1 pincée" },
      { nb: 2, oeufs: "½", huile: "50 ml", moutarde: "1 c.à.c", vinaigre: "½ c.à.c", sel: "1 pincée" },
      { nb: 3, oeufs: "1", huile: "75 ml", moutarde: "1½ c.à.c", vinaigre: "1 c.à.c", sel: "1 pincée" },
      { nb: 4, oeufs: "1¼", huile: "100 ml", moutarde: "2 c.à.c", vinaigre: "1¼ c.à.c", sel: "1 pincée" },
      { nb: 5, oeufs: "1½", huile: "125 ml", moutarde: "2½ c.à.c", vinaigre: "1½ c.à.c", sel: "1 pincée" },
      { nb: 6, oeufs: "1¾", huile: "150 ml", moutarde: "3 c.à.c", vinaigre: "1¾ c.à.c", sel: "1 pincée" },
      { nb: 7, oeufs: "2", huile: "175 ml", moutarde: "3½ c.à.c", vinaigre: "2 c.à.c", sel: "2 pincées" },
      { nb: 8, oeufs: "2½", huile: "200 ml", moutarde: "4 c.à.c", vinaigre: "2½ c.à.c", sel: "2 pincées" },
      { nb: 9, oeufs: "2¾", huile: "225 ml", moutarde: "4½ c.à.c", vinaigre: "2¾ c.à.c", sel: "2 pincées" },
      { nb: 10, oeufs: "3", huile: "250 ml", moutarde: "5 c.à.c", vinaigre: "3 c.à.c", sel: "2 pincées" },
      { nb: 11, oeufs: "3¼", huile: "275 ml", moutarde: "5½ c.à.c", vinaigre: "3¼ c.à.c", sel: "2 pincées" },
      { nb: 12, oeufs: "3½", huile: "300 ml", moutarde: "6 c.à.c", vinaigre: "3½ c.à.c", sel: "2 pincées" },
      { nb: 13, oeufs: "4", huile: "325 ml", moutarde: "6½ c.à.c", vinaigre: "4 c.à.c", sel: "3 pincées" },
      { nb: 14, oeufs: "4¼", huile: "350 ml", moutarde: "7 c.à.c", vinaigre: "4¼ c.à.c", sel: "3 pincées" },
      { nb: 15, oeufs: "4½", huile: "375 ml", moutarde: "7½ c.à.c", vinaigre: "4½ c.à.c", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Base", detail: "Jaune d'œuf + moutarde + sel dans un bol. CLÉ : tous les ingrédients à TEMPÉRATURE AMBIANTE, sinon l'émulsion ne prend pas.", badge: "⏱ 2 min" },
      { icone: "🌀", titre: "Monter", detail: "Verser l'huile EN FILET très fin en fouettant sans arrêt. SECRET : commencer goutte à goutte, accélérer une fois l'émulsion prise.", badge: "⏱ 5 min" },
      { icone: "🍋", titre: "Assaisonner", detail: "Détendre avec un trait de vinaigre ou de citron, rectifier sel/poivre.", badge: "⏱ 1 min" },
      { icone: "🧊", titre: "Conserver", detail: "ASTUCE CHEF : si elle tranche, repartir d'un jaune neuf et y verser la mayo ratée en filet. Se garde 48h au frais.", badge: null }
    ]
  },
  ketchup: {
    cat: "sauces", pays: "usa",
    base: 8,
    temps: "35 min",
    niveau: "⭐ Facile",
    emoji: "🍅",
    description: "Ketchup maison — sauce tomate sucrée-acidulée mijotée et mixée. Moins sucré et plus parfumé que celui du commerce.",
    tableauKetchup: [
      { nb: 1, tomates: "60 g", sucre: "1 c.à.c", vinaigre: "1 c.à.c", oignon: "6 g", sel: "1 pincée" },
      { nb: 2, tomates: "120 g", sucre: "2 c.à.c", vinaigre: "2 c.à.c", oignon: "12 g", sel: "1 pincée" },
      { nb: 3, tomates: "180 g", sucre: "3 c.à.c", vinaigre: "3 c.à.c", oignon: "18 g", sel: "1 pincée" },
      { nb: 4, tomates: "240 g", sucre: "4 c.à.c", vinaigre: "4 c.à.c", oignon: "24 g", sel: "1 pincée" },
      { nb: 5, tomates: "300 g", sucre: "5 c.à.c", vinaigre: "5 c.à.c", oignon: "30 g", sel: "1 pincée" },
      { nb: 6, tomates: "360 g", sucre: "6 c.à.c", vinaigre: "6 c.à.c", oignon: "36 g", sel: "1 pincée" },
      { nb: 7, tomates: "420 g", sucre: "7 c.à.c", vinaigre: "7 c.à.c", oignon: "42 g", sel: "2 pincées" },
      { nb: 8, tomates: "480 g", sucre: "8 c.à.c", vinaigre: "8 c.à.c", oignon: "48 g", sel: "2 pincées" },
      { nb: 9, tomates: "540 g", sucre: "9 c.à.c", vinaigre: "9 c.à.c", oignon: "54 g", sel: "2 pincées" },
      { nb: 10, tomates: "600 g", sucre: "10 c.à.c", vinaigre: "10 c.à.c", oignon: "60 g", sel: "2 pincées" },
      { nb: 11, tomates: "660 g", sucre: "11 c.à.c", vinaigre: "11 c.à.c", oignon: "66 g", sel: "2 pincées" },
      { nb: 12, tomates: "720 g", sucre: "12 c.à.c", vinaigre: "12 c.à.c", oignon: "72 g", sel: "2 pincées" },
      { nb: 13, tomates: "780 g", sucre: "13 c.à.c", vinaigre: "13 c.à.c", oignon: "78 g", sel: "3 pincées" },
      { nb: 14, tomates: "840 g", sucre: "14 c.à.c", vinaigre: "14 c.à.c", oignon: "84 g", sel: "3 pincées" },
      { nb: 15, tomates: "900 g", sucre: "15 c.à.c", vinaigre: "15 c.à.c", oignon: "90 g", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧅", titre: "Revenir", detail: "Faire suer l'oignon émincé. Ajouter les tomates (ou concentré + eau), sucre, vinaigre, sel, épices.", badge: "⏱ 5 min" },
      { icone: "🔥", titre: "Mijoter", detail: "CLÉ : laisser réduire à feu doux 20-25 min jusqu'à une texture épaisse et nappante.", badge: "⏱ 25 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer finement et passer au tamis pour une texture lisse. SECRET : une pointe de clou de girofle ou de cannelle fait le 'goût ketchup'.", badge: "⏱ 3 min" },
      { icone: "🧊", titre: "Conserver", detail: "ASTUCE CHEF : mettre en pot chaud, se garde 2-3 semaines au frais. Laisser refroidir avant de fermer.", badge: null }
    ]
  },
  saucebarbecue: {
    cat: "sauces", pays: "usa",
    base: 8,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🍖",
    description: "Sauce barbecue maison — fumée, sucrée et corsée. Parfaite pour les grillades, ribs, burgers et marinades.",
    tableauSauceBarbecue: [
      { nb: 1, ketchup: "20 g", sucre: "1 c.à.c", vinaigre: "1 c.à.c", moutarde: "¼ c.à.c", paprika: "¼ c.à.c", saucesoja: "½ c.à.c" },
      { nb: 2, ketchup: "40 g", sucre: "2 c.à.c", vinaigre: "2 c.à.c", moutarde: "½ c.à.c", paprika: "½ c.à.c", saucesoja: "1 c.à.c" },
      { nb: 3, ketchup: "60 g", sucre: "3 c.à.c", vinaigre: "3 c.à.c", moutarde: "1 c.à.c", paprika: "1 c.à.c", saucesoja: "1½ c.à.c" },
      { nb: 4, ketchup: "80 g", sucre: "4 c.à.c", vinaigre: "4 c.à.c", moutarde: "1¼ c.à.c", paprika: "1¼ c.à.c", saucesoja: "2 c.à.c" },
      { nb: 5, ketchup: "100 g", sucre: "5 c.à.c", vinaigre: "5 c.à.c", moutarde: "1½ c.à.c", paprika: "1½ c.à.c", saucesoja: "2½ c.à.c" },
      { nb: 6, ketchup: "120 g", sucre: "6 c.à.c", vinaigre: "6 c.à.c", moutarde: "1¾ c.à.c", paprika: "1¾ c.à.c", saucesoja: "3 c.à.c" },
      { nb: 7, ketchup: "140 g", sucre: "7 c.à.c", vinaigre: "7 c.à.c", moutarde: "2 c.à.c", paprika: "2 c.à.c", saucesoja: "3½ c.à.c" },
      { nb: 8, ketchup: "160 g", sucre: "8 c.à.c", vinaigre: "8 c.à.c", moutarde: "2½ c.à.c", paprika: "2½ c.à.c", saucesoja: "4 c.à.c" },
      { nb: 9, ketchup: "180 g", sucre: "9 c.à.c", vinaigre: "9 c.à.c", moutarde: "2¾ c.à.c", paprika: "2¾ c.à.c", saucesoja: "4½ c.à.c" },
      { nb: 10, ketchup: "200 g", sucre: "10 c.à.c", vinaigre: "10 c.à.c", moutarde: "3 c.à.c", paprika: "3 c.à.c", saucesoja: "5 c.à.c" },
      { nb: 11, ketchup: "220 g", sucre: "11 c.à.c", vinaigre: "11 c.à.c", moutarde: "3¼ c.à.c", paprika: "3¼ c.à.c", saucesoja: "5½ c.à.c" },
      { nb: 12, ketchup: "240 g", sucre: "12 c.à.c", vinaigre: "12 c.à.c", moutarde: "3½ c.à.c", paprika: "3½ c.à.c", saucesoja: "6 c.à.c" },
      { nb: 13, ketchup: "260 g", sucre: "13 c.à.c", vinaigre: "13 c.à.c", moutarde: "4 c.à.c", paprika: "4 c.à.c", saucesoja: "6½ c.à.c" },
      { nb: 14, ketchup: "280 g", sucre: "14 c.à.c", vinaigre: "14 c.à.c", moutarde: "4¼ c.à.c", paprika: "4¼ c.à.c", saucesoja: "7 c.à.c" },
      { nb: 15, ketchup: "300 g", sucre: "15 c.à.c", vinaigre: "15 c.à.c", moutarde: "4½ c.à.c", paprika: "4½ c.à.c", saucesoja: "7½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Réunir ketchup, cassonade, vinaigre, moutarde, paprika (fumé !), sauce soja.", badge: "⏱ 3 min" },
      { icone: "🔥", titre: "Mijoter", detail: "CLÉ : faire réduire 12-15 min à feu doux pour que les saveurs se concentrent et que la sauce nappe.", badge: "⏱ 15 min" },
      { icone: "🌶️", titre: "Ajuster", detail: "SECRET : équilibrer sucré/acide/fumé à ton goût. Un trait de Worcestershire ou de fumée liquide pour le vrai goût BBQ.", badge: "⏱ 2 min" },
      { icone: "🧊", titre: "Conserver", detail: "ASTUCE CHEF : meilleure le lendemain. Se garde 2 semaines au frais.", badge: null }
    ]
  },
  harissa: {
    cat: "sauces", pays: "maroc",
    base: 10,
    temps: "20 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🌶️",
    description: "Harissa maison — la pâte de piment maghrébine, parfumée au cumin, à la coriandre et à l'ail. Relève couscous, tajines, sandwichs et soupes.",
    tableauHarissa: [
      { nb: 1, piment: "15 g", ail: "½ gousse", huiledolive: "1 c.à.c", coriandre: "¼ c.à.c", cumin: "¼ c.à.c", sel: "1 pincée" },
      { nb: 2, piment: "30 g", ail: "1 gousse", huiledolive: "2 c.à.c", coriandre: "½ c.à.c", cumin: "½ c.à.c", sel: "1 pincée" },
      { nb: 3, piment: "45 g", ail: "1½ gousse", huiledolive: "3 c.à.c", coriandre: "1 c.à.c", cumin: "1 c.à.c", sel: "1 pincée" },
      { nb: 4, piment: "60 g", ail: "2 gousses", huiledolive: "4 c.à.c", coriandre: "1¼ c.à.c", cumin: "1¼ c.à.c", sel: "1 pincée" },
      { nb: 5, piment: "75 g", ail: "2½ gousses", huiledolive: "5 c.à.c", coriandre: "1½ c.à.c", cumin: "1½ c.à.c", sel: "1 pincée" },
      { nb: 6, piment: "90 g", ail: "3 gousses", huiledolive: "6 c.à.c", coriandre: "1¾ c.à.c", cumin: "1¾ c.à.c", sel: "1 pincée" },
      { nb: 7, piment: "105 g", ail: "3½ gousses", huiledolive: "7 c.à.c", coriandre: "2 c.à.c", cumin: "2 c.à.c", sel: "2 pincées" },
      { nb: 8, piment: "120 g", ail: "4 gousses", huiledolive: "8 c.à.c", coriandre: "2½ c.à.c", cumin: "2½ c.à.c", sel: "2 pincées" },
      { nb: 9, piment: "135 g", ail: "4½ gousses", huiledolive: "9 c.à.c", coriandre: "2¾ c.à.c", cumin: "2¾ c.à.c", sel: "2 pincées" },
      { nb: 10, piment: "150 g", ail: "5 gousses", huiledolive: "10 c.à.c", coriandre: "3 c.à.c", cumin: "3 c.à.c", sel: "2 pincées" },
      { nb: 11, piment: "165 g", ail: "5½ gousses", huiledolive: "11 c.à.c", coriandre: "3¼ c.à.c", cumin: "3¼ c.à.c", sel: "2 pincées" },
      { nb: 12, piment: "180 g", ail: "6 gousses", huiledolive: "12 c.à.c", coriandre: "3½ c.à.c", cumin: "3½ c.à.c", sel: "2 pincées" },
      { nb: 13, piment: "195 g", ail: "6½ gousses", huiledolive: "13 c.à.c", coriandre: "4 c.à.c", cumin: "4 c.à.c", sel: "3 pincées" },
      { nb: 14, piment: "210 g", ail: "7 gousses", huiledolive: "14 c.à.c", coriandre: "4¼ c.à.c", cumin: "4¼ c.à.c", sel: "3 pincées" },
      { nb: 15, piment: "225 g", ail: "7½ gousses", huiledolive: "15 c.à.c", coriandre: "4½ c.à.c", cumin: "4½ c.à.c", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌶️", titre: "Réhydrater", detail: "Faire tremper les piments séchés dans l'eau chaude 15 min, puis les épépiner. ASTUCE : garder quelques graines pour plus de feu.", badge: "⏱ 15 min" },
      { icone: "🧄", titre: "Mixer", detail: "Mixer piments, ail, cumin, coriandre, sel en pâte. SECRET : torréfier les épices à sec avant, ça décuple l'arôme.", badge: "⏱ 3 min" },
      { icone: "🫒", titre: "Monter à l'huile", detail: "Ajouter l'huile d'olive jusqu'à une pâte souple et brillante.", badge: "⏱ 2 min" },
      { icone: "🧊", titre: "Conserver", detail: "CLÉ : couvrir d'un film d'huile dans un pot — se garde plusieurs semaines au frais.", badge: null }
    ]
  },
  saucetomate: {
    cat: "sauces", pays: "italie",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🥫",
    description: "Sauce tomate maison — la base italienne : tomates mijotées avec ail, oignon et basilic. Pour pâtes, pizzas, gratins et bien plus.",
    tableauSauceTomate: [
      { nb: 1, tomates: "90 g", oignon: "10 g", ail: "½ gousse", huiledolive: "½ c.à.c", basilic: "2 feuilles", sucre: "¼ c.à.c" },
      { nb: 2, tomates: "180 g", oignon: "20 g", ail: "1 gousse", huiledolive: "1 c.à.c", basilic: "4 feuilles", sucre: "½ c.à.c" },
      { nb: 3, tomates: "270 g", oignon: "30 g", ail: "1½ gousse", huiledolive: "1½ c.à.c", basilic: "6 feuilles", sucre: "½ c.à.c" },
      { nb: 4, tomates: "360 g", oignon: "40 g", ail: "2 gousses", huiledolive: "2 c.à.c", basilic: "8 feuilles", sucre: "¾ c.à.c" },
      { nb: 5, tomates: "450 g", oignon: "50 g", ail: "2½ gousses", huiledolive: "2½ c.à.c", basilic: "10 feuilles", sucre: "1 c.à.c" },
      { nb: 6, tomates: "540 g", oignon: "60 g", ail: "3 gousses", huiledolive: "3 c.à.c", basilic: "12 feuilles", sucre: "1¼ c.à.c" },
      { nb: 7, tomates: "630 g", oignon: "70 g", ail: "3½ gousses", huiledolive: "3½ c.à.c", basilic: "14 feuilles", sucre: "1½ c.à.c" },
      { nb: 8, tomates: "720 g", oignon: "80 g", ail: "4 gousses", huiledolive: "4 c.à.c", basilic: "16 feuilles", sucre: "1½ c.à.c" },
      { nb: 9, tomates: "810 g", oignon: "90 g", ail: "4½ gousses", huiledolive: "4½ c.à.c", basilic: "18 feuilles", sucre: "1¾ c.à.c" },
      { nb: 10, tomates: "900 g", oignon: "100 g", ail: "5 gousses", huiledolive: "5 c.à.c", basilic: "20 feuilles", sucre: "2 c.à.c" },
      { nb: 11, tomates: "990 g", oignon: "110 g", ail: "5½ gousses", huiledolive: "5½ c.à.c", basilic: "22 feuilles", sucre: "2¼ c.à.c" },
      { nb: 12, tomates: "1080 g", oignon: "120 g", ail: "6 gousses", huiledolive: "6 c.à.c", basilic: "24 feuilles", sucre: "2½ c.à.c" },
      { nb: 13, tomates: "1170 g", oignon: "130 g", ail: "6½ gousses", huiledolive: "6½ c.à.c", basilic: "26 feuilles", sucre: "2½ c.à.c" },
      { nb: 14, tomates: "1260 g", oignon: "140 g", ail: "7 gousses", huiledolive: "7 c.à.c", basilic: "28 feuilles", sucre: "2¾ c.à.c" },
      { nb: 15, tomates: "1350 g", oignon: "150 g", ail: "7½ gousses", huiledolive: "7½ c.à.c", basilic: "30 feuilles", sucre: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧅", titre: "Suer", detail: "Faire revenir oignon et ail dans l'huile d'olive sans coloration.", badge: "⏱ 4 min" },
      { icone: "🍅", titre: "Mijoter", detail: "Ajouter les tomates concassées, sel. CLÉ : mijoter 20-25 min à feu doux pour réduire et concentrer.", badge: "⏱ 25 min" },
      { icone: "🌿", titre: "Équilibrer", detail: "SECRET ANTI-ACIDITÉ : une pincée de sucre coupe l'acidité des tomates. Basilic en fin de cuisson.", badge: "⏱ 2 min" },
      { icone: "🌀", titre: "Finir", detail: "ASTUCE CHEF : mixer pour une sauce lisse, ou laisser rustique. Un filet d'huile crue à la fin.", badge: null }
    ]
  },
  vinaigrette: {
    cat: "sauces", pays: "france",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "Vinaigrette classique — l'assaisonnement de base des salades : moutarde, vinaigre et huile émulsionnés. Le secret d'une bonne salade.",
    tableauVinaigrette: [
      { nb: 1, huile: "1 c.à.s", vinaigre: "½ c.à.s", moutarde: "¼ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 2, huile: "2 c.à.s", vinaigre: "1 c.à.s", moutarde: "½ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 3, huile: "3 c.à.s", vinaigre: "1½ c.à.s", moutarde: "1 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 4, huile: "4 c.à.s", vinaigre: "2 c.à.s", moutarde: "1¼ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 5, huile: "5 c.à.s", vinaigre: "2½ c.à.s", moutarde: "1½ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 6, huile: "6 c.à.s", vinaigre: "3 c.à.s", moutarde: "1¾ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 7, huile: "7 c.à.s", vinaigre: "3½ c.à.s", moutarde: "2 c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 8, huile: "8 c.à.s", vinaigre: "4 c.à.s", moutarde: "2½ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 9, huile: "9 c.à.s", vinaigre: "4½ c.à.s", moutarde: "2¾ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 10, huile: "10 c.à.s", vinaigre: "5 c.à.s", moutarde: "3 c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 11, huile: "11 c.à.s", vinaigre: "5½ c.à.s", moutarde: "3¼ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 12, huile: "12 c.à.s", vinaigre: "6 c.à.s", moutarde: "3½ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 13, huile: "13 c.à.s", vinaigre: "6½ c.à.s", moutarde: "4 c.à.c", sel: "3 pincées", poivre: "3 pincées" },
      { nb: 14, huile: "14 c.à.s", vinaigre: "7 c.à.s", moutarde: "4¼ c.à.c", sel: "3 pincées", poivre: "3 pincées" },
      { nb: 15, huile: "15 c.à.s", vinaigre: "7½ c.à.s", moutarde: "4½ c.à.c", sel: "3 pincées", poivre: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥄", titre: "Base", detail: "Dissoudre le sel dans le vinaigre, ajouter la moutarde. ASTUCE : le sel se dissout dans le vinaigre, pas dans l'huile.", badge: "⏱ 1 min" },
      { icone: "🌀", titre: "Émulsionner", detail: "Verser l'huile en fouettant pour émulsionner. SECRET : ratio 3 huiles pour 1 vinaigre = l'équilibre classique.", badge: "⏱ 2 min" },
      { icone: "🌿", titre: "Varier", detail: "ASTUCE CHEF : échalote, herbes, miel, balsamique… personnalise selon la salade. Émulsionner juste avant de servir.", badge: null }
    ]
  },
  bechamel: {
    cat: "sauces", pays: "france",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🥛",
    description: "Sauce béchamel — la sauce blanche mère : roux beurre-farine lié au lait. Base des gratins, lasagnes, croque-monsieur et sauce Mornay.",
    tableauBechamel: [
      { nb: 1, beurre: "8 g", farine: "8 g", lait: "80 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 2, beurre: "16 g", farine: "16 g", lait: "160 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 3, beurre: "24 g", farine: "24 g", lait: "240 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 4, beurre: "32 g", farine: "32 g", lait: "320 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 5, beurre: "40 g", farine: "40 g", lait: "400 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 6, beurre: "48 g", farine: "48 g", lait: "480 ml", muscade: "1 pincée", sel: "1 pincée" },
      { nb: 7, beurre: "56 g", farine: "56 g", lait: "560 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 8, beurre: "64 g", farine: "64 g", lait: "640 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 9, beurre: "72 g", farine: "72 g", lait: "720 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 10, beurre: "80 g", farine: "80 g", lait: "800 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 11, beurre: "88 g", farine: "88 g", lait: "880 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 12, beurre: "96 g", farine: "96 g", lait: "960 ml", muscade: "2 pincées", sel: "2 pincées" },
      { nb: 13, beurre: "104 g", farine: "104 g", lait: "1040 ml", muscade: "3 pincées", sel: "3 pincées" },
      { nb: 14, beurre: "112 g", farine: "112 g", lait: "1120 ml", muscade: "3 pincées", sel: "3 pincées" },
      { nb: 15, beurre: "120 g", farine: "120 g", lait: "1200 ml", muscade: "3 pincées", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧈", titre: "Roux", detail: "Faire fondre le beurre, ajouter la farine et cuire 1-2 min en remuant (roux blanc, sans coloration).", badge: "⏱ 3 min" },
      { icone: "🥛", titre: "Lait", detail: "CLÉ : verser le lait CHAUD progressivement en fouettant SANS ARRÊT pour éviter les grumeaux.", badge: "⏱ 5 min" },
      { icone: "🔥", titre: "Épaissir", detail: "Cuire à feu doux jusqu'à ce que la sauce nappe la cuillère. Sel, poivre, muscade.", badge: "⏱ 5 min" },
      { icone: "🧀", titre: "Variante", detail: "ASTUCE CHEF : ajouter du gruyère râpé hors du feu = sauce Mornay pour les gratins.", badge: null }
    ]
  },
  pestomaison: {
    cat: "sauces", pays: "italie",
    base: 6,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Pesto maison — la sauce génoise au basilic, pignons, parmesan et huile d'olive. Incomparable, à mixer en 5 minutes pour pâtes et tartines.",
    tableauPestoMaison: [
      { nb: 1, basilic: "12 g", pignon: "5 g", parmesan: "8 g", ail: "¼ gousse", huiledolive: "1½ c.à.c" },
      { nb: 2, basilic: "24 g", pignon: "10 g", parmesan: "16 g", ail: "½ gousse", huiledolive: "3 c.à.c" },
      { nb: 3, basilic: "36 g", pignon: "15 g", parmesan: "24 g", ail: "1 gousse", huiledolive: "4½ c.à.c" },
      { nb: 4, basilic: "48 g", pignon: "20 g", parmesan: "32 g", ail: "1¼ gousse", huiledolive: "6 c.à.c" },
      { nb: 5, basilic: "60 g", pignon: "25 g", parmesan: "40 g", ail: "1½ gousse", huiledolive: "7½ c.à.c" },
      { nb: 6, basilic: "72 g", pignon: "30 g", parmesan: "48 g", ail: "1¾ gousse", huiledolive: "9 c.à.c" },
      { nb: 7, basilic: "84 g", pignon: "35 g", parmesan: "56 g", ail: "2 gousses", huiledolive: "10½ c.à.c" },
      { nb: 8, basilic: "96 g", pignon: "40 g", parmesan: "64 g", ail: "2½ gousses", huiledolive: "12 c.à.c" },
      { nb: 9, basilic: "108 g", pignon: "45 g", parmesan: "72 g", ail: "2¾ gousses", huiledolive: "13½ c.à.c" },
      { nb: 10, basilic: "120 g", pignon: "50 g", parmesan: "80 g", ail: "3 gousses", huiledolive: "15 c.à.c" },
      { nb: 11, basilic: "132 g", pignon: "55 g", parmesan: "88 g", ail: "3¼ gousses", huiledolive: "16½ c.à.c" },
      { nb: 12, basilic: "144 g", pignon: "60 g", parmesan: "96 g", ail: "3½ gousses", huiledolive: "18 c.à.c" },
      { nb: 13, basilic: "156 g", pignon: "65 g", parmesan: "104 g", ail: "4 gousses", huiledolive: "19½ c.à.c" },
      { nb: 14, basilic: "168 g", pignon: "70 g", parmesan: "112 g", ail: "4¼ gousses", huiledolive: "21 c.à.c" },
      { nb: 15, basilic: "180 g", pignon: "75 g", parmesan: "120 g", ail: "4½ gousses", huiledolive: "22½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Torréfier", detail: "Torréfier légèrement les pignons à sec. ASTUCE : ça décuple leur goût (mais surveiller, ça brûle vite).", badge: "⏱ 3 min" },
      { icone: "🌿", titre: "Mixer", detail: "Mixer basilic, pignons, ail, parmesan. SECRET : un mortier (ou mixeur par à-coups) garde la couleur vive ; ne pas chauffer.", badge: "⏱ 3 min" },
      { icone: "🫒", titre: "Monter", detail: "Ajouter l'huile d'olive en filet jusqu'à une pâte onctueuse.", badge: "⏱ 2 min" },
      { icone: "🧊", titre: "Conserver", detail: "ASTUCE CHEF : couvrir d'huile pour qu'il ne noircisse pas. Se garde 1 semaine au frais.", badge: null }
    ]
  },
  aioli: {
    cat: "sauces", pays: "espagne",
    base: 6,
    temps: "10 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🧄",
    description: "Aïoli — l'émulsion provençale et catalane à l'ail : une mayonnaise puissamment aillée. Pour poissons, légumes vapeur et tapas.",
    tableauAioli: [
      { nb: 1, oeufs: "¼", ail: "¾ gousse", huiledolive: "25 ml", citron: "¼ c.à.c", sel: "1 pincée" },
      { nb: 2, oeufs: "½", ail: "1½ gousse", huiledolive: "50 ml", citron: "½ c.à.c", sel: "1 pincée" },
      { nb: 3, oeufs: "¾", ail: "2 gousses", huiledolive: "75 ml", citron: "1 c.à.c", sel: "1 pincée" },
      { nb: 4, oeufs: "1", ail: "2¾ gousses", huiledolive: "100 ml", citron: "1¼ c.à.c", sel: "1 pincée" },
      { nb: 5, oeufs: "1¼", ail: "3½ gousses", huiledolive: "125 ml", citron: "1½ c.à.c", sel: "1 pincée" },
      { nb: 6, oeufs: "1½", ail: "4¼ gousses", huiledolive: "150 ml", citron: "1¾ c.à.c", sel: "1 pincée" },
      { nb: 7, oeufs: "1¾", ail: "5 gousses", huiledolive: "175 ml", citron: "2 c.à.c", sel: "2 pincées" },
      { nb: 8, oeufs: "2", ail: "5½ gousses", huiledolive: "200 ml", citron: "2½ c.à.c", sel: "2 pincées" },
      { nb: 9, oeufs: "2¼", ail: "6¼ gousses", huiledolive: "225 ml", citron: "2¾ c.à.c", sel: "2 pincées" },
      { nb: 10, oeufs: "2½", ail: "7 gousses", huiledolive: "250 ml", citron: "3 c.à.c", sel: "2 pincées" },
      { nb: 11, oeufs: "2¾", ail: "7¾ gousses", huiledolive: "275 ml", citron: "3¼ c.à.c", sel: "2 pincées" },
      { nb: 12, oeufs: "3", ail: "8½ gousses", huiledolive: "300 ml", citron: "3½ c.à.c", sel: "2 pincées" },
      { nb: 13, oeufs: "3¼", ail: "9 gousses", huiledolive: "325 ml", citron: "4 c.à.c", sel: "3 pincées" },
      { nb: 14, oeufs: "3½", ail: "9¾ gousses", huiledolive: "350 ml", citron: "4¼ c.à.c", sel: "3 pincées" },
      { nb: 15, oeufs: "3¾", ail: "10½ gousses", huiledolive: "375 ml", citron: "4½ c.à.c", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧄", titre: "Ail", detail: "Écraser l'ail en purée avec le sel (au mortier, c'est l'idéal).", badge: "⏱ 3 min" },
      { icone: "🥚", titre: "Base", detail: "Ajouter le jaune d'œuf et la moutarde si tu veux une prise plus facile.", badge: "⏱ 1 min" },
      { icone: "🌀", titre: "Monter", detail: "CLÉ : verser l'huile d'olive EN FILET en fouettant, comme une mayonnaise. Tout à température ambiante.", badge: "⏱ 5 min" },
      { icone: "🍋", titre: "Finir", detail: "SECRET : un trait de citron allège l'ensemble. Bien aillé = bien aïoli !", badge: null }
    ]
  },
  saucecesar: {
    cat: "sauces", pays: "usa",
    base: 6,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🧀",
    description: "Sauce César — crémeuse, salée et umami : parmesan, anchois, ail et citron. L'âme de la salade César, parfaite aussi en dip.",
    tableauSauceCesar: [
      { nb: 1, mayonnaise: "15 g", parmesan: "6 g", anchois: "½ filet", ail: "¼ gousse", citron: "¼ c.à.c", moutarde: "¼ c.à.c" },
      { nb: 2, mayonnaise: "30 g", parmesan: "12 g", anchois: "1 filet", ail: "½ gousse", citron: "½ c.à.c", moutarde: "½ c.à.c" },
      { nb: 3, mayonnaise: "45 g", parmesan: "18 g", anchois: "1½ filet", ail: "½ gousse", citron: "1 c.à.c", moutarde: "½ c.à.c" },
      { nb: 4, mayonnaise: "60 g", parmesan: "24 g", anchois: "2 filets", ail: "¾ gousse", citron: "1¼ c.à.c", moutarde: "¾ c.à.c" },
      { nb: 5, mayonnaise: "75 g", parmesan: "30 g", anchois: "2½ filets", ail: "1 gousse", citron: "1½ c.à.c", moutarde: "1 c.à.c" },
      { nb: 6, mayonnaise: "90 g", parmesan: "36 g", anchois: "3 filets", ail: "1¼ gousse", citron: "1¾ c.à.c", moutarde: "1¼ c.à.c" },
      { nb: 7, mayonnaise: "105 g", parmesan: "42 g", anchois: "3½ filets", ail: "1½ gousse", citron: "2 c.à.c", moutarde: "1½ c.à.c" },
      { nb: 8, mayonnaise: "120 g", parmesan: "48 g", anchois: "4 filets", ail: "1½ gousse", citron: "2½ c.à.c", moutarde: "1½ c.à.c" },
      { nb: 9, mayonnaise: "135 g", parmesan: "54 g", anchois: "4½ filets", ail: "1¾ gousse", citron: "2¾ c.à.c", moutarde: "1¾ c.à.c" },
      { nb: 10, mayonnaise: "150 g", parmesan: "60 g", anchois: "5 filets", ail: "2 gousses", citron: "3 c.à.c", moutarde: "2 c.à.c" },
      { nb: 11, mayonnaise: "165 g", parmesan: "66 g", anchois: "5½ filets", ail: "2¼ gousses", citron: "3¼ c.à.c", moutarde: "2¼ c.à.c" },
      { nb: 12, mayonnaise: "180 g", parmesan: "72 g", anchois: "6 filets", ail: "2½ gousses", citron: "3½ c.à.c", moutarde: "2½ c.à.c" },
      { nb: 13, mayonnaise: "195 g", parmesan: "78 g", anchois: "6½ filets", ail: "2½ gousses", citron: "4 c.à.c", moutarde: "2½ c.à.c" },
      { nb: 14, mayonnaise: "210 g", parmesan: "84 g", anchois: "7 filets", ail: "2¾ gousses", citron: "4¼ c.à.c", moutarde: "2¾ c.à.c" },
      { nb: 15, mayonnaise: "225 g", parmesan: "90 g", anchois: "7½ filets", ail: "3 gousses", citron: "4½ c.à.c", moutarde: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🐟", titre: "Base umami", detail: "Écraser les anchois et l'ail en pâte. SECRET : l'anchois fond et donne le goût, on ne le 'sent' pas.", badge: "⏱ 3 min" },
      { icone: "🥄", titre: "Mélanger", detail: "Ajouter mayonnaise, parmesan râpé, moutarde, jus de citron. Bien mélanger.", badge: "⏱ 3 min" },
      { icone: "💧", titre: "Texture", detail: "ASTUCE CHEF : détendre avec un peu d'eau ou d'huile pour une sauce nappante (ni trop épaisse, ni liquide).", badge: "⏱ 1 min" },
      { icone: "🧀", titre: "Servir", detail: "Poivre du moulin. Parfaite sur salade romaine, croûtons et copeaux de parmesan.", badge: null }
    ]
  },
  chimichurri: {
    cat: "sauces", pays: "argentine",
    base: 6,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🥩",
    description: "Chimichurri — la sauce argentine du barbecue : persil, ail, origan, vinaigre et huile, relevée de piment. Indispensable sur la viande grillée.",
    tableauChimichurri: [
      { nb: 1, persil: "8 g", ail: "½ gousse", huiledolive: "1½ c.à.c", vinaigre: "½ c.à.c", origan: "¼ c.à.c", piment: "1 pincée" },
      { nb: 2, persil: "16 g", ail: "¾ gousse", huiledolive: "3 c.à.c", vinaigre: "1 c.à.c", origan: "½ c.à.c", piment: "1 pincée" },
      { nb: 3, persil: "24 g", ail: "1¼ gousse", huiledolive: "4½ c.à.c", vinaigre: "1½ c.à.c", origan: "1 c.à.c", piment: "1 pincée" },
      { nb: 4, persil: "32 g", ail: "1½ gousse", huiledolive: "6 c.à.c", vinaigre: "2 c.à.c", origan: "1¼ c.à.c", piment: "1 pincée" },
      { nb: 5, persil: "40 g", ail: "2 gousses", huiledolive: "7½ c.à.c", vinaigre: "2½ c.à.c", origan: "1½ c.à.c", piment: "1 pincée" },
      { nb: 6, persil: "48 g", ail: "2½ gousses", huiledolive: "9 c.à.c", vinaigre: "3 c.à.c", origan: "1¾ c.à.c", piment: "1 pincée" },
      { nb: 7, persil: "56 g", ail: "2¾ gousses", huiledolive: "10½ c.à.c", vinaigre: "3½ c.à.c", origan: "2 c.à.c", piment: "2 pincées" },
      { nb: 8, persil: "64 g", ail: "3¼ gousses", huiledolive: "12 c.à.c", vinaigre: "4 c.à.c", origan: "2½ c.à.c", piment: "2 pincées" },
      { nb: 9, persil: "72 g", ail: "3½ gousses", huiledolive: "13½ c.à.c", vinaigre: "4½ c.à.c", origan: "2¾ c.à.c", piment: "2 pincées" },
      { nb: 10, persil: "80 g", ail: "4 gousses", huiledolive: "15 c.à.c", vinaigre: "5 c.à.c", origan: "3 c.à.c", piment: "2 pincées" },
      { nb: 11, persil: "88 g", ail: "4½ gousses", huiledolive: "16½ c.à.c", vinaigre: "5½ c.à.c", origan: "3¼ c.à.c", piment: "2 pincées" },
      { nb: 12, persil: "96 g", ail: "4¾ gousses", huiledolive: "18 c.à.c", vinaigre: "6 c.à.c", origan: "3½ c.à.c", piment: "2 pincées" },
      { nb: 13, persil: "104 g", ail: "5¼ gousses", huiledolive: "19½ c.à.c", vinaigre: "6½ c.à.c", origan: "4 c.à.c", piment: "3 pincées" },
      { nb: 14, persil: "112 g", ail: "5½ gousses", huiledolive: "21 c.à.c", vinaigre: "7 c.à.c", origan: "4¼ c.à.c", piment: "3 pincées" },
      { nb: 15, persil: "120 g", ail: "6 gousses", huiledolive: "22½ c.à.c", vinaigre: "7½ c.à.c", origan: "4½ c.à.c", piment: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Hacher", detail: "Hacher FINEMENT persil et ail au couteau. ASTUCE : au couteau plutôt qu'au mixeur, la texture est plus authentique.", badge: "⏱ 5 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger avec origan, piment, vinaigre, sel.", badge: "⏱ 2 min" },
      { icone: "🫒", titre: "Huile", detail: "Ajouter l'huile d'olive, mélanger. SECRET : laisser reposer 30 min, les saveurs infusent dans l'huile.", badge: "⏱ 2 min" },
      { icone: "🥩", titre: "Servir", detail: "ASTUCE CHEF : nappe une viande grillée à la sortie. Se garde 1 semaine au frais.", badge: null }
    ]
  },
  saucecurrycoco: {
    cat: "sauces", pays: "inde",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🍛",
    description: "Sauce curry-coco — douce et parfumée : lait de coco, curry, gingembre et ail. Pour napper poulet, poisson, légumes ou riz.",
    tableauSauceCurryCoco: [
      { nb: 1, laitcoco: "50 ml", curry: "¾ c.à.c", oignon: "10 g", ail: "¼ gousse", gingembre: "2 g", huile: "½ c.à.c" },
      { nb: 2, laitcoco: "100 ml", curry: "1½ c.à.c", oignon: "20 g", ail: "½ gousse", gingembre: "4 g", huile: "1 c.à.c" },
      { nb: 3, laitcoco: "150 ml", curry: "2 c.à.c", oignon: "30 g", ail: "1 gousse", gingembre: "6 g", huile: "1½ c.à.c" },
      { nb: 4, laitcoco: "200 ml", curry: "2¾ c.à.c", oignon: "40 g", ail: "1¼ gousse", gingembre: "8 g", huile: "2 c.à.c" },
      { nb: 5, laitcoco: "250 ml", curry: "3½ c.à.c", oignon: "50 g", ail: "1½ gousse", gingembre: "10 g", huile: "2½ c.à.c" },
      { nb: 6, laitcoco: "300 ml", curry: "4¼ c.à.c", oignon: "60 g", ail: "1¾ gousse", gingembre: "12 g", huile: "3 c.à.c" },
      { nb: 7, laitcoco: "350 ml", curry: "5 c.à.c", oignon: "70 g", ail: "2 gousses", gingembre: "14 g", huile: "3½ c.à.c" },
      { nb: 8, laitcoco: "400 ml", curry: "5½ c.à.c", oignon: "80 g", ail: "2½ gousses", gingembre: "16 g", huile: "4 c.à.c" },
      { nb: 9, laitcoco: "450 ml", curry: "6¼ c.à.c", oignon: "90 g", ail: "2¾ gousses", gingembre: "18 g", huile: "4½ c.à.c" },
      { nb: 10, laitcoco: "500 ml", curry: "7 c.à.c", oignon: "100 g", ail: "3 gousses", gingembre: "20 g", huile: "5 c.à.c" },
      { nb: 11, laitcoco: "550 ml", curry: "7¾ c.à.c", oignon: "110 g", ail: "3¼ gousses", gingembre: "22 g", huile: "5½ c.à.c" },
      { nb: 12, laitcoco: "600 ml", curry: "8½ c.à.c", oignon: "120 g", ail: "3½ gousses", gingembre: "24 g", huile: "6 c.à.c" },
      { nb: 13, laitcoco: "650 ml", curry: "9 c.à.c", oignon: "130 g", ail: "4 gousses", gingembre: "26 g", huile: "6½ c.à.c" },
      { nb: 14, laitcoco: "700 ml", curry: "9¾ c.à.c", oignon: "140 g", ail: "4¼ gousses", gingembre: "28 g", huile: "7 c.à.c" },
      { nb: 15, laitcoco: "750 ml", curry: "10½ c.à.c", oignon: "150 g", ail: "4½ gousses", gingembre: "30 g", huile: "7½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧅", titre: "Aromates", detail: "Faire revenir oignon, ail et gingembre. Ajouter le curry et torréfier 30 s. SECRET : torréfier les épices libère leurs arômes.", badge: "⏱ 5 min" },
      { icone: "🥥", titre: "Lait de coco", detail: "Verser le lait de coco, mélanger.", badge: "⏱ 2 min" },
      { icone: "🔥", titre: "Mijoter", detail: "CLÉ : laisser réduire 10-12 min à feu doux jusqu'à une sauce nappante.", badge: "⏱ 12 min" },
      { icone: "🍋", titre: "Finir", detail: "ASTUCE CHEF : un trait de citron vert et de la coriandre fraîche réveillent la sauce.", badge: null }
    ]
  },
  teriyaki: {
    cat: "sauces", pays: "japon",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍶",
    description: "Sauce teriyaki — la sauce japonaise laquée, sucrée-salée : soja, sucre et gingembre réduits en sirop brillant. Pour poulet, saumon, bœuf.",
    tableauTeriyaki: [
      { nb: 1, saucesoja: "1 c.à.s", sucre: "1 c.à.c", miel: "1 c.à.c", gingembre: "2 g", ail: "¼ gousse" },
      { nb: 2, saucesoja: "2 c.à.s", sucre: "2 c.à.c", miel: "2 c.à.c", gingembre: "4 g", ail: "½ gousse" },
      { nb: 3, saucesoja: "3 c.à.s", sucre: "3 c.à.c", miel: "3 c.à.c", gingembre: "6 g", ail: "½ gousse" },
      { nb: 4, saucesoja: "4 c.à.s", sucre: "4 c.à.c", miel: "4 c.à.c", gingembre: "8 g", ail: "¾ gousse" },
      { nb: 5, saucesoja: "5 c.à.s", sucre: "5 c.à.c", miel: "5 c.à.c", gingembre: "10 g", ail: "1 gousse" },
      { nb: 6, saucesoja: "6 c.à.s", sucre: "6 c.à.c", miel: "6 c.à.c", gingembre: "12 g", ail: "1¼ gousse" },
      { nb: 7, saucesoja: "7 c.à.s", sucre: "7 c.à.c", miel: "7 c.à.c", gingembre: "14 g", ail: "1½ gousse" },
      { nb: 8, saucesoja: "8 c.à.s", sucre: "8 c.à.c", miel: "8 c.à.c", gingembre: "16 g", ail: "1½ gousse" },
      { nb: 9, saucesoja: "9 c.à.s", sucre: "9 c.à.c", miel: "9 c.à.c", gingembre: "18 g", ail: "1¾ gousse" },
      { nb: 10, saucesoja: "10 c.à.s", sucre: "10 c.à.c", miel: "10 c.à.c", gingembre: "20 g", ail: "2 gousses" },
      { nb: 11, saucesoja: "11 c.à.s", sucre: "11 c.à.c", miel: "11 c.à.c", gingembre: "22 g", ail: "2¼ gousses" },
      { nb: 12, saucesoja: "12 c.à.s", sucre: "12 c.à.c", miel: "12 c.à.c", gingembre: "24 g", ail: "2½ gousses" },
      { nb: 13, saucesoja: "13 c.à.s", sucre: "13 c.à.c", miel: "13 c.à.c", gingembre: "26 g", ail: "2½ gousses" },
      { nb: 14, saucesoja: "14 c.à.s", sucre: "14 c.à.c", miel: "14 c.à.c", gingembre: "28 g", ail: "2¾ gousses" },
      { nb: 15, saucesoja: "15 c.à.s", sucre: "15 c.à.c", miel: "15 c.à.c", gingembre: "30 g", ail: "3 gousses" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Réunir sauce soja, sucre (ou miel), gingembre et ail râpés, un peu d'eau.", badge: "⏱ 3 min" },
      { icone: "🔥", titre: "Réduire", detail: "CLÉ : faire réduire à feu moyen jusqu'à ce que ça nappe et devienne sirupeux et brillant.", badge: "⏱ 8 min" },
      { icone: "✨", titre: "Laquer", detail: "SECRET : un peu de maïzena diluée pour une sauce plus épaisse et laquée. ASTUCE CHEF : badigeonner la viande en fin de cuisson, elle caramélise.", badge: "⏱ 2 min" }
    ]
  },
  sauceblanche: {
    cat: "sauces", pays: "monde",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🥙",
    description: "Sauce blanche kebab — crémeuse et fraîche : yaourt, mayonnaise, citron et ail. L'incontournable des sandwichs, kebabs et tacos.",
    tableauSauceBlanche: [
      { nb: 1, yaourtgrec: "30 g", mayonnaise: "10 g", citron: "¼ c.à.c", ail: "¼ gousse", persil: "1 pincée" },
      { nb: 2, yaourtgrec: "60 g", mayonnaise: "20 g", citron: "½ c.à.c", ail: "¼ gousse", persil: "1 pincée" },
      { nb: 3, yaourtgrec: "90 g", mayonnaise: "30 g", citron: "1 c.à.c", ail: "½ gousse", persil: "1 pincée" },
      { nb: 4, yaourtgrec: "120 g", mayonnaise: "40 g", citron: "1¼ c.à.c", ail: "½ gousse", persil: "1 pincée" },
      { nb: 5, yaourtgrec: "150 g", mayonnaise: "50 g", citron: "1½ c.à.c", ail: "¾ gousse", persil: "1 pincée" },
      { nb: 6, yaourtgrec: "180 g", mayonnaise: "60 g", citron: "1¾ c.à.c", ail: "1 gousse", persil: "1 pincée" },
      { nb: 7, yaourtgrec: "210 g", mayonnaise: "70 g", citron: "2 c.à.c", ail: "1 gousse", persil: "2 pincées" },
      { nb: 8, yaourtgrec: "240 g", mayonnaise: "80 g", citron: "2½ c.à.c", ail: "1¼ gousse", persil: "2 pincées" },
      { nb: 9, yaourtgrec: "270 g", mayonnaise: "90 g", citron: "2¾ c.à.c", ail: "1¼ gousse", persil: "2 pincées" },
      { nb: 10, yaourtgrec: "300 g", mayonnaise: "100 g", citron: "3 c.à.c", ail: "1½ gousse", persil: "2 pincées" },
      { nb: 11, yaourtgrec: "330 g", mayonnaise: "110 g", citron: "3¼ c.à.c", ail: "1¾ gousse", persil: "2 pincées" },
      { nb: 12, yaourtgrec: "360 g", mayonnaise: "120 g", citron: "3½ c.à.c", ail: "1¾ gousse", persil: "2 pincées" },
      { nb: 13, yaourtgrec: "390 g", mayonnaise: "130 g", citron: "4 c.à.c", ail: "2 gousses", persil: "3 pincées" },
      { nb: 14, yaourtgrec: "420 g", mayonnaise: "140 g", citron: "4¼ c.à.c", ail: "2 gousses", persil: "3 pincées" },
      { nb: 15, yaourtgrec: "450 g", mayonnaise: "150 g", citron: "4½ c.à.c", ail: "2¼ gousses", persil: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger yaourt, mayonnaise, jus de citron, ail écrasé.", badge: "⏱ 3 min" },
      { icone: "🌿", titre: "Assaisonner", detail: "Sel, poivre, persil ou ciboulette. ASTUCE : une pointe de cumin ou de menthe pour varier.", badge: "⏱ 1 min" },
      { icone: "🧊", titre: "Reposer", detail: "SECRET : 30 min au frais, les saveurs se lient. Ajuster la consistance avec un peu d'eau si trop épaisse.", badge: null }
    ]
  },
  saucesamourai: {
    cat: "sauces", pays: "france",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🌶️",
    description: "Sauce samouraï — la sauce belge piquante : mayonnaise, ketchup et harissa. Parfaite avec les frites, burgers et viandes.",
    tableauSauceSamourai: [
      { nb: 1, mayonnaise: "18 g", ketchup: "8 g", harissa: "½ c.à.c", paprika: "¼ c.à.c" },
      { nb: 2, mayonnaise: "36 g", ketchup: "16 g", harissa: "1 c.à.c", paprika: "½ c.à.c" },
      { nb: 3, mayonnaise: "54 g", ketchup: "24 g", harissa: "1½ c.à.c", paprika: "½ c.à.c" },
      { nb: 4, mayonnaise: "72 g", ketchup: "32 g", harissa: "2 c.à.c", paprika: "¾ c.à.c" },
      { nb: 5, mayonnaise: "90 g", ketchup: "40 g", harissa: "2½ c.à.c", paprika: "1 c.à.c" },
      { nb: 6, mayonnaise: "108 g", ketchup: "48 g", harissa: "3 c.à.c", paprika: "1¼ c.à.c" },
      { nb: 7, mayonnaise: "126 g", ketchup: "56 g", harissa: "3½ c.à.c", paprika: "1½ c.à.c" },
      { nb: 8, mayonnaise: "144 g", ketchup: "64 g", harissa: "4 c.à.c", paprika: "1½ c.à.c" },
      { nb: 9, mayonnaise: "162 g", ketchup: "72 g", harissa: "4½ c.à.c", paprika: "1¾ c.à.c" },
      { nb: 10, mayonnaise: "180 g", ketchup: "80 g", harissa: "5 c.à.c", paprika: "2 c.à.c" },
      { nb: 11, mayonnaise: "198 g", ketchup: "88 g", harissa: "5½ c.à.c", paprika: "2¼ c.à.c" },
      { nb: 12, mayonnaise: "216 g", ketchup: "96 g", harissa: "6 c.à.c", paprika: "2½ c.à.c" },
      { nb: 13, mayonnaise: "234 g", ketchup: "104 g", harissa: "6½ c.à.c", paprika: "2½ c.à.c" },
      { nb: 14, mayonnaise: "252 g", ketchup: "112 g", harissa: "7 c.à.c", paprika: "2¾ c.à.c" },
      { nb: 15, mayonnaise: "270 g", ketchup: "120 g", harissa: "7½ c.à.c", paprika: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger mayonnaise, ketchup et harissa.", badge: "⏱ 2 min" },
      { icone: "🌶️", titre: "Doser le feu", detail: "CLÉ : ajouter la harissa progressivement en goûtant — c'est elle qui pique.", badge: "⏱ 1 min" },
      { icone: "🍟", titre: "Servir", detail: "ASTUCE CHEF : un peu de paprika fumé arrondit le tout. Idéale avec les frites maison.", badge: null }
    ]
  },
  saucetartare: {
    cat: "sauces", pays: "france",
    base: 6,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🥚",
    description: "Sauce tartare — mayonnaise relevée aux cornichons, câpres, échalote et herbes. L'accompagnement classique du poisson pané et frit.",
    tableauSauceTartare: [
      { nb: 1, mayonnaise: "20 g", cornichon: "8 g", capres: "4 g", echalote: "5 g", persil: "1 g", moutarde: "¼ c.à.c" },
      { nb: 2, mayonnaise: "40 g", cornichon: "16 g", capres: "8 g", echalote: "10 g", persil: "2 g", moutarde: "½ c.à.c" },
      { nb: 3, mayonnaise: "60 g", cornichon: "24 g", capres: "12 g", echalote: "15 g", persil: "3 g", moutarde: "½ c.à.c" },
      { nb: 4, mayonnaise: "80 g", cornichon: "32 g", capres: "16 g", echalote: "20 g", persil: "4 g", moutarde: "¾ c.à.c" },
      { nb: 5, mayonnaise: "100 g", cornichon: "40 g", capres: "20 g", echalote: "25 g", persil: "5 g", moutarde: "1 c.à.c" },
      { nb: 6, mayonnaise: "120 g", cornichon: "48 g", capres: "24 g", echalote: "30 g", persil: "6 g", moutarde: "1¼ c.à.c" },
      { nb: 7, mayonnaise: "140 g", cornichon: "56 g", capres: "28 g", echalote: "35 g", persil: "7 g", moutarde: "1½ c.à.c" },
      { nb: 8, mayonnaise: "160 g", cornichon: "64 g", capres: "32 g", echalote: "40 g", persil: "8 g", moutarde: "1½ c.à.c" },
      { nb: 9, mayonnaise: "180 g", cornichon: "72 g", capres: "36 g", echalote: "45 g", persil: "9 g", moutarde: "1¾ c.à.c" },
      { nb: 10, mayonnaise: "200 g", cornichon: "80 g", capres: "40 g", echalote: "50 g", persil: "10 g", moutarde: "2 c.à.c" },
      { nb: 11, mayonnaise: "220 g", cornichon: "88 g", capres: "44 g", echalote: "55 g", persil: "11 g", moutarde: "2¼ c.à.c" },
      { nb: 12, mayonnaise: "240 g", cornichon: "96 g", capres: "48 g", echalote: "60 g", persil: "12 g", moutarde: "2½ c.à.c" },
      { nb: 13, mayonnaise: "260 g", cornichon: "104 g", capres: "52 g", echalote: "65 g", persil: "13 g", moutarde: "2½ c.à.c" },
      { nb: 14, mayonnaise: "280 g", cornichon: "112 g", capres: "56 g", echalote: "70 g", persil: "14 g", moutarde: "2¾ c.à.c" },
      { nb: 15, mayonnaise: "300 g", cornichon: "120 g", capres: "60 g", echalote: "75 g", persil: "15 g", moutarde: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔪", titre: "Hacher", detail: "Hacher finement cornichons, câpres, échalote et persil.", badge: "⏱ 4 min" },
      { icone: "🥄", titre: "Mélanger", detail: "Incorporer à la mayonnaise avec un peu de moutarde. SECRET : un jaune d'œuf dur écrasé pour la version traditionnelle.", badge: "⏱ 3 min" },
      { icone: "🍋", titre: "Assaisonner", detail: "Citron, poivre. ASTUCE CHEF : laisser reposer 30 min pour que les acidités se fondent. Top avec poisson pané.", badge: null }
    ]
  },
  saucehollandaise: {
    cat: "sauces", pays: "france",
    base: 4,
    temps: "15 min",
    niveau: "⭐⭐⭐ Difficile",
    emoji: "🍳",
    description: "Sauce hollandaise — l'émulsion chaude au beurre et au jaune d'œuf, citronnée. Pour asperges, œufs Bénédicte et poissons. Technique mais inratable avec la méthode.",
    tableauSauceHollandaise: [
      { nb: 1, oeufs: "½", beurre: "25 g", citron: "½ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 2, oeufs: "1", beurre: "50 g", citron: "1 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 3, oeufs: "1½", beurre: "75 g", citron: "1½ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 4, oeufs: "2", beurre: "100 g", citron: "2 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 5, oeufs: "2½", beurre: "125 g", citron: "2½ c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 6, oeufs: "3", beurre: "150 g", citron: "3 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 7, oeufs: "3½", beurre: "175 g", citron: "3½ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 8, oeufs: "4", beurre: "200 g", citron: "4 c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 9, oeufs: "4½", beurre: "225 g", citron: "4½ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 10, oeufs: "5", beurre: "250 g", citron: "5 c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 11, oeufs: "5½", beurre: "275 g", citron: "5½ c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 12, oeufs: "6", beurre: "300 g", citron: "6 c.à.c", sel: "2 pincées", poivre: "2 pincées" },
      { nb: 13, oeufs: "6½", beurre: "325 g", citron: "6½ c.à.c", sel: "3 pincées", poivre: "3 pincées" },
      { nb: 14, oeufs: "7", beurre: "350 g", citron: "7 c.à.c", sel: "3 pincées", poivre: "3 pincées" },
      { nb: 15, oeufs: "7½", beurre: "375 g", citron: "7½ c.à.c", sel: "3 pincées", poivre: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧈", titre: "Beurre clarifié", detail: "Faire fondre doucement le beurre. ASTUCE : retirer l'écume, garder la partie claire (beurre clarifié).", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Sabayon", detail: "Fouetter les jaunes avec un peu d'eau et de citron AU BAIN-MARIE. CLÉ : feu très doux, fouetter sans cesse jusqu'à ce que ça épaississe (ne pas cuire l'œuf !).", badge: "⏱ 5 min" },
      { icone: "🌀", titre: "Monter", detail: "SECRET : hors du feu, incorporer le beurre clarifié EN FILET en fouettant, comme une mayonnaise chaude.", badge: "⏱ 4 min" },
      { icone: "🍋", titre: "Finir", detail: "Citron, sel, poivre. ASTUCE CHEF : si elle tranche, fouetter avec une c.à.s d'eau froide. Servir AUSSITÔT (elle n'attend pas).", badge: null }
    ]
  },
  saucesoja: {
    cat: "sauces", pays: "japon",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍶",
    description: "Sauce soja-sésame — sauce d'accompagnement asiatique : soja, sésame, gingembre et touche sucrée. Pour gyozas, sushis, bowls et marinades.",
    tableauSauceSoja: [
      { nb: 1, saucesoja: "15 ml", sesame: "2 g", gingembre: "2 g", sucre: "¼ c.à.c", oignon: "3 g" },
      { nb: 2, saucesoja: "30 ml", sesame: "4 g", gingembre: "4 g", sucre: "½ c.à.c", oignon: "6 g" },
      { nb: 3, saucesoja: "45 ml", sesame: "6 g", gingembre: "6 g", sucre: "1 c.à.c", oignon: "9 g" },
      { nb: 4, saucesoja: "60 ml", sesame: "8 g", gingembre: "8 g", sucre: "1¼ c.à.c", oignon: "12 g" },
      { nb: 5, saucesoja: "75 ml", sesame: "10 g", gingembre: "10 g", sucre: "1½ c.à.c", oignon: "15 g" },
      { nb: 6, saucesoja: "90 ml", sesame: "12 g", gingembre: "12 g", sucre: "1¾ c.à.c", oignon: "18 g" },
      { nb: 7, saucesoja: "105 ml", sesame: "14 g", gingembre: "14 g", sucre: "2 c.à.c", oignon: "21 g" },
      { nb: 8, saucesoja: "120 ml", sesame: "16 g", gingembre: "16 g", sucre: "2½ c.à.c", oignon: "24 g" },
      { nb: 9, saucesoja: "135 ml", sesame: "18 g", gingembre: "18 g", sucre: "2¾ c.à.c", oignon: "27 g" },
      { nb: 10, saucesoja: "150 ml", sesame: "20 g", gingembre: "20 g", sucre: "3 c.à.c", oignon: "30 g" },
      { nb: 11, saucesoja: "165 ml", sesame: "22 g", gingembre: "22 g", sucre: "3¼ c.à.c", oignon: "33 g" },
      { nb: 12, saucesoja: "180 ml", sesame: "24 g", gingembre: "24 g", sucre: "3½ c.à.c", oignon: "36 g" },
      { nb: 13, saucesoja: "195 ml", sesame: "26 g", gingembre: "26 g", sucre: "4 c.à.c", oignon: "39 g" },
      { nb: 14, saucesoja: "210 ml", sesame: "28 g", gingembre: "28 g", sucre: "4¼ c.à.c", oignon: "42 g" },
      { nb: 15, saucesoja: "225 ml", sesame: "30 g", gingembre: "30 g", sucre: "4½ c.à.c", oignon: "45 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger sauce soja, sucre, gingembre râpé, oignon vert ciselé.", badge: "⏱ 3 min" },
      { icone: "🌰", titre: "Sésame", detail: "Ajouter les graines de sésame (torréfiées, c'est meilleur). ASTUCE : un trait d'huile de sésame pour le parfum.", badge: "⏱ 1 min" },
      { icone: "🥟", titre: "Servir", detail: "SECRET : un peu de vinaigre de riz pour la version dipping gyoza. Parfaite en sauce trempette.", badge: null }
    ]
  },
  saucecocktail: {
    cat: "sauces", pays: "france",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍤",
    description: "Sauce cocktail — la mayonnaise rosée légèrement relevée et citronnée. Pour crevettes, avocats et fruits de mer.",
    tableauSauceCocktail: [
      { nb: 1, mayonnaise: "18 g", ketchup: "8 g", citron: "¼ c.à.c", paprika: "1 pincée" },
      { nb: 2, mayonnaise: "36 g", ketchup: "16 g", citron: "½ c.à.c", paprika: "1 pincée" },
      { nb: 3, mayonnaise: "54 g", ketchup: "24 g", citron: "1 c.à.c", paprika: "1 pincée" },
      { nb: 4, mayonnaise: "72 g", ketchup: "32 g", citron: "1¼ c.à.c", paprika: "1 pincée" },
      { nb: 5, mayonnaise: "90 g", ketchup: "40 g", citron: "1½ c.à.c", paprika: "1 pincée" },
      { nb: 6, mayonnaise: "108 g", ketchup: "48 g", citron: "1¾ c.à.c", paprika: "1 pincée" },
      { nb: 7, mayonnaise: "126 g", ketchup: "56 g", citron: "2 c.à.c", paprika: "2 pincées" },
      { nb: 8, mayonnaise: "144 g", ketchup: "64 g", citron: "2½ c.à.c", paprika: "2 pincées" },
      { nb: 9, mayonnaise: "162 g", ketchup: "72 g", citron: "2¾ c.à.c", paprika: "2 pincées" },
      { nb: 10, mayonnaise: "180 g", ketchup: "80 g", citron: "3 c.à.c", paprika: "2 pincées" },
      { nb: 11, mayonnaise: "198 g", ketchup: "88 g", citron: "3¼ c.à.c", paprika: "2 pincées" },
      { nb: 12, mayonnaise: "216 g", ketchup: "96 g", citron: "3½ c.à.c", paprika: "2 pincées" },
      { nb: 13, mayonnaise: "234 g", ketchup: "104 g", citron: "4 c.à.c", paprika: "3 pincées" },
      { nb: 14, mayonnaise: "252 g", ketchup: "112 g", citron: "4¼ c.à.c", paprika: "3 pincées" },
      { nb: 15, mayonnaise: "270 g", ketchup: "120 g", citron: "4½ c.à.c", paprika: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger mayonnaise et ketchup jusqu'à une jolie couleur rosée.", badge: "⏱ 2 min" },
      { icone: "🍋", titre: "Relever", detail: "Citron, paprika, sel. SECRET : quelques gouttes de Worcestershire et un soupçon de cognac pour la version chic.", badge: "⏱ 1 min" },
      { icone: "🍤", titre: "Servir", detail: "ASTUCE CHEF : parfaite sur des crevettes ou en verrine avocat-crevette. Servir frais.", badge: null }
    ]
  },
  sauceaigredouce: {
    cat: "sauces", pays: "chine",
    base: 6,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍍",
    description: "Sauce aigre-douce — l'équilibre sucré-acide chinois : vinaigre, sucre, ketchup et ananas, liée à la maïzena. Pour porc, poulet et nems.",
    tableauSauceAigreDouce: [
      { nb: 1, vinaigre: "1 c.à.c", sucre: "1 c.à.c", ketchup: "6 g", ananas: "15 g", saucesoja: "¼ c.à.c", maizena: "¼ c.à.c" },
      { nb: 2, vinaigre: "2 c.à.c", sucre: "2 c.à.c", ketchup: "12 g", ananas: "30 g", saucesoja: "½ c.à.c", maizena: "½ c.à.c" },
      { nb: 3, vinaigre: "3 c.à.c", sucre: "3 c.à.c", ketchup: "18 g", ananas: "45 g", saucesoja: "1 c.à.c", maizena: "1 c.à.c" },
      { nb: 4, vinaigre: "4 c.à.c", sucre: "4 c.à.c", ketchup: "24 g", ananas: "60 g", saucesoja: "1¼ c.à.c", maizena: "1¼ c.à.c" },
      { nb: 5, vinaigre: "5 c.à.c", sucre: "5 c.à.c", ketchup: "30 g", ananas: "75 g", saucesoja: "1½ c.à.c", maizena: "1½ c.à.c" },
      { nb: 6, vinaigre: "6 c.à.c", sucre: "6 c.à.c", ketchup: "36 g", ananas: "90 g", saucesoja: "1¾ c.à.c", maizena: "1¾ c.à.c" },
      { nb: 7, vinaigre: "7 c.à.c", sucre: "7 c.à.c", ketchup: "42 g", ananas: "105 g", saucesoja: "2 c.à.c", maizena: "2 c.à.c" },
      { nb: 8, vinaigre: "8 c.à.c", sucre: "8 c.à.c", ketchup: "48 g", ananas: "120 g", saucesoja: "2½ c.à.c", maizena: "2½ c.à.c" },
      { nb: 9, vinaigre: "9 c.à.c", sucre: "9 c.à.c", ketchup: "54 g", ananas: "135 g", saucesoja: "2¾ c.à.c", maizena: "2¾ c.à.c" },
      { nb: 10, vinaigre: "10 c.à.c", sucre: "10 c.à.c", ketchup: "60 g", ananas: "150 g", saucesoja: "3 c.à.c", maizena: "3 c.à.c" },
      { nb: 11, vinaigre: "11 c.à.c", sucre: "11 c.à.c", ketchup: "66 g", ananas: "165 g", saucesoja: "3¼ c.à.c", maizena: "3¼ c.à.c" },
      { nb: 12, vinaigre: "12 c.à.c", sucre: "12 c.à.c", ketchup: "72 g", ananas: "180 g", saucesoja: "3½ c.à.c", maizena: "3½ c.à.c" },
      { nb: 13, vinaigre: "13 c.à.c", sucre: "13 c.à.c", ketchup: "78 g", ananas: "195 g", saucesoja: "4 c.à.c", maizena: "4 c.à.c" },
      { nb: 14, vinaigre: "14 c.à.c", sucre: "14 c.à.c", ketchup: "84 g", ananas: "210 g", saucesoja: "4¼ c.à.c", maizena: "4¼ c.à.c" },
      { nb: 15, vinaigre: "15 c.à.c", sucre: "15 c.à.c", ketchup: "90 g", ananas: "225 g", saucesoja: "4½ c.à.c", maizena: "4½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Base", detail: "Mélanger vinaigre, sucre, ketchup, sauce soja et jus d'ananas.", badge: "⏱ 3 min" },
      { icone: "🔥", titre: "Chauffer", detail: "Porter à frémissement. CLÉ : équilibrer le sucré et l'acide à ton goût.", badge: "⏱ 5 min" },
      { icone: "✨", titre: "Lier", detail: "SECRET : maïzena diluée dans un peu d'eau froide, verser en remuant jusqu'à épaississement brillant.", badge: "⏱ 3 min" },
      { icone: "🍍", titre: "Finir", detail: "ASTUCE CHEF : ajouter des dés d'ananas et de poivron pour la version 'plat'. Nappe porc ou poulet frit.", badge: null }
    ]
  },
  saucemoutardemiel: {
    cat: "sauces", pays: "france",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍯",
    description: "Sauce moutarde-miel — l'équilibre parfait du piquant et du sucré. Pour salades, poulet, wraps et dips de légumes.",
    tableauSauceMoutardeMiel: [
      { nb: 1, moutarde: "1 c.à.c", miel: "1 c.à.c", huile: "½ c.à.s", vinaigre: "¼ c.à.c" },
      { nb: 2, moutarde: "2 c.à.c", miel: "2 c.à.c", huile: "1 c.à.s", vinaigre: "½ c.à.c" },
      { nb: 3, moutarde: "3 c.à.c", miel: "3 c.à.c", huile: "1½ c.à.s", vinaigre: "1 c.à.c" },
      { nb: 4, moutarde: "4 c.à.c", miel: "4 c.à.c", huile: "2 c.à.s", vinaigre: "1¼ c.à.c" },
      { nb: 5, moutarde: "5 c.à.c", miel: "5 c.à.c", huile: "2½ c.à.s", vinaigre: "1½ c.à.c" },
      { nb: 6, moutarde: "6 c.à.c", miel: "6 c.à.c", huile: "3 c.à.s", vinaigre: "1¾ c.à.c" },
      { nb: 7, moutarde: "7 c.à.c", miel: "7 c.à.c", huile: "3½ c.à.s", vinaigre: "2 c.à.c" },
      { nb: 8, moutarde: "8 c.à.c", miel: "8 c.à.c", huile: "4 c.à.s", vinaigre: "2½ c.à.c" },
      { nb: 9, moutarde: "9 c.à.c", miel: "9 c.à.c", huile: "4½ c.à.s", vinaigre: "2¾ c.à.c" },
      { nb: 10, moutarde: "10 c.à.c", miel: "10 c.à.c", huile: "5 c.à.s", vinaigre: "3 c.à.c" },
      { nb: 11, moutarde: "11 c.à.c", miel: "11 c.à.c", huile: "5½ c.à.s", vinaigre: "3¼ c.à.c" },
      { nb: 12, moutarde: "12 c.à.c", miel: "12 c.à.c", huile: "6 c.à.s", vinaigre: "3½ c.à.c" },
      { nb: 13, moutarde: "13 c.à.c", miel: "13 c.à.c", huile: "6½ c.à.s", vinaigre: "4 c.à.c" },
      { nb: 14, moutarde: "14 c.à.c", miel: "14 c.à.c", huile: "7 c.à.s", vinaigre: "4¼ c.à.c" },
      { nb: 15, moutarde: "15 c.à.c", miel: "15 c.à.c", huile: "7½ c.à.s", vinaigre: "4½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Fouetter moutarde et miel jusqu'à homogénéité.", badge: "⏱ 2 min" },
      { icone: "🌀", titre: "Émulsionner", detail: "Ajouter l'huile en filet et le vinaigre en fouettant. ASTUCE : un peu de moutarde à l'ancienne pour le croquant des grains.", badge: "⏱ 2 min" },
      { icone: "🥗", titre: "Servir", detail: "SECRET : un trait de jus de citron allège. Parfaite en vinaigrette tiède sur du poulet.", badge: null }
    ]
  },
  saucepoivre: {
    cat: "sauces", pays: "france",
    base: 4,
    temps: "15 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🥩",
    description: "Sauce au poivre — la sauce crémeuse des steaks : crème, poivre concassé et échalote, déglacée au cognac. Onctueuse et relevée.",
    tableauSaucePoivre: [
      { nb: 1, cremefraiche: "30 g", poivre: "½ c.à.c", echalote: "6 g", beurre: "3 g", vinblanc: "5 ml" },
      { nb: 2, cremefraiche: "60 g", poivre: "1 c.à.c", echalote: "12 g", beurre: "6 g", vinblanc: "10 ml" },
      { nb: 3, cremefraiche: "90 g", poivre: "1½ c.à.c", echalote: "18 g", beurre: "9 g", vinblanc: "15 ml" },
      { nb: 4, cremefraiche: "120 g", poivre: "2 c.à.c", echalote: "24 g", beurre: "12 g", vinblanc: "20 ml" },
      { nb: 5, cremefraiche: "150 g", poivre: "2½ c.à.c", echalote: "30 g", beurre: "15 g", vinblanc: "25 ml" },
      { nb: 6, cremefraiche: "180 g", poivre: "3 c.à.c", echalote: "36 g", beurre: "18 g", vinblanc: "30 ml" },
      { nb: 7, cremefraiche: "210 g", poivre: "3½ c.à.c", echalote: "42 g", beurre: "21 g", vinblanc: "35 ml" },
      { nb: 8, cremefraiche: "240 g", poivre: "4 c.à.c", echalote: "48 g", beurre: "24 g", vinblanc: "40 ml" },
      { nb: 9, cremefraiche: "270 g", poivre: "4½ c.à.c", echalote: "54 g", beurre: "27 g", vinblanc: "45 ml" },
      { nb: 10, cremefraiche: "300 g", poivre: "5 c.à.c", echalote: "60 g", beurre: "30 g", vinblanc: "50 ml" },
      { nb: 11, cremefraiche: "330 g", poivre: "5½ c.à.c", echalote: "66 g", beurre: "33 g", vinblanc: "55 ml" },
      { nb: 12, cremefraiche: "360 g", poivre: "6 c.à.c", echalote: "72 g", beurre: "36 g", vinblanc: "60 ml" },
      { nb: 13, cremefraiche: "390 g", poivre: "6½ c.à.c", echalote: "78 g", beurre: "39 g", vinblanc: "65 ml" },
      { nb: 14, cremefraiche: "420 g", poivre: "7 c.à.c", echalote: "84 g", beurre: "42 g", vinblanc: "70 ml" },
      { nb: 15, cremefraiche: "450 g", poivre: "7½ c.à.c", echalote: "90 g", beurre: "45 g", vinblanc: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌶️", titre: "Poivre", detail: "Concasser grossièrement le poivre (mignonnette). ASTUCE : poivre fraîchement concassé = sauce bien plus parfumée.", badge: "⏱ 2 min" },
      { icone: "🧅", titre: "Déglacer", detail: "Suer l'échalote au beurre, ajouter le poivre, déglacer au cognac/vin blanc et flamber (facultatif).", badge: "⏱ 5 min" },
      { icone: "🥛", titre: "Crème", detail: "Ajouter la crème, CLÉ : laisser réduire à feu doux jusqu'à ce que la sauce nappe la cuillère.", badge: "⏱ 6 min" },
      { icone: "🥩", titre: "Servir", detail: "ASTUCE CHEF : récupérer les sucs de cuisson de la viande dans la sauce = goût décuplé. Sel en fin.", badge: null }
    ]
  },
  sauceburger: {
    cat: "sauces", pays: "usa",
    base: 6,
    temps: "5 min",
    niveau: "⭐ Facile",
    emoji: "🍔",
    description: "Sauce burger — la sauce 'spéciale' crémeuse et acidulée façon fast-food maison : mayo, ketchup, moutarde et cornichons. Indispensable dans un burger.",
    tableauSauceBurger: [
      { nb: 1, mayonnaise: "15 g", ketchup: "8 g", moutarde: "¼ c.à.c", cornichon: "6 g", oignon: "4 g", paprika: "1 pincée" },
      { nb: 2, mayonnaise: "30 g", ketchup: "16 g", moutarde: "½ c.à.c", cornichon: "12 g", oignon: "8 g", paprika: "1 pincée" },
      { nb: 3, mayonnaise: "45 g", ketchup: "24 g", moutarde: "1 c.à.c", cornichon: "18 g", oignon: "12 g", paprika: "1 pincée" },
      { nb: 4, mayonnaise: "60 g", ketchup: "32 g", moutarde: "1¼ c.à.c", cornichon: "24 g", oignon: "16 g", paprika: "1 pincée" },
      { nb: 5, mayonnaise: "75 g", ketchup: "40 g", moutarde: "1½ c.à.c", cornichon: "30 g", oignon: "20 g", paprika: "1 pincée" },
      { nb: 6, mayonnaise: "90 g", ketchup: "48 g", moutarde: "1¾ c.à.c", cornichon: "36 g", oignon: "24 g", paprika: "1 pincée" },
      { nb: 7, mayonnaise: "105 g", ketchup: "56 g", moutarde: "2 c.à.c", cornichon: "42 g", oignon: "28 g", paprika: "2 pincées" },
      { nb: 8, mayonnaise: "120 g", ketchup: "64 g", moutarde: "2½ c.à.c", cornichon: "48 g", oignon: "32 g", paprika: "2 pincées" },
      { nb: 9, mayonnaise: "135 g", ketchup: "72 g", moutarde: "2¾ c.à.c", cornichon: "54 g", oignon: "36 g", paprika: "2 pincées" },
      { nb: 10, mayonnaise: "150 g", ketchup: "80 g", moutarde: "3 c.à.c", cornichon: "60 g", oignon: "40 g", paprika: "2 pincées" },
      { nb: 11, mayonnaise: "165 g", ketchup: "88 g", moutarde: "3¼ c.à.c", cornichon: "66 g", oignon: "44 g", paprika: "2 pincées" },
      { nb: 12, mayonnaise: "180 g", ketchup: "96 g", moutarde: "3½ c.à.c", cornichon: "72 g", oignon: "48 g", paprika: "2 pincées" },
      { nb: 13, mayonnaise: "195 g", ketchup: "104 g", moutarde: "4 c.à.c", cornichon: "78 g", oignon: "52 g", paprika: "3 pincées" },
      { nb: 14, mayonnaise: "210 g", ketchup: "112 g", moutarde: "4¼ c.à.c", cornichon: "84 g", oignon: "56 g", paprika: "3 pincées" },
      { nb: 15, mayonnaise: "225 g", ketchup: "120 g", moutarde: "4½ c.à.c", cornichon: "90 g", oignon: "60 g", paprika: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔪", titre: "Hacher", detail: "Hacher TRÈS finement les cornichons et l'oignon.", badge: "⏱ 3 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger mayonnaise, ketchup, moutarde, cornichons et oignon.", badge: "⏱ 2 min" },
      { icone: "🍔", titre: "Assaisonner", detail: "SECRET : une pointe de paprika fumé, de vinaigre de cornichon et de sucre = LE goût 'sauce spéciale'. ASTUCE CHEF : meilleure après 1h au frais.", badge: null }
    ]
  },
  saucechampignon: {
    cat: "sauces", pays: "france",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🍄",
    description: "Sauce aux champignons — crémeuse et forestière : champignons poêlés, échalote et crème. Pour viandes, volailles, pâtes et escalopes.",
    tableauSauceChampignon: [
      { nb: 1, champignon: "40 g", cremefraiche: "25 g", echalote: "8 g", beurre: "4 g", vinblanc: "5 ml", persil: "1 g" },
      { nb: 2, champignon: "80 g", cremefraiche: "50 g", echalote: "16 g", beurre: "8 g", vinblanc: "10 ml", persil: "2 g" },
      { nb: 3, champignon: "120 g", cremefraiche: "75 g", echalote: "24 g", beurre: "12 g", vinblanc: "15 ml", persil: "3 g" },
      { nb: 4, champignon: "160 g", cremefraiche: "100 g", echalote: "32 g", beurre: "16 g", vinblanc: "20 ml", persil: "4 g" },
      { nb: 5, champignon: "200 g", cremefraiche: "125 g", echalote: "40 g", beurre: "20 g", vinblanc: "25 ml", persil: "5 g" },
      { nb: 6, champignon: "240 g", cremefraiche: "150 g", echalote: "48 g", beurre: "24 g", vinblanc: "30 ml", persil: "6 g" },
      { nb: 7, champignon: "280 g", cremefraiche: "175 g", echalote: "56 g", beurre: "28 g", vinblanc: "35 ml", persil: "7 g" },
      { nb: 8, champignon: "320 g", cremefraiche: "200 g", echalote: "64 g", beurre: "32 g", vinblanc: "40 ml", persil: "8 g" },
      { nb: 9, champignon: "360 g", cremefraiche: "225 g", echalote: "72 g", beurre: "36 g", vinblanc: "45 ml", persil: "9 g" },
      { nb: 10, champignon: "400 g", cremefraiche: "250 g", echalote: "80 g", beurre: "40 g", vinblanc: "50 ml", persil: "10 g" },
      { nb: 11, champignon: "440 g", cremefraiche: "275 g", echalote: "88 g", beurre: "44 g", vinblanc: "55 ml", persil: "11 g" },
      { nb: 12, champignon: "480 g", cremefraiche: "300 g", echalote: "96 g", beurre: "48 g", vinblanc: "60 ml", persil: "12 g" },
      { nb: 13, champignon: "520 g", cremefraiche: "325 g", echalote: "104 g", beurre: "52 g", vinblanc: "65 ml", persil: "13 g" },
      { nb: 14, champignon: "560 g", cremefraiche: "350 g", echalote: "112 g", beurre: "56 g", vinblanc: "70 ml", persil: "14 g" },
      { nb: 15, champignon: "600 g", cremefraiche: "375 g", echalote: "120 g", beurre: "60 g", vinblanc: "75 ml", persil: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍄", titre: "Poêler", detail: "Poêler les champignons émincés à feu VIF. CLÉ : feu vif pour qu'ils dorent au lieu de bouillir dans leur eau.", badge: "⏱ 6 min" },
      { icone: "🧅", titre: "Échalote", detail: "Ajouter l'échalote, déglacer au vin blanc et laisser évaporer.", badge: "⏱ 4 min" },
      { icone: "🥛", titre: "Crème", detail: "Ajouter la crème, laisser réduire jusqu'à une sauce nappante. SECRET : un peu de fond de veau corse la sauce.", badge: "⏱ 6 min" },
      { icone: "🌿", titre: "Finir", detail: "Sel, poivre, persil. ASTUCE CHEF : parfaite sur une escalope ou des tagliatelles.", badge: null }
    ]
  },
});
