// ============================================================
// recettes_glaces.js — Recettes de catégorie "glaces" (Glaces & Sorbets) — 20 recettes
// 👉 Pour AJOUTER une glace : place-la juste avant le  });  final.
// ============================================================
Object.assign(recettes, {

  glacevanille: {
    nom: "Glace Vanille",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:00:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace vanille maison onctueuse sur base de crème anglaise, parfumée à la gousse.",
    tableauGlaceVanille: [
      { nb: 1, lait: "23 ml", creme: "18 ml", jaunedoeuf: "1", sucre: "9 g", vanille: "1 g" },
      { nb: 2, lait: "45 ml", creme: "36 ml", jaunedoeuf: "1", sucre: "18 g", vanille: "1 g" },
      { nb: 3, lait: "68 ml", creme: "54 ml", jaunedoeuf: "1", sucre: "27 g", vanille: "1 g" },
      { nb: 4, lait: "90 ml", creme: "72 ml", jaunedoeuf: "2", sucre: "36 g", vanille: "2 g" },
      { nb: 5, lait: "113 ml", creme: "90 ml", jaunedoeuf: "2", sucre: "45 g", vanille: "2 g" },
      { nb: 6, lait: "135 ml", creme: "108 ml", jaunedoeuf: "3", sucre: "54 g", vanille: "3 g" },
      { nb: 7, lait: "158 ml", creme: "126 ml", jaunedoeuf: "3", sucre: "63 g", vanille: "3 g" },
      { nb: 8, lait: "180 ml", creme: "144 ml", jaunedoeuf: "4", sucre: "72 g", vanille: "4 g" },
      { nb: 9, lait: "203 ml", creme: "162 ml", jaunedoeuf: "4", sucre: "81 g", vanille: "4 g" },
      { nb: 10, lait: "225 ml", creme: "180 ml", jaunedoeuf: "5", sucre: "90 g", vanille: "5 g" },
      { nb: 11, lait: "248 ml", creme: "198 ml", jaunedoeuf: "5", sucre: "99 g", vanille: "5 g" },
      { nb: 12, lait: "270 ml", creme: "216 ml", jaunedoeuf: "5", sucre: "108 g", vanille: "5 g" },
      { nb: 13, lait: "293 ml", creme: "234 ml", jaunedoeuf: "6", sucre: "117 g", vanille: "6 g" },
      { nb: 14, lait: "315 ml", creme: "252 ml", jaunedoeuf: "6", sucre: "126 g", vanille: "6 g" },
      { nb: 15, lait: "338 ml", creme: "270 ml", jaunedoeuf: "7", sucre: "135 g", vanille: "7 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Chauffer le lait et la crème avec la gousse de vanille fendue.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter les jaunes avec le sucre jusqu'à blanchiment.", badge: null },
      { icone: "♨️", titre: "Crème anglaise", detail: "Verser le lait chaud sur les jaunes, cuire à feu doux sans bouillir. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir rapidement la crème puis réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner en sorbetière (ou méthode sans).", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Réserver au congélateur pour raffermir.", badge: "⏱ 1 h" }
    ]
  },
  glacechocolat: {
    nom: "Glace Chocolat",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:01:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍫",
    description: "Une glace au chocolat noir intense et crémeuse, sur base de crème anglaise.",
    tableauGlaceChocolat: [
      { nb: 1, lait: "19 ml", creme: "15 ml", chocolatnoir: "10 g", jaunedoeuf: "1", sucre: "6 g" },
      { nb: 2, lait: "38 ml", creme: "31 ml", chocolatnoir: "19 g", jaunedoeuf: "1", sucre: "12 g" },
      { nb: 3, lait: "58 ml", creme: "46 ml", chocolatnoir: "29 g", jaunedoeuf: "1", sucre: "17 g" },
      { nb: 4, lait: "77 ml", creme: "62 ml", chocolatnoir: "38 g", jaunedoeuf: "2", sucre: "23 g" },
      { nb: 5, lait: "96 ml", creme: "77 ml", chocolatnoir: "48 g", jaunedoeuf: "2", sucre: "29 g" },
      { nb: 6, lait: "115 ml", creme: "92 ml", chocolatnoir: "58 g", jaunedoeuf: "2", sucre: "35 g" },
      { nb: 7, lait: "135 ml", creme: "108 ml", chocolatnoir: "67 g", jaunedoeuf: "3", sucre: "40 g" },
      { nb: 8, lait: "154 ml", creme: "123 ml", chocolatnoir: "77 g", jaunedoeuf: "3", sucre: "46 g" },
      { nb: 9, lait: "173 ml", creme: "138 ml", chocolatnoir: "87 g", jaunedoeuf: "3", sucre: "52 g" },
      { nb: 10, lait: "192 ml", creme: "154 ml", chocolatnoir: "96 g", jaunedoeuf: "4", sucre: "58 g" },
      { nb: 11, lait: "212 ml", creme: "169 ml", chocolatnoir: "106 g", jaunedoeuf: "4", sucre: "63 g" },
      { nb: 12, lait: "231 ml", creme: "185 ml", chocolatnoir: "115 g", jaunedoeuf: "5", sucre: "69 g" },
      { nb: 13, lait: "250 ml", creme: "200 ml", chocolatnoir: "125 g", jaunedoeuf: "5", sucre: "75 g" },
      { nb: 14, lait: "269 ml", creme: "215 ml", chocolatnoir: "135 g", jaunedoeuf: "5", sucre: "81 g" },
      { nb: 15, lait: "288 ml", creme: "231 ml", chocolatnoir: "144 g", jaunedoeuf: "6", sucre: "87 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux. ASTUCE CHEF : pas de sorbetière ? Verse dans un bac, place au congélateur et fouette vigoureusement toutes les 30-40 min (3-4 fois) pour casser les cristaux : la texture restera bien crémeuse.", badge: "⏱ 8 min" },
      { icone: "🍫", titre: "Chocolat", detail: "Verser sur le chocolat haché et lisser.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer la préparation.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner puis raffermir au congélateur.", badge: "⏱ 30 min" }
    ]
  },
  glacepistache: {
    nom: "Glace Pistache",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:02:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace à la pistache, douce et parfumée, à la couleur naturelle délicate.",
    tableauGlacePistache: [
      { nb: 1, lait: "19 ml", creme: "15 ml", pistache: "9 g", jaunedoeuf: "1", sucre: "7 g" },
      { nb: 2, lait: "38 ml", creme: "30 ml", pistache: "19 g", jaunedoeuf: "1", sucre: "14 g" },
      { nb: 3, lait: "56 ml", creme: "45 ml", pistache: "28 g", jaunedoeuf: "1", sucre: "20 g" },
      { nb: 4, lait: "75 ml", creme: "60 ml", pistache: "38 g", jaunedoeuf: "2", sucre: "27 g" },
      { nb: 5, lait: "94 ml", creme: "75 ml", pistache: "47 g", jaunedoeuf: "2", sucre: "34 g" },
      { nb: 6, lait: "113 ml", creme: "90 ml", pistache: "56 g", jaunedoeuf: "2", sucre: "41 g" },
      { nb: 7, lait: "132 ml", creme: "105 ml", pistache: "66 g", jaunedoeuf: "3", sucre: "47 g" },
      { nb: 8, lait: "150 ml", creme: "120 ml", pistache: "75 g", jaunedoeuf: "3", sucre: "54 g" },
      { nb: 9, lait: "169 ml", creme: "135 ml", pistache: "85 g", jaunedoeuf: "3", sucre: "61 g" },
      { nb: 10, lait: "188 ml", creme: "150 ml", pistache: "94 g", jaunedoeuf: "4", sucre: "68 g" },
      { nb: 11, lait: "207 ml", creme: "165 ml", pistache: "103 g", jaunedoeuf: "4", sucre: "74 g" },
      { nb: 12, lait: "226 ml", creme: "180 ml", pistache: "113 g", jaunedoeuf: "5", sucre: "81 g" },
      { nb: 13, lait: "244 ml", creme: "195 ml", pistache: "122 g", jaunedoeuf: "5", sucre: "88 g" },
      { nb: 14, lait: "263 ml", creme: "211 ml", pistache: "132 g", jaunedoeuf: "5", sucre: "95 g" },
      { nb: 15, lait: "282 ml", creme: "226 ml", pistache: "141 g", jaunedoeuf: "6", sucre: "102 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Pâte", detail: "Mixer les pistaches en pâte fine. ASTUCE CHEF : utilise des pistaches émondées non salées et mixe-les en pâte, c'est plus parfumé et naturel qu'un arôme.", badge: null },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème avec la pâte de pistache.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise sans bouillir.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacecafe: {
    nom: "Glace Café",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:03:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "☕",
    description: "Une glace au café corsée et veloutée, idéale en affogato ou en fin de repas.",
    tableauGlaceCafe: [
      { nb: 1, lait: "22 ml", creme: "18 ml", cafe: "2 g", jaunedoeuf: "1", sucre: "8 g" },
      { nb: 2, lait: "44 ml", creme: "35 ml", cafe: "4 g", jaunedoeuf: "1", sucre: "16 g" },
      { nb: 3, lait: "66 ml", creme: "53 ml", cafe: "7 g", jaunedoeuf: "1", sucre: "24 g" },
      { nb: 4, lait: "88 ml", creme: "71 ml", cafe: "9 g", jaunedoeuf: "2", sucre: "32 g" },
      { nb: 5, lait: "111 ml", creme: "88 ml", cafe: "11 g", jaunedoeuf: "2", sucre: "40 g" },
      { nb: 6, lait: "133 ml", creme: "106 ml", cafe: "13 g", jaunedoeuf: "3", sucre: "48 g" },
      { nb: 7, lait: "155 ml", creme: "124 ml", cafe: "15 g", jaunedoeuf: "3", sucre: "56 g" },
      { nb: 8, lait: "177 ml", creme: "142 ml", cafe: "18 g", jaunedoeuf: "4", sucre: "64 g" },
      { nb: 9, lait: "199 ml", creme: "159 ml", cafe: "20 g", jaunedoeuf: "4", sucre: "72 g" },
      { nb: 10, lait: "221 ml", creme: "177 ml", cafe: "22 g", jaunedoeuf: "4", sucre: "80 g" },
      { nb: 11, lait: "243 ml", creme: "195 ml", cafe: "24 g", jaunedoeuf: "5", sucre: "88 g" },
      { nb: 12, lait: "265 ml", creme: "212 ml", cafe: "27 g", jaunedoeuf: "5", sucre: "96 g" },
      { nb: 13, lait: "288 ml", creme: "230 ml", cafe: "29 g", jaunedoeuf: "6", sucre: "104 g" },
      { nb: 14, lait: "310 ml", creme: "248 ml", cafe: "31 g", jaunedoeuf: "6", sucre: "112 g" },
      { nb: 15, lait: "332 ml", creme: "265 ml", cafe: "33 g", jaunedoeuf: "7", sucre: "119 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "☕", titre: "Infuser", detail: "Infuser le café fort dans le lait et la crème chauds. ASTUCE CHEF : un expresso serré ou du café soluble de qualité donne plus de profondeur qu'un café allongé.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaunes et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise à feu doux.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍦", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacecaramel: {
    nom: "Glace Caramel Beurre Salé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:04:00",
    base: 1,
    temps: "35 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "La glace au caramel au beurre salé, gourmande et fondante, aux notes ambrées.",
    tableauGlaceCaramel: [
      { nb: 1, sucre: "10 g", beurre: "3 g", lait: "20 ml", creme: "16 ml", jaunedoeuf: "1", sel: "1 g" },
      { nb: 2, sucre: "20 g", beurre: "6 g", lait: "41 ml", creme: "32 ml", jaunedoeuf: "1", sel: "1 g" },
      { nb: 3, sucre: "30 g", beurre: "10 g", lait: "61 ml", creme: "49 ml", jaunedoeuf: "1", sel: "1 g" },
      { nb: 4, sucre: "41 g", beurre: "13 g", lait: "81 ml", creme: "65 ml", jaunedoeuf: "2", sel: "1 g" },
      { nb: 5, sucre: "51 g", beurre: "16 g", lait: "101 ml", creme: "81 ml", jaunedoeuf: "2", sel: "1 g" },
      { nb: 6, sucre: "61 g", beurre: "19 g", lait: "122 ml", creme: "97 ml", jaunedoeuf: "2", sel: "1 g" },
      { nb: 7, sucre: "71 g", beurre: "23 g", lait: "142 ml", creme: "114 ml", jaunedoeuf: "3", sel: "1 g" },
      { nb: 8, sucre: "81 g", beurre: "26 g", lait: "162 ml", creme: "130 ml", jaunedoeuf: "3", sel: "1 g" },
      { nb: 9, sucre: "91 g", beurre: "29 g", lait: "183 ml", creme: "146 ml", jaunedoeuf: "4", sel: "1 g" },
      { nb: 10, sucre: "101 g", beurre: "32 g", lait: "203 ml", creme: "162 ml", jaunedoeuf: "4", sel: "1 g" },
      { nb: 11, sucre: "112 g", beurre: "36 g", lait: "223 ml", creme: "178 ml", jaunedoeuf: "4", sel: "1 g" },
      { nb: 12, sucre: "122 g", beurre: "39 g", lait: "243 ml", creme: "195 ml", jaunedoeuf: "5", sel: "1 g" },
      { nb: 13, sucre: "132 g", beurre: "42 g", lait: "264 ml", creme: "211 ml", jaunedoeuf: "5", sel: "1 g" },
      { nb: 14, sucre: "142 g", beurre: "45 g", lait: "284 ml", creme: "227 ml", jaunedoeuf: "6", sel: "1 g" },
      { nb: 15, sucre: "152 g", beurre: "49 g", lait: "304 ml", creme: "243 ml", jaunedoeuf: "6", sel: "2 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Caramel", detail: "Réaliser un caramel à sec puis décuire au beurre salé. ASTUCE CHEF : pousse le caramel jusqu'à une couleur ambrée foncée (sans brûler) : c'est l'amertume légère qui fait le caractère du caramel beurre salé.", badge: "⏱ 6 min" },
      { icone: "🥛", titre: "Détendre", detail: "Verser lait et crème chauds sur le caramel.", badge: null },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter le jaune.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise caramel.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner et raffermir.", badge: "⏱ 30 min" }
    ]
  },
  glacestracciatella: {
    nom: "Glace Stracciatella",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:05:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "La glace italienne au lait parsemée d'éclats de chocolat croquants.",
    tableauGlaceStracciatella: [
      { nb: 1, lait: "20 ml", creme: "16 ml", sucre: "7 g", jaunedoeuf: "1", chocolatnoir: "6 g" },
      { nb: 2, lait: "41 ml", creme: "33 ml", sucre: "15 g", jaunedoeuf: "1", chocolatnoir: "12 g" },
      { nb: 3, lait: "61 ml", creme: "49 ml", sucre: "22 g", jaunedoeuf: "1", chocolatnoir: "18 g" },
      { nb: 4, lait: "81 ml", creme: "65 ml", sucre: "29 g", jaunedoeuf: "2", chocolatnoir: "24 g" },
      { nb: 5, lait: "102 ml", creme: "81 ml", sucre: "37 g", jaunedoeuf: "2", chocolatnoir: "30 g" },
      { nb: 6, lait: "122 ml", creme: "98 ml", sucre: "44 g", jaunedoeuf: "2", chocolatnoir: "37 g" },
      { nb: 7, lait: "142 ml", creme: "114 ml", sucre: "51 g", jaunedoeuf: "3", chocolatnoir: "43 g" },
      { nb: 8, lait: "163 ml", creme: "130 ml", sucre: "59 g", jaunedoeuf: "3", chocolatnoir: "49 g" },
      { nb: 9, lait: "183 ml", creme: "146 ml", sucre: "66 g", jaunedoeuf: "4", chocolatnoir: "55 g" },
      { nb: 10, lait: "203 ml", creme: "163 ml", sucre: "73 g", jaunedoeuf: "4", chocolatnoir: "61 g" },
      { nb: 11, lait: "224 ml", creme: "179 ml", sucre: "80 g", jaunedoeuf: "4", chocolatnoir: "67 g" },
      { nb: 12, lait: "244 ml", creme: "195 ml", sucre: "88 g", jaunedoeuf: "5", chocolatnoir: "73 g" },
      { nb: 13, lait: "264 ml", creme: "211 ml", sucre: "95 g", jaunedoeuf: "5", chocolatnoir: "79 g" },
      { nb: 14, lait: "285 ml", creme: "228 ml", sucre: "102 g", jaunedoeuf: "6", chocolatnoir: "85 g" },
      { nb: 15, lait: "305 ml", creme: "244 ml", sucre: "110 g", jaunedoeuf: "6", chocolatnoir: "91 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer puis turbiner.", badge: "⏱ 2 h" },
      { icone: "🍫", titre: "Éclats", detail: "En fin de turbinage, verser le chocolat fondu en filet. ASTUCE CHEF : verse le chocolat fondu en mince filet sur la glace en mouvement : il fige instantanément en fins éclats croquants.", badge: null },
      { icone: "🌀", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  glacementhe: {
    nom: "Glace Menthe-Chocolat",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:06:00",
    base: 1,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🌿",
    description: "La glace menthe fraîche aux pépites de chocolat, rafraîchissante et gourmande.",
    tableauGlaceMenthe: [
      { nb: 1, lait: "19 ml", creme: "16 ml", menthe: "2 g", sucre: "7 g", jaunedoeuf: "1", chocolatnoir: "6 g" },
      { nb: 2, lait: "39 ml", creme: "31 ml", menthe: "5 g", sucre: "14 g", jaunedoeuf: "1", chocolatnoir: "12 g" },
      { nb: 3, lait: "58 ml", creme: "47 ml", menthe: "7 g", sucre: "21 g", jaunedoeuf: "1", chocolatnoir: "17 g" },
      { nb: 4, lait: "78 ml", creme: "62 ml", menthe: "9 g", sucre: "28 g", jaunedoeuf: "2", chocolatnoir: "23 g" },
      { nb: 5, lait: "97 ml", creme: "78 ml", menthe: "12 g", sucre: "35 g", jaunedoeuf: "2", chocolatnoir: "29 g" },
      { nb: 6, lait: "116 ml", creme: "93 ml", menthe: "14 g", sucre: "42 g", jaunedoeuf: "2", chocolatnoir: "35 g" },
      { nb: 7, lait: "136 ml", creme: "109 ml", menthe: "16 g", sucre: "49 g", jaunedoeuf: "3", chocolatnoir: "41 g" },
      { nb: 8, lait: "155 ml", creme: "124 ml", menthe: "19 g", sucre: "56 g", jaunedoeuf: "3", chocolatnoir: "47 g" },
      { nb: 9, lait: "174 ml", creme: "140 ml", menthe: "21 g", sucre: "63 g", jaunedoeuf: "3", chocolatnoir: "52 g" },
      { nb: 10, lait: "194 ml", creme: "155 ml", menthe: "23 g", sucre: "70 g", jaunedoeuf: "4", chocolatnoir: "58 g" },
      { nb: 11, lait: "213 ml", creme: "171 ml", menthe: "26 g", sucre: "77 g", jaunedoeuf: "4", chocolatnoir: "64 g" },
      { nb: 12, lait: "233 ml", creme: "186 ml", menthe: "28 g", sucre: "84 g", jaunedoeuf: "5", chocolatnoir: "70 g" },
      { nb: 13, lait: "252 ml", creme: "202 ml", menthe: "30 g", sucre: "91 g", jaunedoeuf: "5", chocolatnoir: "76 g" },
      { nb: 14, lait: "271 ml", creme: "217 ml", menthe: "33 g", sucre: "98 g", jaunedoeuf: "5", chocolatnoir: "81 g" },
      { nb: 15, lait: "291 ml", creme: "233 ml", menthe: "35 g", sucre: "105 g", jaunedoeuf: "6", chocolatnoir: "87 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌿", titre: "Infuser", detail: "Infuser la menthe fraîche dans le lait chaud, puis filtrer. ASTUCE CHEF : infuse de la vraie menthe fraîche puis filtre : le goût est net et naturel, loin du sirop de menthe industriel.", badge: "⏱ 15 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise mentholée.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer.", badge: "⏱ 2 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 30 min" },
      { icone: "🍫", titre: "Pépites", detail: "Ajouter les pépites de chocolat en fin de turbinage.", badge: null }
    ]
  },
  glacerhumraisin: {
    nom: "Glace Rhum-Raisin",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:07:00",
    base: 1,
    temps: "30 min + macération",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace rhum-raisin, classique des grands, aux raisins moelleux gorgés de rhum.",
    tableauGlaceRhumRaisin: [
      { nb: 1, lait: "18 ml", creme: "14 ml", raisinssecs: "7 g", rhum: "4 ml", sucre: "7 g", jaunedoeuf: "1" },
      { nb: 2, lait: "36 ml", creme: "29 ml", raisinssecs: "14 g", rhum: "7 ml", sucre: "13 g", jaunedoeuf: "1" },
      { nb: 3, lait: "54 ml", creme: "43 ml", raisinssecs: "22 g", rhum: "11 ml", sucre: "20 g", jaunedoeuf: "1" },
      { nb: 4, lait: "72 ml", creme: "58 ml", raisinssecs: "29 g", rhum: "14 ml", sucre: "26 g", jaunedoeuf: "1" },
      { nb: 5, lait: "91 ml", creme: "72 ml", raisinssecs: "36 g", rhum: "18 ml", sucre: "33 g", jaunedoeuf: "2" },
      { nb: 6, lait: "109 ml", creme: "87 ml", raisinssecs: "43 g", rhum: "22 ml", sucre: "39 g", jaunedoeuf: "2" },
      { nb: 7, lait: "127 ml", creme: "101 ml", raisinssecs: "51 g", rhum: "25 ml", sucre: "46 g", jaunedoeuf: "3" },
      { nb: 8, lait: "145 ml", creme: "116 ml", raisinssecs: "58 g", rhum: "29 ml", sucre: "52 g", jaunedoeuf: "3" },
      { nb: 9, lait: "163 ml", creme: "130 ml", raisinssecs: "65 g", rhum: "33 ml", sucre: "59 g", jaunedoeuf: "3" },
      { nb: 10, lait: "181 ml", creme: "145 ml", raisinssecs: "72 g", rhum: "36 ml", sucre: "65 g", jaunedoeuf: "4" },
      { nb: 11, lait: "199 ml", creme: "159 ml", raisinssecs: "80 g", rhum: "40 ml", sucre: "72 g", jaunedoeuf: "4" },
      { nb: 12, lait: "217 ml", creme: "174 ml", raisinssecs: "87 g", rhum: "43 ml", sucre: "78 g", jaunedoeuf: "4" },
      { nb: 13, lait: "236 ml", creme: "188 ml", raisinssecs: "94 g", rhum: "47 ml", sucre: "85 g", jaunedoeuf: "5" },
      { nb: 14, lait: "254 ml", creme: "203 ml", raisinssecs: "101 g", rhum: "51 ml", sucre: "91 g", jaunedoeuf: "5" },
      { nb: 15, lait: "272 ml", creme: "217 ml", raisinssecs: "109 g", rhum: "54 ml", sucre: "98 g", jaunedoeuf: "5" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍇", titre: "Macérer", detail: "Faire gonfler les raisins secs dans le rhum tiède. ASTUCE CHEF : laisse macérer les raisins plusieurs heures (voire une nuit) : moelleux et parfumés, ils ne durciront pas au congélateur.", badge: "⏱ 2 h" },
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer lait et crème.", badge: "⏱ 4 min" },
      { icone: "🥚", titre: "Blanchir", detail: "Fouetter jaune et sucre.", badge: null },
      { icone: "♨️", titre: "Anglaise", detail: "Cuire la crème anglaise.", badge: "⏱ 8 min" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner la base refroidie.", badge: "⏱ 30 min" },
      { icone: "🍇", titre: "Raisins", detail: "Incorporer les raisins égouttés en fin de turbinage.", badge: null }
    ]
  },
  sorbetcitron: {
    nom: "Sorbet Citron",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:08:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍋",
    description: "Le sorbet citron vif et désaltérant, parfait nettoyeur de palais.",
    tableauSorbetCitron: [
      { nb: 1, citron: "13 ml", eau: "26 ml", sucre: "11 g" },
      { nb: 2, citron: "26 ml", eau: "52 ml", sucre: "23 g" },
      { nb: 3, citron: "39 ml", eau: "77 ml", sucre: "34 g" },
      { nb: 4, citron: "52 ml", eau: "103 ml", sucre: "45 g" },
      { nb: 5, citron: "65 ml", eau: "129 ml", sucre: "56 g" },
      { nb: 6, citron: "77 ml", eau: "155 ml", sucre: "68 g" },
      { nb: 7, citron: "90 ml", eau: "181 ml", sucre: "79 g" },
      { nb: 8, citron: "103 ml", eau: "206 ml", sucre: "90 g" },
      { nb: 9, citron: "116 ml", eau: "232 ml", sucre: "102 g" },
      { nb: 10, citron: "129 ml", eau: "258 ml", sucre: "113 g" },
      { nb: 11, citron: "142 ml", eau: "284 ml", sucre: "124 g" },
      { nb: 12, citron: "155 ml", eau: "310 ml", sucre: "135 g" },
      { nb: 13, citron: "168 ml", eau: "335 ml", sucre: "147 g" },
      { nb: 14, citron: "181 ml", eau: "361 ml", sucre: "158 g" },
      { nb: 15, citron: "194 ml", eau: "387 ml", sucre: "169 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Porter l'eau et le sucre à frémissement pour dissoudre.", badge: "⏱ 4 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Laisser refroidir complètement le sirop. ASTUCE CHEF : un sirop bien froid avant d'ajouter le jus préserve la fraîcheur et la vitamine C du citron.", badge: null },
      { icone: "🍋", titre: "Presser", detail: "Presser les citrons et filtrer le jus.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger sirop froid et jus de citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à texture sorbet.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetframboise: {
    nom: "Sorbet Framboise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:09:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet framboise intensément fruité, à la jolie couleur rubis.",
    tableauSorbetFramboise: [
      { nb: 1, framboise: "27 g", eau: "12 ml", sucre: "9 g", citron: "2 ml" },
      { nb: 2, framboise: "55 g", eau: "24 ml", sucre: "18 g", citron: "3 ml" },
      { nb: 3, framboise: "82 g", eau: "36 ml", sucre: "27 g", citron: "5 ml" },
      { nb: 4, framboise: "109 g", eau: "48 ml", sucre: "36 g", citron: "6 ml" },
      { nb: 5, framboise: "136 g", eau: "61 ml", sucre: "45 g", citron: "8 ml" },
      { nb: 6, framboise: "164 g", eau: "73 ml", sucre: "55 g", citron: "9 ml" },
      { nb: 7, framboise: "191 g", eau: "85 ml", sucre: "64 g", citron: "11 ml" },
      { nb: 8, framboise: "218 g", eau: "97 ml", sucre: "73 g", citron: "12 ml" },
      { nb: 9, framboise: "245 g", eau: "109 ml", sucre: "82 g", citron: "14 ml" },
      { nb: 10, framboise: "273 g", eau: "121 ml", sucre: "91 g", citron: "15 ml" },
      { nb: 11, framboise: "300 g", eau: "133 ml", sucre: "100 g", citron: "17 ml" },
      { nb: 12, framboise: "327 g", eau: "145 ml", sucre: "109 g", citron: "18 ml" },
      { nb: 13, framboise: "355 g", eau: "158 ml", sucre: "118 g", citron: "20 ml" },
      { nb: 14, framboise: "382 g", eau: "170 ml", sucre: "127 g", citron: "21 ml" },
      { nb: 15, framboise: "409 g", eau: "182 ml", sucre: "136 g", citron: "23 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre et le refroidir.", badge: "⏱ 5 min" },
      { icone: "🍓", titre: "Coulis", detail: "Mixer les framboises en purée.", badge: null },
      { icone: "🫗", titre: "Tamiser", detail: "Passer la purée au tamis pour retirer les pépins. ASTUCE CHEF : tamise le coulis pour un sorbet tout lisse : sans les pépins, la texture en bouche est bien plus agréable.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetmangue: {
    nom: "Sorbet Mangue",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:10:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🥭",
    description: "Le sorbet mangue exotique et velouté, ensoleillé à souhait.",
    tableauSorbetMangue: [
      { nb: 1, mangue: "31 g", eau: "9 ml", sucre: "8 g", citronvert: "2 ml" },
      { nb: 2, mangue: "63 g", eau: "19 ml", sucre: "16 g", citronvert: "3 ml" },
      { nb: 3, mangue: "94 g", eau: "28 ml", sucre: "23 g", citronvert: "5 ml" },
      { nb: 4, mangue: "125 g", eau: "38 ml", sucre: "31 g", citronvert: "6 ml" },
      { nb: 5, mangue: "156 g", eau: "47 ml", sucre: "39 g", citronvert: "8 ml" },
      { nb: 6, mangue: "188 g", eau: "56 ml", sucre: "47 g", citronvert: "9 ml" },
      { nb: 7, mangue: "219 g", eau: "66 ml", sucre: "55 g", citronvert: "11 ml" },
      { nb: 8, mangue: "250 g", eau: "75 ml", sucre: "63 g", citronvert: "13 ml" },
      { nb: 9, mangue: "281 g", eau: "84 ml", sucre: "70 g", citronvert: "14 ml" },
      { nb: 10, mangue: "313 g", eau: "94 ml", sucre: "78 g", citronvert: "16 ml" },
      { nb: 11, mangue: "344 g", eau: "103 ml", sucre: "86 g", citronvert: "17 ml" },
      { nb: 12, mangue: "375 g", eau: "113 ml", sucre: "94 g", citronvert: "19 ml" },
      { nb: 13, mangue: "406 g", eau: "122 ml", sucre: "102 g", citronvert: "20 ml" },
      { nb: 14, mangue: "438 g", eau: "131 ml", sucre: "109 g", citronvert: "22 ml" },
      { nb: 15, mangue: "469 g", eau: "141 ml", sucre: "117 g", citronvert: "23 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥭", titre: "Purée", detail: "Mixer la chair de mangue bien mûre. ASTUCE CHEF : choisis des mangues très mûres et parfumées : plus le fruit est sucré, moins tu ajoutes de sucre.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger et le refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron vert.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner jusqu'à prise.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser à la spatule.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpassion: {
    nom: "Sorbet Fruit de la Passion",
    cat: "glaces",
    pays: "monde",
    dateAjout: "2026-06-08T21:11:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍧",
    description: "Le sorbet fruit de la passion, acidulé et parfumé, d'une fraîcheur tropicale.",
    tableauSorbetPassion: [
      { nb: 1, fruitpassion: "22 g", eau: "16 ml", sucre: "11 g", citron: "1 ml" },
      { nb: 2, fruitpassion: "44 g", eau: "32 ml", sucre: "22 g", citron: "2 ml" },
      { nb: 3, fruitpassion: "66 g", eau: "47 ml", sucre: "33 g", citron: "3 ml" },
      { nb: 4, fruitpassion: "89 g", eau: "63 ml", sucre: "44 g", citron: "4 ml" },
      { nb: 5, fruitpassion: "111 g", eau: "79 ml", sucre: "55 g", citron: "5 ml" },
      { nb: 6, fruitpassion: "133 g", eau: "95 ml", sucre: "66 g", citron: "6 ml" },
      { nb: 7, fruitpassion: "155 g", eau: "111 ml", sucre: "78 g", citron: "7 ml" },
      { nb: 8, fruitpassion: "177 g", eau: "127 ml", sucre: "89 g", citron: "8 ml" },
      { nb: 9, fruitpassion: "199 g", eau: "142 ml", sucre: "100 g", citron: "9 ml" },
      { nb: 10, fruitpassion: "222 g", eau: "158 ml", sucre: "111 g", citron: "9 ml" },
      { nb: 11, fruitpassion: "244 g", eau: "174 ml", sucre: "122 g", citron: "10 ml" },
      { nb: 12, fruitpassion: "266 g", eau: "190 ml", sucre: "133 g", citron: "11 ml" },
      { nb: 13, fruitpassion: "288 g", eau: "206 ml", sucre: "144 g", citron: "12 ml" },
      { nb: 14, fruitpassion: "310 g", eau: "222 ml", sucre: "155 g", citron: "13 ml" },
      { nb: 15, fruitpassion: "332 g", eau: "237 ml", sucre: "166 g", citron: "14 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop eau-sucre, refroidir.", badge: "⏱ 5 min" },
      { icone: "💛", titre: "Pulpe", detail: "Récupérer la pulpe des fruits de la passion.", badge: null },
      { icone: "🫗", titre: "Filtrer", detail: "Filtrer une partie de la pulpe pour retirer des graines. ASTUCE CHEF : garde quelques graines pour le croquant et la couleur, mais filtre le reste pour ne pas avoir un sorbet trop granuleux.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger pulpe, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Raffermir au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetpoire: {
    nom: "Sorbet Poire",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:12:00",
    base: 1,
    temps: "20 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍐",
    description: "Le sorbet poire tout en douceur, délicat et fondant.",
    tableauSorbetPoire: [
      { nb: 1, poire: "31 g", eau: "9 ml", sucre: "8 g", citron: "2 ml" },
      { nb: 2, poire: "63 g", eau: "19 ml", sucre: "16 g", citron: "3 ml" },
      { nb: 3, poire: "94 g", eau: "28 ml", sucre: "23 g", citron: "5 ml" },
      { nb: 4, poire: "125 g", eau: "38 ml", sucre: "31 g", citron: "6 ml" },
      { nb: 5, poire: "156 g", eau: "47 ml", sucre: "39 g", citron: "8 ml" },
      { nb: 6, poire: "188 g", eau: "56 ml", sucre: "47 g", citron: "9 ml" },
      { nb: 7, poire: "219 g", eau: "66 ml", sucre: "55 g", citron: "11 ml" },
      { nb: 8, poire: "250 g", eau: "75 ml", sucre: "63 g", citron: "13 ml" },
      { nb: 9, poire: "281 g", eau: "84 ml", sucre: "70 g", citron: "14 ml" },
      { nb: 10, poire: "313 g", eau: "94 ml", sucre: "78 g", citron: "16 ml" },
      { nb: 11, poire: "344 g", eau: "103 ml", sucre: "86 g", citron: "17 ml" },
      { nb: 12, poire: "375 g", eau: "113 ml", sucre: "94 g", citron: "19 ml" },
      { nb: 13, poire: "406 g", eau: "122 ml", sucre: "102 g", citron: "20 ml" },
      { nb: 14, poire: "438 g", eau: "131 ml", sucre: "109 g", citron: "22 ml" },
      { nb: 15, poire: "469 g", eau: "141 ml", sucre: "117 g", citron: "23 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍐", titre: "Pocher", detail: "Pocher les poires épluchées dans l'eau sucrée.", badge: "⏱ 10 min" },
      { icone: "🌀", titre: "Mixer", detail: "Mixer les poires avec un peu de sirop.", badge: null },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le citron pour éviter le brunissement. ASTUCE CHEF : le jus de citron empêche la purée de poire de brunir et relève sa douceur un peu fade.", badge: null },
      { icone: "❄️", titre: "Refroidir", detail: "Refroidir complètement.", badge: "⏱ 1 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  sorbetfraise: {
    nom: "Sorbet Fraise",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:13:00",
    base: 1,
    temps: "15 min + turbinage",
    niveau: "⭐ Facile",
    emoji: "🍓",
    description: "Le sorbet fraise gourmand, intense en fruit, idéal en été.",
    tableauSorbetFraise: [
      { nb: 1, fraise: "31 g", eau: "9 ml", sucre: "9 g", citron: "2 ml" },
      { nb: 2, fraise: "61 g", eau: "18 ml", sucre: "17 g", citron: "3 ml" },
      { nb: 3, fraise: "92 g", eau: "28 ml", sucre: "26 g", citron: "5 ml" },
      { nb: 4, fraise: "123 g", eau: "37 ml", sucre: "34 g", citron: "6 ml" },
      { nb: 5, fraise: "153 g", eau: "46 ml", sucre: "43 g", citron: "8 ml" },
      { nb: 6, fraise: "184 g", eau: "55 ml", sucre: "52 g", citron: "9 ml" },
      { nb: 7, fraise: "215 g", eau: "64 ml", sucre: "60 g", citron: "11 ml" },
      { nb: 8, fraise: "245 g", eau: "74 ml", sucre: "69 g", citron: "12 ml" },
      { nb: 9, fraise: "276 g", eau: "83 ml", sucre: "77 g", citron: "14 ml" },
      { nb: 10, fraise: "307 g", eau: "92 ml", sucre: "86 g", citron: "15 ml" },
      { nb: 11, fraise: "337 g", eau: "101 ml", sucre: "94 g", citron: "17 ml" },
      { nb: 12, fraise: "368 g", eau: "110 ml", sucre: "103 g", citron: "18 ml" },
      { nb: 13, fraise: "399 g", eau: "120 ml", sucre: "112 g", citron: "20 ml" },
      { nb: 14, fraise: "429 g", eau: "129 ml", sucre: "120 g", citron: "21 ml" },
      { nb: 15, fraise: "460 g", eau: "138 ml", sucre: "129 g", citron: "23 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍓", titre: "Purée", detail: "Mixer les fraises en purée. ASTUCE CHEF : équeute et mixe les fraises crues (sans les cuire) pour garder le goût vif et la couleur éclatante du fruit frais.", badge: null },
      { icone: "🍯", titre: "Sirop", detail: "Préparer un sirop léger, refroidir.", badge: "⏱ 4 min" },
      { icone: "🥣", titre: "Mélanger", detail: "Mélanger purée, sirop et citron.", badge: null },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Lisser", detail: "Lisser et goûter.", badge: null },
      { icone: "❄️", titre: "Prendre", detail: "Réserver au congélateur.", badge: "⏱ 1 h" }
    ]
  },
  vacheringlace: {
    liees: ["glacevanille"],
    nom: "Vacherin Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:14:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍰",
    description: "Le vacherin glacé festif : meringue, crème glacée et coulis de fruits rouges.",
    tableauVacheringGlace: [
      { nb: 1, meringue: "30 g", creme: "60 ml", sucre: "18 g", framboise: "40 g", vanille: "1 g" },
      { nb: 2, meringue: "60 g", creme: "120 ml", sucre: "36 g", framboise: "80 g", vanille: "2 g" },
      { nb: 3, meringue: "90 g", creme: "180 ml", sucre: "54 g", framboise: "120 g", vanille: "3 g" },
      { nb: 4, meringue: "120 g", creme: "240 ml", sucre: "72 g", framboise: "160 g", vanille: "4 g" },
      { nb: 5, meringue: "150 g", creme: "300 ml", sucre: "90 g", framboise: "200 g", vanille: "5 g" },
      { nb: 6, meringue: "180 g", creme: "360 ml", sucre: "108 g", framboise: "240 g", vanille: "6 g" },
      { nb: 7, meringue: "210 g", creme: "420 ml", sucre: "126 g", framboise: "280 g", vanille: "7 g" },
      { nb: 8, meringue: "240 g", creme: "480 ml", sucre: "144 g", framboise: "320 g", vanille: "8 g" },
      { nb: 9, meringue: "270 g", creme: "540 ml", sucre: "162 g", framboise: "360 g", vanille: "9 g" },
      { nb: 10, meringue: "300 g", creme: "600 ml", sucre: "180 g", framboise: "400 g", vanille: "10 g" },
      { nb: 11, meringue: "330 g", creme: "660 ml", sucre: "198 g", framboise: "440 g", vanille: "11 g" },
      { nb: 12, meringue: "360 g", creme: "720 ml", sucre: "216 g", framboise: "480 g", vanille: "12 g" },
      { nb: 13, meringue: "390 g", creme: "780 ml", sucre: "234 g", framboise: "520 g", vanille: "13 g" },
      { nb: 14, meringue: "420 g", creme: "840 ml", sucre: "252 g", framboise: "560 g", vanille: "14 g" },
      { nb: 15, meringue: "450 g", creme: "900 ml", sucre: "270 g", framboise: "600 g", vanille: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly avec un peu de sucre.", badge: null },
      { icone: "🍦", titre: "Glace", detail: "Préparer (ou utiliser) une glace vanille.", badge: null },
      { icone: "🟤", titre: "Meringue", detail: "Émietter ou disposer des meringues. ASTUCE CHEF : monte le vacherin et remets-le au congélateur entre chaque couche pour qu'il garde une forme nette.", badge: null },
      { icone: "🥣", titre: "Monter", detail: "Alterner glace, meringue et chantilly dans un moule.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler le vacherin plusieurs heures.", badge: "⏱ 4 h" },
      { icone: "🍓", titre: "Servir", detail: "Démouler et napper de coulis de framboise.", badge: null }
    ]
  },
  nougatglace: {
    nom: "Nougat Glacé",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-08T21:15:00",
    base: 6,
    temps: "30 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍯",
    description: "Le nougat glacé provençal au miel, fruits confits et amandes caramélisées.",
    tableauNougatGlace: [
      { nb: 1, creme: "60 ml", miel: "20 g", oeuf: "1", amandes: "15 g", fruitsconfits: "15 g", sucre: "10 g" },
      { nb: 2, creme: "120 ml", miel: "40 g", oeuf: "2", amandes: "30 g", fruitsconfits: "30 g", sucre: "20 g" },
      { nb: 3, creme: "180 ml", miel: "60 g", oeuf: "3", amandes: "45 g", fruitsconfits: "45 g", sucre: "30 g" },
      { nb: 4, creme: "240 ml", miel: "80 g", oeuf: "4", amandes: "60 g", fruitsconfits: "60 g", sucre: "40 g" },
      { nb: 5, creme: "300 ml", miel: "100 g", oeuf: "5", amandes: "75 g", fruitsconfits: "75 g", sucre: "50 g" },
      { nb: 6, creme: "360 ml", miel: "120 g", oeuf: "6", amandes: "90 g", fruitsconfits: "90 g", sucre: "60 g" },
      { nb: 7, creme: "420 ml", miel: "140 g", oeuf: "7", amandes: "105 g", fruitsconfits: "105 g", sucre: "70 g" },
      { nb: 8, creme: "480 ml", miel: "160 g", oeuf: "8", amandes: "120 g", fruitsconfits: "120 g", sucre: "80 g" },
      { nb: 9, creme: "540 ml", miel: "180 g", oeuf: "9", amandes: "135 g", fruitsconfits: "135 g", sucre: "90 g" },
      { nb: 10, creme: "600 ml", miel: "200 g", oeuf: "10", amandes: "150 g", fruitsconfits: "150 g", sucre: "100 g" },
      { nb: 11, creme: "660 ml", miel: "220 g", oeuf: "11", amandes: "165 g", fruitsconfits: "165 g", sucre: "110 g" },
      { nb: 12, creme: "720 ml", miel: "240 g", oeuf: "12", amandes: "180 g", fruitsconfits: "180 g", sucre: "120 g" },
      { nb: 13, creme: "780 ml", miel: "260 g", oeuf: "13", amandes: "195 g", fruitsconfits: "195 g", sucre: "130 g" },
      { nb: 14, creme: "840 ml", miel: "280 g", oeuf: "14", amandes: "210 g", fruitsconfits: "210 g", sucre: "140 g" },
      { nb: 15, creme: "900 ml", miel: "300 g", oeuf: "15", amandes: "225 g", fruitsconfits: "225 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Nougatine", detail: "Caraméliser les amandes au sucre puis concasser.", badge: "⏱ 6 min" },
      { icone: "🍯", titre: "Meringue", detail: "Monter les blancs et serrer au miel chaud. ASTUCE CHEF : verse le miel bien chaud en filet sur les blancs en neige : ça les cuit légèrement et donne un nougat glacé stable et aérien.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Incorporer délicatement chantilly, fruits confits et amandes.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans un moule à cake.", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise complète.", badge: "⏱ 5 h" }
    ]
  },
  bananasplit: {
    nom: "Banana Split",
    cat: "glaces",
    pays: "usa",
    dateAjout: "2026-06-08T21:16:00",
    base: 2,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍌",
    description: "Le dessert glacé américain : banane, boules de glace, chantilly, sauce chocolat et amandes.",
    tableauBananaSplit: [
      { nb: 1, banane: "1", creme: "40 ml", chocolatnoir: "20 g", amandes: "10 g", sucre: "10 g" },
      { nb: 2, banane: "2", creme: "80 ml", chocolatnoir: "40 g", amandes: "20 g", sucre: "20 g" },
      { nb: 3, banane: "3", creme: "120 ml", chocolatnoir: "60 g", amandes: "30 g", sucre: "30 g" },
      { nb: 4, banane: "4", creme: "160 ml", chocolatnoir: "80 g", amandes: "40 g", sucre: "40 g" },
      { nb: 5, banane: "5", creme: "200 ml", chocolatnoir: "100 g", amandes: "50 g", sucre: "50 g" },
      { nb: 6, banane: "6", creme: "240 ml", chocolatnoir: "120 g", amandes: "60 g", sucre: "60 g" },
      { nb: 7, banane: "7", creme: "280 ml", chocolatnoir: "140 g", amandes: "70 g", sucre: "70 g" },
      { nb: 8, banane: "8", creme: "320 ml", chocolatnoir: "160 g", amandes: "80 g", sucre: "80 g" },
      { nb: 9, banane: "9", creme: "360 ml", chocolatnoir: "180 g", amandes: "90 g", sucre: "90 g" },
      { nb: 10, banane: "10", creme: "400 ml", chocolatnoir: "200 g", amandes: "100 g", sucre: "100 g" },
      { nb: 11, banane: "11", creme: "440 ml", chocolatnoir: "220 g", amandes: "110 g", sucre: "110 g" },
      { nb: 12, banane: "12", creme: "480 ml", chocolatnoir: "240 g", amandes: "120 g", sucre: "120 g" },
      { nb: 13, banane: "13", creme: "520 ml", chocolatnoir: "260 g", amandes: "130 g", sucre: "130 g" },
      { nb: 14, banane: "14", creme: "560 ml", chocolatnoir: "280 g", amandes: "140 g", sucre: "140 g" },
      { nb: 15, banane: "15", creme: "600 ml", chocolatnoir: "300 g", amandes: "150 g", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍌", titre: "Banane", detail: "Couper la banane en deux dans la longueur.", badge: null },
      { icone: "🍦", titre: "Boules", detail: "Disposer trois boules de glace entre les demi-bananes. ASTUCE CHEF : trempe la cuillère à glace dans l'eau chaude entre chaque boule pour des quenelles nettes et régulières.", badge: null },
      { icone: "🍫", titre: "Sauce", detail: "Faire fondre le chocolat en sauce.", badge: null },
      { icone: "🥚", titre: "Chantilly", detail: "Monter la crème en chantilly.", badge: null },
      { icone: "🌰", titre: "Garnir", detail: "Napper de sauce chocolat et chantilly.", badge: null },
      { icone: "🍒", titre: "Servir", detail: "Parsemer d'amandes et servir aussitôt.", badge: null }
    ]
  },
  gelato: {
    nom: "Gelato Fior di Latte",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:17:00",
    base: 1,
    temps: "25 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "Le gelato fior di latte à l'italienne : dense et soyeux, sans œuf, tout en lait.",
    tableauGelato: [
      { nb: 1, lait: "30 ml", creme: "11 ml", sucre: "8 g", fecule: "1 g" },
      { nb: 2, lait: "59 ml", creme: "22 ml", sucre: "16 g", fecule: "2 g" },
      { nb: 3, lait: "89 ml", creme: "33 ml", sucre: "24 g", fecule: "3 g" },
      { nb: 4, lait: "119 ml", creme: "44 ml", sucre: "33 g", fecule: "4 g" },
      { nb: 5, lait: "148 ml", creme: "56 ml", sucre: "41 g", fecule: "6 g" },
      { nb: 6, lait: "178 ml", creme: "67 ml", sucre: "49 g", fecule: "7 g" },
      { nb: 7, lait: "207 ml", creme: "78 ml", sucre: "57 g", fecule: "8 g" },
      { nb: 8, lait: "237 ml", creme: "89 ml", sucre: "65 g", fecule: "9 g" },
      { nb: 9, lait: "267 ml", creme: "100 ml", sucre: "73 g", fecule: "10 g" },
      { nb: 10, lait: "296 ml", creme: "111 ml", sucre: "81 g", fecule: "11 g" },
      { nb: 11, lait: "326 ml", creme: "122 ml", sucre: "90 g", fecule: "12 g" },
      { nb: 12, lait: "356 ml", creme: "133 ml", sucre: "98 g", fecule: "13 g" },
      { nb: 13, lait: "385 ml", creme: "144 ml", sucre: "106 g", fecule: "14 g" },
      { nb: 14, lait: "415 ml", creme: "156 ml", sucre: "114 g", fecule: "16 g" },
      { nb: 15, lait: "444 ml", creme: "167 ml", sucre: "122 g", fecule: "17 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Chauffer", detail: "Chauffer le lait, la crème et le sucre.", badge: "⏱ 4 min" },
      { icone: "🥄", titre: "Lier", detail: "Délayer la fécule à froid et l'incorporer pour épaissir légèrement. ASTUCE CHEF : le gelato contient moins de crème et d'air qu'une glace : c'est ce qui lui donne sa densité soyeuse caractéristique.", badge: "⏱ 3 min" },
      { icone: "❄️", titre: "Refroidir", detail: "Réfrigérer bien la base.", badge: "⏱ 3 h" },
      { icone: "🌀", titre: "Turbiner", detail: "Turbiner lentement.", badge: "⏱ 25 min" },
      { icone: "🍨", titre: "Texture", detail: "Servir plus tempéré qu'une glace classique.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Déguster en boules généreuses.", badge: null }
    ]
  },
  kulfi: {
    nom: "Kulfi",
    cat: "glaces",
    pays: "inde",
    dateAjout: "2026-06-08T21:18:00",
    base: 4,
    temps: "40 min + congélation",
    niveau: "⭐⭐ Moyen",
    emoji: "🍦",
    description: "La glace indienne au lait réduit, parfumée à la cardamome et aux pistaches.",
    tableauKulfi: [
      { nb: 1, lait: "100 ml", laitconcentre: "15 g", sucre: "15 g", cardamome: "1 g", pistache: "8 g" },
      { nb: 2, lait: "200 ml", laitconcentre: "30 g", sucre: "30 g", cardamome: "2 g", pistache: "16 g" },
      { nb: 3, lait: "300 ml", laitconcentre: "45 g", sucre: "45 g", cardamome: "3 g", pistache: "24 g" },
      { nb: 4, lait: "400 ml", laitconcentre: "60 g", sucre: "60 g", cardamome: "4 g", pistache: "32 g" },
      { nb: 5, lait: "500 ml", laitconcentre: "75 g", sucre: "75 g", cardamome: "5 g", pistache: "40 g" },
      { nb: 6, lait: "600 ml", laitconcentre: "90 g", sucre: "90 g", cardamome: "6 g", pistache: "48 g" },
      { nb: 7, lait: "700 ml", laitconcentre: "105 g", sucre: "105 g", cardamome: "7 g", pistache: "56 g" },
      { nb: 8, lait: "800 ml", laitconcentre: "120 g", sucre: "120 g", cardamome: "8 g", pistache: "64 g" },
      { nb: 9, lait: "900 ml", laitconcentre: "135 g", sucre: "135 g", cardamome: "9 g", pistache: "72 g" },
      { nb: 10, lait: "1000 ml", laitconcentre: "150 g", sucre: "150 g", cardamome: "10 g", pistache: "80 g" },
      { nb: 11, lait: "1100 ml", laitconcentre: "165 g", sucre: "165 g", cardamome: "11 g", pistache: "88 g" },
      { nb: 12, lait: "1200 ml", laitconcentre: "180 g", sucre: "180 g", cardamome: "12 g", pistache: "96 g" },
      { nb: 13, lait: "1300 ml", laitconcentre: "195 g", sucre: "195 g", cardamome: "13 g", pistache: "104 g" },
      { nb: 14, lait: "1400 ml", laitconcentre: "210 g", sucre: "210 g", cardamome: "14 g", pistache: "112 g" },
      { nb: 15, lait: "1500 ml", laitconcentre: "225 g", sucre: "225 g", cardamome: "15 g", pistache: "120 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥛", titre: "Réduire", detail: "Faire réduire longuement le lait à feu doux. ASTUCE CHEF : réduis le lait de moitié en remuant : cette concentration donne au kulfi son goût lacté intense et sa texture dense.", badge: "⏱ 30 min" },
      { icone: "🍬", titre: "Sucrer", detail: "Ajouter le lait concentré et le sucre.", badge: null },
      { icone: "🌿", titre: "Parfumer", detail: "Parfumer à la cardamome et aux pistaches.", badge: null },
      { icone: "🧊", titre: "Mouler", detail: "Verser dans des moules (sans turbiner).", badge: null },
      { icone: "❄️", titre: "Congeler", detail: "Congeler jusqu'à prise.", badge: "⏱ 5 h" },
      { icone: "🌰", titre: "Servir", detail: "Démouler et parsemer de pistaches.", badge: null }
    ]
  },
  granite: {
    nom: "Granité Citron",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-08T21:19:00",
    base: 1,
    temps: "10 min + congélation",
    niveau: "⭐ Facile",
    emoji: "🧊",
    description: "Le granité sicilien au citron, cristaux glacés à gratter à la fourchette, sans sorbetière.",
    tableauGranite: [
      { nb: 1, citron: "13 ml", eau: "28 ml", sucre: "9 g" },
      { nb: 2, citron: "25 ml", eau: "56 ml", sucre: "19 g" },
      { nb: 3, citron: "38 ml", eau: "84 ml", sucre: "28 g" },
      { nb: 4, citron: "50 ml", eau: "113 ml", sucre: "38 g" },
      { nb: 5, citron: "63 ml", eau: "141 ml", sucre: "47 g" },
      { nb: 6, citron: "75 ml", eau: "169 ml", sucre: "56 g" },
      { nb: 7, citron: "88 ml", eau: "197 ml", sucre: "66 g" },
      { nb: 8, citron: "100 ml", eau: "225 ml", sucre: "75 g" },
      { nb: 9, citron: "113 ml", eau: "253 ml", sucre: "84 g" },
      { nb: 10, citron: "125 ml", eau: "281 ml", sucre: "94 g" },
      { nb: 11, citron: "138 ml", eau: "309 ml", sucre: "103 g" },
      { nb: 12, citron: "150 ml", eau: "338 ml", sucre: "113 g" },
      { nb: 13, citron: "163 ml", eau: "366 ml", sucre: "122 g" },
      { nb: 14, citron: "175 ml", eau: "394 ml", sucre: "131 g" },
      { nb: 15, citron: "188 ml", eau: "422 ml", sucre: "141 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍯", titre: "Sirop", detail: "Dissoudre le sucre dans l'eau tiède, refroidir.", badge: "⏱ 4 min" },
      { icone: "🍋", titre: "Citron", detail: "Ajouter le jus de citron filtré.", badge: null },
      { icone: "🧊", titre: "Congeler", detail: "Verser dans un bac peu profond et placer au congélateur.", badge: null },
      { icone: "🍴", titre: "Gratter", detail: "Gratter à la fourchette toutes les 30 min. ASTUCE CHEF : c'est le grattage régulier qui crée les cristaux du granité : ne le laisse jamais prendre en bloc, racle-le 4-5 fois.", badge: "⏱ 2 h" },
      { icone: "❄️", titre: "Texture", detail: "Obtenir une neige de cristaux légers.", badge: null },
      { icone: "🥄", titre: "Servir", detail: "Servir aussitôt en verrines givrées.", badge: null }
    ]
  },
  frozenyogurt: {
    nom: "Frozen yogurt", cat: "glaces", pays: "usa", dateAjout: "2026-06-17T10:00:00",
    base: 1, temps: "10 min + congélation", niveau: "⭐ Facile", emoji: "🍦",
    description: "L'alternative légère et acidulée à la glace : un yaourt grec onctueux glacé aux fruits rouges. Plus frais et moins sucré qu'une crème glacée.",
    saisons: ["ete"],
    ingredients: {},
    tableauFrozenYogurt: [
      { nb: 1, yaourtgrec: "32 g", sucreglace: "5 g", miel: "3 g", citron: "1 ml", fraise: "9 g" },
      { nb: 2, yaourtgrec: "63 g", sucreglace: "10 g", miel: "5 g", citron: "3 ml", fraise: "19 g" },
      { nb: 3, yaourtgrec: "95 g", sucreglace: "15 g", miel: "8 g", citron: "4 ml", fraise: "28 g" },
      { nb: 4, yaourtgrec: "127 g", sucreglace: "20 g", miel: "10 g", citron: "5 ml", fraise: "38 g" },
      { nb: 5, yaourtgrec: "158 g", sucreglace: "25 g", miel: "13 g", citron: "6 ml", fraise: "47 g" },
      { nb: 6, yaourtgrec: "190 g", sucreglace: "30 g", miel: "15 g", citron: "8 ml", fraise: "57 g" },
      { nb: 7, yaourtgrec: "222 g", sucreglace: "35 g", miel: "18 g", citron: "9 ml", fraise: "66 g" },
      { nb: 8, yaourtgrec: "253 g", sucreglace: "41 g", miel: "20 g", citron: "10 ml", fraise: "76 g" },
      { nb: 9, yaourtgrec: "285 g", sucreglace: "46 g", miel: "23 g", citron: "11 ml", fraise: "85 g" },
      { nb: 10, yaourtgrec: "316 g", sucreglace: "51 g", miel: "25 g", citron: "13 ml", fraise: "95 g" },
      { nb: 11, yaourtgrec: "348 g", sucreglace: "56 g", miel: "28 g", citron: "14 ml", fraise: "104 g" },
      { nb: 12, yaourtgrec: "380 g", sucreglace: "61 g", miel: "30 g", citron: "15 ml", fraise: "114 g" },
      { nb: 13, yaourtgrec: "411 g", sucreglace: "66 g", miel: "33 g", citron: "16 ml", fraise: "123 g" },
      { nb: 14, yaourtgrec: "443 g", sucreglace: "71 g", miel: "35 g", citron: "18 ml", fraise: "133 g" },
      { nb: 15, yaourtgrec: "475 g", sucreglace: "76 g", miel: "38 g", citron: "19 ml", fraise: "142 g" }
    ],
    etapes: [
      { icone: "🥣", titre: "Mélanger", detail: "Fouetter le yaourt grec avec le sucre glace, le miel et le jus de citron.", badge: null },
      { icone: "🍓", titre: "Fruits", detail: "Incorporer les fruits rouges, écrasés ou entiers selon l'envie.", badge: null },
      { icone: "🧊", titre: "Turbiner", detail: "Verser en sorbetière jusqu'à une texture crémeuse, ou placer au congélateur.", badge: "⏱ 30 min" },
      { icone: "🥄", titre: "Lisser", detail: "Sans sorbetière, mélanger toutes les 30 min pour éviter les cristaux.", badge: null },
      { icone: "🍨", titre: "Servir", detail: "Servir en boules, légèrement souple, avec quelques fruits frais.", badge: null }
    ]
  },
  glacenoixpecan: {
    nom: "Glace Noix de Pécan",
    cat: "glaces",
    pays: "etats-unis",
    dateAjout: "2026-06-22T11:00:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍨",
    description: "Une glace américaine régressive : crème vanillée au caramel de cassonade et éclats de noix de pécan torréfiées au beurre. Le butter pecan, le vrai.",
    tableauGlacenoixpecan: [
      { nb: 1, lait: "22 ml", creme: "18 ml", jaunesoeufs: "1", cassonade: "10 g", noixpecan: "12 g", beurre: "3 g", sel: "1 g" },
      { nb: 2, lait: "44 ml", creme: "36 ml", jaunesoeufs: "1", cassonade: "20 g", noixpecan: "24 g", beurre: "6 g", sel: "1 g" },
      { nb: 3, lait: "66 ml", creme: "54 ml", jaunesoeufs: "1", cassonade: "30 g", noixpecan: "36 g", beurre: "9 g", sel: "1 g" },
      { nb: 4, lait: "88 ml", creme: "72 ml", jaunesoeufs: "2", cassonade: "40 g", noixpecan: "48 g", beurre: "12 g", sel: "1 g" },
      { nb: 5, lait: "110 ml", creme: "90 ml", jaunesoeufs: "2", cassonade: "50 g", noixpecan: "60 g", beurre: "15 g", sel: "2 g" },
      { nb: 6, lait: "132 ml", creme: "108 ml", jaunesoeufs: "2", cassonade: "60 g", noixpecan: "72 g", beurre: "18 g", sel: "2 g" },
      { nb: 7, lait: "154 ml", creme: "126 ml", jaunesoeufs: "3", cassonade: "70 g", noixpecan: "84 g", beurre: "21 g", sel: "2 g" },
      { nb: 8, lait: "176 ml", creme: "144 ml", jaunesoeufs: "3", cassonade: "80 g", noixpecan: "96 g", beurre: "24 g", sel: "2 g" },
      { nb: 9, lait: "198 ml", creme: "162 ml", jaunesoeufs: "4", cassonade: "90 g", noixpecan: "108 g", beurre: "27 g", sel: "3 g" },
      { nb: 10, lait: "220 ml", creme: "180 ml", jaunesoeufs: "4", cassonade: "100 g", noixpecan: "120 g", beurre: "30 g", sel: "3 g" },
      { nb: 11, lait: "242 ml", creme: "198 ml", jaunesoeufs: "4", cassonade: "110 g", noixpecan: "132 g", beurre: "33 g", sel: "3 g" },
      { nb: 12, lait: "264 ml", creme: "216 ml", jaunesoeufs: "5", cassonade: "120 g", noixpecan: "144 g", beurre: "36 g", sel: "4 g" },
      { nb: 13, lait: "286 ml", creme: "234 ml", jaunesoeufs: "5", cassonade: "130 g", noixpecan: "156 g", beurre: "39 g", sel: "4 g" },
      { nb: 14, lait: "308 ml", creme: "252 ml", jaunesoeufs: "6", cassonade: "140 g", noixpecan: "168 g", beurre: "42 g", sel: "4 g" },
      { nb: 15, lait: "330 ml", creme: "270 ml", jaunesoeufs: "6", cassonade: "150 g", noixpecan: "180 g", beurre: "45 g", sel: "5 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌰", titre: "Torréfier", detail: "Faire dorer les noix de pécan dans le beurre avec une pincée de sel.", badge: "⏱ 5 min" },
      { icone: "🥛", titre: "Crème anglaise", detail: "Cuire lait, crème, jaunes et cassonade à 83°C jusqu'à napper la cuillère.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Turbiner", detail: "Refroidir puis turbiner. ASTUCE CHEF : ajoute les pécans en toute fin de turbinage pour qu'ils gardent leur croquant.", badge: "⏱ 30 min" },
      { icone: "🍨", titre: "Prendre", detail: "Mettre au congélateur 2 h avant de servir en boules.", badge: null }
    ]
  },
  glacecookiedough: {
    nom: "Glace Cookie Dough",
    cat: "glaces",
    pays: "etats-unis",
    dateAjout: "2026-06-22T11:00:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍪",
    description: "La glace gourmande par excellence : une base vanille parsemée de morceaux de pâte à cookie crue (sans œuf) aux pépites de chocolat.",
    tableauGlacecookiedough: [
      { nb: 1, lait: "20 ml", creme: "18 ml", jaunesoeufs: "1", sucre: "8 g", farine: "8 g", beurre: "5 g", cassonade: "5 g", chocolatNoir: "6 g", vanille: "1 g" },
      { nb: 2, lait: "40 ml", creme: "36 ml", jaunesoeufs: "1", sucre: "16 g", farine: "16 g", beurre: "10 g", cassonade: "10 g", chocolatNoir: "12 g", vanille: "1 g" },
      { nb: 3, lait: "60 ml", creme: "54 ml", jaunesoeufs: "1", sucre: "24 g", farine: "24 g", beurre: "15 g", cassonade: "15 g", chocolatNoir: "18 g", vanille: "1 g" },
      { nb: 4, lait: "80 ml", creme: "72 ml", jaunesoeufs: "2", sucre: "32 g", farine: "32 g", beurre: "20 g", cassonade: "20 g", chocolatNoir: "24 g", vanille: "1 g" },
      { nb: 5, lait: "100 ml", creme: "90 ml", jaunesoeufs: "2", sucre: "40 g", farine: "40 g", beurre: "25 g", cassonade: "25 g", chocolatNoir: "30 g", vanille: "2 g" },
      { nb: 6, lait: "120 ml", creme: "108 ml", jaunesoeufs: "2", sucre: "48 g", farine: "48 g", beurre: "30 g", cassonade: "30 g", chocolatNoir: "36 g", vanille: "2 g" },
      { nb: 7, lait: "140 ml", creme: "126 ml", jaunesoeufs: "3", sucre: "56 g", farine: "56 g", beurre: "35 g", cassonade: "35 g", chocolatNoir: "42 g", vanille: "2 g" },
      { nb: 8, lait: "160 ml", creme: "144 ml", jaunesoeufs: "3", sucre: "64 g", farine: "64 g", beurre: "40 g", cassonade: "40 g", chocolatNoir: "48 g", vanille: "2 g" },
      { nb: 9, lait: "180 ml", creme: "162 ml", jaunesoeufs: "4", sucre: "72 g", farine: "72 g", beurre: "45 g", cassonade: "45 g", chocolatNoir: "54 g", vanille: "3 g" },
      { nb: 10, lait: "200 ml", creme: "180 ml", jaunesoeufs: "4", sucre: "80 g", farine: "80 g", beurre: "50 g", cassonade: "50 g", chocolatNoir: "60 g", vanille: "3 g" },
      { nb: 11, lait: "220 ml", creme: "198 ml", jaunesoeufs: "4", sucre: "88 g", farine: "88 g", beurre: "55 g", cassonade: "55 g", chocolatNoir: "66 g", vanille: "3 g" },
      { nb: 12, lait: "240 ml", creme: "216 ml", jaunesoeufs: "5", sucre: "96 g", farine: "96 g", beurre: "60 g", cassonade: "60 g", chocolatNoir: "72 g", vanille: "4 g" },
      { nb: 13, lait: "260 ml", creme: "234 ml", jaunesoeufs: "5", sucre: "104 g", farine: "104 g", beurre: "65 g", cassonade: "65 g", chocolatNoir: "78 g", vanille: "4 g" },
      { nb: 14, lait: "280 ml", creme: "252 ml", jaunesoeufs: "6", sucre: "112 g", farine: "112 g", beurre: "70 g", cassonade: "70 g", chocolatNoir: "84 g", vanille: "4 g" },
      { nb: 15, lait: "300 ml", creme: "270 ml", jaunesoeufs: "6", sucre: "120 g", farine: "120 g", beurre: "75 g", cassonade: "75 g", chocolatNoir: "90 g", vanille: "5 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍪", titre: "Pâte à cookie", detail: "Mélanger farine (torréfiée), beurre, cassonade et chocolat concassé en pâte, façonner de petits morceaux.", badge: "⏱ 10 min" },
      { icone: "🥛", titre: "Base vanille", detail: "Cuire lait, crème, jaunes, sucre et vanille en crème anglaise.", badge: "⏱ 8 min" },
      { icone: "❄️", titre: "Turbiner", detail: "Turbiner la base. ASTUCE CHEF : torréfie la farine au four 10 min avant — la pâte à cookie crue est alors sans risque à déguster.", badge: "⏱ 30 min" },
      { icone: "🍨", titre: "Mélanger", detail: "Incorporer les morceaux de pâte en fin de turbinage et congeler 2 h.", badge: null }
    ]
  },
  glacetiramisu: {
    nom: "Glace Tiramisu",
    cat: "glaces",
    pays: "italie",
    dateAjout: "2026-06-22T11:00:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍮",
    description: "Le tiramisu version glacée : mascarpone, café et biscuits cuillère imbibés, le tout poudré de cacao. Le dessert italien en boule.",
    tableauGlacetiramisu: [
      { nb: 1, mascarpone: "18 g", creme: "15 ml", lait: "12 ml", jaunesoeufs: "1", sucre: "8 g", cafe: "5 ml", biscuitscuillere: "8 g", cacao: "1 g" },
      { nb: 2, mascarpone: "36 g", creme: "30 ml", lait: "24 ml", jaunesoeufs: "1", sucre: "16 g", cafe: "10 ml", biscuitscuillere: "16 g", cacao: "2 g" },
      { nb: 3, mascarpone: "54 g", creme: "45 ml", lait: "36 ml", jaunesoeufs: "1", sucre: "24 g", cafe: "15 ml", biscuitscuillere: "24 g", cacao: "3 g" },
      { nb: 4, mascarpone: "72 g", creme: "60 ml", lait: "48 ml", jaunesoeufs: "2", sucre: "32 g", cafe: "20 ml", biscuitscuillere: "32 g", cacao: "4 g" },
      { nb: 5, mascarpone: "90 g", creme: "75 ml", lait: "60 ml", jaunesoeufs: "2", sucre: "40 g", cafe: "25 ml", biscuitscuillere: "40 g", cacao: "5 g" },
      { nb: 6, mascarpone: "108 g", creme: "90 ml", lait: "72 ml", jaunesoeufs: "2", sucre: "48 g", cafe: "30 ml", biscuitscuillere: "48 g", cacao: "6 g" },
      { nb: 7, mascarpone: "126 g", creme: "105 ml", lait: "84 ml", jaunesoeufs: "3", sucre: "56 g", cafe: "35 ml", biscuitscuillere: "56 g", cacao: "7 g" },
      { nb: 8, mascarpone: "144 g", creme: "120 ml", lait: "96 ml", jaunesoeufs: "3", sucre: "64 g", cafe: "40 ml", biscuitscuillere: "64 g", cacao: "8 g" },
      { nb: 9, mascarpone: "162 g", creme: "135 ml", lait: "108 ml", jaunesoeufs: "4", sucre: "72 g", cafe: "45 ml", biscuitscuillere: "72 g", cacao: "9 g" },
      { nb: 10, mascarpone: "180 g", creme: "150 ml", lait: "120 ml", jaunesoeufs: "4", sucre: "80 g", cafe: "50 ml", biscuitscuillere: "80 g", cacao: "10 g" },
      { nb: 11, mascarpone: "198 g", creme: "165 ml", lait: "132 ml", jaunesoeufs: "4", sucre: "88 g", cafe: "55 ml", biscuitscuillere: "88 g", cacao: "11 g" },
      { nb: 12, mascarpone: "216 g", creme: "180 ml", lait: "144 ml", jaunesoeufs: "5", sucre: "96 g", cafe: "60 ml", biscuitscuillere: "96 g", cacao: "12 g" },
      { nb: 13, mascarpone: "234 g", creme: "195 ml", lait: "156 ml", jaunesoeufs: "5", sucre: "104 g", cafe: "65 ml", biscuitscuillere: "104 g", cacao: "13 g" },
      { nb: 14, mascarpone: "252 g", creme: "210 ml", lait: "168 ml", jaunesoeufs: "6", sucre: "112 g", cafe: "70 ml", biscuitscuillere: "112 g", cacao: "14 g" },
      { nb: 15, mascarpone: "270 g", creme: "225 ml", lait: "180 ml", jaunesoeufs: "6", sucre: "120 g", cafe: "75 ml", biscuitscuillere: "120 g", cacao: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "☕", titre: "Café", detail: "Préparer un café serré et y imbiber rapidement les biscuits cuillère émiettés.", badge: null },
      { icone: "🧀", titre: "Crème", detail: "Battre mascarpone, crème, lait, jaunes et sucre en base lisse.", badge: "⏱ 5 min" },
      { icone: "❄️", titre: "Turbiner", detail: "Turbiner la base. ASTUCE CHEF : n'imbibe pas trop les biscuits — détrempés, ils disparaissent ; juste humides, ils gardent du mâché.", badge: "⏱ 30 min" },
      { icone: "🍫", titre: "Monter", detail: "Alterner glace et biscuits imbibés, poudrer de cacao et congeler 2 h.", badge: null }
    ]
  },
  sorbetmelon: {
    nom: "Sorbet Melon",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["ete"],
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍧",
    description: "Le sorbet le plus rafraîchissant de l'été : melon bien mûr, un trait de citron et juste ce qu'il faut de sucre. 100 % fruit.",
    tableauSorbetmelon: [
      { nb: 1, melon: "40 g", eau: "10 ml", sucre: "10 g", citron: "2 ml" },
      { nb: 2, melon: "80 g", eau: "20 ml", sucre: "20 g", citron: "4 ml" },
      { nb: 3, melon: "120 g", eau: "30 ml", sucre: "30 g", citron: "6 ml" },
      { nb: 4, melon: "160 g", eau: "40 ml", sucre: "40 g", citron: "8 ml" },
      { nb: 5, melon: "200 g", eau: "50 ml", sucre: "50 g", citron: "10 ml" },
      { nb: 6, melon: "240 g", eau: "60 ml", sucre: "60 g", citron: "12 ml" },
      { nb: 7, melon: "280 g", eau: "70 ml", sucre: "70 g", citron: "14 ml" },
      { nb: 8, melon: "320 g", eau: "80 ml", sucre: "80 g", citron: "16 ml" },
      { nb: 9, melon: "360 g", eau: "90 ml", sucre: "90 g", citron: "18 ml" },
      { nb: 10, melon: "400 g", eau: "100 ml", sucre: "100 g", citron: "20 ml" },
      { nb: 11, melon: "440 g", eau: "110 ml", sucre: "110 g", citron: "22 ml" },
      { nb: 12, melon: "480 g", eau: "120 ml", sucre: "120 g", citron: "24 ml" },
      { nb: 13, melon: "520 g", eau: "130 ml", sucre: "130 g", citron: "26 ml" },
      { nb: 14, melon: "560 g", eau: "140 ml", sucre: "140 g", citron: "28 ml" },
      { nb: 15, melon: "600 g", eau: "150 ml", sucre: "150 g", citron: "30 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍈", titre: "Mixer", detail: "Mixer la chair de melon bien mûre avec le citron.", badge: null },
      { icone: "💧", titre: "Sirop", detail: "Faire fondre le sucre dans l'eau et l'ajouter à la purée de melon.", badge: null },
      { icone: "❄️", titre: "Turbiner", detail: "Turbiner. ASTUCE CHEF : choisis un melon très parfumé — un sorbet ne fait que concentrer le goût du fruit, il ne le crée pas.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Congeler 2 h avant de servir.", badge: null }
    ]
  },
  sorbetlitchi: {
    nom: "Sorbet Litchi",
    cat: "glaces",
    pays: "chine",
    dateAjout: "2026-06-22T11:00:00",
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍧",
    description: "Un sorbet floral et délicat : litchis parfumés relevés d'un trait de citron vert. Léger, exotique et élégant en fin de repas.",
    tableauSorbetlitchi: [
      { nb: 1, litchi: "38 g", eau: "12 ml", sucre: "9 g", citronvert: "2 ml" },
      { nb: 2, litchi: "76 g", eau: "24 ml", sucre: "18 g", citronvert: "4 ml" },
      { nb: 3, litchi: "114 g", eau: "36 ml", sucre: "27 g", citronvert: "6 ml" },
      { nb: 4, litchi: "152 g", eau: "48 ml", sucre: "36 g", citronvert: "8 ml" },
      { nb: 5, litchi: "190 g", eau: "60 ml", sucre: "45 g", citronvert: "10 ml" },
      { nb: 6, litchi: "228 g", eau: "72 ml", sucre: "54 g", citronvert: "12 ml" },
      { nb: 7, litchi: "266 g", eau: "84 ml", sucre: "63 g", citronvert: "14 ml" },
      { nb: 8, litchi: "304 g", eau: "96 ml", sucre: "72 g", citronvert: "16 ml" },
      { nb: 9, litchi: "342 g", eau: "108 ml", sucre: "81 g", citronvert: "18 ml" },
      { nb: 10, litchi: "380 g", eau: "120 ml", sucre: "90 g", citronvert: "20 ml" },
      { nb: 11, litchi: "418 g", eau: "132 ml", sucre: "99 g", citronvert: "22 ml" },
      { nb: 12, litchi: "456 g", eau: "144 ml", sucre: "108 g", citronvert: "24 ml" },
      { nb: 13, litchi: "494 g", eau: "156 ml", sucre: "117 g", citronvert: "26 ml" },
      { nb: 14, litchi: "532 g", eau: "168 ml", sucre: "126 g", citronvert: "28 ml" },
      { nb: 15, litchi: "570 g", eau: "180 ml", sucre: "135 g", citronvert: "30 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌸", titre: "Mixer", detail: "Mixer les litchis dénoyautés avec le citron vert.", badge: null },
      { icone: "💧", titre: "Sirop", detail: "Dissoudre le sucre dans l'eau et incorporer à la purée.", badge: null },
      { icone: "❄️", titre: "Turbiner", detail: "Turbiner. ASTUCE CHEF : le citron vert réveille le litchi qui, seul, peut être un peu plat — n'en mets pas trop pour autant.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Congeler 2 h avant de servir.", badge: null }
    ]
  },
  sorbetcassis: {
    nom: "Sorbet Cassis",
    cat: "glaces",
    pays: "france",
    dateAjout: "2026-06-22T11:00:00",
    saisons: ["ete"],
    base: 4,
    temps: "30 min + turbinage",
    niveau: "⭐⭐ Moyen",
    emoji: "🍧",
    description: "Un sorbet intense et acidulé : le cassis dans toute sa puissance aromatique, à peine sucré. Une couleur violette spectaculaire.",
    tableauSorbetcassis: [
      { nb: 1, cassis: "35 g", eau: "13 ml", sucre: "12 g", citron: "2 ml" },
      { nb: 2, cassis: "70 g", eau: "26 ml", sucre: "24 g", citron: "4 ml" },
      { nb: 3, cassis: "105 g", eau: "39 ml", sucre: "36 g", citron: "6 ml" },
      { nb: 4, cassis: "140 g", eau: "52 ml", sucre: "48 g", citron: "8 ml" },
      { nb: 5, cassis: "175 g", eau: "65 ml", sucre: "60 g", citron: "10 ml" },
      { nb: 6, cassis: "210 g", eau: "78 ml", sucre: "72 g", citron: "12 ml" },
      { nb: 7, cassis: "245 g", eau: "91 ml", sucre: "84 g", citron: "14 ml" },
      { nb: 8, cassis: "280 g", eau: "104 ml", sucre: "96 g", citron: "16 ml" },
      { nb: 9, cassis: "315 g", eau: "117 ml", sucre: "108 g", citron: "18 ml" },
      { nb: 10, cassis: "350 g", eau: "130 ml", sucre: "120 g", citron: "20 ml" },
      { nb: 11, cassis: "385 g", eau: "143 ml", sucre: "132 g", citron: "22 ml" },
      { nb: 12, cassis: "420 g", eau: "156 ml", sucre: "144 g", citron: "24 ml" },
      { nb: 13, cassis: "455 g", eau: "169 ml", sucre: "156 g", citron: "26 ml" },
      { nb: 14, cassis: "490 g", eau: "182 ml", sucre: "168 g", citron: "28 ml" },
      { nb: 15, cassis: "525 g", eau: "195 ml", sucre: "180 g", citron: "30 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🫐", titre: "Mixer", detail: "Mixer le cassis avec le citron puis passer au tamis pour retirer les pépins.", badge: null },
      { icone: "💧", titre: "Sirop", detail: "Dissoudre le sucre dans l'eau et mélanger à la purée tamisée.", badge: null },
      { icone: "❄️", titre: "Turbiner", detail: "Turbiner. ASTUCE CHEF : tamise bien — les pépins de cassis sont durs et gâcheraient la texture lisse du sorbet.", badge: "⏱ 25 min" },
      { icone: "🍧", titre: "Prendre", detail: "Congeler 2 h avant de servir.", badge: null }
    ]
  },
});
