// ============================================================
// recettes_salades.js — Recettes de catégorie "salades" (Salades) — 24 recettes
// 👉 Pour AJOUTER une recette Salades : place-la juste avant le  });  final.
//    (le plus simple : copie une recette existante et change les valeurs)
// ============================================================
Object.assign(recettes, {
  "saladeniçoise": {
    cat: "salades", saisons: ["ete"], pays: "france",
    base: 4,
    temps: "25 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "La salade niçoise authentique — tomates, thon, anchois, olives et œufs durs. Le soleil de la Méditerranée dans l'assiette.",
    tableauSaladeNicoise: [
      { nb: 1, tomates: "2", thon: "40 g", oeufs: "1", olives: "30 g", anchois: "3", salade: "¼", oignon: "¼", huile: "1 c.à.s" },
      { nb: 2, tomates: "3", thon: "80 g", oeufs: "1", olives: "60 g", anchois: "6", salade: "½", oignon: "½", huile: "2 c.à.s" },
      { nb: 3, tomates: "4", thon: "120 g", oeufs: "2", olives: "90 g", anchois: "9", salade: "¾", oignon: "½", huile: "3 c.à.s" },
      { nb: 4, tomates: "6", thon: "160 g", oeufs: "3", olives: "120 g", anchois: "12", salade: "1", oignon: "1", huile: "4 c.à.s" },
      { nb: 5, tomates: "7", thon: "200 g", oeufs: "4", olives: "150 g", anchois: "15", salade: "1", oignon: "1", huile: "5 c.à.s" },
      { nb: 6, tomates: "9", thon: "240 g", oeufs: "4", olives: "180 g", anchois: "18", salade: "1½", oignon: "1", huile: "6 c.à.s" },
      { nb: 7, tomates: "10", thon: "280 g", oeufs: "5", olives: "210 g", anchois: "21", salade: "1½", oignon: "1", huile: "7 c.à.s" },
      { nb: 8, tomates: "12", thon: "320 g", oeufs: "6", olives: "240 g", anchois: "24", salade: "2", oignon: "2", huile: "8 c.à.s" },
      { nb: 9, tomates: "13", thon: "360 g", oeufs: "7", olives: "270 g", anchois: "27", salade: "2", oignon: "2", huile: "9 c.à.s" },
      { nb: 10, tomates: "15", thon: "400 g", oeufs: "8", olives: "300 g", anchois: "30", salade: "2", oignon: "2", huile: "10 c.à.s" },
      { nb: 11, tomates: "16", thon: "440 g", oeufs: "8", olives: "330 g", anchois: "33", salade: "2½", oignon: "2", huile: "11 c.à.s" },
      { nb: 12, tomates: "18", thon: "480 g", oeufs: "9", olives: "360 g", anchois: "36", salade: "2½", oignon: "3", huile: "12 c.à.s" },
      { nb: 13, tomates: "20", thon: "520 g", oeufs: "9.8", olives: "390 g", anchois: "39", salade: "3.2", oignon: "3.2", huile: "13 c.à.s" },
      { nb: 14, tomates: "21", thon: "560 g", oeufs: "10", olives: "420 g", anchois: "42", salade: "3.5", oignon: "3.5", huile: "14 c.à.s" },
      { nb: 15, tomates: "22", thon: "600 g", oeufs: "11", olives: "450 g", anchois: "45", salade: "3.8", oignon: "3.8", huile: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Cuire les œufs durs", detail: "Plonger les œufs dans l'eau bouillante. Refroidir sous l'eau froide, écaler et couper en quartiers. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 10 min" },
      { icone: "🍅", titre: "Préparer les légumes", detail: "Laver et couper les tomates en quartiers. Émincer l'oignon rouge en fines rondelles. Laver et essorer la salade. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🐟", titre: "Préparer le thon", detail: "Égoutter le thon et l'émietter grossièrement. Rincer les filets d'anchois. Rincer abondamment à l'eau froide.", badge: null },
      { icone: "🥗", titre: "Dresser la salade", detail: "Disposer la salade dans un plat. Ajouter les tomates, l'oignon, les olives, le thon, les anchois et les œufs en quartiers. Ne pas mélanger — présenter chaque ingrédient séparément.", badge: null },
      { icone: "🫒", titre: "Assaisonner", detail: "Arroser d'un généreux filet d'huile d'olive, saler, poivrer. Parsemer de basilic frais ciselé. Servir immédiatement.", badge: null }
    ]
  },
  saladecesar: {
    cat: "salades", pays: "usa",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥬",
    description: "La salade César avec sa sauce crémeuse à l'ail, parmesan, croûtons dorés et poulet grillé.",
    tableauSaladeCesar: [
      { nb: 1, laitue: "¼", poulet: "50 g", parmesan: "15 g", pain: "1 tr.", ail: "½ gousse", citron: "¼", sel: "1 pincée", poivre: "1 pincée", huile: "1 c.à.s" },
      { nb: 2, laitue: "½", poulet: "100 g", parmesan: "30 g", pain: "2 tr.", ail: "½ gousse", citron: "¼", sel: "1 pincée", poivre: "1 pincée", huile: "2 c.à.s" },
      { nb: 3, laitue: "¾", poulet: "150 g", parmesan: "45 g", pain: "3 tr.", ail: "1 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "3 c.à.s" },
      { nb: 4, laitue: "1", poulet: "200 g", parmesan: "60 g", pain: "4 tr.", ail: "1 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "4 c.à.s" },
      { nb: 5, laitue: "1", poulet: "250 g", parmesan: "75 g", pain: "5 tr.", ail: "1 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "5 c.à.s" },
      { nb: 6, laitue: "1½", poulet: "300 g", parmesan: "90 g", pain: "6 tr.", ail: "2 gousses", citron: "1", sel: "1 pincée", poivre: "1 pincée", huile: "6 c.à.s" },
      { nb: 7, laitue: "1½", poulet: "350 g", parmesan: "105 g", pain: "7 tr.", ail: "2 gousses", citron: "1", sel: "1 pincée", poivre: "1 pincée", huile: "7 c.à.s" },
      { nb: 8, laitue: "2", poulet: "400 g", parmesan: "120 g", pain: "8 tr.", ail: "2 gousses", citron: "1", sel: "1 pincée", poivre: "1 pincée", huile: "8 c.à.s" },
      { nb: 9, laitue: "2", poulet: "450 g", parmesan: "135 g", pain: "9 tr.", ail: "2 gousses", citron: "1", sel: "1 pincée", poivre: "1 pincée", huile: "9 c.à.s" },
      { nb: 10, laitue: "2½", poulet: "500 g", parmesan: "150 g", pain: "10 tr.", ail: "3 gousses", citron: "1½", sel: "1 pincée", poivre: "1 pincée", huile: "10 c.à.s" },
      { nb: 11, laitue: "2½", poulet: "550 g", parmesan: "165 g", pain: "11 tr.", ail: "3 gousses", citron: "1½", sel: "1 pincée", poivre: "1 pincée", huile: "11 c.à.s" },
      { nb: 12, laitue: "3", poulet: "600 g", parmesan: "180 g", pain: "12 tr.", ail: "3 gousses", citron: "2", sel: "1 pincée", poivre: "1 pincée", huile: "12 c.à.s" },
      { nb: 13, laitue: "3.2", poulet: "650 g", parmesan: "195 g", pain: "13 tr.", ail: "3.2 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "13 c.à.s" },
      { nb: 14, laitue: "3.5", poulet: "700 g", parmesan: "210 g", pain: "14 tr.", ail: "3.5 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "14 c.à.s" },
      { nb: 15, laitue: "3.8", poulet: "750 g", parmesan: "225 g", pain: "15 tr.", ail: "3.8 gousse", citron: "½", sel: "1 pincée", poivre: "1 pincée", huile: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍞", titre: "Faire les croûtons", detail: "Couper le pain en cubes. Les faire dorer à la poêle avec un filet d'huile d'olive et une gousse d'ail écrasée. Réserver. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 5 min" },
      { icone: "🍗", titre: "Griller le poulet", detail: "Saler, poivrer et griller les escalopes de poulet à la poêle ou au four. Laisser reposer 5 min puis couper en tranches. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 10 min" },
      { icone: "🥚", titre: "Préparer la sauce César", detail: "Mélanger : 2 jaunes d'œufs, 1 c.à.s de moutarde, jus de citron, ail pressé, 4 c.à.s d'huile d'olive, parmesan râpé, sel, poivre. Fouetter jusqu'à émulsion.", badge: null },
      { icone: "🥬", titre: "Dresser", detail: "Laver et déchirer la laitue romaine. La mélanger avec la sauce César. Disposer le poulet en tranches, les croûtons et des copeaux de parmesan.", badge: null }
    ]
  },
  saladegreque: {
    cat: "salades", saisons: ["ete"], pays: "grece",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🫒",
    description: "La salade grecque fraîche et colorée — tomates, concombre, feta, olives et oignon rouge. Idéale l'été.",
    tableauSaladeGreque: [
      { nb: 1, tomates: "1", concombre: "¼", feta: "40 g", olives: "15 g", oignon: "¼", huile: "1 c.à.s" },
      { nb: 2, tomates: "2", concombre: "½", feta: "80 g", olives: "30 g", oignon: "½", huile: "2 c.à.s" },
      { nb: 3, tomates: "3", concombre: "¾", feta: "120 g", olives: "45 g", oignon: "½", huile: "3 c.à.s" },
      { nb: 4, tomates: "4", concombre: "1", feta: "160 g", olives: "60 g", oignon: "1", huile: "4 c.à.s" },
      { nb: 5, tomates: "5", concombre: "1", feta: "200 g", olives: "75 g", oignon: "1", huile: "5 c.à.s" },
      { nb: 6, tomates: "6", concombre: "1½", feta: "240 g", olives: "90 g", oignon: "1", huile: "6 c.à.s" },
      { nb: 7, tomates: "7", concombre: "1½", feta: "280 g", olives: "105 g", oignon: "1", huile: "7 c.à.s" },
      { nb: 8, tomates: "8", concombre: "2", feta: "320 g", olives: "120 g", oignon: "2", huile: "8 c.à.s" },
      { nb: 9, tomates: "9", concombre: "2", feta: "360 g", olives: "135 g", oignon: "2", huile: "9 c.à.s" },
      { nb: 10, tomates: "10", concombre: "2½", feta: "400 g", olives: "150 g", oignon: "2", huile: "10 c.à.s" },
      { nb: 11, tomates: "11", concombre: "2½", feta: "440 g", olives: "165 g", oignon: "2", huile: "11 c.à.s" },
      { nb: 12, tomates: "12", concombre: "3", feta: "480 g", olives: "180 g", oignon: "3", huile: "12 c.à.s" },
      { nb: 13, tomates: "13", concombre: "3.2", feta: "520 g", olives: "195 g", oignon: "3.2", huile: "13 c.à.s" },
      { nb: 14, tomates: "14", concombre: "3.5", feta: "560 g", olives: "210 g", oignon: "3.5", huile: "14 c.à.s" },
      { nb: 15, tomates: "15", concombre: "3.8", feta: "600 g", olives: "225 g", oignon: "3.8", huile: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥗", titre: "Préparation soignée", detail: "Laver soigneusement les légumes feuilles. Bien essorer (eau = vinaigrette diluée). ASTUCE CHEF : couper au dernier moment pour conserver la fraîcheur.", badge: "⏱ 10 min" },
      { icone: "🍅", titre: "Couper les légumes", detail: "Couper les tomates en quartiers, le concombre en demi-rondelles, l'oignon rouge en fines lamelles. Disposer dans un saladier. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🫒", titre: "Ajouter les olives", detail: "Ajouter les olives noires de Kalamata. Émietter ou couper la feta en cubes et disposer par-dessus. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🌿", titre: "Assaisonner", detail: "Arroser d'huile d'olive généreusement. Saupoudrer d'origan séché. Saler légèrement (la feta est déjà salée), poivrer. Servir immédiatement.", badge: null },
      { icone: "🍽️", titre: "Service immédiat", detail: "Mélanger délicatement avec la vinaigrette JUSTE avant de servir (sinon les feuilles cuisent). Servir IMMÉDIATEMENT à température ambiante.", badge: null }
    ]
  },
  saladepatasthon: {
    cat: "salades", saisons: ["ete"], pays: "france",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🍝",
    description: "Une salade de pâtes au thon fraîche et rassasiante — parfaite pour un déjeuner estival rapide.",
    tableauSaladePatas: [
      { nb: 1, pates: "60 g", thon: "40 g", tomates: "2", mais: "30 g", oignon: "¼", sel: "1 pincée", poivre: "1 pincée", huile: "1 c.à.s" },
      { nb: 2, pates: "120 g", thon: "80 g", tomates: "3", mais: "60 g", oignon: "½", sel: "1 pincée", poivre: "1 pincée", huile: "2 c.à.s" },
      { nb: 3, pates: "180 g", thon: "120 g", tomates: "4", mais: "90 g", oignon: "½", sel: "1 pincée", poivre: "1 pincée", huile: "3 c.à.s" },
      { nb: 4, pates: "250 g", thon: "160 g", tomates: "6", mais: "120 g", oignon: "1", sel: "1 pincée", poivre: "1 pincée", huile: "4 c.à.s" },
      { nb: 5, pates: "310 g", thon: "200 g", tomates: "7", mais: "150 g", oignon: "1", sel: "1 pincée", poivre: "1 pincée", huile: "5 c.à.s" },
      { nb: 6, pates: "370 g", thon: "240 g", tomates: "9", mais: "180 g", oignon: "1", sel: "1 pincée", poivre: "1 pincée", huile: "6 c.à.s" },
      { nb: 7, pates: "430 g", thon: "280 g", tomates: "10", mais: "210 g", oignon: "1", sel: "1 pincée", poivre: "1 pincée", huile: "7 c.à.s" },
      { nb: 8, pates: "500 g", thon: "320 g", tomates: "12", mais: "240 g", oignon: "2", sel: "1 pincée", poivre: "1 pincée", huile: "8 c.à.s" },
      { nb: 9, pates: "560 g", thon: "360 g", tomates: "13", mais: "270 g", oignon: "2", sel: "1 pincée", poivre: "1 pincée", huile: "9 c.à.s" },
      { nb: 10, pates: "620 g", thon: "400 g", tomates: "15", mais: "300 g", oignon: "2", sel: "1 pincée", poivre: "1 pincée", huile: "10 c.à.s" },
      { nb: 11, pates: "680 g", thon: "440 g", tomates: "16", mais: "330 g", oignon: "2", sel: "1 pincée", poivre: "1 pincée", huile: "11 c.à.s" },
      { nb: 12, pates: "750 g", thon: "480 g", tomates: "18", mais: "360 g", oignon: "3", sel: "1 pincée", poivre: "1 pincée", huile: "12 c.à.s" },
      { nb: 13, pates: "812 g", thon: "520 g", tomates: "20", mais: "390 g", oignon: "3.2", sel: "1 pincée", poivre: "1 pincée", huile: "13 c.à.s" },
      { nb: 14, pates: "875 g", thon: "560 g", tomates: "21", mais: "420 g", oignon: "3.5", sel: "1 pincée", poivre: "1 pincée", huile: "14 c.à.s" },
      { nb: 15, pates: "938 g", thon: "600 g", tomates: "22", mais: "450 g", oignon: "3.8", sel: "1 pincée", poivre: "1 pincée", huile: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍝", titre: "Cuire les pâtes", detail: "Cuire les pâtes courtes (fusilli, farfalle, penne) dans l'eau bouillante salée. Les égoutter et les rincer à l'eau froide pour stopper la cuisson. Laisser refroidir. Rincer abondamment à l'eau froide.", badge: "⏱ selon paquet" },
      { icone: "🐟", titre: "Préparer le thon", detail: "Égoutter le thon et l'émietter. Couper les tomates cerises en deux, émincer l'oignon. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🥗", titre: "Assembler", detail: "Mélanger les pâtes froides avec le thon, les tomates, le maïs et l'oignon. Ajouter des olives et du basilic si souhaité.", badge: null },
      { icone: "🫒", titre: "Assaisonner", detail: "Assaisonner avec de l'huile d'olive, du vinaigre de cidre, du sel et du poivre. Bien mélanger. Réfrigérer 30 min avant de servir. Sel, poivre généreusement. Goûter et ajuster TOUJOURS.", badge: "⏱ 30 min au frais" }
    ]
  },
  saladerizmediterranee: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "25 min",
    niveau: "⭐ Facile",
    emoji: "🍚",
    description: "Une salade de riz méditerranéenne colorée aux légumes grillés, olives et herbes fraîches.",
    tableauSaladeRiz: [
      { nb: 1, riz: "60 g", poivron: "¼", courgette: "¼", tomates: "2", olives: "20 g", sel: "1 pincée", poivre: "1 pincée", huile: "1 c.à.s", citron: "⅓ citron" },
      { nb: 2, riz: "120 g", poivron: "½", courgette: "½", tomates: "3", olives: "40 g", sel: "1 pincée", poivre: "1 pincée", huile: "2 c.à.s", citron: "⅔ citron" },
      { nb: 3, riz: "180 g", poivron: "¾", courgette: "¾", tomates: "4", olives: "60 g", sel: "1 pincée", poivre: "1 pincée", huile: "3 c.à.s", citron: "1 citron" },
      { nb: 4, riz: "250 g", poivron: "1", courgette: "1", tomates: "6", olives: "80 g", sel: "1 pincée", poivre: "1 pincée", huile: "4 c.à.s", citron: "2 citrons" },
      { nb: 5, riz: "310 g", poivron: "1", courgette: "1", tomates: "7", olives: "100 g", sel: "1 pincée", poivre: "1 pincée", huile: "5 c.à.s", citron: "2 citrons" },
      { nb: 6, riz: "370 g", poivron: "1½", courgette: "1½", tomates: "9", olives: "120 g", sel: "1 pincée", poivre: "1 pincée", huile: "6 c.à.s", citron: "2 citrons" },
      { nb: 7, riz: "430 g", poivron: "1½", courgette: "1½", tomates: "10", olives: "140 g", sel: "1 pincée", poivre: "1 pincée", huile: "7 c.à.s", citron: "3 citrons" },
      { nb: 8, riz: "500 g", poivron: "2", courgette: "2", tomates: "12", olives: "160 g", sel: "1 pincée", poivre: "1 pincée", huile: "8 c.à.s", citron: "3 citrons" },
      { nb: 9, riz: "560 g", poivron: "2", courgette: "2", tomates: "13", olives: "180 g", sel: "1 pincée", poivre: "1 pincée", huile: "9 c.à.s", citron: "3 citrons" },
      { nb: 10, riz: "620 g", poivron: "2½", courgette: "2½", tomates: "15", olives: "200 g", sel: "1 pincée", poivre: "1 pincée", huile: "10 c.à.s", citron: "4 citrons" },
      { nb: 11, riz: "680 g", poivron: "2½", courgette: "2½", tomates: "16", olives: "220 g", sel: "1 pincée", poivre: "1 pincée", huile: "11 c.à.s", citron: "4 citrons" },
      { nb: 12, riz: "750 g", poivron: "3", courgette: "3", tomates: "18", olives: "240 g", sel: "1 pincée", poivre: "1 pincée", huile: "12 c.à.s", citron: "4 citrons" },
      { nb: 13, riz: "812 g", poivron: "3.2", courgette: "3.2", tomates: "20", olives: "260 g", sel: "1 pincée", poivre: "1 pincée", huile: "13 c.à.s", citron: "5 citrons" },
      { nb: 14, riz: "875 g", poivron: "3.5", courgette: "3.5", tomates: "21", olives: "280 g", sel: "1 pincée", poivre: "1 pincée", huile: "14 c.à.s", citron: "5 citrons" },
      { nb: 15, riz: "938 g", poivron: "3.8", courgette: "3.8", tomates: "22", olives: "300 g", sel: "1 pincée", poivre: "1 pincée", huile: "15 c.à.s", citron: "5 citrons" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍚", titre: "Cuire le riz", detail: "Cuire le riz dans l'eau bouillante salée. Égoutter et rincer à l'eau froide. Laisser refroidir complètement. Rincer abondamment à l'eau froide.", badge: "⏱ 15 min" },
      { icone: "🔥", titre: "Griller les légumes", detail: "Couper poivron et courgette en dés. Faire griller à la poêle avec un filet d'huile d'olive jusqu'à légère coloration. Laisser refroidir. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 8 min" },
      { icone: "🥗", titre: "Assembler", detail: "Mélanger le riz froid avec les légumes grillés refroidis, les tomates cerises coupées en deux et les olives.", badge: null },
      { icone: "🌿", titre: "Assaisonner", detail: "Arroser d'huile d'olive, jus de citron, sel, poivre. Ajouter du basilic et du persil frais ciselés. Réfrigérer avant de servir.", badge: "⏱ 30 min au frais" }
    ]
  },
  tabulemaison: {
    cat: "salades", saisons: ["ete"], pays: "liban",
    base: 4,
    temps: "20 min + repos",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Un taboulé maison frais et parfumé — semoule, tomates, concombre, menthe et citron. Le classique de l'été.",
    tableauTabule: [
      { nb: 1, semoule: "40 g", tomates: "1", concombre: "¼", persil: "¼ botte", menthe: "5 feuilles", citron: "¼", huile: "1 c.à.s" },
      { nb: 2, semoule: "80 g", tomates: "2", concombre: "½", persil: "½ botte", menthe: "10 feuilles", citron: "½", huile: "2 c.à.s" },
      { nb: 3, semoule: "120 g", tomates: "3", concombre: "½", persil: "½ botte", menthe: "15 feuilles", citron: "½", huile: "3 c.à.s" },
      { nb: 4, semoule: "160 g", tomates: "4", concombre: "1", persil: "1 botte", menthe: "20 feuilles", citron: "1", huile: "4 c.à.s" },
      { nb: 5, semoule: "200 g", tomates: "5", concombre: "1", persil: "1 botte", menthe: "25 feuilles", citron: "1", huile: "5 c.à.s" },
      { nb: 6, semoule: "240 g", tomates: "6", concombre: "1½", persil: "1½ botte", menthe: "30 feuilles", citron: "1", huile: "6 c.à.s" },
      { nb: 7, semoule: "280 g", tomates: "7", concombre: "1½", persil: "1½ botte", menthe: "35 feuilles", citron: "1½", huile: "7 c.à.s" },
      { nb: 8, semoule: "320 g", tomates: "8", concombre: "2", persil: "2 bottes", menthe: "40 feuilles", citron: "2", huile: "8 c.à.s" },
      { nb: 9, semoule: "360 g", tomates: "9", concombre: "2", persil: "2 bottes", menthe: "45 feuilles", citron: "2", huile: "9 c.à.s" },
      { nb: 10, semoule: "400 g", tomates: "10", concombre: "2½", persil: "2 bottes", menthe: "50 feuilles", citron: "2", huile: "10 c.à.s" },
      { nb: 11, semoule: "440 g", tomates: "11", concombre: "2½", persil: "2½ bottes", menthe: "55 feuilles", citron: "2½", huile: "11 c.à.s" },
      { nb: 12, semoule: "480 g", tomates: "12", concombre: "3", persil: "3 bottes", menthe: "60 feuilles", citron: "3", huile: "12 c.à.s" },
      { nb: 13, semoule: "520 g", tomates: "13", concombre: "3.2", persil: "3.2 botte", menthe: "65 feuilles", citron: "3.2", huile: "13 c.à.s" },
      { nb: 14, semoule: "560 g", tomates: "14", concombre: "3.5", persil: "3.5 botte", menthe: "70 feuilles", citron: "3.5", huile: "14 c.à.s" },
      { nb: 15, semoule: "600 g", tomates: "15", concombre: "3.8", persil: "3.8 botte", menthe: "75 feuilles", citron: "3.8", huile: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Hydrater la semoule", detail: "Verser la semoule dans un saladier. Ajouter la même quantité d'eau bouillante salée. Couvrir et laisser gonfler 5 min. Égrainer à la fourchette et laisser refroidir.", badge: "⏱ 5 min repos" },
      { icone: "🍅", titre: "Préparer les légumes", detail: "Couper les tomates et le concombre épépiné en très petits dés. Ciseler finement le persil plat et la menthe. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🥗", titre: "Mélanger", detail: "Ajouter les légumes et les herbes à la semoule refroidie. Bien mélanger.", badge: null },
      { icone: "🍋", titre: "Assaisonner et reposer", detail: "Arroser de jus de citron et d'huile d'olive. Saler, poivrer. Mélanger et réfrigérer. Plus le taboulé repose, plus il est savoureux !", badge: "⏱ 1h minimum au frais" }
    ]
  },
  saladelentilles: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🥜",
    description: "Une salade de lentilles tiède ou froide — légumineuses, légumes croquants et vinaigrette moutardée.",
    tableauSaladeLentilles: [
      { nb: 1, lentilles: "60 g", carottes: "½", oignon: "¼", lardons: "25 g", sel: "1 pincée", poivre: "1 pincée", huile: "1 c.à.s", vin: "50 ml" },
      { nb: 2, lentilles: "120 g", carottes: "1", oignon: "½", lardons: "50 g", sel: "1 pincée", poivre: "1 pincée", huile: "2 c.à.s", vin: "100 ml" },
      { nb: 3, lentilles: "180 g", carottes: "1", oignon: "½", lardons: "75 g", sel: "1 pincée", poivre: "1 pincée", huile: "3 c.à.s", vin: "150 ml" },
      { nb: 4, lentilles: "250 g", carottes: "2", oignon: "1", lardons: "100 g", sel: "1 pincée", poivre: "1 pincée", huile: "4 c.à.s", vin: "200 ml" },
      { nb: 5, lentilles: "310 g", carottes: "2", oignon: "1", lardons: "125 g", sel: "1 pincée", poivre: "1 pincée", huile: "5 c.à.s", vin: "250 ml" },
      { nb: 6, lentilles: "370 g", carottes: "3", oignon: "1", lardons: "150 g", sel: "1 pincée", poivre: "1 pincée", huile: "6 c.à.s", vin: "300 ml" },
      { nb: 7, lentilles: "430 g", carottes: "3", oignon: "1", lardons: "175 g", sel: "1 pincée", poivre: "1 pincée", huile: "7 c.à.s", vin: "350 ml" },
      { nb: 8, lentilles: "500 g", carottes: "4", oignon: "2", lardons: "200 g", sel: "1 pincée", poivre: "1 pincée", huile: "8 c.à.s", vin: "400 ml" },
      { nb: 9, lentilles: "560 g", carottes: "4", oignon: "2", lardons: "225 g", sel: "1 pincée", poivre: "1 pincée", huile: "9 c.à.s", vin: "450 ml" },
      { nb: 10, lentilles: "620 g", carottes: "5", oignon: "2", lardons: "250 g", sel: "1 pincée", poivre: "1 pincée", huile: "10 c.à.s", vin: "500 ml" },
      { nb: 11, lentilles: "680 g", carottes: "5", oignon: "2", lardons: "275 g", sel: "1 pincée", poivre: "1 pincée", huile: "11 c.à.s", vin: "550 ml" },
      { nb: 12, lentilles: "750 g", carottes: "6", oignon: "3", lardons: "300 g", sel: "1 pincée", poivre: "1 pincée", huile: "12 c.à.s", vin: "600 ml" },
      { nb: 13, lentilles: "812 g", carottes: "6.5", oignon: "3.2", lardons: "325 g", sel: "1 pincée", poivre: "1 pincée", huile: "13 c.à.s", vin: "650 ml" },
      { nb: 14, lentilles: "875 g", carottes: "7", oignon: "3.5", lardons: "350 g", sel: "1 pincée", poivre: "1 pincée", huile: "14 c.à.s", vin: "700 ml" },
      { nb: 15, lentilles: "938 g", carottes: "7.5", oignon: "3.8", lardons: "375 g", sel: "1 pincée", poivre: "1 pincée", huile: "15 c.à.s", vin: "750 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥜", titre: "Cuire les lentilles", detail: "Rincer les lentilles vertes (du Puy de préférence). Les plonger dans l'eau froide avec un bouquet garni et les carottes coupées. Porter à ébullition puis cuire à feu moyen. Ne pas saler en début de cuisson. Rincer abondamment à l'eau froide.", badge: "⏱ 20–25 min" },
      { icone: "🥓", titre: "Faire revenir les lardons", detail: "Faire dorer les lardons à la poêle sans matière grasse. Égoutter sur du papier absorbant. Surveiller : couleur dorée uniforme = c'est prêt, pas plus sinon ça brûle.", badge: "⏱ 5 min" },
      { icone: "🥣", titre: "Préparer la vinaigrette", detail: "Mélanger 1 c.à.s de moutarde, 2 c.à.s de vinaigre de vin, 4 c.à.s d'huile d'olive, sel et poivre. Bien fouetter.", badge: null },
      { icone: "🥗", titre: "Assembler", detail: "Égoutter les lentilles encore chaudes et les mélanger immédiatement avec la vinaigrette. Ajouter les lardons et l'oignon émincé. Servir tiède ou froid.", badge: null }
    ]
  },
  saladeavocatcrevettes: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🥑",
    description: "Une salade fraîche et élégante — avocat crémeux, crevettes roses et sauce cocktail. Parfaite en entrée.",
    tableauAvocatCrevettes: [
      { nb: 1, avocats: "½", crevettes: "60 g", salade: "¼", citron: "¼", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 2, avocats: "1", crevettes: "120 g", salade: "½", citron: "½", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 3, avocats: "1½", crevettes: "180 g", salade: "¾", citron: "½", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 4, avocats: "2", crevettes: "250 g", salade: "1", citron: "1", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 5, avocats: "2½", crevettes: "300 g", salade: "1", citron: "1", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 6, avocats: "3", crevettes: "370 g", salade: "1½", citron: "1", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 7, avocats: "3½", crevettes: "430 g", salade: "1½", citron: "1½", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 8, avocats: "4", crevettes: "500 g", salade: "2", citron: "2", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 9, avocats: "4½", crevettes: "560 g", salade: "2", citron: "2", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 10, avocats: "5", crevettes: "620 g", salade: "2½", citron: "2", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 11, avocats: "5½", crevettes: "680 g", salade: "2½", citron: "2½", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 12, avocats: "6", crevettes: "750 g", salade: "3", citron: "3", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 13, avocats: "6.5", crevettes: "812 g", salade: "3.2", citron: "3.2", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 14, avocats: "7", crevettes: "875 g", salade: "3.5", citron: "3.5", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 15, avocats: "7.5", crevettes: "938 g", salade: "3.8", citron: "3.8", sel: "1 pincée", poivre: "1 pincée" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥑", titre: "Préparer les avocats", detail: "Couper les avocats en deux, retirer le noyau. Les couper en tranches ou en dés. Arroser immédiatement de jus de citron pour éviter l'oxydation. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🦐", titre: "Préparer les crevettes", detail: "Si besoin, décortiquer les crevettes roses cuites. Les garder entières ou les couper en deux. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🍶", titre: "Préparer la sauce cocktail", detail: "Mélanger 3 c.à.s de mayonnaise, 1 c.à.s de ketchup, quelques gouttes de Tabasco, jus de citron, sel et poivre.", badge: null },
      { icone: "🥗", titre: "Dresser", detail: "Disposer la salade dans les assiettes. Ajouter l'avocat et les crevettes. Napper de sauce cocktail. Garnir d'aneth ou de ciboulette.", badge: null }
    ]
  },
  saladeThai: {
    cat: "salades", saisons: ["ete"], pays: "asie",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "Salade thaï — vermicelles de riz, légumes croquants, coriandre fraîche et vinaigrette au citron vert et sauce nuoc-mâm. Fraîche et explosive en saveurs.",
    tableauSaladeThai: [
      { nb: 1, pates: "50 g", carottes: "0.5", concombre: "0.25", coriandre: "5 g", citrons: "0.5", ail: "1 gousse", sucre: "10 g" },
      { nb: 2, pates: "100 g", carottes: "1", concombre: "0.5", coriandre: "10 g", citrons: "1", ail: "2 gousses", sucre: "20 g" },
      { nb: 3, pates: "150 g", carottes: "1.5", concombre: "0.75", coriandre: "15 g", citrons: "1.5", ail: "3 gousses", sucre: "30 g" },
      { nb: 4, pates: "200 g", carottes: "2", concombre: "1", coriandre: "20 g", citrons: "2", ail: "4 gousses", sucre: "40 g" },
      { nb: 5, pates: "250 g", carottes: "2.5", concombre: "1.25", coriandre: "25 g", citrons: "2.5", ail: "5 gousses", sucre: "50 g" },
      { nb: 6, pates: "300 g", carottes: "3", concombre: "1.5", coriandre: "30 g", citrons: "3", ail: "6 gousses", sucre: "60 g" },
      { nb: 7, pates: "350 g", carottes: "3.5", concombre: "1.75", coriandre: "35 g", citrons: "3.5", ail: "7 gousses", sucre: "70 g" },
      { nb: 8, pates: "400 g", carottes: "4", concombre: "2", coriandre: "40 g", citrons: "4", ail: "8 gousses", sucre: "80 g" },
      { nb: 9, pates: "450 g", carottes: "4.5", concombre: "2.25", coriandre: "45 g", citrons: "4.5", ail: "9 gousses", sucre: "90 g" },
      { nb: 10, pates: "500 g", carottes: "5", concombre: "2.5", coriandre: "50 g", citrons: "5", ail: "10 gousses", sucre: "100 g" },
      { nb: 11, pates: "550 g", carottes: "5.5", concombre: "2.75", coriandre: "55 g", citrons: "5.5", ail: "11 gousses", sucre: "110 g" },
      { nb: 12, pates: "600 g", carottes: "6", concombre: "3", coriandre: "60 g", citrons: "6", ail: "12 gousses", sucre: "120 g" },
      { nb: 13, pates: "650 g", carottes: "6.5", concombre: "3.25", coriandre: "65 g", citrons: "6.5", ail: "13 gousses", sucre: "130 g" },
      { nb: 14, pates: "700 g", carottes: "7", concombre: "3.5", coriandre: "70 g", citrons: "7", ail: "14 gousses", sucre: "140 g" },
      { nb: 15, pates: "750 g", carottes: "7.5", concombre: "3.75", coriandre: "75 g", citrons: "7.5", ail: "15 gousses", sucre: "150 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍜", titre: "Tremper les vermicelles", detail: "Faire tremper les vermicelles de riz dans l'eau chaude 5 min. Égoutter et rincer à l'eau froide. Rincer abondamment à l'eau froide.", badge: "⏱ 5 min" },
      { icone: "🥕", titre: "Préparer les légumes", detail: "Râper les carottes. Trancher finement le concombre. Ciseler la coriandre, la menthe et les oignons verts. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🍋", titre: "Faire la vinaigrette", detail: "Mélanger jus de citron vert, sauce nuoc-mâm, sucre, ail, piment. Goûter et ajuster.", badge: null },
      { icone: "🥗", titre: "Assembler", detail: "Mélanger vermicelles, légumes, cacahuètes concassées. Arroser de vinaigrette. Garnir de coriandre.", badge: null }
    ]
  },
  saladeHaricotsVerts: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🟢",
    description: "Salade de haricots verts croquants aux amandes grillées — vinaigrette moutardée et œufs durs. Simple et délicieuse en entrée ou accompagnement.",
    tableauSaladeHV: [
      { nb: 1, haricots: "100 g", oeuf: "0.5", amandes: "10 g", moutarde: "½ c.à.c", vinaigre: "5 ml" },
      { nb: 2, haricots: "200 g", oeuf: "1", amandes: "20 g", moutarde: "1 c.à.c", vinaigre: "10 ml" },
      { nb: 3, haricots: "300 g", oeuf: "1.5", amandes: "30 g", moutarde: "1½ c.à.c", vinaigre: "15 ml" },
      { nb: 4, haricots: "400 g", oeuf: "2", amandes: "40 g", moutarde: "2 c.à.c", vinaigre: "20 ml" },
      { nb: 5, haricots: "500 g", oeuf: "2.5", amandes: "50 g", moutarde: "2½ c.à.c", vinaigre: "25 ml" },
      { nb: 6, haricots: "600 g", oeuf: "3", amandes: "60 g", moutarde: "3 c.à.c", vinaigre: "30 ml" },
      { nb: 7, haricots: "700 g", oeuf: "3.5", amandes: "70 g", moutarde: "3½ c.à.c", vinaigre: "35 ml" },
      { nb: 8, haricots: "800 g", oeuf: "4", amandes: "80 g", moutarde: "4 c.à.c", vinaigre: "40 ml" },
      { nb: 9, haricots: "900 g", oeuf: "4.5", amandes: "90 g", moutarde: "4½ c.à.c", vinaigre: "45 ml" },
      { nb: 10, haricots: "1000 g", oeuf: "5", amandes: "100 g", moutarde: "5 c.à.c", vinaigre: "50 ml" },
      { nb: 11, haricots: "1100 g", oeuf: "5.5", amandes: "110 g", moutarde: "5½ c.à.c", vinaigre: "55 ml" },
      { nb: 12, haricots: "1200 g", oeuf: "6", amandes: "120 g", moutarde: "6 c.à.c", vinaigre: "60 ml" },
      { nb: 13, haricots: "1300 g", oeuf: "6.5", amandes: "130 g", moutarde: "6½ c.à.c", vinaigre: "65 ml" },
      { nb: 14, haricots: "1400 g", oeuf: "7", amandes: "140 g", moutarde: "7 c.à.c", vinaigre: "70 ml" },
      { nb: 15, haricots: "1500 g", oeuf: "7.5", amandes: "150 g", moutarde: "7½ c.à.c", vinaigre: "75 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🟢", titre: "Cuire les haricots", detail: "Cuire les haricots verts al dente dans l'eau bouillante salée. Refroidir immédiatement dans l'eau glacée pour garder la couleur. 1 min de moins que sur l'emballage. Goûter pour vérifier.", badge: "⏱ 5 min" },
      { icone: "🥚", titre: "Cuire les œufs durs", detail: "Cuire les œufs 9 min dans l'eau bouillante. Refroidir et écaler.", badge: "⏱ 9 min" },
      { icone: "🌰", titre: "Griller les amandes", detail: "Faire griller les amandes effilées à sec dans une poêle jusqu'à coloration dorée. Préchauffer le gril 5 min. Surface très chaude pour de belles marques.", badge: "⏱ 3 min" },
      { icone: "🥗", titre: "Dresser", detail: "Disposer les haricots. Ajouter les œufs coupés en quartiers, les amandes. Arroser de vinaigrette moutardée.", badge: null }
    ]
  },
  saladeFruitsMer: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "25 min",
    niveau: "⭐ Facile",
    emoji: "🦐",
    description: "Salade de fruits de mer — crevettes, moules et calamars marinés à l'huile d'olive citronnée avec ail et persil. Fraîcheur marine garantie.",
    tableauSaladeFM: [
      { nb: 1, crevettes: "75 g", moule: "75 g", calamars: "50 g", citrons: "0.5", persil: "5 g", sel: "1 pincée", poivre: "1 pincée", huile: "1 c.à.s", ail: "1 gousse" },
      { nb: 2, crevettes: "150 g", moule: "150 g", calamars: "100 g", citrons: "1", persil: "10 g", sel: "1 pincée", poivre: "1 pincée", huile: "2 c.à.s", ail: "2 gousses" },
      { nb: 3, crevettes: "225 g", moule: "225 g", calamars: "150 g", citrons: "1.5", persil: "15 g", sel: "1 pincée", poivre: "1 pincée", huile: "3 c.à.s", ail: "3 gousses" },
      { nb: 4, crevettes: "300 g", moule: "300 g", calamars: "200 g", citrons: "2", persil: "20 g", sel: "1 pincée", poivre: "1 pincée", huile: "4 c.à.s", ail: "4 gousses" },
      { nb: 5, crevettes: "375 g", moule: "375 g", calamars: "250 g", citrons: "2.5", persil: "25 g", sel: "1 pincée", poivre: "1 pincée", huile: "5 c.à.s", ail: "5 gousses" },
      { nb: 6, crevettes: "450 g", moule: "450 g", calamars: "300 g", citrons: "3", persil: "30 g", sel: "1 pincée", poivre: "1 pincée", huile: "6 c.à.s", ail: "6 gousses" },
      { nb: 7, crevettes: "525 g", moule: "525 g", calamars: "350 g", citrons: "3.5", persil: "35 g", sel: "1 pincée", poivre: "1 pincée", huile: "7 c.à.s", ail: "7 gousses" },
      { nb: 8, crevettes: "600 g", moule: "600 g", calamars: "400 g", citrons: "4", persil: "40 g", sel: "1 pincée", poivre: "1 pincée", huile: "8 c.à.s", ail: "8 gousses" },
      { nb: 9, crevettes: "675 g", moule: "675 g", calamars: "450 g", citrons: "4.5", persil: "45 g", sel: "1 pincée", poivre: "1 pincée", huile: "9 c.à.s", ail: "9 gousses" },
      { nb: 10, crevettes: "750 g", moule: "750 g", calamars: "500 g", citrons: "5", persil: "50 g", sel: "1 pincée", poivre: "1 pincée", huile: "10 c.à.s", ail: "10 gousses" },
      { nb: 11, crevettes: "825 g", moule: "825 g", calamars: "550 g", citrons: "5.5", persil: "55 g", sel: "1 pincée", poivre: "1 pincée", huile: "11 c.à.s", ail: "11 gousses" },
      { nb: 12, crevettes: "900 g", moule: "900 g", calamars: "600 g", citrons: "6", persil: "60 g", sel: "1 pincée", poivre: "1 pincée", huile: "12 c.à.s", ail: "12 gousses" },
      { nb: 13, crevettes: "975 g", moule: "975 g", calamars: "650 g", citrons: "6.5", persil: "65 g", sel: "1 pincée", poivre: "1 pincée", huile: "13 c.à.s", ail: "13 gousses" },
      { nb: 14, crevettes: "1050 g", moule: "1050 g", calamars: "700 g", citrons: "7", persil: "70 g", sel: "1 pincée", poivre: "1 pincée", huile: "14 c.à.s", ail: "14 gousses" },
      { nb: 15, crevettes: "1125 g", moule: "1125 g", calamars: "750 g", citrons: "7.5", persil: "75 g", sel: "1 pincée", poivre: "1 pincée", huile: "15 c.à.s", ail: "15 gousses" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🦐", titre: "Cuire les fruits de mer", detail: "Cuire les moules à la marinière. Poêler les calamars et les crevettes 2 min. Laisser refroidir.", badge: "⏱ 10 min" },
      { icone: "🍋", titre: "Préparer la marinade", detail: "Mélanger huile d'olive, jus de citron, ail haché, persil, sel, poivre, piment d'Espelette.", badge: null },
      { icone: "⏳", titre: "Mariner", detail: "Mélanger tous les fruits de mer avec la marinade. Laisser mariner au frais.", badge: "⏱ 15 min" },
      { icone: "🥗", titre: "Dresser", detail: "Disposer sur un lit de roquette ou salade verte. Garnir de quartiers de citron.", badge: null }
    ]
  },
  saladePoulpe: {
    cat: "salades", pays: "grece",
    base: 4,
    temps: "1h30",
    niveau: "⭐⭐ Moyen",
    emoji: "🐙",
    description: "Salade de poulpe à la grecque — poulpe tendre cuit longuement, mariné à l'huile d'olive, citron, câpres et olives. Méditerranéen et savoureux.",
    tableauSaladePoulpe: [
      { nb: 1, poulpe: "200 g", olives: "20 g", capres: "10 g", citrons: "0.5", huile: "15 ml", sel: "1 pincée", poivre: "1 pincée", ail: "1 gousse" },
      { nb: 2, poulpe: "400 g", olives: "40 g", capres: "20 g", citrons: "1", huile: "30 ml", sel: "1 pincée", poivre: "1 pincée", ail: "2 gousses" },
      { nb: 3, poulpe: "600 g", olives: "60 g", capres: "30 g", citrons: "1.5", huile: "45 ml", sel: "1 pincée", poivre: "1 pincée", ail: "3 gousses" },
      { nb: 4, poulpe: "800 g", olives: "80 g", capres: "40 g", citrons: "2", huile: "60 ml", sel: "1 pincée", poivre: "1 pincée", ail: "4 gousses" },
      { nb: 5, poulpe: "1000 g", olives: "100 g", capres: "50 g", citrons: "2.5", huile: "75 ml", sel: "1 pincée", poivre: "1 pincée", ail: "5 gousses" },
      { nb: 6, poulpe: "1200 g", olives: "120 g", capres: "60 g", citrons: "3", huile: "90 ml", sel: "1 pincée", poivre: "1 pincée", ail: "6 gousses" },
      { nb: 7, poulpe: "1400 g", olives: "140 g", capres: "70 g", citrons: "3.5", huile: "105 ml", sel: "1 pincée", poivre: "1 pincée", ail: "7 gousses" },
      { nb: 8, poulpe: "1600 g", olives: "160 g", capres: "80 g", citrons: "4", huile: "120 ml", sel: "1 pincée", poivre: "1 pincée", ail: "8 gousses" },
      { nb: 9, poulpe: "1800 g", olives: "180 g", capres: "90 g", citrons: "4.5", huile: "135 ml", sel: "1 pincée", poivre: "1 pincée", ail: "9 gousses" },
      { nb: 10, poulpe: "2000 g", olives: "200 g", capres: "100 g", citrons: "5", huile: "150 ml", sel: "1 pincée", poivre: "1 pincée", ail: "10 gousses" },
      { nb: 11, poulpe: "2200 g", olives: "220 g", capres: "110 g", citrons: "5.5", huile: "165 ml", sel: "1 pincée", poivre: "1 pincée", ail: "11 gousses" },
      { nb: 12, poulpe: "2400 g", olives: "240 g", capres: "120 g", citrons: "6", huile: "180 ml", sel: "1 pincée", poivre: "1 pincée", ail: "12 gousses" },
      { nb: 13, poulpe: "2600 g", olives: "260 g", capres: "130 g", citrons: "6.5", huile: "195 ml", sel: "1 pincée", poivre: "1 pincée", ail: "13 gousses" },
      { nb: 14, poulpe: "2800 g", olives: "280 g", capres: "140 g", citrons: "7", huile: "210 ml", sel: "1 pincée", poivre: "1 pincée", ail: "14 gousses" },
      { nb: 15, poulpe: "3000 g", olives: "300 g", capres: "150 g", citrons: "7.5", huile: "225 ml", sel: "1 pincée", poivre: "1 pincée", ail: "15 gousses" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🐙", titre: "Cuire le poulpe", detail: "Plonger le poulpe dans l'eau bouillante avec laurier, sel, grains de poivre. Laisser mijoter. ASTUCE CHEF : couvercle entrouvert pour une meilleure réduction.", badge: "⏱ 1h" },
      { icone: "✂️", titre: "Découper", detail: "Laisser refroidir. Couper les tentacules en rondelles. Réserver les plus belles pour la présentation. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🍯", titre: "Préparer la marinade", detail: "Mélanger huile d'olive, jus de citron, ail, persil, câpres, olives, origan. Assaisonner. Sel, poivre généreusement. Goûter et ajuster TOUJOURS.", badge: null },
      { icone: "⏳", titre: "Mariner et servir", detail: "Mélanger poulpe et marinade. Laisser reposer 30 min. Servir sur lit de roquette. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 30 min" }
    ]
  },
  saladechorizofeves: {
    cat: "salades", saisons: ["printemps"], pays: "espagne",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🟢",
    description: "Salade chorizo-fèves — un printemps espagnol dans l'assiette. Fèves fraîches, chorizo doux poêlé, jambon Serrano et feta. Vivifiant.",
    tableauSaladeChorizoFeves: [
      { nb: 1, feves: "150 g", chorizo: "50 g", serrano: "2", feta: "40 g", menthe: "3 c.à.c", huile: "1 c.à.s", citron: "2/7", poivre: "1 pincée" },
      { nb: 2, feves: "300 g", chorizo: "100 g", serrano: "4", feta: "80 g", menthe: "6 c.à.c", huile: "2 c.à.s", citron: "3/5", poivre: "1 pincée" },
      { nb: 3, feves: "450 g", chorizo: "150 g", serrano: "6", feta: "120 g", menthe: "9 c.à.c", huile: "3 c.à.s", citron: "7/8", poivre: "1 pincée" },
      { nb: 4, feves: "600 g", chorizo: "200 g", serrano: "8", feta: "160 g", menthe: "12 c.à.c", huile: "4 c.à.s", citron: "6/5", poivre: "1 pincée" },
      { nb: 5, feves: "750 g", chorizo: "250 g", serrano: "10", feta: "200 g", menthe: "15 c.à.c", huile: "5 c.à.s", citron: "1½", poivre: "1 pincée" },
      { nb: 6, feves: "900 g", chorizo: "300 g", serrano: "12", feta: "240 g", menthe: "18 c.à.c", huile: "6 c.à.s", citron: "9/5", poivre: "1 pincée" },
      { nb: 7, feves: "1.1 kg", chorizo: "350 g", serrano: "14", feta: "280 g", menthe: "21 c.à.c", huile: "7 c.à.s", citron: "17/8", poivre: "1 pincée" },
      { nb: 8, feves: "1.2 kg", chorizo: "400 g", serrano: "16", feta: "320 g", menthe: "24 c.à.c", huile: "8 c.à.s", citron: "12/5", poivre: "1 pincée" },
      { nb: 9, feves: "1.4 kg", chorizo: "450 g", serrano: "18", feta: "360 g", menthe: "27 c.à.c", huile: "9 c.à.s", citron: "19/7", poivre: "1 pincée" },
      { nb: 10, feves: "1.5 kg", chorizo: "500 g", serrano: "20", feta: "400 g", menthe: "30 c.à.c", huile: "10 c.à.s", citron: "3", poivre: "1 pincée" },
      { nb: 11, feves: "1.6 kg", chorizo: "550 g", serrano: "22", feta: "440 g", menthe: "33 c.à.c", huile: "11 c.à.s", citron: "23/7", poivre: "1 pincée" },
      { nb: 12, feves: "1.8 kg", chorizo: "600 g", serrano: "24", feta: "480 g", menthe: "36 c.à.c", huile: "12 c.à.s", citron: "18/5", poivre: "1 pincée" },
      { nb: 13, feves: "1.9 kg", chorizo: "650 g", serrano: "26", feta: "520 g", menthe: "39 c.à.c", huile: "13 c.à.s", citron: "31/8", poivre: "1 pincée" },
      { nb: 14, feves: "2.1 kg", chorizo: "700 g", serrano: "28", feta: "560 g", menthe: "42 c.à.c", huile: "14 c.à.s", citron: "21/5", poivre: "1 pincée" },
      { nb: 15, feves: "2.2 kg", chorizo: "750 g", serrano: "30", feta: "600 g", menthe: "45 c.à.c", huile: "15 c.à.s", citron: "4½", poivre: "1 pincée" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🟢", titre: "Éplucher les fèves", detail: "Écosser les fèves fraîches. Blanchir 1 min, plonger dans l'eau glacée, enlever la deuxième peau (plus tendre !). ASTUCE PRO : eau bouillante salée 2-3 min puis eau glacée. Arrête la cuisson et garde la couleur vive.", badge: "⏱ 10 min" },
      { icone: "🌶️", titre: "Chorizo", detail: "Couper le chorizo doux en rondelles. Le poêler à sec 2 min par face pour libérer l'huile parfumée. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 4 min" },
      { icone: "🥗", titre: "Dresser", detail: "Disposer les fèves, le chorizo et son huile, le jambon Serrano en chiffonnade, la feta émiettée.", badge: null },
      { icone: "🌿", titre: "Finition", detail: "Parsemer de menthe fraîche, arroser d'huile d'olive et jus de citron. Poivre du moulin généreux. Servir tiède.", badge: null }
    ]
  },
  tabboulehlibanais: {
    cat: "salades", saisons: ["ete"], pays: "liban",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Taboulé libanais authentique — l'inverse du français. Énormément de persil, peu de boulghour, tomate, menthe, citron. Vert et frais !",
    tableauTabbouleh: [
      { nb: 1, persil: "1", boulghour: "15 g", tomate: "1", oignonNouveau: "1", menthe: "5 c.à.c", citron: "½", huile: "1 c.à.s", sumac: "0.3 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 2, persil: "2", boulghour: "30 g", tomate: "2", oignonNouveau: "2", menthe: "10 c.à.c", citron: "1", huile: "2 c.à.s", sumac: "0.6 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 3, persil: "3", boulghour: "45 g", tomate: "3", oignonNouveau: "3", menthe: "15 c.à.c", citron: "1½", huile: "3 c.à.s", sumac: "0.9 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 4, persil: "4", boulghour: "60 g", tomate: "4", oignonNouveau: "4", menthe: "20 c.à.c", citron: "2", huile: "4 c.à.s", sumac: "1.2 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 5, persil: "5", boulghour: "75 g", tomate: "5", oignonNouveau: "5", menthe: "25 c.à.c", citron: "2½", huile: "5 c.à.s", sumac: "1.5 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 6, persil: "6", boulghour: "90 g", tomate: "6", oignonNouveau: "6", menthe: "30 c.à.c", citron: "3", huile: "6 c.à.s", sumac: "1.8 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 7, persil: "7", boulghour: "105 g", tomate: "7", oignonNouveau: "7", menthe: "35 c.à.c", citron: "3½", huile: "7 c.à.s", sumac: "2.1 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 8, persil: "8", boulghour: "120 g", tomate: "8", oignonNouveau: "8", menthe: "40 c.à.c", citron: "4", huile: "8 c.à.s", sumac: "2.4 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 9, persil: "9", boulghour: "135 g", tomate: "9", oignonNouveau: "9", menthe: "45 c.à.c", citron: "4½", huile: "9 c.à.s", sumac: "2.7 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 10, persil: "10", boulghour: "150 g", tomate: "10", oignonNouveau: "10", menthe: "50 c.à.c", citron: "5", huile: "10 c.à.s", sumac: "3 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 11, persil: "11", boulghour: "165 g", tomate: "11", oignonNouveau: "11", menthe: "55 c.à.c", citron: "5½", huile: "11 c.à.s", sumac: "3.3 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 12, persil: "12", boulghour: "180 g", tomate: "12", oignonNouveau: "12", menthe: "60 c.à.c", citron: "6", huile: "12 c.à.s", sumac: "3.6 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 13, persil: "13", boulghour: "195 g", tomate: "13", oignonNouveau: "13", menthe: "65 c.à.c", citron: "6½", huile: "13 c.à.s", sumac: "3.9 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 14, persil: "14", boulghour: "210 g", tomate: "14", oignonNouveau: "14", menthe: "70 c.à.c", citron: "7", huile: "14 c.à.s", sumac: "4.2 c.à.c", sel: "1 pincée", poivre: "1 pincée" },
      { nb: 15, persil: "15", boulghour: "225 g", tomate: "15", oignonNouveau: "15", menthe: "75 c.à.c", citron: "7½", huile: "15 c.à.s", sumac: "4.5 c.à.c", sel: "1 pincée", poivre: "1 pincée" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Hydrater le boulghour", detail: "Faire tremper le boulghour FIN 10 min dans le jus d'une moitié de citron (pas d'eau !).", badge: "⏱ 10 min" },
      { icone: "🌿", titre: "Ciseler les herbes", detail: "Le secret : énormément de persil plat (1 botte par personne) ciselé très finement au couteau (pas d'hachoir, ça noircit).", badge: "⏱ 15 min" },
      { icone: "🍅", titre: "Légumes", detail: "Couper la tomate en très petits dés (sans pépins). Émincer l'oignon nouveau finement.", badge: null },
      { icone: "🥗", titre: "Mélanger", detail: "Mélanger tous les ingrédients : persil, menthe, tomate, oignon, boulghour. Assaisonner huile, citron, sel, poivre.", badge: null },
      { icone: "❄️", titre: "Reposer", detail: "Réfrigérer 30 min minimum. Servir bien froid avec des feuilles de laitue romaine en cuillère.", badge: "⏱ 30 min" }
    ]
  },
  poissoncrutahitien: {
    cat: "salades", saisons: ["ete"], pays: "polynesie",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🐟",
    description: "Poisson cru à la tahitienne — thon ou daurade marinés au lait de coco et citron vert. Carotte, concombre, tomate. Soleil garanti.",
    tableauPoissonTahiti: [
      { nb: 1, poisson: "120 g", laitcoco: "60 ml", citronvert: "1", carotte: "½", concombre: "2/7", tomate: "1", oignon: "2/7", ail: "½" },
      { nb: 2, poisson: "240 g", laitcoco: "120 ml", citronvert: "2", carotte: "1", concombre: "3/5", tomate: "2", oignon: "3/5", ail: "1" },
      { nb: 3, poisson: "360 g", laitcoco: "180 ml", citronvert: "3", carotte: "1½", concombre: "7/8", tomate: "3", oignon: "7/8", ail: "1½" },
      { nb: 4, poisson: "480 g", laitcoco: "240 ml", citronvert: "4", carotte: "2", concombre: "6/5", tomate: "4", oignon: "6/5", ail: "2" },
      { nb: 5, poisson: "600 g", laitcoco: "300 ml", citronvert: "5", carotte: "2½", concombre: "1½", tomate: "5", oignon: "1½", ail: "2½" },
      { nb: 6, poisson: "720 g", laitcoco: "360 ml", citronvert: "6", carotte: "3", concombre: "9/5", tomate: "6", oignon: "9/5", ail: "3" },
      { nb: 7, poisson: "840 g", laitcoco: "420 ml", citronvert: "7", carotte: "3½", concombre: "17/8", tomate: "7", oignon: "17/8", ail: "3½" },
      { nb: 8, poisson: "960 g", laitcoco: "480 ml", citronvert: "8", carotte: "4", concombre: "12/5", tomate: "8", oignon: "12/5", ail: "4" },
      { nb: 9, poisson: "1.1 kg", laitcoco: "540 ml", citronvert: "9", carotte: "4½", concombre: "19/7", tomate: "9", oignon: "19/7", ail: "4½" },
      { nb: 10, poisson: "1.2 kg", laitcoco: "600 ml", citronvert: "10", carotte: "5", concombre: "3", tomate: "10", oignon: "3", ail: "5" },
      { nb: 11, poisson: "1.3 kg", laitcoco: "660 ml", citronvert: "11", carotte: "5½", concombre: "23/7", tomate: "11", oignon: "23/7", ail: "5½" },
      { nb: 12, poisson: "1.4 kg", laitcoco: "720 ml", citronvert: "12", carotte: "6", concombre: "18/5", tomate: "12", oignon: "18/5", ail: "6" },
      { nb: 13, poisson: "1.6 kg", laitcoco: "780 ml", citronvert: "13", carotte: "6½", concombre: "31/8", tomate: "13", oignon: "31/8", ail: "6½" },
      { nb: 14, poisson: "1.7 kg", laitcoco: "840 ml", citronvert: "14", carotte: "7", concombre: "21/5", tomate: "14", oignon: "21/5", ail: "7" },
      { nb: 15, poisson: "1.8 kg", laitcoco: "900 ml", citronvert: "15", carotte: "7½", concombre: "4½", tomate: "15", oignon: "4½", ail: "7½" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🐟", titre: "Couper le poisson", detail: "Couper le thon ou la daurade très frais en dés de 1,5 cm. Saler généreusement. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null },
      { icone: "🍋", titre: "Citron", detail: "Arroser de jus de citron vert (3 citrons pour 4 personnes). Mélanger doucement, laisser 5 min seulement.", badge: "⏱ 5 min" },
      { icone: "🥥", titre: "Lait de coco", detail: "Égoutter le poisson. Verser le lait de coco froid bien battu, mélanger délicatement.", badge: null },
      { icone: "🥕", titre: "Légumes", detail: "Ajouter carotte râpée, concombre en cubes, tomate en cubes, oignon rouge émincé, ail râpé. Mélanger.", badge: null },
      { icone: "❄️", titre: "Servir", detail: "Servir bien frais, idéalement dans une noix de coco si vous en avez ! Plat \"Ia Ora Na\" du dimanche.", badge: null }
    ]
  },
  saladewasabi: {
    cat: "salades", saisons: ["ete"], pays: "japon",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🥒",
    description: "Salade concombre-wasabi — sunomono japonais relevé au wasabi. Croquant, vif, frais. Parfait en accompagnement ou apéritif léger.",
    tableauSaladeWasabi: [
      { nb: 1, concombre: "1", wasabi: "0.3 c.à.c", vinaigreRiz: "1 c.à.s", sojaSauce: "1 c.à.c", sucre: "0.5 c.à.c", sesame: "1 c.à.c", gingembre: "0.3 c.à.c", mirin: "1 c.à.c" },
      { nb: 2, concombre: "2", wasabi: "0.6 c.à.c", vinaigreRiz: "2 c.à.s", sojaSauce: "2 c.à.c", sucre: "1 c.à.c", sesame: "2 c.à.c", gingembre: "0.6 c.à.c", mirin: "2 c.à.c" },
      { nb: 3, concombre: "3", wasabi: "0.9 c.à.c", vinaigreRiz: "3 c.à.s", sojaSauce: "3 c.à.c", sucre: "1.5 c.à.c", sesame: "3 c.à.c", gingembre: "0.9 c.à.c", mirin: "3 c.à.c" },
      { nb: 4, concombre: "4", wasabi: "1.2 c.à.c", vinaigreRiz: "4 c.à.s", sojaSauce: "4 c.à.c", sucre: "2 c.à.c", sesame: "4 c.à.c", gingembre: "1.2 c.à.c", mirin: "4 c.à.c" },
      { nb: 5, concombre: "5", wasabi: "1.5 c.à.c", vinaigreRiz: "5 c.à.s", sojaSauce: "5 c.à.c", sucre: "2.5 c.à.c", sesame: "5 c.à.c", gingembre: "1.5 c.à.c", mirin: "5 c.à.c" },
      { nb: 6, concombre: "6", wasabi: "1.8 c.à.c", vinaigreRiz: "6 c.à.s", sojaSauce: "6 c.à.c", sucre: "3 c.à.c", sesame: "6 c.à.c", gingembre: "1.8 c.à.c", mirin: "6 c.à.c" },
      { nb: 7, concombre: "7", wasabi: "2.1 c.à.c", vinaigreRiz: "7 c.à.s", sojaSauce: "7 c.à.c", sucre: "3.5 c.à.c", sesame: "7 c.à.c", gingembre: "2.1 c.à.c", mirin: "7 c.à.c" },
      { nb: 8, concombre: "8", wasabi: "2.4 c.à.c", vinaigreRiz: "8 c.à.s", sojaSauce: "8 c.à.c", sucre: "4 c.à.c", sesame: "8 c.à.c", gingembre: "2.4 c.à.c", mirin: "8 c.à.c" },
      { nb: 9, concombre: "9", wasabi: "2.7 c.à.c", vinaigreRiz: "9 c.à.s", sojaSauce: "9 c.à.c", sucre: "4.5 c.à.c", sesame: "9 c.à.c", gingembre: "2.7 c.à.c", mirin: "9 c.à.c" },
      { nb: 10, concombre: "10", wasabi: "3 c.à.c", vinaigreRiz: "10 c.à.s", sojaSauce: "10 c.à.c", sucre: "5 c.à.c", sesame: "10 c.à.c", gingembre: "3 c.à.c", mirin: "10 c.à.c" },
      { nb: 11, concombre: "11", wasabi: "3.3 c.à.c", vinaigreRiz: "11 c.à.s", sojaSauce: "11 c.à.c", sucre: "5.5 c.à.c", sesame: "11 c.à.c", gingembre: "3.3 c.à.c", mirin: "11 c.à.c" },
      { nb: 12, concombre: "12", wasabi: "3.6 c.à.c", vinaigreRiz: "12 c.à.s", sojaSauce: "12 c.à.c", sucre: "6 c.à.c", sesame: "12 c.à.c", gingembre: "3.6 c.à.c", mirin: "12 c.à.c" },
      { nb: 13, concombre: "13", wasabi: "3.9 c.à.c", vinaigreRiz: "13 c.à.s", sojaSauce: "13 c.à.c", sucre: "6.5 c.à.c", sesame: "13 c.à.c", gingembre: "3.9 c.à.c", mirin: "13 c.à.c" },
      { nb: 14, concombre: "14", wasabi: "4.2 c.à.c", vinaigreRiz: "14 c.à.s", sojaSauce: "14 c.à.c", sucre: "7 c.à.c", sesame: "14 c.à.c", gingembre: "4.2 c.à.c", mirin: "14 c.à.c" },
      { nb: 15, concombre: "15", wasabi: "4.5 c.à.c", vinaigreRiz: "15 c.à.s", sojaSauce: "15 c.à.c", sucre: "7.5 c.à.c", sesame: "15 c.à.c", gingembre: "4.5 c.à.c", mirin: "15 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥒", titre: "Préparer concombre", detail: "Couper le concombre en rondelles très fines à la mandoline (1-2 mm). Saler généreusement, laisser dégorger 10 min. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: "⏱ 10 min" },
      { icone: "💧", titre: "Essorer", detail: "Bien presser le concombre dans un torchon propre pour éliminer un maximum d'eau.", badge: null },
      { icone: "🥣", titre: "Sauce wasabi", detail: "Mélanger vinaigre de riz, sauce soja, sucre, mirin, wasabi (dosez selon goût), gingembre râpé.", badge: null },
      { icone: "🥗", titre: "Mélanger", detail: "Verser la sauce sur le concombre. Mélanger délicatement.", badge: null },
      { icone: "🌱", titre: "Finition", detail: "Parsemer de graines de sésame toastées. Servir immédiatement, très frais.", badge: null }
    ]
  },
  saladeburrata: {
    cat: "salades", saisons: ["ete","printemps"], pays: "italie",
    base: 2,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🧀",
    description: "Salade burrata italienne — entrée fraîcheur ultra-simple : burrata crémeuse, tomates anciennes, pesto, basilic, huile d'olive. La burrata est la star, pas besoin de plus.",
    tableauSaladeBurrata: [
      { nb: 1, burrata: "½", tomates: "150 g", pesto: "15 g", basilic: "3 g", huileolive: "10 ml", balsamique: "5 ml", sel: "1 pincée", poivre: "0.1 c.à.c" },
      { nb: 2, burrata: "1", tomates: "300 g", pesto: "30 g", basilic: "6 g", huileolive: "20 ml", balsamique: "10 ml", sel: "1 pincée", poivre: "0.2 c.à.c" },
      { nb: 3, burrata: "1½", tomates: "450 g", pesto: "45 g", basilic: "9 g", huileolive: "30 ml", balsamique: "15 ml", sel: "1 pincée", poivre: "0.3 c.à.c" },
      { nb: 4, burrata: "2", tomates: "600 g", pesto: "60 g", basilic: "12 g", huileolive: "40 ml", balsamique: "20 ml", sel: "1 pincée", poivre: "0.4 c.à.c" },
      { nb: 5, burrata: "2½", tomates: "750 g", pesto: "75 g", basilic: "15 g", huileolive: "50 ml", balsamique: "25 ml", sel: "1 pincée", poivre: "0.5 c.à.c" },
      { nb: 6, burrata: "3", tomates: "900 g", pesto: "90 g", basilic: "18 g", huileolive: "60 ml", balsamique: "30 ml", sel: "1 pincée", poivre: "0.6 c.à.c" },
      { nb: 7, burrata: "3½", tomates: "1.1 kg", pesto: "105 g", basilic: "21 g", huileolive: "70 ml", balsamique: "35 ml", sel: "1 pincée", poivre: "0.7 c.à.c" },
      { nb: 8, burrata: "4", tomates: "1.2 kg", pesto: "120 g", basilic: "24 g", huileolive: "80 ml", balsamique: "40 ml", sel: "1 pincée", poivre: "0.8 c.à.c" },
      { nb: 9, burrata: "4½", tomates: "1.4 kg", pesto: "135 g", basilic: "27 g", huileolive: "90 ml", balsamique: "45 ml", sel: "1 pincée", poivre: "0.9 c.à.c" },
      { nb: 10, burrata: "5", tomates: "1.5 kg", pesto: "150 g", basilic: "30 g", huileolive: "100 ml", balsamique: "50 ml", sel: "1 pincée", poivre: "1 c.à.c" },
      { nb: 11, burrata: "5½", tomates: "1.6 kg", pesto: "165 g", basilic: "33 g", huileolive: "110 ml", balsamique: "55 ml", sel: "1 pincée", poivre: "1.1 c.à.c" },
      { nb: 12, burrata: "6", tomates: "1.8 kg", pesto: "180 g", basilic: "36 g", huileolive: "120 ml", balsamique: "60 ml", sel: "1 pincée", poivre: "1.2 c.à.c" },
      { nb: 13, burrata: "6½", tomates: "1.9 kg", pesto: "195 g", basilic: "39 g", huileolive: "130 ml", balsamique: "65 ml", sel: "1 pincée", poivre: "1.3 c.à.c" },
      { nb: 14, burrata: "7", tomates: "2.1 kg", pesto: "210 g", basilic: "42 g", huileolive: "140 ml", balsamique: "70 ml", sel: "1 pincée", poivre: "1.4 c.à.c" },
      { nb: 15, burrata: "7½", tomates: "2.2 kg", pesto: "225 g", basilic: "45 g", huileolive: "150 ml", balsamique: "75 ml", sel: "1 pincée", poivre: "1.5 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧀", titre: "Choisir la burrata", detail: "ESSENTIEL : burrata FRAÎCHE des Pouilles (DOP idéalement). À sortir 30 MIN du frigo avant service (cœur tiède = crème coulante). NE JAMAIS servir froide.", badge: "⏱ 30 min" },
      { icone: "🍅", titre: "Tomates anciennes", detail: "SECRET DE LA SALADE : utiliser un MIX de tomates anciennes (cœur de bœuf, ananas, noire de Crimée, green zebra). Couleurs et tailles variées = visuel + saveurs. À défaut : tomates grappe MÛRES.", badge: "⏱ 5 min" },
      { icone: "🔪", titre: "Découpe tomates", detail: "Couper les tomates en TRANCHES IRRÉGULIÈRES selon leur forme (rondelles épaisses, quartiers, cubes). ASTUCE CHEF : on cherche l'effet rustique et coloré.", badge: "⏱ 5 min" },
      { icone: "🧂", titre: "Saler les tomates", detail: "ASTUCE PRO : saler les tomates 5 min AVANT de servir. Le sel fait sortir l'eau et concentre la saveur (= jus à récupérer).", badge: "⏱ 5 min" },
      { icone: "🥗", titre: "Dressage", detail: "Dans un grand plat ou assiette : disposer les tomates en rosace ou en désordre artistique. Réserver le jus.", badge: "⏱ 3 min" },
      { icone: "🧀", titre: "Burrata trônante", detail: "Poser la burrata ENTIÈRE au centre. Au moment de servir : OUVRIR la burrata en croix au couteau. La crème (stracciatella) doit couler sur les tomates. Magique.", badge: "⏱ 1 min" },
      { icone: "🌿", titre: "Le pesto", detail: "Ajouter quelques cuillerées de pesto frais autour. ASTUCE CHEF : faire son pesto maison (basilic + parmesan + pignons + ail + huile d'olive) pour le top.", badge: "⏱ 2 min" },
      { icone: "✨", titre: "Touches finales", detail: "Drizzle généreux d'HUILE D'OLIVE EXTRA-VIERGE de qualité (toute la salade en dépend). Quelques gouttes de réduction balsamique (15 ans). Fleur de sel. Poivre du moulin.", badge: null },
      { icone: "🌿", titre: "Décor", detail: "Quelques feuilles de basilic FRAIS (jamais ciselé — entier pour le visuel). Option : pignons grillés ou graines de pin. Servir IMMÉDIATEMENT.", badge: "⏱ 1 min" },
      { icone: "🥖", titre: "Service italien", detail: "Accompagner de pain ciabatta toasté ou focaccia tiède pour saucer la crème et le jus de tomate. Vin : rosé de Provence ou Trebbiano. Mangiare !", badge: null }
    ]
  },
  coleslaw: {
    cat: "salades", pays: "usa",
    base: 6,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥬",
    description: "Coleslaw — la salade de chou américaine, croquante et crémeuse : chou blanc, carotte et sauce mayo-vinaigre légèrement sucrée. Parfaite avec un barbecue.",
    tableauColeslaw: [
      { nb: 1, chou: "60 g", carotte: "25 g", mayonnaise: "15 g", vinaigre: "½ c.à.c", moutarde: "¼ c.à.c", sucre: "¼ c.à.c" },
      { nb: 2, chou: "120 g", carotte: "50 g", mayonnaise: "30 g", vinaigre: "1 c.à.c", moutarde: "½ c.à.c", sucre: "½ c.à.c" },
      { nb: 3, chou: "180 g", carotte: "75 g", mayonnaise: "45 g", vinaigre: "1½ c.à.c", moutarde: "½ c.à.c", sucre: "½ c.à.c" },
      { nb: 4, chou: "240 g", carotte: "100 g", mayonnaise: "60 g", vinaigre: "2 c.à.c", moutarde: "¾ c.à.c", sucre: "¾ c.à.c" },
      { nb: 5, chou: "300 g", carotte: "125 g", mayonnaise: "75 g", vinaigre: "2½ c.à.c", moutarde: "1 c.à.c", sucre: "1 c.à.c" },
      { nb: 6, chou: "360 g", carotte: "150 g", mayonnaise: "90 g", vinaigre: "3 c.à.c", moutarde: "1¼ c.à.c", sucre: "1¼ c.à.c" },
      { nb: 7, chou: "420 g", carotte: "175 g", mayonnaise: "105 g", vinaigre: "3½ c.à.c", moutarde: "1½ c.à.c", sucre: "1½ c.à.c" },
      { nb: 8, chou: "480 g", carotte: "200 g", mayonnaise: "120 g", vinaigre: "4 c.à.c", moutarde: "1½ c.à.c", sucre: "1½ c.à.c" },
      { nb: 9, chou: "540 g", carotte: "225 g", mayonnaise: "135 g", vinaigre: "4½ c.à.c", moutarde: "1¾ c.à.c", sucre: "1¾ c.à.c" },
      { nb: 10, chou: "600 g", carotte: "250 g", mayonnaise: "150 g", vinaigre: "5 c.à.c", moutarde: "2 c.à.c", sucre: "2 c.à.c" },
      { nb: 11, chou: "660 g", carotte: "275 g", mayonnaise: "165 g", vinaigre: "5½ c.à.c", moutarde: "2¼ c.à.c", sucre: "2¼ c.à.c" },
      { nb: 12, chou: "720 g", carotte: "300 g", mayonnaise: "180 g", vinaigre: "6 c.à.c", moutarde: "2½ c.à.c", sucre: "2½ c.à.c" },
      { nb: 13, chou: "780 g", carotte: "325 g", mayonnaise: "195 g", vinaigre: "6½ c.à.c", moutarde: "2½ c.à.c", sucre: "2½ c.à.c" },
      { nb: 14, chou: "840 g", carotte: "350 g", mayonnaise: "210 g", vinaigre: "7 c.à.c", moutarde: "2¾ c.à.c", sucre: "2¾ c.à.c" },
      { nb: 15, chou: "900 g", carotte: "375 g", mayonnaise: "225 g", vinaigre: "7½ c.à.c", moutarde: "3 c.à.c", sucre: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔪", titre: "Émincer", detail: "Émincer le chou TRÈS finement, râper la carotte. ASTUCE : saler le chou 10 min puis l'essorer, il reste croquant sans rendre d'eau.", badge: "⏱ 10 min" },
      { icone: "🥄", titre: "Sauce", detail: "Mélanger mayonnaise, vinaigre, moutarde, une pointe de sucre. SECRET : un filet de citron pour la fraîcheur.", badge: "⏱ 3 min" },
      { icone: "🥗", titre: "Mélanger", detail: "Enrober les légumes de sauce, poivrer.", badge: "⏱ 2 min" },
      { icone: "🧊", titre: "Reposer", detail: "CLÉ : 1h au frais minimum, les saveurs se lient et le chou s'attendrit juste ce qu'il faut.", badge: null }
    ]
  },
  saladewaldorf: {
    cat: "salades", pays: "usa",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍎",
    description: "Salade Waldorf — l'élégante salade new-yorkaise : pomme, céleri, noix et raisins secs liés d'une sauce crémeuse au citron. Croquante et fraîche.",
    tableauSaladeWaldorf: [
      { nb: 1, pomme: "½", celeri: "25 g", noix: "10 g", raisinsec: "8 g", mayonnaise: "12 g", citron: "¼ c.à.c" },
      { nb: 2, pomme: "1", celeri: "50 g", noix: "20 g", raisinsec: "16 g", mayonnaise: "24 g", citron: "½ c.à.c" },
      { nb: 3, pomme: "1½", celeri: "75 g", noix: "30 g", raisinsec: "24 g", mayonnaise: "36 g", citron: "½ c.à.c" },
      { nb: 4, pomme: "2", celeri: "100 g", noix: "40 g", raisinsec: "32 g", mayonnaise: "48 g", citron: "¾ c.à.c" },
      { nb: 5, pomme: "2½", celeri: "125 g", noix: "50 g", raisinsec: "40 g", mayonnaise: "60 g", citron: "1 c.à.c" },
      { nb: 6, pomme: "3", celeri: "150 g", noix: "60 g", raisinsec: "48 g", mayonnaise: "72 g", citron: "1¼ c.à.c" },
      { nb: 7, pomme: "3½", celeri: "175 g", noix: "70 g", raisinsec: "56 g", mayonnaise: "84 g", citron: "1½ c.à.c" },
      { nb: 8, pomme: "4", celeri: "200 g", noix: "80 g", raisinsec: "64 g", mayonnaise: "96 g", citron: "1½ c.à.c" },
      { nb: 9, pomme: "4½", celeri: "225 g", noix: "90 g", raisinsec: "72 g", mayonnaise: "108 g", citron: "1¾ c.à.c" },
      { nb: 10, pomme: "5", celeri: "250 g", noix: "100 g", raisinsec: "80 g", mayonnaise: "120 g", citron: "2 c.à.c" },
      { nb: 11, pomme: "5½", celeri: "275 g", noix: "110 g", raisinsec: "88 g", mayonnaise: "132 g", citron: "2¼ c.à.c" },
      { nb: 12, pomme: "6", celeri: "300 g", noix: "120 g", raisinsec: "96 g", mayonnaise: "144 g", citron: "2½ c.à.c" },
      { nb: 13, pomme: "6½", celeri: "325 g", noix: "130 g", raisinsec: "104 g", mayonnaise: "156 g", citron: "2½ c.à.c" },
      { nb: 14, pomme: "7", celeri: "350 g", noix: "140 g", raisinsec: "112 g", mayonnaise: "168 g", citron: "2¾ c.à.c" },
      { nb: 15, pomme: "7½", celeri: "375 g", noix: "150 g", raisinsec: "120 g", mayonnaise: "180 g", citron: "3 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍎", titre: "Couper", detail: "Pommes (avec la peau) et céleri en petits dés. ASTUCE : citronner les pommes tout de suite pour qu'elles ne noircissent pas.", badge: "⏱ 6 min" },
      { icone: "🥄", titre: "Sauce", detail: "Mélanger mayonnaise (ou yaourt en version légère) + jus de citron. SECRET : une pointe de moutarde douce.", badge: "⏱ 2 min" },
      { icone: "🥗", titre: "Assembler", detail: "Mêler pommes, céleri, noix concassées et raisins secs à la sauce.", badge: "⏱ 3 min" },
      { icone: "🍽️", titre: "Servir", detail: "ASTUCE CHEF : servir sur feuilles de salade, ajouter les noix au dernier moment pour le croquant.", badge: null }
    ]
  },
  saladebetteravechevre: {
    cat: "salades", pays: "france",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🧀",
    description: "Salade betterave & chèvre — douceur terreuse de la betterave, crémeux du chèvre, croquant des noix, sur un lit de roquette. Couleurs et contrastes.",
    tableauSaladeBetteraveChevre: [
      { nb: 1, betterave: "50 g", chevre: "25 g", roquette: "20 g", noix: "8 g", huiledolive: "½ c.à.c", miel: "¼ c.à.c" },
      { nb: 2, betterave: "100 g", chevre: "50 g", roquette: "40 g", noix: "16 g", huiledolive: "1 c.à.c", miel: "½ c.à.c" },
      { nb: 3, betterave: "150 g", chevre: "75 g", roquette: "60 g", noix: "24 g", huiledolive: "1½ c.à.c", miel: "1 c.à.c" },
      { nb: 4, betterave: "200 g", chevre: "100 g", roquette: "80 g", noix: "32 g", huiledolive: "2 c.à.c", miel: "1¼ c.à.c" },
      { nb: 5, betterave: "250 g", chevre: "125 g", roquette: "100 g", noix: "40 g", huiledolive: "2½ c.à.c", miel: "1½ c.à.c" },
      { nb: 6, betterave: "300 g", chevre: "150 g", roquette: "120 g", noix: "48 g", huiledolive: "3 c.à.c", miel: "1¾ c.à.c" },
      { nb: 7, betterave: "350 g", chevre: "175 g", roquette: "140 g", noix: "56 g", huiledolive: "3½ c.à.c", miel: "2 c.à.c" },
      { nb: 8, betterave: "400 g", chevre: "200 g", roquette: "160 g", noix: "64 g", huiledolive: "4 c.à.c", miel: "2½ c.à.c" },
      { nb: 9, betterave: "450 g", chevre: "225 g", roquette: "180 g", noix: "72 g", huiledolive: "4½ c.à.c", miel: "2¾ c.à.c" },
      { nb: 10, betterave: "500 g", chevre: "250 g", roquette: "200 g", noix: "80 g", huiledolive: "5 c.à.c", miel: "3 c.à.c" },
      { nb: 11, betterave: "550 g", chevre: "275 g", roquette: "220 g", noix: "88 g", huiledolive: "5½ c.à.c", miel: "3¼ c.à.c" },
      { nb: 12, betterave: "600 g", chevre: "300 g", roquette: "240 g", noix: "96 g", huiledolive: "6 c.à.c", miel: "3½ c.à.c" },
      { nb: 13, betterave: "650 g", chevre: "325 g", roquette: "260 g", noix: "104 g", huiledolive: "6½ c.à.c", miel: "4 c.à.c" },
      { nb: 14, betterave: "700 g", chevre: "350 g", roquette: "280 g", noix: "112 g", huiledolive: "7 c.à.c", miel: "4¼ c.à.c" },
      { nb: 15, betterave: "750 g", chevre: "375 g", roquette: "300 g", noix: "120 g", huiledolive: "7½ c.à.c", miel: "4½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🔪", titre: "Préparer", detail: "Couper la betterave cuite en dés ou fines tranches. ASTUCE : les betteraves cuites sous vide font gagner du temps.", badge: "⏱ 4 min" },
      { icone: "🥗", titre: "Dresser", detail: "Lit de roquette, dés de betterave, chèvre émietté, noix concassées.", badge: "⏱ 4 min" },
      { icone: "🍯", titre: "Vinaigrette", detail: "SECRET : vinaigrette miel + huile d'olive + balsamique, qui sublime betterave et chèvre.", badge: "⏱ 2 min" },
      { icone: "🌿", titre: "Finir", detail: "ASTUCE CHEF : arroser au dernier moment pour ne pas faire retomber la roquette. Poivre du moulin.", badge: null }
    ]
  },
  saladefiguejambon: {
    cat: "salades", pays: "italie",
    base: 4,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🍖",
    description: "Salade figues & jambon cru — l'accord sucré-salé de l'été italien : figues fraîches, jambon de Parme, copeaux de parmesan et roquette.",
    tableauSaladeFigueJambon: [
      { nb: 1, figue: "1½ figue", jambon: "20 g", roquette: "20 g", parmesan: "8 g", huiledolive: "½ c.à.c", miel: "¼ c.à.c" },
      { nb: 2, figue: "3 figues", jambon: "40 g", roquette: "40 g", parmesan: "16 g", huiledolive: "1 c.à.c", miel: "½ c.à.c" },
      { nb: 3, figue: "4½ figues", jambon: "60 g", roquette: "60 g", parmesan: "24 g", huiledolive: "1½ c.à.c", miel: "1 c.à.c" },
      { nb: 4, figue: "6 figues", jambon: "80 g", roquette: "80 g", parmesan: "32 g", huiledolive: "2 c.à.c", miel: "1¼ c.à.c" },
      { nb: 5, figue: "7½ figues", jambon: "100 g", roquette: "100 g", parmesan: "40 g", huiledolive: "2½ c.à.c", miel: "1½ c.à.c" },
      { nb: 6, figue: "9 figues", jambon: "120 g", roquette: "120 g", parmesan: "48 g", huiledolive: "3 c.à.c", miel: "1¾ c.à.c" },
      { nb: 7, figue: "10½ figues", jambon: "140 g", roquette: "140 g", parmesan: "56 g", huiledolive: "3½ c.à.c", miel: "2 c.à.c" },
      { nb: 8, figue: "12 figues", jambon: "160 g", roquette: "160 g", parmesan: "64 g", huiledolive: "4 c.à.c", miel: "2½ c.à.c" },
      { nb: 9, figue: "13½ figues", jambon: "180 g", roquette: "180 g", parmesan: "72 g", huiledolive: "4½ c.à.c", miel: "2¾ c.à.c" },
      { nb: 10, figue: "15 figues", jambon: "200 g", roquette: "200 g", parmesan: "80 g", huiledolive: "5 c.à.c", miel: "3 c.à.c" },
      { nb: 11, figue: "16½ figues", jambon: "220 g", roquette: "220 g", parmesan: "88 g", huiledolive: "5½ c.à.c", miel: "3¼ c.à.c" },
      { nb: 12, figue: "18 figues", jambon: "240 g", roquette: "240 g", parmesan: "96 g", huiledolive: "6 c.à.c", miel: "3½ c.à.c" },
      { nb: 13, figue: "19½ figues", jambon: "260 g", roquette: "260 g", parmesan: "104 g", huiledolive: "6½ c.à.c", miel: "4 c.à.c" },
      { nb: 14, figue: "21 figues", jambon: "280 g", roquette: "280 g", parmesan: "112 g", huiledolive: "7 c.à.c", miel: "4¼ c.à.c" },
      { nb: 15, figue: "22½ figues", jambon: "300 g", roquette: "300 g", parmesan: "120 g", huiledolive: "7½ c.à.c", miel: "4½ c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍶", titre: "Figues", detail: "Couper les figues bien mûres en quartiers. CLÉ : des figues à maturité, c'est tout le plat.", badge: "⏱ 4 min" },
      { icone: "🥗", titre: "Dresser", detail: "Lit de roquette, quartiers de figues, tranches de jambon cru drapées, copeaux de parmesan.", badge: "⏱ 4 min" },
      { icone: "🍯", titre: "Assaisonner", detail: "SECRET : huile d'olive + quelques gouttes de balsamique ou de miel. Pas de sel (jambon + parmesan).", badge: "⏱ 2 min" },
      { icone: "🌿", titre: "Finir", detail: "ASTUCE CHEF : un tour de poivre et, si envie, quelques noix grillées pour le croquant.", badge: null }
    ]
  },
  saladeroquetteparmesan: {
    cat: "salades", pays: "italie",
    base: 4,
    temps: "10 min",
    niveau: "⭐ Facile",
    emoji: "🌿",
    description: "Salade roquette-parmesan — la salade italienne minimaliste et parfaite : roquette poivrée, copeaux de parmesan, citron et huile d'olive. En 10 minutes.",
    tableauSaladeRoquetteParmesan: [
      { nb: 1, roquette: "30 g", parmesan: "10 g", pignon: "5 g", citron: "¼ c.à.c", huiledolive: "½ c.à.c", poivre: "1 pincée" },
      { nb: 2, roquette: "60 g", parmesan: "20 g", pignon: "10 g", citron: "½ c.à.c", huiledolive: "1 c.à.c", poivre: "1 pincée" },
      { nb: 3, roquette: "90 g", parmesan: "30 g", pignon: "15 g", citron: "½ c.à.c", huiledolive: "1½ c.à.c", poivre: "1 pincée" },
      { nb: 4, roquette: "120 g", parmesan: "40 g", pignon: "20 g", citron: "¾ c.à.c", huiledolive: "2 c.à.c", poivre: "1 pincée" },
      { nb: 5, roquette: "150 g", parmesan: "50 g", pignon: "25 g", citron: "1 c.à.c", huiledolive: "2½ c.à.c", poivre: "1 pincée" },
      { nb: 6, roquette: "180 g", parmesan: "60 g", pignon: "30 g", citron: "1¼ c.à.c", huiledolive: "3 c.à.c", poivre: "1 pincée" },
      { nb: 7, roquette: "210 g", parmesan: "70 g", pignon: "35 g", citron: "1½ c.à.c", huiledolive: "3½ c.à.c", poivre: "2 pincées" },
      { nb: 8, roquette: "240 g", parmesan: "80 g", pignon: "40 g", citron: "1½ c.à.c", huiledolive: "4 c.à.c", poivre: "2 pincées" },
      { nb: 9, roquette: "270 g", parmesan: "90 g", pignon: "45 g", citron: "1¾ c.à.c", huiledolive: "4½ c.à.c", poivre: "2 pincées" },
      { nb: 10, roquette: "300 g", parmesan: "100 g", pignon: "50 g", citron: "2 c.à.c", huiledolive: "5 c.à.c", poivre: "2 pincées" },
      { nb: 11, roquette: "330 g", parmesan: "110 g", pignon: "55 g", citron: "2¼ c.à.c", huiledolive: "5½ c.à.c", poivre: "2 pincées" },
      { nb: 12, roquette: "360 g", parmesan: "120 g", pignon: "60 g", citron: "2½ c.à.c", huiledolive: "6 c.à.c", poivre: "2 pincées" },
      { nb: 13, roquette: "390 g", parmesan: "130 g", pignon: "65 g", citron: "2½ c.à.c", huiledolive: "6½ c.à.c", poivre: "3 pincées" },
      { nb: 14, roquette: "420 g", parmesan: "140 g", pignon: "70 g", citron: "2¾ c.à.c", huiledolive: "7 c.à.c", poivre: "3 pincées" },
      { nb: 15, roquette: "450 g", parmesan: "150 g", pignon: "75 g", citron: "3 c.à.c", huiledolive: "7½ c.à.c", poivre: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥗", titre: "Roquette", detail: "Laver et bien essorer la roquette (bien sèche, sinon la vinaigrette glisse).", badge: "⏱ 3 min" },
      { icone: "🧀", titre: "Copeaux", detail: "Copeaux de parmesan à l'économe. ASTUCE : du vrai Parmigiano Reggiano fait toute la différence.", badge: "⏱ 2 min" },
      { icone: "🍋", titre: "Assaisonner", detail: "SECRET ITALIEN : huile d'olive + jus de citron + poivre, à la main, dans cet ordre. Pas de vinaigre.", badge: "⏱ 2 min" },
      { icone: "🌰", titre: "Finir", detail: "ASTUCE CHEF : pignons torréfiés à sec pour le croquant. Servir aussitôt, la roquette retombe vite.", badge: null }
    ]
  },
  saladeolivier: {
    cat: "salades", pays: "russie",
    dateAjout: "2026-06-01",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "Salade Olivier — la salade russe des fêtes : pommes de terre, œufs, petits pois, cornichons et jambon liés à la mayonnaise. Généreuse et conviviale.",
    tableauSaladeolivier: [
      { nb: 1, pommeDeTerre: "1", oeuf: "1", petitsPois: "30 g", cornichons: "20 g", jambon: "40 g", mayonnaise: "1 c.à.s" },
      { nb: 2, pommeDeTerre: "2", oeuf: "2", petitsPois: "60 g", cornichons: "40 g", jambon: "80 g", mayonnaise: "2 c.à.s" },
      { nb: 3, pommeDeTerre: "3", oeuf: "3", petitsPois: "90 g", cornichons: "60 g", jambon: "120 g", mayonnaise: "3 c.à.s" },
      { nb: 4, pommeDeTerre: "4", oeuf: "4", petitsPois: "120 g", cornichons: "80 g", jambon: "160 g", mayonnaise: "4 c.à.s" },
      { nb: 5, pommeDeTerre: "5", oeuf: "5", petitsPois: "150 g", cornichons: "100 g", jambon: "200 g", mayonnaise: "5 c.à.s" },
      { nb: 6, pommeDeTerre: "6", oeuf: "6", petitsPois: "180 g", cornichons: "120 g", jambon: "240 g", mayonnaise: "6 c.à.s" },
      { nb: 7, pommeDeTerre: "7", oeuf: "7", petitsPois: "210 g", cornichons: "140 g", jambon: "280 g", mayonnaise: "7 c.à.s" },
      { nb: 8, pommeDeTerre: "8", oeuf: "8", petitsPois: "240 g", cornichons: "160 g", jambon: "320 g", mayonnaise: "8 c.à.s" },
      { nb: 9, pommeDeTerre: "9", oeuf: "9", petitsPois: "270 g", cornichons: "180 g", jambon: "360 g", mayonnaise: "9 c.à.s" },
      { nb: 10, pommeDeTerre: "10", oeuf: "10", petitsPois: "300 g", cornichons: "200 g", jambon: "400 g", mayonnaise: "10 c.à.s" },
      { nb: 11, pommeDeTerre: "10", oeuf: "10", petitsPois: "330 g", cornichons: "220 g", jambon: "440 g", mayonnaise: "10 c.à.s" },
      { nb: 12, pommeDeTerre: "10", oeuf: "10", petitsPois: "360 g", cornichons: "240 g", jambon: "480 g", mayonnaise: "10 c.à.s" },
      { nb: 13, pommeDeTerre: "15", oeuf: "15", petitsPois: "390 g", cornichons: "260 g", jambon: "520 g", mayonnaise: "15 c.à.s" },
      { nb: 14, pommeDeTerre: "15", oeuf: "15", petitsPois: "420 g", cornichons: "280 g", jambon: "560 g", mayonnaise: "15 c.à.s" },
      { nb: 15, pommeDeTerre: "15", oeuf: "15", petitsPois: "450 g", cornichons: "300 g", jambon: "600 g", mayonnaise: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "💧", titre: "Cuire", detail: "Cuire les pommes de terre et les œufs durs, puis les laisser refroidir complètement.", badge: "⏱ 15 min" },
      { icone: "🔪", titre: "Tailler", detail: "Couper pommes de terre, œufs, cornichons et jambon en petits dés réguliers.", badge: null },
      { icone: "🟢", titre: "Petits pois", detail: "Égoutter les petits pois.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir tous les ingrédients dans un saladier.", badge: null },
      { icone: "🥄", titre: "Lier", detail: "Lier à la mayonnaise, saler et poivrer.", badge: null },
      { icone: "❄️", titre: "Reposer", detail: "Réserver au frais au moins 1 heure pour que les saveurs se marient.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Servir bien frais, décoré d'un peu d'œuf. ASTUCE CHEF : taillez tout en dés bien réguliers, c'est ce qui donne sa texture caractéristique à la salade Olivier.", badge: null }
    ]
  },
  somtam: {
    cat: "salades", pays: "thailande",
    dateAjout: "2026-06-02",
    base: 4,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    nom: "Som Tam",
    description: "La salade thaïe de papaye verte, pilée au mortier : croquante, acidulée, sucrée-salée et bien relevée. Fraîcheur explosive ! 🇹🇭",
    ingredients: {},
    tableauSomtam: [
      { nb: 1, papaye: "0.5", tomate: "0.5", carotte: "0.5", cacahuete: "15 g", citronvert: "0.5", nuocmam: "7.5 ml", piment: "1.5 g", ail: "0.5", sucre: "5 g" },
      { nb: 2, papaye: "0.5", tomate: "1", carotte: "0.5", cacahuete: "25 g", citronvert: "1", nuocmam: "15 ml", piment: "2.5 g", ail: "1", sucre: "10 g" },
      { nb: 3, papaye: "1", tomate: "1.5", carotte: "1", cacahuete: "40 g", citronvert: "1.5", nuocmam: "25 ml", piment: "4 g", ail: "1.5", sucre: "15 g" },
      { nb: 4, papaye: "1", tomate: "2", carotte: "1", cacahuete: "50 g", citronvert: "2", nuocmam: "30 ml", piment: "5 g", ail: "2", sucre: "20 g" },
      { nb: 5, papaye: "1.5", tomate: "2.5", carotte: "1.5", cacahuete: "65 g", citronvert: "2.5", nuocmam: "40 ml", piment: "6.5 g", ail: "2.5", sucre: "25 g" },
      { nb: 6, papaye: "1.5", tomate: "3", carotte: "1.5", cacahuete: "75 g", citronvert: "3", nuocmam: "45 ml", piment: "7.5 g", ail: "3", sucre: "30 g" },
      { nb: 7, papaye: "2", tomate: "3.5", carotte: "2", cacahuete: "90 g", citronvert: "3.5", nuocmam: "55 ml", piment: "9 g", ail: "3.5", sucre: "35 g" },
      { nb: 8, papaye: "2", tomate: "4", carotte: "2", cacahuete: "100 g", citronvert: "4", nuocmam: "60 ml", piment: "10 g", ail: "4", sucre: "40 g" },
      { nb: 9, papaye: "2.5", tomate: "4.5", carotte: "2.5", cacahuete: "110 g", citronvert: "4.5", nuocmam: "70 ml", piment: "10 g", ail: "4.5", sucre: "45 g" },
      { nb: 10, papaye: "2.5", tomate: "5", carotte: "2.5", cacahuete: "130 g", citronvert: "5", nuocmam: "75 ml", piment: "15 g", ail: "5", sucre: "50 g" },
      { nb: 11, papaye: "3", tomate: "5.5", carotte: "3", cacahuete: "140 g", citronvert: "5.5", nuocmam: "85 ml", piment: "15 g", ail: "5.5", sucre: "55 g" },
      { nb: 12, papaye: "3", tomate: "6", carotte: "3", cacahuete: "150 g", citronvert: "6", nuocmam: "90 ml", piment: "15 g", ail: "6", sucre: "60 g" },
      { nb: 13, papaye: "3.5", tomate: "6.5", carotte: "3.5", cacahuete: "160 g", citronvert: "6.5", nuocmam: "100 ml", piment: "15 g", ail: "6.5", sucre: "65 g" },
      { nb: 14, papaye: "3.5", tomate: "7", carotte: "3.5", cacahuete: "180 g", citronvert: "7", nuocmam: "110 ml", piment: "20 g", ail: "7", sucre: "70 g" },
      { nb: 15, papaye: "4", tomate: "7.5", carotte: "4", cacahuete: "190 g", citronvert: "7.5", nuocmam: "110 ml", piment: "20 g", ail: "7.5", sucre: "75 g" }
    ],
    etapes: [
      { icone: "🥭", titre: "Préparer", detail: "Râper la papaye verte et la carotte en fins bâtonnets, couper les tomates en quartiers.", badge: null },
      { icone: "🧄", titre: "Piler la base", detail: "Piler ail, piment et sucre au mortier jusqu'à obtenir une pâte.", badge: null },
      { icone: "🍋", titre: "La sauce", detail: "Ajouter nuoc-mâm et jus de citron vert, puis piler pour mélanger.", badge: null },
      { icone: "🥗", titre: "Mélanger", detail: "Incorporer papaye, carotte et tomates, piler doucement pour les imprégner sans les écraser.", badge: null },
      { icone: "🥜", titre: "Cacahuètes", detail: "Ajouter les cacahuètes concassées et mélanger.", badge: null },
      { icone: "🧊", titre: "Servir", detail: "Servir bien frais, en entrée ou en accompagnement.", badge: null }
    ]
  },
  saladepates: {
    nom: "Salade de pâtes",
    dateAjout: "2026-06-04",
    cat: "salades", pays: "france",
    base: 2,
    temps: "20 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "Une salade de pâtes fraîche et complète, parfaite pour l'été ou les pique-niques : pâtes, tomates, jambon et œuf dur.",
    tableauSaladePates: [
      { nb: 1, pates: "80 g", tomate: "80 g", jambon: "40 g", oeufs: "1", huileolive: "1 c.à.s" },
      { nb: 2, pates: "160 g", tomate: "160 g", jambon: "80 g", oeufs: "2", huileolive: "2 c.à.s" },
      { nb: 3, pates: "240 g", tomate: "240 g", jambon: "120 g", oeufs: "3", huileolive: "3 c.à.s" },
      { nb: 4, pates: "320 g", tomate: "320 g", jambon: "160 g", oeufs: "4", huileolive: "4 c.à.s" },
      { nb: 5, pates: "400 g", tomate: "400 g", jambon: "200 g", oeufs: "5", huileolive: "5 c.à.s" },
      { nb: 6, pates: "480 g", tomate: "480 g", jambon: "240 g", oeufs: "6", huileolive: "6 c.à.s" },
      { nb: 7, pates: "560 g", tomate: "560 g", jambon: "280 g", oeufs: "7", huileolive: "7 c.à.s" },
      { nb: 8, pates: "640 g", tomate: "640 g", jambon: "320 g", oeufs: "8", huileolive: "8 c.à.s" },
      { nb: 9, pates: "720 g", tomate: "720 g", jambon: "360 g", oeufs: "9", huileolive: "9 c.à.s" },
      { nb: 10, pates: "800 g", tomate: "800 g", jambon: "400 g", oeufs: "10", huileolive: "10 c.à.s" },
      { nb: 11, pates: "880 g", tomate: "880 g", jambon: "440 g", oeufs: "11", huileolive: "11 c.à.s" },
      { nb: 12, pates: "960 g", tomate: "960 g", jambon: "480 g", oeufs: "12", huileolive: "12 c.à.s" },
      { nb: 13, pates: "1040 g", tomate: "1040 g", jambon: "520 g", oeufs: "13", huileolive: "13 c.à.s" },
      { nb: 14, pates: "1120 g", tomate: "1120 g", jambon: "560 g", oeufs: "14", huileolive: "14 c.à.s" },
      { nb: 15, pates: "1200 g", tomate: "1200 g", jambon: "600 g", oeufs: "15", huileolive: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "💧", titre: "Eau salée", detail: "Porter une casserole d'eau salée à ébullition.", badge: null },
      { icone: "🍝", titre: "Cuire les pâtes", detail: "Cuire les pâtes al dente, les égoutter et les rincer à l'eau froide. ASTUCE CHEF : un filet d'huile évite qu'elles collent en refroidissant.", badge: "⏱ 10 min" },
      { icone: "🥚", titre: "Œufs durs", detail: "Cuire les œufs durs 9 min, les rafraîchir, les écaler et les couper en quartiers.", badge: "⏱ 9 min" },
      { icone: "🔪", titre: "Préparer", detail: "Couper les tomates et le jambon en dés.", badge: null },
      { icone: "🥗", titre: "Assembler", detail: "Mélanger les pâtes avec les tomates, le jambon et l'huile d'olive. Saler, poivrer.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Disposer les œufs sur le dessus et servir frais. ASTUCE CHEF : une cuillère de moutarde dans l'assaisonnement relève la salade.", badge: null }
    ]
  },
  saladecomposee: {
    nom: "Salade composée",
    dateAjout: "2026-06-04",
    cat: "salades", pays: "france",
    base: 2,
    temps: "15 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "Une grande salade composée complète : salade verte, tomates, maïs, jambon et œuf dur. Le repas léger express.",
    tableauSaladeComposee: [
      { nb: 1, salade: "1", tomate: "80 g", mais: "40 g", jambon: "40 g", oeufs: "1", huileolive: "1 c.à.s" },
      { nb: 2, salade: "1", tomate: "160 g", mais: "80 g", jambon: "80 g", oeufs: "2", huileolive: "2 c.à.s" },
      { nb: 3, salade: "2", tomate: "240 g", mais: "120 g", jambon: "120 g", oeufs: "3", huileolive: "3 c.à.s" },
      { nb: 4, salade: "2", tomate: "320 g", mais: "160 g", jambon: "160 g", oeufs: "4", huileolive: "4 c.à.s" },
      { nb: 5, salade: "3", tomate: "400 g", mais: "200 g", jambon: "200 g", oeufs: "5", huileolive: "5 c.à.s" },
      { nb: 6, salade: "3", tomate: "480 g", mais: "240 g", jambon: "240 g", oeufs: "6", huileolive: "6 c.à.s" },
      { nb: 7, salade: "4", tomate: "560 g", mais: "280 g", jambon: "280 g", oeufs: "7", huileolive: "7 c.à.s" },
      { nb: 8, salade: "4", tomate: "640 g", mais: "320 g", jambon: "320 g", oeufs: "8", huileolive: "8 c.à.s" },
      { nb: 9, salade: "5", tomate: "720 g", mais: "360 g", jambon: "360 g", oeufs: "9", huileolive: "9 c.à.s" },
      { nb: 10, salade: "5", tomate: "800 g", mais: "400 g", jambon: "400 g", oeufs: "10", huileolive: "10 c.à.s" },
      { nb: 11, salade: "6", tomate: "880 g", mais: "440 g", jambon: "440 g", oeufs: "11", huileolive: "11 c.à.s" },
      { nb: 12, salade: "6", tomate: "960 g", mais: "480 g", jambon: "480 g", oeufs: "12", huileolive: "12 c.à.s" },
      { nb: 13, salade: "7", tomate: "1040 g", mais: "520 g", jambon: "520 g", oeufs: "13", huileolive: "13 c.à.s" },
      { nb: 14, salade: "7", tomate: "1120 g", mais: "560 g", jambon: "560 g", oeufs: "14", huileolive: "14 c.à.s" },
      { nb: 15, salade: "8", tomate: "1200 g", mais: "600 g", jambon: "600 g", oeufs: "15", huileolive: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥚", titre: "Œufs durs", detail: "Cuire les œufs durs 9 min, les rafraîchir, les écaler et les couper en quartiers.", badge: "⏱ 9 min" },
      { icone: "🥬", titre: "Salade", detail: "Laver et essorer la salade, puis la déchirer en morceaux. ASTUCE CHEF : bien essorer pour que la vinaigrette accroche.", badge: null },
      { icone: "🔪", titre: "Préparer", detail: "Couper les tomates, égoutter le maïs et couper le jambon en lanières.", badge: null },
      { icone: "🥗", titre: "Assembler", detail: "Disposer la salade dans un saladier, ajouter tomates, maïs, jambon et œufs.", badge: null },
      { icone: "🫒", titre: "Vinaigrette", detail: "Préparer une vinaigrette à l'huile d'olive, saler et poivrer. ASTUCE CHEF : assaisonner juste avant de servir pour garder la salade croquante.", badge: null },
      { icone: "🍽️", titre: "Servir", detail: "Servir frais.", badge: null }
    ]
  },
  saladepiemontaise: {
    nom: "Salade piémontaise",
    dateAjout: "2026-06-05",
    cat: "salades", pays: "france",
    base: 4,
    temps: "30 min",
    niveau: "⭐ Facile",
    emoji: "🥗",
    description: "La salade conviviale des buffets : pommes de terre, œufs, jambon et cornichons liés à la mayonnaise.",
    tableauSaladepiemontaise: [
      { nb: 1, pommeDeTerre: "150 g", oeuf: "½", jambon: "30 g", cornichons: "15 g", tomate: "50 g", mayonnaise: "1 c.à.s" },
      { nb: 2, pommeDeTerre: "300 g", oeuf: "1", jambon: "60 g", cornichons: "30 g", tomate: "100 g", mayonnaise: "2 c.à.s" },
      { nb: 3, pommeDeTerre: "450 g", oeuf: "1½", jambon: "90 g", cornichons: "45 g", tomate: "150 g", mayonnaise: "3 c.à.s" },
      { nb: 4, pommeDeTerre: "600 g", oeuf: "2", jambon: "120 g", cornichons: "60 g", tomate: "200 g", mayonnaise: "4 c.à.s" },
      { nb: 5, pommeDeTerre: "750 g", oeuf: "2½", jambon: "150 g", cornichons: "75 g", tomate: "250 g", mayonnaise: "5 c.à.s" },
      { nb: 6, pommeDeTerre: "900 g", oeuf: "3", jambon: "180 g", cornichons: "90 g", tomate: "300 g", mayonnaise: "6 c.à.s" },
      { nb: 7, pommeDeTerre: "1050 g", oeuf: "3½", jambon: "210 g", cornichons: "105 g", tomate: "350 g", mayonnaise: "7 c.à.s" },
      { nb: 8, pommeDeTerre: "1200 g", oeuf: "4", jambon: "240 g", cornichons: "120 g", tomate: "400 g", mayonnaise: "8 c.à.s" },
      { nb: 9, pommeDeTerre: "1350 g", oeuf: "4½", jambon: "270 g", cornichons: "135 g", tomate: "450 g", mayonnaise: "9 c.à.s" },
      { nb: 10, pommeDeTerre: "1500 g", oeuf: "5", jambon: "300 g", cornichons: "150 g", tomate: "500 g", mayonnaise: "10 c.à.s" },
      { nb: 11, pommeDeTerre: "1650 g", oeuf: "5½", jambon: "330 g", cornichons: "165 g", tomate: "550 g", mayonnaise: "11 c.à.s" },
      { nb: 12, pommeDeTerre: "1800 g", oeuf: "6", jambon: "360 g", cornichons: "180 g", tomate: "600 g", mayonnaise: "12 c.à.s" },
      { nb: 13, pommeDeTerre: "1950 g", oeuf: "6½", jambon: "390 g", cornichons: "195 g", tomate: "650 g", mayonnaise: "13 c.à.s" },
      { nb: 14, pommeDeTerre: "2100 g", oeuf: "7", jambon: "420 g", cornichons: "210 g", tomate: "700 g", mayonnaise: "14 c.à.s" },
      { nb: 15, pommeDeTerre: "2250 g", oeuf: "7½", jambon: "450 g", cornichons: "225 g", tomate: "750 g", mayonnaise: "15 c.à.s" }
    ],
    ingredients: {},
    etapes: [
      { icone: "💧", titre: "Cuire", detail: "Cuire les pommes de terre et les œufs durs, puis laisser refroidir.", badge: "⏱ 15 min" },
      { icone: "🔪", titre: "Tailler", detail: "Couper pommes de terre, œufs, jambon, cornichons et tomates en dés.", badge: null },
      { icone: "🥣", titre: "Mélanger", detail: "Réunir le tout dans un saladier.", badge: null },
      { icone: "🥄", titre: "Lier", detail: "Lier à la mayonnaise, saler et poivrer.", badge: null },
      { icone: "❄️", titre: "Reposer", detail: "Réserver au frais au moins 1 heure. ASTUCE CHEF : ajoutez les tomates juste avant de servir pour qu'elles ne détrempent pas la salade.", badge: "⏱ 1 h" },
      { icone: "🍽️", titre: "Servir", detail: "Servir bien frais, décoré d'œuf.", badge: null }
    ]
  },
});
