// ============================================================
// recettes_boulangerie.js — Recettes de catégorie "boulangerie" (Boulangerie) — 23 recettes
// 👉 Pour AJOUTER une recette Boulangerie : place-la juste avant le  });  final.
//    (le plus simple : copie une recette existante et change les valeurs)
// ============================================================
Object.assign(recettes, {
  pizza: {
    nom: "Pâte à pizza",
    cat: "boulangerie", pays: "italie",
    base: 4,
    temps: "48h fermentation",
    niveau: "⭐⭐ Moyen",
    emoji: "🥙",
    description: "La pâte à pizza napolitaine authentique — légère et croustillante grâce à une longue fermentation. Base pour toutes vos pizzas !",
    tableauPatons: [
      { patons: 0, total: "0 g", farine: "0 g", eau: "0 g", sel: "0 g", levure: "0 g" },
      { patons: 1, total: "280 g", farine: "168 g", eau: "109 g", sel: "5 g", levure: "0,5 g" },
      { patons: 2, total: "560 g", farine: "335 g", eau: "218 g", sel: "10 g", levure: "1 g" },
      { patons: 3, total: "840 g", farine: "503 g", eau: "327 g", sel: "15 g", levure: "1,5 g" },
      { patons: 4, total: "1120 g", farine: "670 g", eau: "436 g", sel: "20 g", levure: "2 g" },
      { patons: 5, total: "1400 g", farine: "838 g", eau: "545 g", sel: "25 g", levure: "2,5 g" },
      { patons: 6, total: "1680 g", farine: "1005 g", eau: "653 g", sel: "30 g", levure: "3 g" },
      { patons: 7, total: "1960 g", farine: "1173 g", eau: "762 g", sel: "35 g", levure: "3,5 g" },
      { patons: 8, total: "2240 g", farine: "1340 g", eau: "871 g", sel: "40 g", levure: "4 g" },
      { patons: 9, total: "2520 g", farine: "1508 g", eau: "980 g", sel: "45 g", levure: "4,5 g" },
      { patons: 10, total: "2800 g", farine: "1675 g", eau: "1089 g", sel: "50 g", levure: "5 g" },
      { patons: 11, total: "3080 g", farine: "1843 g", eau: "1198 g", sel: "55 g", levure: "5,5 g" },
      { patons: 12, total: "3360 g", farine: "2010 g", eau: "1305 g", sel: "60 g", levure: "6 g" },
      { patons: 13, total: "3640 g", farine: "2178 g", eau: "1415 g", sel: "65 g", levure: "6,5 g" },
      { patons: 14, total: "3920 g", farine: "2345 g", eau: "1524 g", sel: "70 g", levure: "7 g" },
      { patons: 15, total: "4200 g", farine: "2513 g", eau: "1633 g", sel: "75 g", levure: "7,5 g" },
      { patons: 16, total: "4480 g", farine: "2680 g", eau: "1742 g", sel: "80 g", levure: "8 g" },
      { patons: 17, total: "4760 g", farine: "2848 g", eau: "1851 g", sel: "85 g", levure: "8,5 g" },
      { patons: 18, total: "5040 g", farine: "3015 g", eau: "1960 g", sel: "90 g", levure: "9 g" },
      { patons: 19, total: "5320 g", farine: "3183 g", eau: "2069 g", sel: "95 g", levure: "9,5 g" },
      { patons: 20, total: "5600 g", farine: "3350 g", eau: "2178 g", sel: "100 g", levure: "10 g" }
    ],
    ingredients: {
      "Farine (g)": 670,
      "Eau (ml)": 436,
      "Sel (g)": 20,
      "Levure fraîche (g)": 2,
    },
    etapes: [
      { icone: "🌾", titre: "Farine seule", detail: "Mettre toute la farine dans le bol.", badge: "🤲 Pétrissage : 1 min vitesse faible" },
      { icone: "🟨", titre: "Ajouter levure fraîche", detail: "Ajouter directement la levure. Objectif : aérer farine + levure.", badge: "🤲 Pétrissage : 2 min" },
      { icone: "💧", titre: "Ajouter 90–95 % de l'eau", detail: "Verser progressivement l'eau froide.", badge: "🤲 Pétrissage : ≈ 15 min" },
      { icone: "🧂", titre: "Ajouter sel + reste eau", detail: "Finir l'hydratation. Surveiller la température de la pâte.", badge: "⚠️ Ne pas dépasser 25 °C" },
      { icone: "⏳", titre: "Repos masse", detail: "Laisser reposer la pâte en masse dans le bol. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ Temps : 2 h" },
      { icone: "🍕", titre: "Former les pâtons", detail: "280 g par pâton. Faire des boules serrées en repliant la pâte sous elle-même.", badge: null },
      { icone: "❄️", titre: "Frigo", detail: "Placer les pâtons dans des boîtes hermétiques au réfrigérateur pour une fermentation lente.", badge: "⏱ Temps : 24 h minimum" },
      { icone: "🔥", titre: "Avant cuisson", detail: "Sortir les pâtons du frigo et les laisser revenir à température ambiante avant d'étaler.", badge: "⏱ Temps : 2–3 h" }
    ]
  },
  painbaguette: {
    nom: "Pain — Baguette",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "3h",
    niveau: "⭐⭐ Intermédiaire",
    emoji: "🥖",
    description: "Une vraie baguette maison — croûte dorée et craquante, mie alvéolée. Quantités pour 1 à 6 baguettes.",
    ingredients: {},
    tableauPainBaguette: [
      { nb: 1, farine: "250 g", eau: "160 ml", levure: "8 g", sel: "5 g" },
      { nb: 2, farine: "500 g", eau: "320 ml", levure: "16 g", sel: "10 g" },
      { nb: 3, farine: "750 g", eau: "480 ml", levure: "24 g", sel: "15 g" },
      { nb: 4, farine: "1000 g", eau: "640 ml", levure: "32 g", sel: "20 g" },
      { nb: 5, farine: "1250 g", eau: "800 ml", levure: "40 g", sel: "25 g" },
      { nb: 6, farine: "1500 g", eau: "960 ml", levure: "48 g", sel: "30 g" }
    ],
    etapes: [
      { icone: "🟨", titre: "Diluer la levure", detail: "Diluer la levure fraîche dans l'eau tiède (max 35°C). Laisser reposer 5 min. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 5 min" },
      { icone: "🌾", titre: "Former la pâte", detail: "Dans un grand bol, mélanger la farine et le sel. Ajouter le mélange eau-levure. Mélanger jusqu'à formation d'une pâte homogène.", badge: null },
      { icone: "🤲", titre: "Pétrir", detail: "Pétrir énergiquement la pâte pendant 10 min jusqu'à ce qu'elle soit lisse et élastique. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "Première levée", detail: "Couvrir d'un torchon et laisser lever dans un endroit chaud jusqu'à ce que la pâte double de volume. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 1h30" },
      { icone: "🥖", titre: "Façonner la baguette", detail: "Dégazer la pâte. L'étirer en rectangle puis la rouler en forme de baguette en scellant bien les bords. Placer sur une plaque farinée.", badge: null },
      { icone: "⏳", titre: "Deuxième levée", detail: "Couvrir et laisser lever à nouveau. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 45 min" },
      { icone: "✂️", titre: "Grigner et enfourner", detail: "Préchauffer le four à 240°C avec un bol d'eau pour créer de la vapeur. Faire des entailles en diagonale sur la baguette avec une lame. Enfourner. Minimum 10 min à la bonne température pour un démarrage de cuisson correct.", badge: "⏱ 20–25 min à 240°C" }
    ]
  },
  paindemie: {
    nom: "Pain de mie",
    cat: "boulangerie", pays: "france",
    base: 20,
    temps: "2h30",
    niveau: "⭐ Facile",
    emoji: "🍞",
    description: "Un pain de mie maison moelleux — pour des toasts, sandwichs et croque-monsieur bien meilleurs que ceux du commerce.",
    tableauPainDeMie: [
      { nb: 1, farine: "18 g", lait: "11 ml", beurre: "2 g", sucre: "1 g", levure: "0.5 g", sel: "0.3 g" },
      { nb: 2, farine: "35 g", lait: "22 ml", beurre: "4 g", sucre: "2 g", levure: "1 g", sel: "0.5 g" },
      { nb: 3, farine: "53 g", lait: "33 ml", beurre: "6 g", sucre: "3 g", levure: "1.5 g", sel: "0.8 g" },
      { nb: 4, farine: "70 g", lait: "44 ml", beurre: "8 g", sucre: "4 g", levure: "2 g", sel: "1 g" },
      { nb: 5, farine: "88 g", lait: "55 ml", beurre: "10 g", sucre: "5 g", levure: "2.5 g", sel: "1.3 g" },
      { nb: 6, farine: "105 g", lait: "66 ml", beurre: "12 g", sucre: "6 g", levure: "3 g", sel: "1.5 g" },
      { nb: 7, farine: "123 g", lait: "77 ml", beurre: "14 g", sucre: "7 g", levure: "3.5 g", sel: "1.8 g" },
      { nb: 8, farine: "140 g", lait: "88 ml", beurre: "16 g", sucre: "8 g", levure: "4 g", sel: "2 g" },
      { nb: 9, farine: "158 g", lait: "99 ml", beurre: "18 g", sucre: "9 g", levure: "4.5 g", sel: "2.3 g" },
      { nb: 10, farine: "175 g", lait: "110 ml", beurre: "20 g", sucre: "10 g", levure: "5 g", sel: "2.5 g" },
      { nb: 11, farine: "193 g", lait: "121 ml", beurre: "22 g", sucre: "11 g", levure: "5.5 g", sel: "2.8 g" },
      { nb: 12, farine: "210 g", lait: "132 ml", beurre: "24 g", sucre: "12 g", levure: "6 g", sel: "3 g" },
      { nb: 13, farine: "228 g", lait: "143 ml", beurre: "26 g", sucre: "13 g", levure: "6.5 g", sel: "3.3 g" },
      { nb: 14, farine: "245 g", lait: "154 ml", beurre: "28 g", sucre: "14 g", levure: "7 g", sel: "3.5 g" },
      { nb: 15, farine: "263 g", lait: "165 ml", beurre: "30 g", sucre: "15 g", levure: "7.5 g", sel: "3.8 g" },
      { nb: 16, farine: "280 g", lait: "176 ml", beurre: "32 g", sucre: "16 g", levure: "8 g", sel: "4 g" },
      { nb: 17, farine: "298 g", lait: "187 ml", beurre: "34 g", sucre: "17 g", levure: "8.5 g", sel: "4.3 g" },
      { nb: 18, farine: "315 g", lait: "198 ml", beurre: "36 g", sucre: "18 g", levure: "9 g", sel: "4.5 g" },
      { nb: 19, farine: "333 g", lait: "209 ml", beurre: "38 g", sucre: "19 g", levure: "9.5 g", sel: "4.8 g" },
      { nb: 20, farine: "350 g", lait: "220 ml", beurre: "40 g", sucre: "20 g", levure: "10 g", sel: "5 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🟨", titre: "Activer la levure", detail: "Diluer la levure dans le lait tiède avec le sucre. Laisser reposer 5 min. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 5 min" },
      { icone: "🌾", titre: "Former la pâte", detail: "Mélanger farine et sel. Ajouter le mélange lait-levure. Pétrir jusqu'à obtenir une pâte homogène. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 8 min" },
      { icone: "🧈", titre: "Incorporer le beurre", detail: "Ajouter le beurre mou en morceaux progressivement tout en continuant de pétrir. La pâte doit être lisse et souple.", badge: "⏱ 5 min" },
      { icone: "⏳", titre: "Première levée", detail: "Couvrir et laisser lever dans un endroit chaud. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 1h" },
      { icone: "🍞", titre: "Façonner et mouler", detail: "Dégazer, façonner en rectangle et placer dans un moule à cake beurré. Égaliser la surface.", badge: null },
      { icone: "⏳", titre: "Deuxième levée", detail: "Couvrir et laisser lever jusqu'à ce que la pâte dépasse légèrement le moule. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 1h" },
      { icone: "🔥", titre: "Cuire", detail: "Enfourner à 180°C. Le pain est cuit quand il est bien doré et sonne creux quand on tape dessous. Chaleur tournante pour une cuisson uniforme.", badge: "⏱ 25–30 min à 180°C" }
    ]
  },
  patefeuilletee: {
    nom: "Pâte feuilletée",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "2h + repos",
    niveau: "⭐⭐⭐ Difficile",
    emoji: "🥧",
    description: "La vraie pâte feuilletée maison — croustillante, beurrée et feuilletée. Quantités pour 1 à 6 pâtes (moule ~28 cm).",
    ingredients: {},
    tableauPateFeuilletee: [
      { nb: 1, farine: "250 g", beurre: "205 g", eau: "125 ml", sel: "5 g" },
      { nb: 2, farine: "500 g", beurre: "410 g", eau: "250 ml", sel: "10 g" },
      { nb: 3, farine: "750 g", beurre: "615 g", eau: "375 ml", sel: "15 g" },
      { nb: 4, farine: "1000 g", beurre: "820 g", eau: "500 ml", sel: "20 g" },
      { nb: 5, farine: "1250 g", beurre: "1025 g", eau: "625 ml", sel: "25 g" },
      { nb: 6, farine: "1500 g", beurre: "1230 g", eau: "750 ml", sel: "30 g" }
    ],
    etapes: [
        { icone: "🌾", titre: "La détrempe", detail: "Mélanger la farine et le sel. Ajouter l'eau froide petit à petit jusqu'à former une boule souple, sans trop pétrir. Inciser une croix sur le dessus, filmer et réserver au frais.", badge: "⏱ 30 min au frigo" },
        { icone: "🧈", titre: "Le beurre de tourage", detail: "Placer le beurre froid entre deux feuilles de papier et l'aplatir au rouleau en un carré régulier d'environ 1 cm. ASTUCE CHEF : le beurre doit avoir la même souplesse que la détrempe, ni dur ni fondu, sinon il transperce la pâte au tourage.", badge: null },
        { icone: "📦", titre: "Enfermer le beurre", detail: "Étaler la détrempe en croix, poser le carré de beurre au centre et replier les quatre rabats par-dessus pour l'enfermer complètement, comme une enveloppe.", badge: null },
        { icone: "📏", titre: "Premier tour double", detail: "Étaler en un long rectangle régulier, puis replier en portefeuille (les deux extrémités vers le centre, puis plier en deux). Filmer et reposer au frais.", badge: "⏱ 30 min au frigo" },
        { icone: "📏", titre: "Deuxième tour double", detail: "Tourner la pâte d'un quart de tour, étaler de nouveau en rectangle et replier en portefeuille. Filmer et remettre au frais.", badge: "⏱ 30 min au frigo" },
        { icone: "📏", titre: "Troisième tour double", detail: "Répéter une dernière fois le quart de tour, l'étalage et le pliage en portefeuille. Trois tours doubles au total : ce repos final fixe le feuilletage.", badge: "⏱ 30 min au frigo" },
        { icone: "✅", titre: "Étaler et conserver", detail: "Étaler à l'épaisseur voulue, prête à foncer ou découper. Elle se garde 3 jours au frais, ou 3 mois au congélateur bien filmée.", badge: null }
      ]
  },
  patebrisee: {
    nom: "Pâte brisée",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "15 min + repos",
    niveau: "⭐ Facile",
    emoji: "🥧",
    description: "La pâte brisée maison — croustillante et fondante. Quantités pour 1 à 6 pâtes (moule ~28 cm).",
    ingredients: {},
    tableauPateBrisee: [
      { nb: 1, farine: "200 g", beurre: "100 g", eau: "50 ml", sel: "4 g" },
      { nb: 2, farine: "400 g", beurre: "200 g", eau: "100 ml", sel: "8 g" },
      { nb: 3, farine: "600 g", beurre: "300 g", eau: "150 ml", sel: "12 g" },
      { nb: 4, farine: "800 g", beurre: "400 g", eau: "200 ml", sel: "16 g" },
      { nb: 5, farine: "1000 g", beurre: "500 g", eau: "250 ml", sel: "20 g" },
      { nb: 6, farine: "1200 g", beurre: "600 g", eau: "300 ml", sel: "24 g" }
    ],
    etapes: [
        { icone: "🌾", titre: "Sabler la farine", detail: "Verser la farine et le sel dans un saladier. Ajouter le beurre froid en petits dés et le frotter du bout des doigts avec la farine jusqu'à une texture sableuse et granuleuse.", badge: null },
        { icone: "💧", titre: "Ajouter l'eau", detail: "Verser l'eau froide cuillère par cuillère en mélangeant, juste assez pour que la pâte commence à s'amalgamer. ASTUCE CHEF : on arrête dès qu'elle se rassemble — trop d'eau ou trop de travail rend la pâte dure.", badge: null },
        { icone: "👐", titre: "Former la boule", detail: "Rassembler la pâte à la main, en l'écrasant une ou deux fois avec la paume (fraisage) pour répartir le beurre, puis former une boule sans pétrir.", badge: null },
        { icone: "❄️", titre: "Repos au frais", detail: "Aplatir en disque, filmer et laisser reposer au réfrigérateur. Ce repos détend le gluten et évite que la pâte se rétracte à la cuisson.", badge: "⏱ 30 min minimum" },
        { icone: "📏", titre: "Étaler et foncer", detail: "Étaler sur un plan fariné en un disque régulier, puis foncer le moule en chassant l'air sur les bords. Couper l'excédent de pâte.", badge: null },
        { icone: "🍴", titre: "Piquer le fond", detail: "Piquer le fond à la fourchette pour éviter qu'il ne gonfle. La pâte est prête à garnir et à cuire selon la recette.", badge: null }
      ]
  },
  patesablee: {
    nom: "Pâte sablée",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "15 min + repos",
    niveau: "⭐ Facile",
    emoji: "🍪",
    description: "La pâte sablée maison — plus sucrée et friable que la brisée. Quantités pour 1 à 6 pâtes (moule ~28 cm).",
    ingredients: {},
    tableauPateSablee: [
      { nb: 1, farine: "200 g", beurre: "100 g", sucre: "80 g", oeufs: "1", amande: "20 g", sel: "1 g" },
      { nb: 2, farine: "400 g", beurre: "200 g", sucre: "160 g", oeufs: "2", amande: "40 g", sel: "2 g" },
      { nb: 3, farine: "600 g", beurre: "300 g", sucre: "240 g", oeufs: "3", amande: "60 g", sel: "3 g" },
      { nb: 4, farine: "800 g", beurre: "400 g", sucre: "320 g", oeufs: "4", amande: "80 g", sel: "4 g" },
      { nb: 5, farine: "1000 g", beurre: "500 g", sucre: "400 g", oeufs: "5", amande: "100 g", sel: "5 g" },
      { nb: 6, farine: "1200 g", beurre: "600 g", sucre: "480 g", oeufs: "6", amande: "120 g", sel: "6 g" }
    ],
    etapes: [
        { icone: "🧈", titre: "Crémer beurre et sucre", detail: "Travailler le beurre mou avec le sucre glace au fouet ou à la spatule jusqu'à un mélange lisse et crémeux.", badge: null },
        { icone: "🥚", titre: "Incorporer l'œuf", detail: "Ajouter l'œuf et mélanger jusqu'à ce qu'il soit complètement absorbé et le mélange homogène.", badge: null },
        { icone: "🌾", titre: "Ajouter les poudres", detail: "Verser la farine, la poudre d'amande et le sel. Mélanger juste assez pour rassembler. ASTUCE CHEF : dès que la pâte forme une boule, on arrête — trop travaillée, elle perd son côté friable.", badge: null },
        { icone: "❄️", titre: "Repos au frais", detail: "Aplatir en disque, filmer et laisser reposer au réfrigérateur. Le froid raffermit le beurre et facilite l'étalage.", badge: "⏱ 1h minimum" },
        { icone: "📏", titre: "Étaler et foncer", detail: "Étaler délicatement (la pâte est fragile), entre deux feuilles de papier si besoin, puis foncer le moule.", badge: null },
        { icone: "♨️", titre: "Cuisson à blanc", detail: "Piquer le fond, couvrir de papier et de billes de cuisson (ou légumes secs) et cuire à blanc avant de garnir.", badge: "⏱ 15 min à 170°C" }
      ]
  },
  painburger: {
    nom: "Pain Burger (Buns)",
    cat: "boulangerie", pays: "usa",
    base: 6,
    temps: "2h30 (dont 1h30 levée)",
    niveau: "⭐ Facile",
    emoji: "🍔",
    description: "Des buns briochés ultra moelleux à la mie aérienne — croûte fine et légèrement dorée. Une fois faits maison, impossible de revenir aux buns du commerce !",
    tableauPainBurger: [
      { nb: 1, farine: "65 g", lait: "35 ml", beurre: "10 g", huile: "3.5 ml", oeufs: "⅓", levure: "1.5 g", sucre: "4 g", miel: "1.5 g", sel: "1 g" },
      { nb: 2, farine: "130 g", lait: "70 ml", beurre: "20 g", huile: "7 ml", oeufs: "⅓", levure: "3 g", sucre: "8 g", miel: "3 g", sel: "2 g" },
      { nb: 3, farine: "195 g", lait: "105 ml", beurre: "30 g", huile: "10 ml", oeufs: "⅓", levure: "4.5 g", sucre: "12 g", miel: "4.5 g", sel: "3 g" },
      { nb: 4, farine: "260 g", lait: "140 ml", beurre: "40 g", huile: "14 ml", oeufs: "⅔", levure: "5 g", sucre: "15 g", miel: "5 g", sel: "4 g" },
      { nb: 5, farine: "325 g", lait: "175 ml", beurre: "50 g", huile: "18 ml", oeufs: "⅔", levure: "6.2 g", sucre: "19 g", miel: "6.2 g", sel: "5 g" },
      { nb: 6, farine: "400 g", lait: "210 ml", beurre: "60 g", huile: "20 ml", oeufs: "1", levure: "8 g", sucre: "22 g", miel: "8 g", sel: "6 g" },
      { nb: 7, farine: "467 g", lait: "245 ml", beurre: "70 g", huile: "23 ml", oeufs: "1.2", levure: "9.3 g", sucre: "26 g", miel: "9.3 g", sel: "7 g" },
      { nb: 8, farine: "530 g", lait: "280 ml", beurre: "80 g", huile: "27 ml", oeufs: "1⅓", levure: "10 g", sucre: "30 g", miel: "10 g", sel: "8 g" },
      { nb: 9, farine: "596 g", lait: "315 ml", beurre: "90 g", huile: "30 ml", oeufs: "1.1 ⅓", levure: "11 g", sucre: "34 g", miel: "11 g", sel: "9 g" },
      { nb: 10, farine: "660 g", lait: "350 ml", beurre: "100 g", huile: "34 ml", oeufs: "1⅔", levure: "13 g", sucre: "37 g", miel: "13 g", sel: "10 g" },
      { nb: 11, farine: "726 g", lait: "385 ml", beurre: "110 g", huile: "37 ml", oeufs: "1.1 ⅔", levure: "14 g", sucre: "41 g", miel: "14 g", sel: "11 g" },
      { nb: 12, farine: "800 g", lait: "420 ml", beurre: "120 g", huile: "40 ml", oeufs: "2", levure: "16 g", sucre: "44 g", miel: "16 g", sel: "12 g" },
      { nb: 13, farine: "867 g", lait: "455 ml", beurre: "130 g", huile: "43 ml", oeufs: "2.2", levure: "17 g", sucre: "48 g", miel: "17 g", sel: "13 g" },
      { nb: 14, farine: "933 g", lait: "490 ml", beurre: "140 g", huile: "47 ml", oeufs: "2.3", levure: "19 g", sucre: "51 g", miel: "19 g", sel: "14 g" },
      { nb: 15, farine: "1000 g", lait: "525 ml", beurre: "150 g", huile: "50 ml", oeufs: "2.5", levure: "20 g", sucre: "55 g", miel: "20 g", sel: "15 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🟨", titre: "Activer la levure", detail: "Diluer la levure fraîche dans le lait tiède (35°C max). Ajouter le miel et laisser reposer 10 min jusqu'à ce que ça mousse. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 10 min" },
      { icone: "🌾", titre: "Former la pâte", detail: "Dans un grand bol, mélanger farine, sucre et sel. Creuser un puits, y verser le mélange lait-levure, l'œuf et l'huile. Mélanger jusqu'à pâte homogène.", badge: null },
      { icone: "🧈", titre: "Incorporer le beurre", detail: "Ajouter le beurre mou en morceaux progressivement. Pétrir 10 min à la main ou au robot jusqu'à obtenir une pâte lisse, souple et légèrement collante.", badge: "⏱ 10 min pétrissage" },
      { icone: "⏳", titre: "Première levée", detail: "Former une boule, couvrir d'un torchon humide et laisser lever dans un endroit chaud jusqu'à ce que la pâte double de volume. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 1h à 1h30" },
      { icone: "⚖️", titre: "Façonner les buns", detail: "Dégazer délicatement la pâte. Diviser en portions égales de 90-100g. Former des boules lisses en repliant la pâte dessous. Disposer sur une plaque avec papier sulfurisé, bien espacés.", badge: null },
      { icone: "⏳", titre: "Deuxième levée", detail: "Couvrir et laisser lever jusqu'à ce que les buns aient bien gonflé. La pâte doit DOUBLER de volume dans un endroit tiède (25°C, four éteint avec lampe allumée).", badge: "⏱ 30-45 min" },
      { icone: "🥚", titre: "Dorer et garnir", detail: "Préchauffer le four à 180°C. Badigeonner délicatement les buns de lait (ou jaune d'œuf dilué). Parsemer de graines de sésame. Minimum 10 min à la bonne température pour un démarrage de cuisson correct.", badge: null },
      { icone: "🔥", titre: "Cuire", detail: "Enfourner à 180°C. Les buns sont prêts quand ils sont bien dorés et sonnent creux. À la sortie du four, badigeonner de beurre fondu pour un aspect brillant. Chaleur tournante pour une cuisson uniforme.", badge: "⏱ 13-15 min à 180°C" }
    ]
  },
  galettetacos: {
    nom: "Galette à Tacos",
    cat: "boulangerie", pays: "mexique",
    base: 8,
    temps: "45 min (dont 30 min repos)",
    niveau: "⭐ Facile",
    emoji: "🌮",
    description: "Les galettes à tacos maison souples et moelleuses — bien meilleures que celles du commerce et ultra simples à faire. Parfaites pour tacos, wraps et fajitas !",
    tableauGaletteTacos: [
      { nb: 1, farine: "30 g", eau: "18 ml", huile: "2.5 ml", sel: "0.5 g" },
      { nb: 2, farine: "60 g", eau: "35 ml", huile: "5 ml", sel: "1 g" },
      { nb: 3, farine: "90 g", eau: "52 ml", huile: "7.5 ml", sel: "1.5 g" },
      { nb: 4, farine: "120 g", eau: "70 ml", huile: "10 ml", sel: "2 g" },
      { nb: 5, farine: "150 g", eau: "88 ml", huile: "12 ml", sel: "2.5 g" },
      { nb: 6, farine: "180 g", eau: "105 ml", huile: "15 ml", sel: "3 g" },
      { nb: 7, farine: "210 g", eau: "123 ml", huile: "18 ml", sel: "3.5 g" },
      { nb: 8, farine: "240 g", eau: "140 ml", huile: "20 ml", sel: "4 g" },
      { nb: 9, farine: "270 g", eau: "158 ml", huile: "22 ml", sel: "4.5 g" },
      { nb: 10, farine: "300 g", eau: "175 ml", huile: "25 ml", sel: "5 g" },
      { nb: 11, farine: "330 g", eau: "193 ml", huile: "28 ml", sel: "5.5 g" },
      { nb: 12, farine: "360 g", eau: "210 ml", huile: "30 ml", sel: "6 g" },
      { nb: 13, farine: "390 g", eau: "227 ml", huile: "32 ml", sel: "6.5 g" },
      { nb: 14, farine: "420 g", eau: "245 ml", huile: "35 ml", sel: "7 g" },
      { nb: 15, farine: "450 g", eau: "262 ml", huile: "38 ml", sel: "7.5 g" },
      { nb: 16, farine: "480 g", eau: "280 ml", huile: "40 ml", sel: "8 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Mélanger les ingrédients", detail: "Dans un saladier, mélanger la farine et le sel. Ajouter l'huile et l'eau tiède progressivement. Mélanger à la fourchette puis pétrir à la main jusqu'à obtenir une pâte lisse et souple qui ne colle plus.", badge: "⏱ 5 min pétrissage" },
      { icone: "⏳", titre: "Repos de la pâte", detail: "Former une boule, couvrir d'un torchon humide ou d'un film alimentaire. Laisser reposer à température ambiante. Ce repos est essentiel — la pâte bien reposée s'étale mieux et ne se rétracte pas.", badge: "⏱ 30 min" },
      { icone: "⚖️", titre: "Diviser et former", detail: "Diviser la pâte en portions égales de 30g environ. Rouler en boules. Toujours garder les boules non étalées couvertes pour éviter qu'elles sèchent.", badge: null },
      { icone: "📏", titre: "Étaler finement", detail: "Sur un plan de travail légèrement fariné, étaler chaque boule au rouleau en un disque fin de 20-22 cm. Plus la galette est fine, plus elle sera souple.", badge: null },
      { icone: "🍳", titre: "Cuire à sec", detail: "Chauffer une poêle antiadhésive à feu moyen-vif sans matière grasse. Cuire chaque galette jusqu'à l'apparition de petites bulles et taches dorées, retourner et cuire l'autre côté.", badge: "⏱ 20-30 sec par face" },
      { icone: "🌯", titre: "Couvrir pour garder le moelleux", detail: "Empiler les galettes cuites dans un torchon propre en les couvrant immédiatement — c'est le secret du moelleux ! La vapeur emprisonnée les garde souples. Se conservent 3 jours dans un sac hermétique.", badge: null }
    ]
  },
  brioche: {
    nom: "Brioche",
    cat: "boulangerie", pays: "france",
    base: 1,
    temps: "~2h + 35 min cuisson",
    niveau: "⭐⭐ Moyen",
    emoji: "🍞",
    description: "Une brioche filante et dorée. Recette pour 1 à 5 brioches de 400g.",
    tableauBrioche: [
      { nb:  1, label: "1 brioche", oeufs: "~200 g", vanille: "7,5 g", lait: "87,5 g", sucre: "65 g", levure: "15 g", sel: "9 g", farine: "500 g", beurre: "150 g", total: "1034 g" },
      { nb:  2, label: "2 brioches", oeufs: "~400 g", vanille: "15 g", lait: "175 g", sucre: "130 g", levure: "30 g", sel: "18 g", farine: "1000 g", beurre: "300 g", total: "2068 g" },
      { nb:  3, label: "3 brioches", oeufs: "~600 g", vanille: "22,5 g", lait: "262,5 g", sucre: "195 g", levure: "45 g", sel: "27 g", farine: "1500 g", beurre: "450 g", total: "3102 g" },
      { nb:  4, label: "4 brioches", oeufs: "~800 g", vanille: "30 g", lait: "350 g", sucre: "260 g", levure: "60 g", sel: "36 g", farine: "2000 g", beurre: "600 g", total: "4136 g" },
      { nb:  5, label: "5 brioches", oeufs: "~1000 g", vanille: "37,5 g", lait: "437,5 g", sucre: "325 g", levure: "75 g", sel: "45 g", farine: "2500 g", beurre: "750 g", total: "5170 g" }
    ],
    ingredients: {
      "Œufs (g)": 200,
      "Extrait de vanille (g)": 7.5,
      "Lait (g)": 87.5,
      "Sucre (g)": 65,
      "Levure fraîche (g)": 15,
      "Sel (g)": 9,
      "Farine (g)": 500,
      "Beurre froid (g)": 150,
    },
    etapes: [
      { icone: "🥚", titre: "Mettre tous les ingrédients sauf le beurre", detail: "Dans le bol du robot : œufs + levure fraîche + extrait de vanille + sucre + farine + sel (+ lait si version avec lait). Ne pas mettre le beurre.", badge: null },
      { icone: "🤲", titre: "Pétrissage petite vitesse", detail: "Mélanger à petite vitesse jusqu'à ce que la pâte soit homogène.", badge: "⏱ 5 min petite vitesse" },
      { icone: "⚡", titre: "Pétrissage grande vitesse", detail: "Passer en grande vitesse pour développer le réseau de gluten.", badge: "⏱ 6 min grande vitesse" },
      { icone: "🧈", titre: "Ajouter le beurre froid", detail: "Incorporer le beurre froid coupé en morceaux progressivement.", badge: "⏱ 5 min vitesse moyenne" },
      { icone: "⚡", titre: "Finition grande vitesse", detail: "Terminer le pétrissage en grande vitesse. La pâte doit être lisse et se décoller des parois.", badge: "⏱ 3 min grande vitesse" },
      { icone: "🌡️", titre: "Surveiller la température", detail: "La pâte ne doit pas dépasser 22–24 °C. Si elle chauffe trop, mettre le bol au frigo quelques minutes.", badge: "⚠️ Max 22–24 °C" },
      { icone: "🔥", titre: "Cuire au four", detail: "Façonner, laisser pousser selon votre méthode, puis enfourner. Cuisson à 150 °C. Chaleur tournante pour une cuisson uniforme.", badge: "⏱ ~35 min à 150 °C" }
    ]
  },
  lasagne: {
    nom: "Pâte à Lasagne",
    cat: "boulangerie", pays: "italie",
    base: 1,
    temps: "1h30",
    niveau: "⭐⭐ Moyen",
    emoji: "🍝",
    description: "Pâte à Lasagne maison : 1 œuf pour 100 g de farine, 1 pincée de sel.",
    tableauLasagne: [
      { nb: 1, farine: "100 g", oeufs: 1, sel: "1 pincée" },
      { nb: 2, farine: "200 g", oeufs: 2, sel: "1 pincée" },
      { nb: 3, farine: "300 g", oeufs: 3, sel: "1 pincée" },
      { nb: 4, farine: "400 g", oeufs: 4, sel: "1 pincée" },
      { nb: 5, farine: "500 g", oeufs: 5, sel: "1 pincée" },
      { nb: 6, farine: "600 g", oeufs: 6, sel: "1 pincée" },
      { nb: 7, farine: "700 g", oeufs: 7, sel: "1 pincée" },
      { nb: 8, farine: "800 g", oeufs: 8, sel: "1 pincée" },
      { nb: 9, farine: "900 g", oeufs: 9, sel: "1 pincée" },
      { nb: 10, farine: "1000 g", oeufs: 10, sel: "1 pincée" },
      { nb: 11, farine: "1100 g", sel: "2.8 pincée" },
      { nb: 12, farine: "1200 g", sel: "3 pincée" },
      { nb: 13, farine: "1300 g", sel: "3.2 pincée" },
      { nb: 14, farine: "1400 g", sel: "3.5 pincée" },
      { nb: 15, farine: "1500 g", sel: "3.8 pincée" }
    ],
    ingredients: {
      "Farine (g)": 100,
      "Œufs": 1,
    },
    etapes: [
      { icone: "🌾", titre: "Mélanger farine + sel", detail: "Verser la farine en fontaine sur le plan de travail. Ajouter une pincée de sel.", badge: null },
      { icone: "🥚", titre: "Ajouter les œufs", detail: "Casser les œufs au centre de la fontaine. Les incorporer progressivement à la farine en partant du centre.", badge: null },
      { icone: "🤲", titre: "Pétrir", detail: "Pétrir énergiquement jusqu'à obtenir une pâte lisse, souple et homogène. Si la pâte colle, ajouter un peu de farine. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "Repos", detail: "Envelopper la pâte dans du film alimentaire et laisser reposer à température ambiante. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 30 min minimum" },
      { icone: "📏", titre: "Abaisser", detail: "Diviser la pâte en portions. L'étaler au rouleau ou au laminoir le plus fin possible.", badge: null },
      { icone: "✂️", titre: "Découper", detail: "Découper les feuilles à la taille de votre plat. Fariner légèrement pour éviter qu'elles ne collent. ASTUCE CHEF : couteau bien aiguisé pour des coupes nettes.", badge: null }
    ]
  },
  painauchocolat: {
    nom: "Pain au Chocolat",
    cat: "boulangerie", pays: "france",
    base: 8,
    temps: "3h + repos",
    niveau: "⭐⭐⭐ Difficile",
    emoji: "🍫",
    description: "Les pains au chocolat maison — pâte feuilletée levée, beurre de tourage et barres de chocolat. Le vrai travail de boulanger !",
    tableauPainAuChocolat: [
      { nb: 1, farine: "32 g", lait: "18 ml", beurre: "4 g", sucre: "3 g", levure: "1 g", beurrage: "22 g", chocolat: "10 g", sel: "1 pincée" },
      { nb: 2, farine: "63 g", lait: "35 ml", beurre: "8 g", sucre: "6 g", levure: "2 g", beurrage: "44 g", chocolat: "20 g", sel: "1 pincée" },
      { nb: 3, farine: "94 g", lait: "52 ml", beurre: "12 g", sucre: "9 g", levure: "3 g", beurrage: "66 g", chocolat: "30 g", sel: "1 pincée" },
      { nb: 4, farine: "125 g", lait: "70 ml", beurre: "15 g", sucre: "12 g", levure: "4 g", beurrage: "88 g", chocolat: "40 g", sel: "1 pincée" },
      { nb: 5, farine: "156 g", lait: "88 ml", beurre: "19 g", sucre: "15 g", levure: "5 g", beurrage: "110 g", chocolat: "50 g", sel: "1 pincée" },
      { nb: 6, farine: "188 g", lait: "105 ml", beurre: "23 g", sucre: "18 g", levure: "6 g", beurrage: "131 g", chocolat: "60 g", sel: "1 pincée" },
      { nb: 7, farine: "219 g", lait: "123 ml", beurre: "27 g", sucre: "21 g", levure: "7 g", beurrage: "153 g", chocolat: "70 g", sel: "1 pincée" },
      { nb: 8, farine: "250 g", lait: "140 ml", beurre: "30 g", sucre: "25 g", levure: "8 g", beurrage: "175 g", chocolat: "80 g", sel: "1 pincée" },
      { nb: 9, farine: "281 g", lait: "158 ml", beurre: "34 g", sucre: "28 g", levure: "9 g", beurrage: "197 g", chocolat: "90 g", sel: "1 pincée" },
      { nb: 10, farine: "313 g", lait: "175 ml", beurre: "38 g", sucre: "31 g", levure: "10 g", beurrage: "219 g", chocolat: "100 g", sel: "1 pincée" },
      { nb: 11, farine: "344 g", lait: "193 ml", beurre: "42 g", sucre: "34 g", levure: "11 g", beurrage: "241 g", chocolat: "110 g", sel: "1 pincée" },
      { nb: 12, farine: "375 g", lait: "210 ml", beurre: "45 g", sucre: "37 g", levure: "12 g", beurrage: "263 g", chocolat: "120 g", sel: "1 pincée" },
      { nb: 13, farine: "406 g", lait: "227 ml", beurre: "49 g", sucre: "40 g", levure: "13 g", beurrage: "285 g", chocolat: "130 g", sel: "1 pincée" },
      { nb: 14, farine: "438 g", lait: "245 ml", beurre: "53 g", sucre: "43 g", levure: "14 g", beurrage: "306 g", chocolat: "140 g", sel: "1 pincée" },
      { nb: 15, farine: "469.3 g", lait: "262.5 ml", beurre: "56.8 g", sucre: "46.1 g", levure: "15 g", beurrage: "327.9 g", chocolat: "150 g", sel: "1 pincée" }
    ],
    ingredients: {},
    etapes: [
        { icone: "🌾", titre: "La détrempe", detail: "Mélanger la farine, le sel, le sucre, la levure et le lait tiède. Pétrir jusqu'à une pâte lisse et souple, puis incorporer un peu de beurre mou. Former un rectangle, filmer et réfrigérer.", badge: "⏱ 1h au frigo" },
        { icone: "🧈", titre: "Le beurre de tourage", detail: "Aplatir le beurre froid au rouleau en un carré régulier d'environ 1 cm. ASTUCE CHEF : il doit être souple mais froid, à la consistance de la détrempe, sinon il casse au lieu de s'étaler.", badge: null },
        { icone: "📦", titre: "Enfermer le beurre", detail: "Étaler la détrempe, poser le beurre au centre et l'envelopper complètement dedans.", badge: null },
        { icone: "📏", titre: "Les tourages", detail: "Étaler en rectangle et plier en trois (tour simple). Tourner d'un quart de tour et répéter, en reposant au frais entre chaque tour. Trois tours au total.", badge: "⏱ 3 × 30 min repos" },
        { icone: "🔪", titre: "Découper", detail: "Étaler la pâte en un rectangle de 3 mm d'épaisseur, puis découper des rectangles réguliers.", badge: null },
        { icone: "🍫", titre: "Façonner", detail: "Déposer 1 à 2 barres de chocolat sur chaque rectangle et rouler bien serré, la soudure dessous.", badge: null },
        { icone: "⏲️", titre: "La pousse", detail: "Laisser lever à température ambiante jusqu'à ce que les pains doublent de volume et deviennent moelleux au toucher.", badge: "⏱ environ 2h" },
        { icone: "🔥", titre: "Dorure et cuisson", detail: "Dorer au jaune d'œuf battu et enfourner. Surveiller la coloration : dès que c'est doré uniforme, c'est prêt.", badge: "⏱ 15-18 min à 180°C" }
      ]
  },
  croissant: {
    nom: "Croissants au Beurre",
    cat: "boulangerie", pays: "france",
    base: 8,
    temps: "3h + 12h repos",
    niveau: "⭐⭐⭐ Expert",
    emoji: "🥐",
    description: "Croissants au Beurre — la recette classique de la boulangerie française. Feuilletage beurré, croustillant dehors et filant dedans.",
    tableauCroissant: [
      { nb: 1, farine: "62 g", beurre: "44 g", lait: "35 ml", sucre: "8 g", levure: "2 g", sel: "1 pincée" },
      { nb: 2, farine: "124 g", beurre: "88 g", lait: "70 ml", sucre: "16 g", levure: "4 g", sel: "2 pincées" },
      { nb: 3, farine: "186 g", beurre: "132 g", lait: "105 ml", sucre: "24 g", levure: "6 g", sel: "3 pincées" },
      { nb: 4, farine: "248 g", beurre: "176 g", lait: "140 ml", sucre: "32 g", levure: "8 g", sel: "4 pincées" },
      { nb: 5, farine: "310 g", beurre: "220 g", lait: "175 ml", sucre: "40 g", levure: "10 g", sel: "5 pincées" },
      { nb: 6, farine: "372 g", beurre: "264 g", lait: "210 ml", sucre: "48 g", levure: "12 g", sel: "6 pincées" },
      { nb: 7, farine: "434 g", beurre: "308 g", lait: "245 ml", sucre: "56 g", levure: "14 g", sel: "7 pincées" },
      { nb: 8, farine: "496 g", beurre: "352 g", lait: "280 ml", sucre: "64 g", levure: "16 g", sel: "8 pincées" },
      { nb: 9, farine: "558 g", beurre: "396 g", lait: "315 ml", sucre: "72 g", levure: "18 g", sel: "9 pincées" },
      { nb: 10, farine: "620 g", beurre: "440 g", lait: "350 ml", sucre: "80 g", levure: "20 g", sel: "10 pincées" },
      { nb: 11, farine: "682 g", beurre: "484 g", lait: "385 ml", sucre: "88 g", levure: "22 g", sel: "11 pincées" },
      { nb: 12, farine: "744 g", beurre: "528 g", lait: "420 ml", sucre: "96 g", levure: "24 g", sel: "12 pincées" },
      { nb: 13, farine: "806 g", beurre: "572 g", lait: "455 ml", sucre: "104 g", levure: "26 g", sel: "13 pincées" },
      { nb: 14, farine: "868 g", beurre: "616 g", lait: "490 ml", sucre: "112 g", levure: "28 g", sel: "14 pincées" },
      { nb: 15, farine: "930 g", beurre: "660 g", lait: "525 ml", sucre: "120 g", levure: "30 g", sel: "15 pincées" }
    ],
    ingredients: {},
    etapes: [
        { icone: "🌾", titre: "La détrempe", detail: "Mélanger farine, sucre, sel, levure, lait tiède et un peu de beurre fondu. Pétrir jusqu'à obtenir une pâte lisse.", badge: null },
        { icone: "⏲️", titre: "Première pousse", detail: "Laisser pousser 1h à température ambiante, puis filmer et placer une nuit au frais pour développer les arômes.", badge: "⏱ 1h + 12h au froid" },
        { icone: "🧈", titre: "Le beurre de tourage", detail: "Aplatir le beurre froid en un carré régulier. ASTUCE CHEF : travaillez toujours au frais — si le beurre commence à fondre, remettez tout au frigo, c'est la clé d'un feuilletage net.", badge: null },
        { icone: "📦", titre: "Enfermer le beurre", detail: "Étaler la détrempe froide et envelopper le beurre complètement dedans.", badge: null },
        { icone: "📏", titre: "Les tourages", detail: "Trois tours simples : étaler en rectangle, plier en trois, tourner d'un quart de tour, avec un repos au frais entre chaque tour.", badge: "⏱ 3 × 30 min" },
        { icone: "✂️", titre: "Façonnage", detail: "Étaler en un grand rectangle fin, découper des triangles, puis rouler chacun de la base vers la pointe et courber légèrement les extrémités.", badge: null },
        { icone: "⏲️", titre: "La pousse", detail: "Laisser pousser à température ambiante jusqu'à ce que les croissants soient bien gonflés et souples.", badge: "⏱ environ 2h" },
        { icone: "🔥", titre: "Dorure et cuisson", detail: "Dorer à l'œuf battu et enfourner jusqu'à belle couleur dorée et feuilletage croustillant.", badge: "⏱ 15 min à 200°C" }
      ]
  },
  focacciaolives: {
    nom: "Focaccia Olives-Romarin",
    cat: "boulangerie", saisons: ["ete"], pays: "italie",
    base: 6,
    temps: "2h30",
    niveau: "⭐⭐ Moyen",
    emoji: "🥖",
    description: "Focaccia olives-romarin — pain plat italien moelleux, croûte huilée, garni d'olives noires et romarin frais. Parfait à l'apéro.",
    tableauFocacciaOlives: [
      { nb: 1, farine: "100 g", eau: "70 ml", levure: "2 g", huile: "1 c.à.s", olives: "25 g", romarin: "1", selFleur: "1 pincée", semoule: "5 g" },
      { nb: 2, farine: "200 g", eau: "140 ml", levure: "4 g", huile: "2 c.à.s", olives: "50 g", romarin: "2", selFleur: "1 pincée", semoule: "10 g" },
      { nb: 3, farine: "300 g", eau: "210 ml", levure: "6 g", huile: "3 c.à.s", olives: "75 g", romarin: "3", selFleur: "1 pincée", semoule: "15 g" },
      { nb: 4, farine: "400 g", eau: "280 ml", levure: "8 g", huile: "4 c.à.s", olives: "100 g", romarin: "4", selFleur: "1 pincée", semoule: "20 g" },
      { nb: 5, farine: "500 g", eau: "350 ml", levure: "10 g", huile: "5 c.à.s", olives: "125 g", romarin: "5", selFleur: "1 pincée", semoule: "25 g" },
      { nb: 6, farine: "600 g", eau: "420 ml", levure: "12 g", huile: "6 c.à.s", olives: "150 g", romarin: "6", selFleur: "1 pincée", semoule: "30 g" },
      { nb: 7, farine: "700 g", eau: "490 ml", levure: "14 g", huile: "7 c.à.s", olives: "175 g", romarin: "7", selFleur: "1 pincée", semoule: "35 g" },
      { nb: 8, farine: "800 g", eau: "560 ml", levure: "16 g", huile: "8 c.à.s", olives: "200 g", romarin: "8", selFleur: "1 pincée", semoule: "40 g" },
      { nb: 9, farine: "900 g", eau: "630 ml", levure: "18 g", huile: "9 c.à.s", olives: "225 g", romarin: "9", selFleur: "1 pincée", semoule: "45 g" },
      { nb: 10, farine: "1 kg", eau: "700 ml", levure: "20 g", huile: "10 c.à.s", olives: "250 g", romarin: "10", selFleur: "1 pincée", semoule: "50 g" },
      { nb: 11, farine: "1.1 kg", eau: "770 ml", levure: "22 g", huile: "11 c.à.s", olives: "275 g", romarin: "11", selFleur: "1 pincée", semoule: "55 g" },
      { nb: 12, farine: "1.2 kg", eau: "840 ml", levure: "24 g", huile: "12 c.à.s", olives: "300 g", romarin: "12", selFleur: "1 pincée", semoule: "60 g" },
      { nb: 13, farine: "1.3 kg", eau: "910 ml", levure: "26 g", huile: "13 c.à.s", olives: "325 g", romarin: "13", selFleur: "1 pincée", semoule: "65 g" },
      { nb: 14, farine: "1.4 kg", eau: "980 ml", levure: "28 g", huile: "14 c.à.s", olives: "350 g", romarin: "14", selFleur: "1 pincée", semoule: "70 g" },
      { nb: 15, farine: "1.5 kg", eau: "1.1 l", levure: "30 g", huile: "15 c.à.s", olives: "375 g", romarin: "15", selFleur: "1 pincée", semoule: "75 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Pétrir", detail: "Mélanger farine T55 ou T65, eau tiède, levure boulangère, sel, huile d'olive. Pétrir 10 min jusqu'à pâte lisse et élastique. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "1ère pousse", detail: "Couvrir et laisser doubler de volume à température ambiante 1h.", badge: "⏱ 1h" },
      { icone: "🥧", titre: "Étaler", detail: "Verser sur plaque huilée. Étaler doucement avec les doigts huilés sans déchirer. Laisser pousser encore 30 min.", badge: "⏱ 30 min" },
      { icone: "👆", titre: "Marquer", detail: "Avec les doigts huilés, faire des trous profonds dans toute la surface (signature de la focaccia).", badge: null },
      { icone: "🫒", titre: "Garnir", detail: "Enfoncer les olives noires Taggiasche. Arroser généreusement d'huile d'olive. Romarin frais et fleur de sel.", badge: null },
      { icone: "🔥", titre: "Cuire", detail: "Cuire au four à 230°C 18-22 min jusqu'à dorée. Refroidir 10 min sur grille.", badge: "⏱ 22 min" }
    ]
  },
  khachapuri: {
    nom: "Khachapuri",
    cat: "boulangerie", pays: "georgie",
    base: 4,
    temps: "1h30",
    niveau: "⭐⭐⭐ Élevé",
    emoji: "🛶",
    description: "Khachapuri Adjarian — pain géorgien en forme de barque rempli de fromage fondu, œuf coulant et beurre. Le pain le plus addictif au monde.",
    tableauKhachapuri: [
      { nb: 1, farine: "100 g", lait: "50 ml", levure: "2 g", sucre: "2 g", fromage: "80 g", oeufs: "1", beurre: "15 g", sel: "1 pincée" },
      { nb: 2, farine: "200 g", lait: "100 ml", levure: "4 g", sucre: "4 g", fromage: "160 g", oeufs: "2", beurre: "30 g", sel: "1 pincée" },
      { nb: 3, farine: "300 g", lait: "150 ml", levure: "6 g", sucre: "6 g", fromage: "240 g", oeufs: "3", beurre: "45 g", sel: "1 pincée" },
      { nb: 4, farine: "400 g", lait: "200 ml", levure: "8 g", sucre: "8 g", fromage: "320 g", oeufs: "4", beurre: "60 g", sel: "1 pincée" },
      { nb: 5, farine: "500 g", lait: "250 ml", levure: "10 g", sucre: "10 g", fromage: "400 g", oeufs: "5", beurre: "75 g", sel: "1 pincée" },
      { nb: 6, farine: "600 g", lait: "300 ml", levure: "12 g", sucre: "12 g", fromage: "480 g", oeufs: "6", beurre: "90 g", sel: "1 pincée" },
      { nb: 7, farine: "700 g", lait: "350 ml", levure: "14 g", sucre: "14 g", fromage: "560 g", oeufs: "7", beurre: "105 g", sel: "1 pincée" },
      { nb: 8, farine: "800 g", lait: "400 ml", levure: "16 g", sucre: "16 g", fromage: "640 g", oeufs: "8", beurre: "120 g", sel: "1 pincée" },
      { nb: 9, farine: "900 g", lait: "450 ml", levure: "18 g", sucre: "18 g", fromage: "720 g", oeufs: "9", beurre: "135 g", sel: "1 pincée" },
      { nb: 10, farine: "1 kg", lait: "500 ml", levure: "20 g", sucre: "20 g", fromage: "800 g", oeufs: "10", beurre: "150 g", sel: "1 pincée" },
      { nb: 11, farine: "1.1 kg", lait: "550 ml", levure: "22 g", sucre: "22 g", fromage: "880 g", oeufs: "11", beurre: "165 g", sel: "1 pincée" },
      { nb: 12, farine: "1.2 kg", lait: "600 ml", levure: "24 g", sucre: "24 g", fromage: "960 g", oeufs: "12", beurre: "180 g", sel: "1 pincée" },
      { nb: 13, farine: "1.3 kg", lait: "650 ml", levure: "26 g", sucre: "26 g", fromage: "1 kg", oeufs: "13", beurre: "195 g", sel: "1 pincée" },
      { nb: 14, farine: "1.4 kg", lait: "700 ml", levure: "28 g", sucre: "28 g", fromage: "1.1 kg", oeufs: "14", beurre: "210 g", sel: "1 pincée" },
      { nb: 15, farine: "1.5 kg", lait: "750 ml", levure: "30 g", sucre: "30 g", fromage: "1.2 kg", oeufs: "15", beurre: "225 g", sel: "1 pincée" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Pâte levée", detail: "Mélanger lait tiède, levure, sucre, attendre 10 min. Ajouter farine, sel, 1 œuf, beurre fondu. Pétrir 8 min. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "Pousser", detail: "Couvrir et laisser doubler 1h à température ambiante.", badge: "⏱ 1h" },
      { icone: "🛶", titre: "Façonner", detail: "Étaler la pâte en ovale (30cm). Rouler fermement les bords vers l'intérieur en formant une barque ouverte. Pincer les pointes.", badge: null },
      { icone: "🧀", titre: "Garnir", detail: "Disposer du fromage (mélange mozzarella et feta ou mieux sulguni géorgien) dans la barque.", badge: null },
      { icone: "🔥", titre: "Cuire", detail: "Cuire à 230°C 12 min. Sortir, casser un œuf entier dans la barque, ajouter une noisette de beurre. Remettre 3 min — le blanc doit être tout juste pris.", badge: "⏱ 15 min" },
      { icone: "🥄", titre: "Servir", detail: "À table, le convive mélange l'œuf, le beurre et le fromage avec la pointe de la barque cassée. Mange à la cuillère. Vie changée.", badge: null }
    ]
  },
  painpita: {
    nom: "Pain Pita",
    cat: "boulangerie", pays: "liban",
    base: 6,
    temps: "2h",
    niveau: "⭐⭐ Moyen",
    emoji: "🥙",
    description: "Pain pita maison — pain plat libanais qui gonfle au four en formant une poche. Parfait pour les sandwichs et mezzés. Magique à voir.",
    tableauPainPita: [
      { nb: 1, farine: "80 g", eau: "50 ml", levure: "2 g", huile: "1 c.à.s", sucre: "1 c.à.c", sel: "1 pincée", semoule: "5 g", sesame: "1 c.à.c" },
      { nb: 2, farine: "160 g", eau: "100 ml", levure: "4 g", huile: "2 c.à.s", sucre: "2 c.à.c", sel: "1 pincée", semoule: "10 g", sesame: "2 c.à.c" },
      { nb: 3, farine: "240 g", eau: "150 ml", levure: "6 g", huile: "3 c.à.s", sucre: "3 c.à.c", sel: "1 pincée", semoule: "15 g", sesame: "3 c.à.c" },
      { nb: 4, farine: "320 g", eau: "200 ml", levure: "8 g", huile: "4 c.à.s", sucre: "4 c.à.c", sel: "1 pincée", semoule: "20 g", sesame: "4 c.à.c" },
      { nb: 5, farine: "400 g", eau: "250 ml", levure: "10 g", huile: "5 c.à.s", sucre: "5 c.à.c", sel: "1 pincée", semoule: "25 g", sesame: "5 c.à.c" },
      { nb: 6, farine: "480 g", eau: "300 ml", levure: "12 g", huile: "6 c.à.s", sucre: "6 c.à.c", sel: "1 pincée", semoule: "30 g", sesame: "6 c.à.c" },
      { nb: 7, farine: "560 g", eau: "350 ml", levure: "14 g", huile: "7 c.à.s", sucre: "7 c.à.c", sel: "1 pincée", semoule: "35 g", sesame: "7 c.à.c" },
      { nb: 8, farine: "640 g", eau: "400 ml", levure: "16 g", huile: "8 c.à.s", sucre: "8 c.à.c", sel: "1 pincée", semoule: "40 g", sesame: "8 c.à.c" },
      { nb: 9, farine: "720 g", eau: "450 ml", levure: "18 g", huile: "9 c.à.s", sucre: "9 c.à.c", sel: "1 pincée", semoule: "45 g", sesame: "9 c.à.c" },
      { nb: 10, farine: "800 g", eau: "500 ml", levure: "20 g", huile: "10 c.à.s", sucre: "10 c.à.c", sel: "1 pincée", semoule: "50 g", sesame: "10 c.à.c" },
      { nb: 11, farine: "880 g", eau: "550 ml", levure: "22 g", huile: "11 c.à.s", sucre: "11 c.à.c", sel: "1 pincée", semoule: "55 g", sesame: "11 c.à.c" },
      { nb: 12, farine: "960 g", eau: "600 ml", levure: "24 g", huile: "12 c.à.s", sucre: "12 c.à.c", sel: "1 pincée", semoule: "60 g", sesame: "12 c.à.c" },
      { nb: 13, farine: "1 kg", eau: "650 ml", levure: "26 g", huile: "13 c.à.s", sucre: "13 c.à.c", sel: "1 pincée", semoule: "65 g", sesame: "13 c.à.c" },
      { nb: 14, farine: "1.1 kg", eau: "700 ml", levure: "28 g", huile: "14 c.à.s", sucre: "14 c.à.c", sel: "1 pincée", semoule: "70 g", sesame: "14 c.à.c" },
      { nb: 15, farine: "1.2 kg", eau: "750 ml", levure: "30 g", huile: "15 c.à.s", sucre: "15 c.à.c", sel: "1 pincée", semoule: "75 g", sesame: "15 c.à.c" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Pâte", detail: "Mélanger farine, eau tiède, levure, sucre, sel, huile. Pétrir 10 min jusqu'à lisse et souple. Pétrir 10 min à la main ou 7 min au robot — la pâte doit être lisse et élastique.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "1ère pousse", detail: "Couvrir et laisser doubler 1h.", badge: "⏱ 1h" },
      { icone: "🟢", titre: "Boules", detail: "Dégazer. Diviser en boules de 80g. Laisser reposer 20 min sous un linge. ASTUCE CHEF : ce repos est ESSENTIEL pour la texture finale.", badge: "⏱ 20 min" },
      { icone: "🥏", titre: "Étaler", detail: "Étaler chaque boule en disque très fin (3-4mm) sur plan de travail fariné.", badge: null },
      { icone: "🔥", titre: "Four ultra chaud", detail: "Préchauffer le four à 250°C avec une plaque dedans. Déposer les disques directement sur la plaque très chaude. Minimum 10 min à la bonne température pour un démarrage de cuisson correct.", badge: "⏱ 30 min" },
      { icone: "✨", titre: "Magie", detail: "Cuire 4-5 min — les pitas vont GONFLER en formant une poche d'air. C'est magique ! Refroidir sous linge pour qu'ils restent souples.", badge: "⏱ 5 min" }
    ]
  },
  painsigle: {
    nom: "Pain de Seigle",
    cat: "boulangerie", pays: "france",
    base: 1,
    temps: "2h30",
    niveau: "⭐⭐ Moyen",
    emoji: "🍞",
    description: "Pain de seigle traditionnel — pain rustique au levain de seigle, mie dense et alvéolée, croûte craquante. Parfait avec fromage, saumon fumé ou foie gras.",
    tableauPainSeigle: [
      { nb: 1, farineseigle: "300 g", farineble: "200 g", eau: "330 ml", levure: "8 g", sel: "10 g", sucre: "5 g", graines: "20 g" },
      { nb: 2, farineseigle: "600 g", farineble: "400 g", eau: "660 ml", levure: "16 g", sel: "20 g", sucre: "10 g", graines: "40 g" },
      { nb: 3, farineseigle: "900 g", farineble: "600 g", eau: "990 ml", levure: "24 g", sel: "30 g", sucre: "15 g", graines: "60 g" },
      { nb: 4, farineseigle: "1.2 kg", farineble: "800 g", eau: "1.3 l", levure: "32 g", sel: "40 g", sucre: "20 g", graines: "80 g" },
      { nb: 5, farineseigle: "1.5 kg", farineble: "1 kg", eau: "1.6 l", levure: "40 g", sel: "50 g", sucre: "25 g", graines: "100 g" },
      { nb: 6, farineseigle: "1.8 kg", farineble: "1.2 kg", eau: "2 l", levure: "48 g", sel: "60 g", sucre: "30 g", graines: "120 g" },
      { nb: 7, farineseigle: "2.1 kg", farineble: "1.4 kg", eau: "2.3 l", levure: "56 g", sel: "70 g", sucre: "35 g", graines: "140 g" },
      { nb: 8, farineseigle: "2.4 kg", farineble: "1.6 kg", eau: "2.6 l", levure: "64 g", sel: "80 g", sucre: "40 g", graines: "160 g" },
      { nb: 9, farineseigle: "2.7 kg", farineble: "1.8 kg", eau: "3 l", levure: "72 g", sel: "90 g", sucre: "45 g", graines: "180 g" },
      { nb: 10, farineseigle: "3 kg", farineble: "2 kg", eau: "3.3 l", levure: "80 g", sel: "100 g", sucre: "50 g", graines: "200 g" },
      { nb: 11, farineseigle: "3.3 kg", farineble: "2.2 kg", eau: "3.6 l", levure: "88 g", sel: "110 g", sucre: "55 g", graines: "220 g" },
      { nb: 12, farineseigle: "3.6 kg", farineble: "2.4 kg", eau: "4 l", levure: "96 g", sel: "120 g", sucre: "60 g", graines: "240 g" },
      { nb: 13, farineseigle: "3.9 kg", farineble: "2.6 kg", eau: "4.3 l", levure: "104 g", sel: "130 g", sucre: "65 g", graines: "260 g" },
      { nb: 14, farineseigle: "4.2 kg", farineble: "2.8 kg", eau: "4.6 l", levure: "112 g", sel: "140 g", sucre: "70 g", graines: "280 g" },
      { nb: 15, farineseigle: "4.5 kg", farineble: "3 kg", eau: "5 l", levure: "120 g", sel: "150 g", sucre: "75 g", graines: "300 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🧂", titre: "Mélanger les secs", detail: "Dans un grand bol : farine de seigle + farine de blé T80 ou T110 + sel + sucre. Mélanger.", badge: null },
      { icone: "💧", titre: "Lever la levure", detail: "Dissoudre la levure boulangère dans l'eau tiède (35°C, pas plus !). Laisser 5 min jusqu'à mousseux. ASTUCE CHEF : si pas mousseux, levure morte → repartir.", badge: "⏱ 5 min" },
      { icone: "✋", titre: "Pétrir", detail: "Verser le mélange liquide dans les farines. Mélanger puis pétrir 10 min. ATTENTION : la pâte de seigle est COLLANTE et plus dense qu'une pâte à pain classique. C'est normal !", badge: "⏱ 10 min" },
      { icone: "🌿", titre: "Graines", detail: "Incorporer graines de tournesol, lin, sésame en pétrissant. Former une boule.", badge: null },
      { icone: "⏳", titre: "1ère pousse", detail: "Couvrir d'un linge humide et laisser pousser à 25°C (four éteint avec lampe allumée) pendant 1h30. La pâte doit doubler.", badge: "⏱ 1h30" },
      { icone: "🥖", titre: "Façonner", detail: "Dégazer doucement. Former un pâton oblong ou rond sur plaque farinée. Faire des entailles décoratives au couteau bien aiguisé.", badge: "⏱ 5 min" },
      { icone: "⏳", titre: "2ème pousse", detail: "Laisser repousser 30 min. Pendant ce temps : préchauffer le four à 240°C avec une plaque vide en bas.", badge: "⏱ 30 min" },
      { icone: "💨", titre: "Cuisson au four", detail: "ASTUCE CHEF : enfourner, verser 200 ml d'eau bouillante dans la plaque du bas (vapeur = croûte croustillante). Cuire 15 min à 240°C, puis 30 min à 200°C.", badge: "⏱ 45 min" },
      { icone: "🎵", titre: "Tester la cuisson", detail: "Tapoter le dessous du pain : son creux = c'est cuit. Sinon, 5-10 min de plus. Laisser refroidir COMPLÈTEMENT sur grille (au moins 1h) avant de trancher.", badge: "⏱ 1h" }
    ]
  },
  paincampagne: {
    nom: "Pain de Campagne",
    cat: "boulangerie", pays: "france",
    base: 1,
    temps: "3h",
    niveau: "⭐⭐ Moyen",
    emoji: "🌾",
    description: "Pain de campagne traditionnel — mélange farines blé et seigle, longue fermentation, croûte épaisse et croustillante, mie aérée. Le pain quotidien français par excellence.",
    tableauPainCampagne: [
      { nb: 1, farineT80: "400 g", farineseigle: "100 g", eau: "340 ml", levure: "5 g", sel: "10 g", levain: "50 g" },
      { nb: 2, farineT80: "800 g", farineseigle: "200 g", eau: "680 ml", levure: "10 g", sel: "20 g", levain: "100 g" },
      { nb: 3, farineT80: "1.2 kg", farineseigle: "300 g", eau: "1 l", levure: "15 g", sel: "30 g", levain: "150 g" },
      { nb: 4, farineT80: "1.6 kg", farineseigle: "400 g", eau: "1.4 l", levure: "20 g", sel: "40 g", levain: "200 g" },
      { nb: 5, farineT80: "2 kg", farineseigle: "500 g", eau: "1.7 l", levure: "25 g", sel: "50 g", levain: "250 g" },
      { nb: 6, farineT80: "2.4 kg", farineseigle: "600 g", eau: "2 l", levure: "30 g", sel: "60 g", levain: "300 g" },
      { nb: 7, farineT80: "2.8 kg", farineseigle: "700 g", eau: "2.4 l", levure: "35 g", sel: "70 g", levain: "350 g" },
      { nb: 8, farineT80: "3.2 kg", farineseigle: "800 g", eau: "2.7 l", levure: "40 g", sel: "80 g", levain: "400 g" },
      { nb: 9, farineT80: "3.6 kg", farineseigle: "900 g", eau: "3.1 l", levure: "45 g", sel: "90 g", levain: "450 g" },
      { nb: 10, farineT80: "4 kg", farineseigle: "1 kg", eau: "3.4 l", levure: "50 g", sel: "100 g", levain: "500 g" },
      { nb: 11, farineT80: "4.4 kg", farineseigle: "1.1 kg", eau: "3.7 l", levure: "55 g", sel: "110 g", levain: "550 g" },
      { nb: 12, farineT80: "4.8 kg", farineseigle: "1.2 kg", eau: "4.1 l", levure: "60 g", sel: "120 g", levain: "600 g" },
      { nb: 13, farineT80: "5.2 kg", farineseigle: "1.3 kg", eau: "4.4 l", levure: "65 g", sel: "130 g", levain: "650 g" },
      { nb: 14, farineT80: "5.6 kg", farineseigle: "1.4 kg", eau: "4.8 l", levure: "70 g", sel: "140 g", levain: "700 g" },
      { nb: 15, farineT80: "6 kg", farineseigle: "1.5 kg", eau: "5.1 l", levure: "75 g", sel: "150 g", levain: "750 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🌾", titre: "Autolyse", detail: "ÉTAPE PRO : mélanger juste les farines (T80 + seigle) avec 320ml d'eau, sans levure ni sel. Couvrir et laisser reposer 30 min. La pâte va se développer toute seule. ASTUCE CHEF : améliore énormément la mie.", badge: "⏱ 30 min" },
      { icone: "🧪", titre: "Levain et levure", detail: "Dissoudre la levure dans 20ml d'eau tiède. Ajouter au mélange précédent avec le levain (si vous en avez) et le sel.", badge: null },
      { icone: "✋", titre: "Pétrissage", detail: "Pétrir 10 min au robot ou 15 min à la main. La pâte doit être souple, élastique, légèrement collante. ASTUCE : test de la fenêtre — étirer la pâte, doit former un voile sans déchirer.", badge: "⏱ 15 min" },
      { icone: "⏳", titre: "Pointage", detail: "Première levée : couvrir et laisser pousser 1h30 à 25°C jusqu'à doublement.", badge: "⏱ 1h30" },
      { icone: "✋", titre: "Rabats", detail: "ASTUCE PRO : pendant les 1h30, faire 2 rabats (replier la pâte sur elle-même) à 30 min d'intervalle. Donne du corps à la pâte.", badge: "⏱ 2x 1 min" },
      { icone: "🥖", titre: "Façonnage", detail: "Verser la pâte sur le plan fariné. Plier en 3 puis en 3 (lettre). Bouler. Mettre dans un banneton fariné, couture vers le HAUT.", badge: "⏱ 5 min" },
      { icone: "⏳", titre: "Apprêt", detail: "Deuxième levée 1h dans le banneton, couvert d'un linge. Pendant ce temps : préchauffer le four à 250°C avec une cocotte en fonte dedans.", badge: "⏱ 1h" },
      { icone: "🔥", titre: "Cuisson en cocotte", detail: "SECRET BOULANGER : retourner la pâte dans la cocotte ULTRA-CHAUDE. Faire des entailles. Couvrir et cuire 20 min à 250°C, puis 25 min sans couvercle à 230°C. Croûte parfaite garantie.", badge: "⏱ 45 min" },
      { icone: "🎵", titre: "Refroidir", detail: "Laisser refroidir SUR GRILLE au moins 1h avant de trancher. La mie continue de cuire en refroidissant.", badge: "⏱ 1h" }
    ]
  },
  bretzelallemand: {
    nom: "Bretzel Allemand",
    cat: "boulangerie", pays: "allemagne",
    base: 6,
    temps: "2h",
    niveau: "⭐⭐ Moyen",
    emoji: "🥨",
    description: "Bretzel allemand traditionnel — pâte briochée tressée en forme de nœud, ébouillantée au bicarbonate pour la croûte brillante caramélisée, parsemée de gros sel. Apéritif bavarois iconique.",
    tableauBretzel: [
      { nb: 1, farine: "80 g", lait: "45 ml", beurre: "8 g", levure: "2 g", sucre: "3 g", sel: "1 g", bicarbonate: "5 g", grossel: "2 g" },
      { nb: 2, farine: "160 g", lait: "90 ml", beurre: "16 g", levure: "3 g", sucre: "6 g", sel: "2 g", bicarbonate: "10 g", grossel: "4 g" },
      { nb: 3, farine: "240 g", lait: "135 ml", beurre: "24 g", levure: "4 g", sucre: "9 g", sel: "3 g", bicarbonate: "15 g", grossel: "6 g" },
      { nb: 4, farine: "320 g", lait: "180 ml", beurre: "32 g", levure: "6 g", sucre: "12 g", sel: "4 g", bicarbonate: "20 g", grossel: "8 g" },
      { nb: 5, farine: "400 g", lait: "225 ml", beurre: "40 g", levure: "8 g", sucre: "15 g", sel: "5 g", bicarbonate: "25 g", grossel: "10 g" },
      { nb: 6, farine: "480 g", lait: "270 ml", beurre: "48 g", levure: "9 g", sucre: "18 g", sel: "6 g", bicarbonate: "30 g", grossel: "12 g" },
      { nb: 7, farine: "560 g", lait: "315 ml", beurre: "56 g", levure: "10 g", sucre: "21 g", sel: "7 g", bicarbonate: "35 g", grossel: "14 g" },
      { nb: 8, farine: "640 g", lait: "360 ml", beurre: "64 g", levure: "12 g", sucre: "24 g", sel: "8 g", bicarbonate: "40 g", grossel: "16 g" },
      { nb: 9, farine: "720 g", lait: "405 ml", beurre: "72 g", levure: "14 g", sucre: "27 g", sel: "9 g", bicarbonate: "45 g", grossel: "18 g" },
      { nb: 10, farine: "800 g", lait: "450 ml", beurre: "80 g", levure: "15 g", sucre: "30 g", sel: "10 g", bicarbonate: "50 g", grossel: "20 g" },
      { nb: 11, farine: "880 g", lait: "495 ml", beurre: "88 g", levure: "16 g", sucre: "33 g", sel: "11 g", bicarbonate: "55 g", grossel: "22 g" },
      { nb: 12, farine: "960 g", lait: "540 ml", beurre: "96 g", levure: "18 g", sucre: "36 g", sel: "12 g", bicarbonate: "60 g", grossel: "24 g" },
      { nb: 13, farine: "1 kg", lait: "585 ml", beurre: "104 g", levure: "20 g", sucre: "39 g", sel: "13 g", bicarbonate: "65 g", grossel: "26 g" },
      { nb: 14, farine: "1.1 kg", lait: "630 ml", beurre: "112 g", levure: "21 g", sucre: "42 g", sel: "14 g", bicarbonate: "70 g", grossel: "28 g" },
      { nb: 15, farine: "1.2 kg", lait: "675 ml", beurre: "120 g", levure: "22 g", sucre: "45 g", sel: "15 g", bicarbonate: "75 g", grossel: "30 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Pâte briochée", detail: "Dans un grand bol : farine + sucre + sel. Faire un puits, ajouter levure dissoute dans le lait tiède (35°C) + beurre fondu. Mélanger jusqu'à pâte homogène.", badge: "⏱ 5 min" },
      { icone: "✋", titre: "Pétrissage", detail: "Pétrir 10 min à la main ou 7 min au robot. La pâte doit être SOUPLE et ÉLASTIQUE. ASTUCE CHEF : si trop collante, ajouter 1 cs de farine ; si trop sèche, 1 cs de lait.", badge: "⏱ 10 min" },
      { icone: "⏳", titre: "Première pousse", detail: "Couvrir d'un linge humide. Laisser pousser à 25°C (four éteint avec lampe allumée) 1h jusqu'à doublement du volume.", badge: "⏱ 1h" },
      { icone: "🥨", titre: "Façonnage en bretzel", detail: "Diviser en pâtons de 80g. Rouler chacun en LONG boudin de 50cm (fin aux extrémités). Former le nœud caractéristique : faire une boucle, tordre les 2 extrémités, ramener vers le bas. ASTUCE CHEF : pas évident la 1ère fois !", badge: "⏱ 15 min" },
      { icone: "❄️", titre: "Repos au froid", detail: "Disposer les bretzels sur une plaque farinée. RÉFRIGÉRER 30 min — étape CLÉE : pâte ferme = plus facile à plonger dans le bicarbonate.", badge: "⏱ 30 min" },
      { icone: "💧", titre: "Bain de bicarbonate", detail: "SECRET DU BRETZEL : porter 1L d'eau à frémissement avec 4 cs de bicarbonate. Plonger chaque bretzel 30 secondes. C'est ce bain qui donne la couleur brune et le goût caractéristique.", badge: "⏱ 5 min" },
      { icone: "✂️", titre: "Incision et sel", detail: "Sur plaque avec papier sulfurisé, inciser le ventre du bretzel au cutter (favorise l'ouverture à la cuisson). Saupoudrer généreusement de GROS SEL (kosher idéalement).", badge: "⏱ 3 min" },
      { icone: "🔥", titre: "Cuisson", detail: "Enfourner à 220°C chaleur tournante 15-18 min. Les bretzels doivent être BRUN DORÉ profond. ASTUCE CHEF : tourner la plaque à mi-cuisson pour uniformité.", badge: "⏱ 18 min" },
      { icone: "🍻", titre: "Service bavarois", detail: "Servir TIÈDES avec moutarde douce (Süßer Senf), beurre frais ou Obatzda (préparation au camembert). Boisson : bière weissbier ou eau. Prost !", badge: null }
    ]
  },
  fougasse: {
    nom: "Fougasse aux olives",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "30 min + repos",
    niveau: "⭐⭐ Moyen",
    emoji: "🫒",
    description: "Fougasse provençale — pain plat moelleux entaillé en épi, parfumé aux olives et au romarin, huilé à l'huile d'olive. Idéale à partager.",
    tableauFougasse: [
      { nb: 1, farine: "100 g", eau: "65 ml", levure: "2 g", huile: "1 c.à.s", olives: "20 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 2, farine: "200 g", eau: "130 ml", levure: "4 g", huile: "2 c.à.s", olives: "40 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 3, farine: "300 g", eau: "195 ml", levure: "6 g", huile: "3 c.à.s", olives: "60 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 4, farine: "400 g", eau: "260 ml", levure: "8 g", huile: "4 c.à.s", olives: "80 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 5, farine: "500 g", eau: "325 ml", levure: "10 g", huile: "5 c.à.s", olives: "100 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 6, farine: "600 g", eau: "390 ml", levure: "12 g", huile: "6 c.à.s", olives: "120 g", romarin: "1 pincée", sel: "1 pincée" },
      { nb: 7, farine: "700 g", eau: "455 ml", levure: "14 g", huile: "7 c.à.s", olives: "140 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 8, farine: "800 g", eau: "520 ml", levure: "16 g", huile: "8 c.à.s", olives: "160 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 9, farine: "900 g", eau: "585 ml", levure: "18 g", huile: "9 c.à.s", olives: "180 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 10, farine: "1000 g", eau: "650 ml", levure: "20 g", huile: "10 c.à.s", olives: "200 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 11, farine: "1100 g", eau: "715 ml", levure: "22 g", huile: "11 c.à.s", olives: "220 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 12, farine: "1200 g", eau: "780 ml", levure: "24 g", huile: "12 c.à.s", olives: "240 g", romarin: "2 pincées", sel: "2 pincées" },
      { nb: 13, farine: "1300 g", eau: "845 ml", levure: "26 g", huile: "13 c.à.s", olives: "260 g", romarin: "3 pincées", sel: "3 pincées" },
      { nb: 14, farine: "1400 g", eau: "910 ml", levure: "28 g", huile: "14 c.à.s", olives: "280 g", romarin: "3 pincées", sel: "3 pincées" },
      { nb: 15, farine: "1500 g", eau: "975 ml", levure: "30 g", huile: "15 c.à.s", olives: "300 g", romarin: "3 pincées", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
        { icone: "🥣", titre: "Pétrir la pâte", detail: "Pétrir la farine, l'eau tiède, la levure, le sel et l'huile d'olive 8 à 10 min. ASTUCE CHEF : la pâte doit rester souple et légèrement collante, c'est ce qui donne une mie aérée.", badge: "⏱ 10 min" },
        { icone: "⏲️", titre: "Première pousse", detail: "Couvrir d'un linge et laisser doubler de volume à l'abri des courants d'air.", badge: "⏱ environ 1h" },
        { icone: "🫒", titre: "Façonner", detail: "Dégazer la pâte et l'étaler en un ovale plat directement sur la plaque. Parsemer d'olives et de romarin en les enfonçant légèrement.", badge: null },
        { icone: "🔪", titre: "Inciser en épi", detail: "Entailler la pâte de coups obliques pour dessiner les nervures d'une feuille, puis écarter franchement les fentes avec les doigts pour qu'elles ne se referment pas à la cuisson.", badge: null },
        { icone: "♨️", titre: "Cuisson", detail: "Enfourner four bien chaud jusqu'à ce que la fougasse soit dorée et croustillante.", badge: "⏱ 18-20 min à 220°C" },
        { icone: "✨", titre: "Finition", detail: "À la sortie du four, badigeonner d'huile d'olive et parsemer de fleur de sel pendant que c'est encore chaud.", badge: null }
      ]
  },
  painauxraisins: {
    nom: "Pain aux raisins",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "40 min + repos",
    niveau: "⭐⭐⭐ Difficile",
    emoji: "🌀",
    description: "Pain aux raisins — la viennoiserie escargot : pâte levée feuilletée, crème pâtissière et raisins secs. Le réconfort du petit-déjeuner.",
    tableauPainAuxRaisins: [
      { nb: 1, farine: "55 g", beurre: "25 g", lait: "30 ml", sucre: "12 g", oeufs: "¼", raisinsec: "15 g", levure: "2 g" },
      { nb: 2, farine: "110 g", beurre: "50 g", lait: "60 ml", sucre: "24 g", oeufs: "½", raisinsec: "30 g", levure: "4 g" },
      { nb: 3, farine: "165 g", beurre: "75 g", lait: "90 ml", sucre: "36 g", oeufs: "1", raisinsec: "45 g", levure: "6 g" },
      { nb: 4, farine: "220 g", beurre: "100 g", lait: "120 ml", sucre: "48 g", oeufs: "1¼", raisinsec: "60 g", levure: "8 g" },
      { nb: 5, farine: "275 g", beurre: "125 g", lait: "150 ml", sucre: "60 g", oeufs: "1½", raisinsec: "75 g", levure: "10 g" },
      { nb: 6, farine: "330 g", beurre: "150 g", lait: "180 ml", sucre: "72 g", oeufs: "1¾", raisinsec: "90 g", levure: "12 g" },
      { nb: 7, farine: "385 g", beurre: "175 g", lait: "210 ml", sucre: "84 g", oeufs: "2", raisinsec: "105 g", levure: "14 g" },
      { nb: 8, farine: "440 g", beurre: "200 g", lait: "240 ml", sucre: "96 g", oeufs: "2½", raisinsec: "120 g", levure: "16 g" },
      { nb: 9, farine: "495 g", beurre: "225 g", lait: "270 ml", sucre: "108 g", oeufs: "2¾", raisinsec: "135 g", levure: "18 g" },
      { nb: 10, farine: "550 g", beurre: "250 g", lait: "300 ml", sucre: "120 g", oeufs: "3", raisinsec: "150 g", levure: "20 g" },
      { nb: 11, farine: "605 g", beurre: "275 g", lait: "330 ml", sucre: "132 g", oeufs: "3¼", raisinsec: "165 g", levure: "22 g" },
      { nb: 12, farine: "660 g", beurre: "300 g", lait: "360 ml", sucre: "144 g", oeufs: "3½", raisinsec: "180 g", levure: "24 g" },
      { nb: 13, farine: "715 g", beurre: "325 g", lait: "390 ml", sucre: "156 g", oeufs: "4", raisinsec: "195 g", levure: "26 g" },
      { nb: 14, farine: "770 g", beurre: "350 g", lait: "420 ml", sucre: "168 g", oeufs: "4¼", raisinsec: "210 g", levure: "28 g" },
      { nb: 15, farine: "825 g", beurre: "375 g", lait: "450 ml", sucre: "180 g", oeufs: "4½", raisinsec: "225 g", levure: "30 g" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Détrempe", detail: "Pétrir farine, lait tiède, sucre, levure, œuf et sel en pâte lisse. ASTUCE : une pâte un peu ferme se toure plus facilement.", badge: "⏱ 10 min" },
      { icone: "⏲️", titre: "1re pousse", detail: "Laisser pousser 1h, dégazer, puis 30 min au frais pour raffermir.", badge: "⏱ 90 min" },
      { icone: "🧈", titre: "Tourage", detail: "SECRET DU FEUILLETAGE : enfermer le beurre froid, donner 2-3 tours simples avec 20 min de repos au froid entre chaque. Tout doit rester FROID.", badge: "⏱ 40 min" },
      { icone: "🍮", titre: "Crème & raisins", detail: "Abaisser, étaler une fine couche de crème pâtissière froide, parsemer de raisins secs (réhydratés au rhum, c'est mieux).", badge: "⏱ 8 min" },
      { icone: "🌀", titre: "Rouler & couper", detail: "CLÉ : rouler bien serré en boudin, couper des tronçons de 2 cm au couteau fariné (sinon l'escargot s'écrase).", badge: "⏱ 6 min" },
      { icone: "♨️", titre: "Pousse & cuisson", detail: "Pousse 45 min, dorer à l'œuf, four 180°C 15-18 min. ASTUCE CHEF : sirop eau+sucre au pinceau à la sortie pour le brillant.", badge: "⏱ 18 min" }
    ]
  },
  chaussonpommes: {
    nom: "Chausson aux pommes",
    cat: "boulangerie", pays: "france",
    base: 6,
    temps: "35 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🍎",
    description: "Chausson aux pommes — pâte feuilletée dorée renfermant une compote de pommes maison à la cannelle. Croustillant dehors, fondant dedans.",
    tableauChaussonPommes: [
      { nb: 1, patefeuilletee: "60 g", pomme: "¾", sucre: "8 g", beurre: "5 g", oeufs: "¼", cannelle: "1 pincée" },
      { nb: 2, patefeuilletee: "120 g", pomme: "1½", sucre: "16 g", beurre: "10 g", oeufs: "¼", cannelle: "1 pincée" },
      { nb: 3, patefeuilletee: "180 g", pomme: "2", sucre: "24 g", beurre: "15 g", oeufs: "½", cannelle: "1 pincée" },
      { nb: 4, patefeuilletee: "240 g", pomme: "2¾", sucre: "32 g", beurre: "20 g", oeufs: "½", cannelle: "1 pincée" },
      { nb: 5, patefeuilletee: "300 g", pomme: "3½", sucre: "40 g", beurre: "25 g", oeufs: "¾", cannelle: "1 pincée" },
      { nb: 6, patefeuilletee: "360 g", pomme: "4¼", sucre: "48 g", beurre: "30 g", oeufs: "1", cannelle: "1 pincée" },
      { nb: 7, patefeuilletee: "420 g", pomme: "5", sucre: "56 g", beurre: "35 g", oeufs: "1", cannelle: "2 pincées" },
      { nb: 8, patefeuilletee: "480 g", pomme: "5½", sucre: "64 g", beurre: "40 g", oeufs: "1¼", cannelle: "2 pincées" },
      { nb: 9, patefeuilletee: "540 g", pomme: "6¼", sucre: "72 g", beurre: "45 g", oeufs: "1¼", cannelle: "2 pincées" },
      { nb: 10, patefeuilletee: "600 g", pomme: "7", sucre: "80 g", beurre: "50 g", oeufs: "1½", cannelle: "2 pincées" },
      { nb: 11, patefeuilletee: "660 g", pomme: "7¾", sucre: "88 g", beurre: "55 g", oeufs: "1¾", cannelle: "2 pincées" },
      { nb: 12, patefeuilletee: "720 g", pomme: "8½", sucre: "96 g", beurre: "60 g", oeufs: "1¾", cannelle: "2 pincées" },
      { nb: 13, patefeuilletee: "780 g", pomme: "9", sucre: "104 g", beurre: "65 g", oeufs: "2", cannelle: "3 pincées" },
      { nb: 14, patefeuilletee: "840 g", pomme: "9¾", sucre: "112 g", beurre: "70 g", oeufs: "2", cannelle: "3 pincées" },
      { nb: 15, patefeuilletee: "900 g", pomme: "10½", sucre: "120 g", beurre: "75 g", oeufs: "2¼", cannelle: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
        { icone: "🍎", titre: "La compote", detail: "Cuire les pommes en dés avec le sucre, le beurre et la cannelle. ASTUCE CHEF : visez une compote bien épaisse — trop liquide, elle détrempe et perce la pâte.", badge: "⏱ 10-12 min" },
        { icone: "❄️", titre: "Refroidir", detail: "Laisser la compote refroidir complètement avant de garnir, sinon elle fait fondre le beurre du feuilletage.", badge: null },
        { icone: "🥐", titre: "Découper la pâte", detail: "Découper des ovales réguliers dans la pâte feuilletée bien froide.", badge: null },
        { icone: "🥄", titre: "Garnir", detail: "Déposer une cuillère de compote sur une moitié de chaque ovale en laissant un bord libre. Humidifier ce bord au pinceau.", badge: null },
        { icone: "🔒", titre: "Souder", detail: "Replier la pâte sur la garniture et souder fermement les bords en pressant avec les dents d'une fourchette.", badge: null },
        { icone: "🖌️", titre: "Dorer et décorer", detail: "Dorer le dessus à l'œuf battu, rayer délicatement la surface au couteau pour le décor, et percer un petit trou au centre pour laisser s'échapper la vapeur.", badge: null },
        { icone: "♨️", titre: "Cuisson", detail: "Enfourner jusqu'à ce que les chaussons soient bien dorés et gonflés.", badge: "⏱ 18-20 min à 200°C" }
      ]
  },
  ciabatta: {
    nom: "Ciabatta",
    cat: "boulangerie", pays: "italie",
    base: 4,
    temps: "30 min + repos",
    niveau: "⭐⭐⭐ Difficile",
    emoji: "🥖",
    description: "Ciabatta — le pain italien à la mie alvéolée et à la croûte fine. Très hydratée, parfaite pour les bruschettas et paninis.",
    tableauCiabatta: [
      { nb: 1, farine: "100 g", eau: "75 ml", levure: "2 g", huiledolive: "1 c.à.c", sel: "1 pincée" },
      { nb: 2, farine: "200 g", eau: "150 ml", levure: "4 g", huiledolive: "2 c.à.c", sel: "1 pincée" },
      { nb: 3, farine: "300 g", eau: "225 ml", levure: "6 g", huiledolive: "3 c.à.c", sel: "1 pincée" },
      { nb: 4, farine: "400 g", eau: "300 ml", levure: "8 g", huiledolive: "4 c.à.c", sel: "1 pincée" },
      { nb: 5, farine: "500 g", eau: "375 ml", levure: "10 g", huiledolive: "5 c.à.c", sel: "1 pincée" },
      { nb: 6, farine: "600 g", eau: "450 ml", levure: "12 g", huiledolive: "6 c.à.c", sel: "1 pincée" },
      { nb: 7, farine: "700 g", eau: "525 ml", levure: "14 g", huiledolive: "7 c.à.c", sel: "2 pincées" },
      { nb: 8, farine: "800 g", eau: "600 ml", levure: "16 g", huiledolive: "8 c.à.c", sel: "2 pincées" },
      { nb: 9, farine: "900 g", eau: "675 ml", levure: "18 g", huiledolive: "9 c.à.c", sel: "2 pincées" },
      { nb: 10, farine: "1000 g", eau: "750 ml", levure: "20 g", huiledolive: "10 c.à.c", sel: "2 pincées" },
      { nb: 11, farine: "1100 g", eau: "825 ml", levure: "22 g", huiledolive: "11 c.à.c", sel: "2 pincées" },
      { nb: 12, farine: "1200 g", eau: "900 ml", levure: "24 g", huiledolive: "12 c.à.c", sel: "2 pincées" },
      { nb: 13, farine: "1300 g", eau: "975 ml", levure: "26 g", huiledolive: "13 c.à.c", sel: "3 pincées" },
      { nb: 14, farine: "1400 g", eau: "1050 ml", levure: "28 g", huiledolive: "14 c.à.c", sel: "3 pincées" },
      { nb: 15, farine: "1500 g", eau: "1125 ml", levure: "30 g", huiledolive: "15 c.à.c", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Pâte très hydratée", detail: "Mélanger farine, eau, levure en pâte TRÈS collante (hydratation ~75%). C'est voulu : ne pas ajouter de farine.", badge: "⏱ 8 min" },
      { icone: "💪", titre: "Rabats", detail: "SECRET DE LA MIE ALVÉOLÉE : pas de pétrissage, mais 3-4 séries de rabats (replier la pâte sur elle-même) espacées de 30 min.", badge: "⏱ 10 min" },
      { icone: "⏲️", titre: "Pointage", detail: "Laisser pousser 1h30-2h jusqu'à ce que la pâte double et se remplisse de grosses bulles.", badge: "⏱ 120 min" },
      { icone: "🤲", titre: "Façonnage", detail: "CLÉ : verser sur un plan TRÈS fariné, diviser et étirer en rectangles SANS dégazer (on garde les bulles).", badge: "⏱ 8 min" },
      { icone: "⏲️", titre: "Apprêt", detail: "Laisser détendre 30 min sur un linge fariné, plis en dessous.", badge: "⏱ 30 min" },
      { icone: "♨️", titre: "Cuisson", detail: "Four 240°C AVEC vapeur (lèchefrite d'eau dans le bas) 20-25 min. ASTUCE CHEF : la vapeur donne la croûte fine et la couleur.", badge: "⏱ 25 min" }
    ]
  },
  injera: {
    nom: "Injera",
    cat: "boulangerie", pays: "ethiopie",
    dateAjout: "2026-06-01",
    base: 4,
    temps: "30 min",
    niveau: "⭐⭐ Moyen",
    emoji: "🫓",
    description: "Injera — grande galette éthiopienne spongieuse au teff, légèrement acidulée par une fermentation. Elle sert à la fois d'assiette et de couvert.",
    tableauInjera: [
      { nb: 1, farineTeff: "80 g", eau: "120 ml" },
      { nb: 2, farineTeff: "160 g", eau: "240 ml" },
      { nb: 3, farineTeff: "240 g", eau: "360 ml" },
      { nb: 4, farineTeff: "320 g", eau: "480 ml" },
      { nb: 5, farineTeff: "400 g", eau: "600 ml" },
      { nb: 6, farineTeff: "480 g", eau: "720 ml" },
      { nb: 7, farineTeff: "560 g", eau: "840 ml" },
      { nb: 8, farineTeff: "640 g", eau: "960 ml" },
      { nb: 9, farineTeff: "720 g", eau: "1080 ml" },
      { nb: 10, farineTeff: "800 g", eau: "1200 ml" },
      { nb: 11, farineTeff: "880 g", eau: "1320 ml" },
      { nb: 12, farineTeff: "960 g", eau: "1440 ml" },
      { nb: 13, farineTeff: "1040 g", eau: "1560 ml" },
      { nb: 14, farineTeff: "1120 g", eau: "1680 ml" },
      { nb: 15, farineTeff: "1200 g", eau: "1800 ml" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🥣", titre: "Pâte", detail: "Mélanger la farine de teff avec l'eau en une pâte liquide.", badge: null },
      { icone: "🫧", titre: "Fermenter", detail: "Couvrir et laisser fermenter plusieurs jours jusqu'à ce qu'elle bulle et aigrisse.", badge: "⏱ 3 j" },
      { icone: "🥄", titre: "Détendre", detail: "Détendre éventuellement avec un peu d'eau pour une pâte fluide.", badge: null },
      { icone: "🔥", titre: "Chauffer", detail: "Chauffer une grande plaque (ou poêle) sans matière grasse.", badge: null },
      { icone: "🌀", titre: "Cuire", detail: "Verser la pâte en spirale et couvrir, sans la retourner.", badge: null },
      { icone: "🫧", titre: "Texture", detail: "Cuire jusqu'à ce que la surface soit criblée de petits trous.", badge: null },
      { icone: "🍽️", titre: "Service", detail: "Servir comme base et assiette pour les wat. ASTUCE CHEF : la fermentation est essentielle, c'est elle qui donne à l'injera son goût acidulé et ses bulles caractéristiques.", badge: null }
    ]
  },
  cramique: {
    nom: "Cramique",
    cat: "boulangerie",
    pays: "belgique",
    dateAjout: "2026-06-07T22:19:00",
    base: 8,
    temps: "3 h (avec pousse)",
    niveau: "⭐⭐ Moyen",
    emoji: "🍞",
    description: "La brioche belge moelleuse aux raisins, dorée et filante. Parfaite au petit-déjeuner ou au goûter, tartinée de beurre tant qu'elle est encore tiède.",
    tableauCramique: [
      { nb: 1, farine: "60 g", lait: "30 ml", beurre: "18 g", sucre: "8 g", oeuf: "1", raisinssecs: "18 g", levure: "2 g", sel: "1 pincée" },
      { nb: 2, farine: "120 g", lait: "60 ml", beurre: "36 g", sucre: "16 g", oeuf: "1", raisinssecs: "36 g", levure: "4 g", sel: "1 pincée" },
      { nb: 3, farine: "180 g", lait: "90 ml", beurre: "54 g", sucre: "24 g", oeuf: "1", raisinssecs: "54 g", levure: "6 g", sel: "1 pincée" },
      { nb: 4, farine: "240 g", lait: "120 ml", beurre: "72 g", sucre: "32 g", oeuf: "1", raisinssecs: "72 g", levure: "8 g", sel: "1 pincée" },
      { nb: 5, farine: "300 g", lait: "150 ml", beurre: "90 g", sucre: "40 g", oeuf: "2", raisinssecs: "90 g", levure: "10 g", sel: "1 pincée" },
      { nb: 6, farine: "360 g", lait: "180 ml", beurre: "108 g", sucre: "48 g", oeuf: "2", raisinssecs: "108 g", levure: "12 g", sel: "2 pincées" },
      { nb: 7, farine: "420 g", lait: "210 ml", beurre: "126 g", sucre: "56 g", oeuf: "2", raisinssecs: "126 g", levure: "14 g", sel: "2 pincées" },
      { nb: 8, farine: "480 g", lait: "240 ml", beurre: "144 g", sucre: "64 g", oeuf: "2", raisinssecs: "144 g", levure: "16 g", sel: "2 pincées" },
      { nb: 9, farine: "540 g", lait: "270 ml", beurre: "162 g", sucre: "72 g", oeuf: "3", raisinssecs: "162 g", levure: "18 g", sel: "2 pincées" },
      { nb: 10, farine: "600 g", lait: "300 ml", beurre: "180 g", sucre: "80 g", oeuf: "3", raisinssecs: "180 g", levure: "20 g", sel: "2 pincées" },
      { nb: 11, farine: "660 g", lait: "330 ml", beurre: "198 g", sucre: "88 g", oeuf: "3", raisinssecs: "198 g", levure: "22 g", sel: "3 pincées" },
      { nb: 12, farine: "720 g", lait: "360 ml", beurre: "216 g", sucre: "96 g", oeuf: "4", raisinssecs: "216 g", levure: "24 g", sel: "3 pincées" },
      { nb: 13, farine: "780 g", lait: "390 ml", beurre: "234 g", sucre: "104 g", oeuf: "4", raisinssecs: "234 g", levure: "26 g", sel: "3 pincées" },
      { nb: 14, farine: "840 g", lait: "420 ml", beurre: "252 g", sucre: "112 g", oeuf: "4", raisinssecs: "252 g", levure: "28 g", sel: "3 pincées" },
      { nb: 15, farine: "900 g", lait: "450 ml", beurre: "270 g", sucre: "120 g", oeuf: "5", raisinssecs: "270 g", levure: "30 g", sel: "3 pincées" }
    ],
    ingredients: {},
    etapes: [
      { icone: "🍇", titre: "Tremper les raisins", detail: "Faire gonfler les raisins secs dans un peu d'eau tiède (ou de thé), puis les égoutter.", badge: "⏱ 15 min" },
      { icone: "🥛", titre: "Levain", detail: "Délayer la levure dans le lait tiède avec une pincée de sucre, laisser mousser.", badge: "⏱ 10 min" },
      { icone: "🥣", titre: "Pétrir", detail: "Pétrir farine, sucre, sel, œuf et levain jusqu'à une pâte souple, puis incorporer le beurre mou. ASTUCE CHEF : pétrir longuement jusqu'à ce que la pâte se décolle du bol et devienne élastique, c'est ce qui donne le moelleux filant.", badge: "⏱ 15 min" },
      { icone: "🍇", titre: "Ajouter les raisins", detail: "Incorporer délicatement les raisins égouttés en fin de pétrissage.", badge: "⏱ 3 min" },
      { icone: "⏳", titre: "Première pousse", detail: "Couvrir et laisser doubler de volume dans un endroit tiède.", badge: "⏱ 1 h 30" },
      { icone: "🍞", titre: "Façonner", detail: "Dégazer, façonner en pain et déposer dans un moule à cake beurré.", badge: "⏱ 8 min" },
      { icone: "⏳", titre: "Seconde pousse", detail: "Laisser de nouveau gonfler jusqu'au bord du moule, puis dorer à l'œuf.", badge: "⏱ 45 min" },
      { icone: "🔥", titre: "Cuire", detail: "Enfourner à 180°C jusqu'à ce que la cramique soit bien dorée et sonne creux.", badge: "⏱ 30 min" }
    ]
  },
});
